// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.22/06       [398854]
Creator        : konstantin
Date           : Wed Mar 24 00:19:09 2021
Host           : Linux mach 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/konstantin/Projects/CERN/TMVA_MLP
Training events: 170672
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "400" [Number of training cycles]
HiddenLayers: "N+10,N" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
TestRate: "5" [Test for overtraining performed at each #th epochs]
BPMode: "batch" [Back-propagation learning mode: sequential or batch]
BatchSize: "7" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "2.500000e-03" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "5" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
mJJ                           mJJ                           mJJ                           mJJ                                                             'F'    [22.7864818573,7838.75537109]
deltaYJJ                      deltaYJJ                      deltaYJJ                      deltaYJJ                                                        'F'    [2.2119609639e-05,8.68471050262]
metPt                         metPt                         metPt                         metPt                                                           'F'    [125.825294495,2277.4987793]
ptBalance                     ptBalance                     ptBalance                     ptBalance                                                       'F'    [4.91857872476e-06,0.47649076581]
subleadJetEta                 subleadJetEta                 subleadJetEta                 subleadJetEta                                                   'F'    [-4.50663423538,4.51134681702]
leadJetPt                     leadJetPt                     leadJetPt                     leadJetPt                                                       'F'    [50.0584754944,2753.2824707]
photonEta                     photonEta                     photonEta                     photonEta                                                       'F'    [-2.4010925293,2.39041256905]
ptBalanceRed                  ptBalanceRed                  ptBalanceRed                  ptBalanceRed                                                    'F'    [0.0229892414063,0.999983787537]
nJets                         nJets                         nJets                         nJets                                                           'F'    [2,9]
sinDeltaPhiJJOver2            sinDeltaPhiJJOver2            sinDeltaPhiJJOver2            sinDeltaPhiJJOver2                                              'F'    [1.5914440155e-05,1]
deltaYJPh                     deltaYJPh                     deltaYJPh                     deltaYJPh                                                       'F'    [1.18112052405e-06,6.68952894211]
NSpec 1
weightModified                weightModified                weightModified                F                                                               'F'    [-0.191263645887,1.09073340893]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 11 )
   {
      // the training input variables
      const char* inputVars[] = { "mJJ", "deltaYJJ", "metPt", "ptBalance", "subleadJetEta", "leadJetPt", "photonEta", "ptBalanceRed", "nJets", "sinDeltaPhiJJOver2", "deltaYJPh" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fOff_1[3][11];
   double fScal_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   double fWeightMatrix0to1[22][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][22];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][12];   // weight matrix from layer 2 to 3

};

inline void ReadMLP::Initialize()
{
   // build network structure
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.484588024688428;
   fWeightMatrix0to1[1][0] = 2.25094651895827;
   fWeightMatrix0to1[2][0] = 1.2188822849698;
   fWeightMatrix0to1[3][0] = 2.38000882505763;
   fWeightMatrix0to1[4][0] = -2.02212655478799;
   fWeightMatrix0to1[5][0] = -0.102246439558647;
   fWeightMatrix0to1[6][0] = -0.362296811532435;
   fWeightMatrix0to1[7][0] = 2.17961905571999;
   fWeightMatrix0to1[8][0] = -1.8041844815475;
   fWeightMatrix0to1[9][0] = -1.81757090194557;
   fWeightMatrix0to1[10][0] = -2.79251065575344;
   fWeightMatrix0to1[11][0] = -4.43381496590764;
   fWeightMatrix0to1[12][0] = -1.63534705988921;
   fWeightMatrix0to1[13][0] = 0.344145841695604;
   fWeightMatrix0to1[14][0] = -1.35280813518788;
   fWeightMatrix0to1[15][0] = -1.94130778362946;
   fWeightMatrix0to1[16][0] = 0.18267378851762;
   fWeightMatrix0to1[17][0] = 1.42294018376897;
   fWeightMatrix0to1[18][0] = 0.211624676299742;
   fWeightMatrix0to1[19][0] = 1.68051598120085;
   fWeightMatrix0to1[20][0] = 0.871607126386418;
   fWeightMatrix0to1[0][1] = -2.52802734062147;
   fWeightMatrix0to1[1][1] = -0.841896744961497;
   fWeightMatrix0to1[2][1] = 0.171583468083417;
   fWeightMatrix0to1[3][1] = -2.8239245867217;
   fWeightMatrix0to1[4][1] = -1.3846594953705;
   fWeightMatrix0to1[5][1] = 3.17579454331025;
   fWeightMatrix0to1[6][1] = -2.35299289916131;
   fWeightMatrix0to1[7][1] = -2.08361833810012;
   fWeightMatrix0to1[8][1] = 1.26039866537424;
   fWeightMatrix0to1[9][1] = -0.364345846244691;
   fWeightMatrix0to1[10][1] = 2.64321605089905;
   fWeightMatrix0to1[11][1] = -1.6707309114165;
   fWeightMatrix0to1[12][1] = -0.415627048509867;
   fWeightMatrix0to1[13][1] = 0.341418017863669;
   fWeightMatrix0to1[14][1] = -3.2343112001016;
   fWeightMatrix0to1[15][1] = -1.57884748028657;
   fWeightMatrix0to1[16][1] = 1.71326343329683;
   fWeightMatrix0to1[17][1] = -1.84434968340139;
   fWeightMatrix0to1[18][1] = 0.781768585886377;
   fWeightMatrix0to1[19][1] = 1.73787373582691;
   fWeightMatrix0to1[20][1] = 2.90366979403358;
   fWeightMatrix0to1[0][2] = 2.14895005683985;
   fWeightMatrix0to1[1][2] = 1.87668919921435;
   fWeightMatrix0to1[2][2] = -1.18420168381139;
   fWeightMatrix0to1[3][2] = -0.318417146747864;
   fWeightMatrix0to1[4][2] = 0.158943836337777;
   fWeightMatrix0to1[5][2] = 0.0192563438531963;
   fWeightMatrix0to1[6][2] = 1.91427611576206;
   fWeightMatrix0to1[7][2] = 1.11707250502979;
   fWeightMatrix0to1[8][2] = 1.26538158178913;
   fWeightMatrix0to1[9][2] = 1.63451204781047;
   fWeightMatrix0to1[10][2] = -2.25500688620161;
   fWeightMatrix0to1[11][2] = 1.10587775567142;
   fWeightMatrix0to1[12][2] = -1.13709794396791;
   fWeightMatrix0to1[13][2] = -1.51224656587466;
   fWeightMatrix0to1[14][2] = -1.63559255441945;
   fWeightMatrix0to1[15][2] = -2.14195166005261;
   fWeightMatrix0to1[16][2] = 1.65316396288245;
   fWeightMatrix0to1[17][2] = 1.1226307361561;
   fWeightMatrix0to1[18][2] = -1.49269690845805;
   fWeightMatrix0to1[19][2] = 0.259805923631707;
   fWeightMatrix0to1[20][2] = 0.491908513918059;
   fWeightMatrix0to1[0][3] = 0.839687230780956;
   fWeightMatrix0to1[1][3] = 3.32762426637206;
   fWeightMatrix0to1[2][3] = 0.259474811723635;
   fWeightMatrix0to1[3][3] = 0.843440487709469;
   fWeightMatrix0to1[4][3] = 0.617849290392114;
   fWeightMatrix0to1[5][3] = 0.573541738662671;
   fWeightMatrix0to1[6][3] = -1.03427674343562;
   fWeightMatrix0to1[7][3] = -1.09862207512651;
   fWeightMatrix0to1[8][3] = -1.14933762698719;
   fWeightMatrix0to1[9][3] = 1.0831616913515;
   fWeightMatrix0to1[10][3] = 1.31326227298387;
   fWeightMatrix0to1[11][3] = 1.52149193864993;
   fWeightMatrix0to1[12][3] = 0.121700691511407;
   fWeightMatrix0to1[13][3] = -1.86544552062652;
   fWeightMatrix0to1[14][3] = 0.0801859859662892;
   fWeightMatrix0to1[15][3] = 3.019613412349;
   fWeightMatrix0to1[16][3] = 0.106530408942495;
   fWeightMatrix0to1[17][3] = 2.67069966811027;
   fWeightMatrix0to1[18][3] = 0.591192869221042;
   fWeightMatrix0to1[19][3] = 0.455015975141236;
   fWeightMatrix0to1[20][3] = -0.734144640010088;
   fWeightMatrix0to1[0][4] = -1.99214689255164;
   fWeightMatrix0to1[1][4] = 0.26263739796466;
   fWeightMatrix0to1[2][4] = 1.08501793569894;
   fWeightMatrix0to1[3][4] = -0.393331981808358;
   fWeightMatrix0to1[4][4] = -1.11147218809103;
   fWeightMatrix0to1[5][4] = -1.28002653822603;
   fWeightMatrix0to1[6][4] = -0.639996746969747;
   fWeightMatrix0to1[7][4] = 0.691070741471755;
   fWeightMatrix0to1[8][4] = 1.70727516105525;
   fWeightMatrix0to1[9][4] = -1.59344197493572;
   fWeightMatrix0to1[10][4] = -0.948178706552214;
   fWeightMatrix0to1[11][4] = 1.64731952968856;
   fWeightMatrix0to1[12][4] = -0.661604095730941;
   fWeightMatrix0to1[13][4] = 0.262108199710423;
   fWeightMatrix0to1[14][4] = -3.73004752843166;
   fWeightMatrix0to1[15][4] = -0.362504598973233;
   fWeightMatrix0to1[16][4] = -0.936807125929997;
   fWeightMatrix0to1[17][4] = -1.99637327243735;
   fWeightMatrix0to1[18][4] = 0.933175222274699;
   fWeightMatrix0to1[19][4] = 1.41444267093088;
   fWeightMatrix0to1[20][4] = -3.43904815258146;
   fWeightMatrix0to1[0][5] = 2.1566028266232;
   fWeightMatrix0to1[1][5] = -1.70946704357804;
   fWeightMatrix0to1[2][5] = -0.301948240811692;
   fWeightMatrix0to1[3][5] = 0.500095671820205;
   fWeightMatrix0to1[4][5] = 1.03692712343038;
   fWeightMatrix0to1[5][5] = -1.55528842035243;
   fWeightMatrix0to1[6][5] = 0.0139024402481005;
   fWeightMatrix0to1[7][5] = 0.31317176473331;
   fWeightMatrix0to1[8][5] = -0.185752814162411;
   fWeightMatrix0to1[9][5] = -0.511422581600856;
   fWeightMatrix0to1[10][5] = 1.3941755283407;
   fWeightMatrix0to1[11][5] = -0.66714010898556;
   fWeightMatrix0to1[12][5] = -0.61393210131739;
   fWeightMatrix0to1[13][5] = 1.22550282536877;
   fWeightMatrix0to1[14][5] = -0.276191533302999;
   fWeightMatrix0to1[15][5] = -2.43122267536312;
   fWeightMatrix0to1[16][5] = 0.545253377064859;
   fWeightMatrix0to1[17][5] = -0.515048924482687;
   fWeightMatrix0to1[18][5] = 2.36129947876437;
   fWeightMatrix0to1[19][5] = 0.599150686067416;
   fWeightMatrix0to1[20][5] = -1.19120193512816;
   fWeightMatrix0to1[0][6] = -0.121697471958678;
   fWeightMatrix0to1[1][6] = -0.0374011501025525;
   fWeightMatrix0to1[2][6] = -2.85934920144875;
   fWeightMatrix0to1[3][6] = 0.67988816487437;
   fWeightMatrix0to1[4][6] = 0.938944777951571;
   fWeightMatrix0to1[5][6] = -0.647106640073445;
   fWeightMatrix0to1[6][6] = -0.0285890558181529;
   fWeightMatrix0to1[7][6] = -1.16566185130717;
   fWeightMatrix0to1[8][6] = 0.620092285663961;
   fWeightMatrix0to1[9][6] = 0.995748184100152;
   fWeightMatrix0to1[10][6] = 1.03714954021081;
   fWeightMatrix0to1[11][6] = -0.84392349822483;
   fWeightMatrix0to1[12][6] = 0.204447206255464;
   fWeightMatrix0to1[13][6] = 2.27418304202662;
   fWeightMatrix0to1[14][6] = 1.43789568139168;
   fWeightMatrix0to1[15][6] = 0.32176261334587;
   fWeightMatrix0to1[16][6] = -1.61811048055058;
   fWeightMatrix0to1[17][6] = -0.981977439217703;
   fWeightMatrix0to1[18][6] = -1.0940233989851;
   fWeightMatrix0to1[19][6] = 1.13222143083577;
   fWeightMatrix0to1[20][6] = 1.85458425661532;
   fWeightMatrix0to1[0][7] = -0.266637881496679;
   fWeightMatrix0to1[1][7] = 0.00732139216569256;
   fWeightMatrix0to1[2][7] = -0.028341588163789;
   fWeightMatrix0to1[3][7] = -0.873835331829395;
   fWeightMatrix0to1[4][7] = 0.152899162069351;
   fWeightMatrix0to1[5][7] = 0.571778511258215;
   fWeightMatrix0to1[6][7] = 0.566628823851717;
   fWeightMatrix0to1[7][7] = -1.43802546510291;
   fWeightMatrix0to1[8][7] = 0.120322466661273;
   fWeightMatrix0to1[9][7] = 0.1945773880305;
   fWeightMatrix0to1[10][7] = -0.464908581715185;
   fWeightMatrix0to1[11][7] = 0.295434278201006;
   fWeightMatrix0to1[12][7] = -0.984507655328165;
   fWeightMatrix0to1[13][7] = 1.2559660153622;
   fWeightMatrix0to1[14][7] = 0.0645501333239298;
   fWeightMatrix0to1[15][7] = 1.05561484445624;
   fWeightMatrix0to1[16][7] = 0.142883111913986;
   fWeightMatrix0to1[17][7] = 1.16280090230871;
   fWeightMatrix0to1[18][7] = 0.205981284306732;
   fWeightMatrix0to1[19][7] = -0.291881927993934;
   fWeightMatrix0to1[20][7] = 0.606676808111661;
   fWeightMatrix0to1[0][8] = -1.13486765592642;
   fWeightMatrix0to1[1][8] = -0.31749013417816;
   fWeightMatrix0to1[2][8] = 2.39528383994818;
   fWeightMatrix0to1[3][8] = 1.9229932393766;
   fWeightMatrix0to1[4][8] = -0.164588408508078;
   fWeightMatrix0to1[5][8] = 1.1746417307841;
   fWeightMatrix0to1[6][8] = 1.14742903708177;
   fWeightMatrix0to1[7][8] = -2.75935971024005;
   fWeightMatrix0to1[8][8] = 0.606967383860775;
   fWeightMatrix0to1[9][8] = 0.223134574317046;
   fWeightMatrix0to1[10][8] = -0.644524789254823;
   fWeightMatrix0to1[11][8] = -1.40328063759625;
   fWeightMatrix0to1[12][8] = -1.24998172015815;
   fWeightMatrix0to1[13][8] = 2.21242999636922;
   fWeightMatrix0to1[14][8] = 2.98066186667427;
   fWeightMatrix0to1[15][8] = -0.817880445176992;
   fWeightMatrix0to1[16][8] = -0.471251381526905;
   fWeightMatrix0to1[17][8] = -0.211404587351123;
   fWeightMatrix0to1[18][8] = 0.925717231298946;
   fWeightMatrix0to1[19][8] = 1.0134433051878;
   fWeightMatrix0to1[20][8] = -1.99866308664481;
   fWeightMatrix0to1[0][9] = -0.19284571247373;
   fWeightMatrix0to1[1][9] = -0.262938947026264;
   fWeightMatrix0to1[2][9] = 1.13570542161641;
   fWeightMatrix0to1[3][9] = 0.589225090486293;
   fWeightMatrix0to1[4][9] = 2.72699224514622;
   fWeightMatrix0to1[5][9] = 0.518784806704511;
   fWeightMatrix0to1[6][9] = -0.925029429761156;
   fWeightMatrix0to1[7][9] = -0.86266565189385;
   fWeightMatrix0to1[8][9] = 1.12515925643036;
   fWeightMatrix0to1[9][9] = 0.605760927824938;
   fWeightMatrix0to1[10][9] = -1.19921364118223;
   fWeightMatrix0to1[11][9] = 0.444974139438682;
   fWeightMatrix0to1[12][9] = 0.163475631276062;
   fWeightMatrix0to1[13][9] = 0.0167732675151214;
   fWeightMatrix0to1[14][9] = -0.13575618335434;
   fWeightMatrix0to1[15][9] = -0.0225860582088188;
   fWeightMatrix0to1[16][9] = 0.474822738897968;
   fWeightMatrix0to1[17][9] = -1.06807228977214;
   fWeightMatrix0to1[18][9] = -0.1013815405344;
   fWeightMatrix0to1[19][9] = 1.6658200800715;
   fWeightMatrix0to1[20][9] = 0.348091826032918;
   fWeightMatrix0to1[0][10] = -0.127198174477895;
   fWeightMatrix0to1[1][10] = 0.634263940301693;
   fWeightMatrix0to1[2][10] = -1.94438121962743;
   fWeightMatrix0to1[3][10] = -0.117745609624954;
   fWeightMatrix0to1[4][10] = 1.52656652514479;
   fWeightMatrix0to1[5][10] = 0.960507100971055;
   fWeightMatrix0to1[6][10] = 1.06301902062142;
   fWeightMatrix0to1[7][10] = -0.0209174386829263;
   fWeightMatrix0to1[8][10] = 1.88820157651293;
   fWeightMatrix0to1[9][10] = -3.12281046566561;
   fWeightMatrix0to1[10][10] = -0.160105822338123;
   fWeightMatrix0to1[11][10] = 0.38351563253444;
   fWeightMatrix0to1[12][10] = -1.9830388128023;
   fWeightMatrix0to1[13][10] = -0.2044900499156;
   fWeightMatrix0to1[14][10] = 2.27558050875178;
   fWeightMatrix0to1[15][10] = -0.172791971335392;
   fWeightMatrix0to1[16][10] = 0.43866008393954;
   fWeightMatrix0to1[17][10] = 0.569019649573819;
   fWeightMatrix0to1[18][10] = -1.67447172439241;
   fWeightMatrix0to1[19][10] = -1.78746636760411;
   fWeightMatrix0to1[20][10] = -2.01389567742549;
   fWeightMatrix0to1[0][11] = 0.0946392664364726;
   fWeightMatrix0to1[1][11] = 4.67569450895252;
   fWeightMatrix0to1[2][11] = -1.20291768009371;
   fWeightMatrix0to1[3][11] = 3.27595036332778;
   fWeightMatrix0to1[4][11] = -4.022555472524;
   fWeightMatrix0to1[5][11] = 2.81939482482035;
   fWeightMatrix0to1[6][11] = 0.303645417764824;
   fWeightMatrix0to1[7][11] = -1.56991632120449;
   fWeightMatrix0to1[8][11] = -1.16551246690031;
   fWeightMatrix0to1[9][11] = -4.63467553587874;
   fWeightMatrix0to1[10][11] = -1.90422382943281;
   fWeightMatrix0to1[11][11] = -5.12665560679905;
   fWeightMatrix0to1[12][11] = -2.67681134328554;
   fWeightMatrix0to1[13][11] = -0.848318999960636;
   fWeightMatrix0to1[14][11] = -1.6363991568229;
   fWeightMatrix0to1[15][11] = -4.56234071602336;
   fWeightMatrix0to1[16][11] = -2.05944822997768;
   fWeightMatrix0to1[17][11] = 0.408364272480202;
   fWeightMatrix0to1[18][11] = -0.577594897828735;
   fWeightMatrix0to1[19][11] = 0.679330337033189;
   fWeightMatrix0to1[20][11] = -0.646659342748922;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.603335101183691;
   fWeightMatrix1to2[1][0] = 2.15287298763691;
   fWeightMatrix1to2[2][0] = 1.6023607849205;
   fWeightMatrix1to2[3][0] = -0.609649389971641;
   fWeightMatrix1to2[4][0] = -0.731137881095979;
   fWeightMatrix1to2[5][0] = -1.5979499469078;
   fWeightMatrix1to2[6][0] = -0.683130865785536;
   fWeightMatrix1to2[7][0] = -3.0004462532827;
   fWeightMatrix1to2[8][0] = 1.7903903357908;
   fWeightMatrix1to2[9][0] = 0.45191805628383;
   fWeightMatrix1to2[10][0] = 1.87885054898116;
   fWeightMatrix1to2[0][1] = -1.32701863914725;
   fWeightMatrix1to2[1][1] = 0.641466379903894;
   fWeightMatrix1to2[2][1] = -0.4586206085431;
   fWeightMatrix1to2[3][1] = -1.35481802787977;
   fWeightMatrix1to2[4][1] = 0.45791204874143;
   fWeightMatrix1to2[5][1] = 1.32726587906526;
   fWeightMatrix1to2[6][1] = -1.00348493940286;
   fWeightMatrix1to2[7][1] = -3.05532087391619;
   fWeightMatrix1to2[8][1] = -0.514175456286847;
   fWeightMatrix1to2[9][1] = 3.31563952805882;
   fWeightMatrix1to2[10][1] = 0.466813325657979;
   fWeightMatrix1to2[0][2] = -0.333305855905681;
   fWeightMatrix1to2[1][2] = 0.190563185176181;
   fWeightMatrix1to2[2][2] = 1.28428816817586;
   fWeightMatrix1to2[3][2] = 1.66843585789133;
   fWeightMatrix1to2[4][2] = 0.659220278888534;
   fWeightMatrix1to2[5][2] = -1.14663967679057;
   fWeightMatrix1to2[6][2] = 0.815399566013133;
   fWeightMatrix1to2[7][2] = -0.510040397052068;
   fWeightMatrix1to2[8][2] = -2.58571236555486;
   fWeightMatrix1to2[9][2] = -0.681865906724682;
   fWeightMatrix1to2[10][2] = -1.75611679829924;
   fWeightMatrix1to2[0][3] = -0.613114804514859;
   fWeightMatrix1to2[1][3] = -0.646942080014156;
   fWeightMatrix1to2[2][3] = 1.85829754879545;
   fWeightMatrix1to2[3][3] = -1.17891526917857;
   fWeightMatrix1to2[4][3] = 0.937116452847973;
   fWeightMatrix1to2[5][3] = -1.33796622365482;
   fWeightMatrix1to2[6][3] = 0.729589284187691;
   fWeightMatrix1to2[7][3] = -1.92574031275726;
   fWeightMatrix1to2[8][3] = 1.04444603763327;
   fWeightMatrix1to2[9][3] = 2.85889371166567;
   fWeightMatrix1to2[10][3] = -1.86997556323598;
   fWeightMatrix1to2[0][4] = 0.829994874131734;
   fWeightMatrix1to2[1][4] = 0.758123538336634;
   fWeightMatrix1to2[2][4] = -2.08937780145967;
   fWeightMatrix1to2[3][4] = -1.59907489763389;
   fWeightMatrix1to2[4][4] = -1.96011212871726;
   fWeightMatrix1to2[5][4] = -0.944361040694293;
   fWeightMatrix1to2[6][4] = 1.99598101825111;
   fWeightMatrix1to2[7][4] = -1.67851284217398;
   fWeightMatrix1to2[8][4] = -0.492900998991867;
   fWeightMatrix1to2[9][4] = -1.48330210011784;
   fWeightMatrix1to2[10][4] = -1.18154358171816;
   fWeightMatrix1to2[0][5] = -1.56821734726505;
   fWeightMatrix1to2[1][5] = -0.329732991813442;
   fWeightMatrix1to2[2][5] = -1.34944724222599;
   fWeightMatrix1to2[3][5] = 1.55846028664502;
   fWeightMatrix1to2[4][5] = 0.382446142030203;
   fWeightMatrix1to2[5][5] = -1.88843064344269;
   fWeightMatrix1to2[6][5] = 2.07120731518192;
   fWeightMatrix1to2[7][5] = 0.0626159525130384;
   fWeightMatrix1to2[8][5] = -0.612495330910586;
   fWeightMatrix1to2[9][5] = 2.36119932145139;
   fWeightMatrix1to2[10][5] = -1.81717123010262;
   fWeightMatrix1to2[0][6] = 1.44990632350326;
   fWeightMatrix1to2[1][6] = 1.13059624699424;
   fWeightMatrix1to2[2][6] = -0.830915008151928;
   fWeightMatrix1to2[3][6] = -0.160396498816856;
   fWeightMatrix1to2[4][6] = 0.361033795939166;
   fWeightMatrix1to2[5][6] = -0.550713906966213;
   fWeightMatrix1to2[6][6] = -0.398963099372016;
   fWeightMatrix1to2[7][6] = 0.722889253642683;
   fWeightMatrix1to2[8][6] = 2.29434862721692;
   fWeightMatrix1to2[9][6] = 2.58819473101993;
   fWeightMatrix1to2[10][6] = -1.38105733148583;
   fWeightMatrix1to2[0][7] = 0.409362616843318;
   fWeightMatrix1to2[1][7] = -2.24365763389062;
   fWeightMatrix1to2[2][7] = 0.343761437065412;
   fWeightMatrix1to2[3][7] = -2.30097507159015;
   fWeightMatrix1to2[4][7] = -2.86969041265851;
   fWeightMatrix1to2[5][7] = 0.119227822691141;
   fWeightMatrix1to2[6][7] = 0.827130075269112;
   fWeightMatrix1to2[7][7] = 0.177425602728293;
   fWeightMatrix1to2[8][7] = 0.813538071567293;
   fWeightMatrix1to2[9][7] = 0.703095245229739;
   fWeightMatrix1to2[10][7] = -0.182256697990831;
   fWeightMatrix1to2[0][8] = 0.419580992013956;
   fWeightMatrix1to2[1][8] = 0.0803854346634522;
   fWeightMatrix1to2[2][8] = 1.81456302965983;
   fWeightMatrix1to2[3][8] = -1.31030118742182;
   fWeightMatrix1to2[4][8] = 0.258393217640869;
   fWeightMatrix1to2[5][8] = -0.896602078422179;
   fWeightMatrix1to2[6][8] = -0.756068118462548;
   fWeightMatrix1to2[7][8] = -0.753135021298489;
   fWeightMatrix1to2[8][8] = 0.300178932675605;
   fWeightMatrix1to2[9][8] = -1.17845777140231;
   fWeightMatrix1to2[10][8] = 0.965681737277793;
   fWeightMatrix1to2[0][9] = 3.10427417827822;
   fWeightMatrix1to2[1][9] = 0.799467149864214;
   fWeightMatrix1to2[2][9] = 0.157814642510422;
   fWeightMatrix1to2[3][9] = -0.868382942274355;
   fWeightMatrix1to2[4][9] = -1.29006501168961;
   fWeightMatrix1to2[5][9] = -1.8255311995733;
   fWeightMatrix1to2[6][9] = 1.11822399837234;
   fWeightMatrix1to2[7][9] = -2.46012162785394;
   fWeightMatrix1to2[8][9] = -0.609693533461188;
   fWeightMatrix1to2[9][9] = -0.180952835695293;
   fWeightMatrix1to2[10][9] = -1.69953794702834;
   fWeightMatrix1to2[0][10] = -0.804445461034693;
   fWeightMatrix1to2[1][10] = -1.60399226798235;
   fWeightMatrix1to2[2][10] = 0.957665875708752;
   fWeightMatrix1to2[3][10] = -0.888677263232229;
   fWeightMatrix1to2[4][10] = -2.28863494519693;
   fWeightMatrix1to2[5][10] = -0.493600103512817;
   fWeightMatrix1to2[6][10] = -0.807988467029639;
   fWeightMatrix1to2[7][10] = -2.32756972593702;
   fWeightMatrix1to2[8][10] = 0.241861874848436;
   fWeightMatrix1to2[9][10] = -2.75131319711144;
   fWeightMatrix1to2[10][10] = -1.23128107236662;
   fWeightMatrix1to2[0][11] = 3.06987187090596;
   fWeightMatrix1to2[1][11] = 0.418159012758095;
   fWeightMatrix1to2[2][11] = 0.212228978983515;
   fWeightMatrix1to2[3][11] = 0.973582708897148;
   fWeightMatrix1to2[4][11] = 0.759583294018276;
   fWeightMatrix1to2[5][11] = 1.77091408291964;
   fWeightMatrix1to2[6][11] = -0.0513421856197255;
   fWeightMatrix1to2[7][11] = -3.56575100153745;
   fWeightMatrix1to2[8][11] = -0.352224059624556;
   fWeightMatrix1to2[9][11] = -2.6280202850751;
   fWeightMatrix1to2[10][11] = 0.912436846177887;
   fWeightMatrix1to2[0][12] = -0.116193528049497;
   fWeightMatrix1to2[1][12] = 0.00629706367758038;
   fWeightMatrix1to2[2][12] = 1.37881677689815;
   fWeightMatrix1to2[3][12] = 0.490436356116404;
   fWeightMatrix1to2[4][12] = 1.85774396199728;
   fWeightMatrix1to2[5][12] = -1.40596995977942;
   fWeightMatrix1to2[6][12] = 1.40551966048411;
   fWeightMatrix1to2[7][12] = 1.654424982367;
   fWeightMatrix1to2[8][12] = -2.1341993168893;
   fWeightMatrix1to2[9][12] = 0.500539209714327;
   fWeightMatrix1to2[10][12] = -1.06423947221877;
   fWeightMatrix1to2[0][13] = 1.10621281668077;
   fWeightMatrix1to2[1][13] = 0.733323191036721;
   fWeightMatrix1to2[2][13] = 1.15956181182243;
   fWeightMatrix1to2[3][13] = 2.28154924705964;
   fWeightMatrix1to2[4][13] = -1.20904326549064;
   fWeightMatrix1to2[5][13] = 2.17841238042315;
   fWeightMatrix1to2[6][13] = 1.2907003581994;
   fWeightMatrix1to2[7][13] = 1.16337290595525;
   fWeightMatrix1to2[8][13] = -1.67225855418727;
   fWeightMatrix1to2[9][13] = 1.65847112822456;
   fWeightMatrix1to2[10][13] = -1.96534536247707;
   fWeightMatrix1to2[0][14] = 3.34862776879417;
   fWeightMatrix1to2[1][14] = 2.13051017081539;
   fWeightMatrix1to2[2][14] = -0.257474563806821;
   fWeightMatrix1to2[3][14] = 1.24177084352249;
   fWeightMatrix1to2[4][14] = 0.0159781680269031;
   fWeightMatrix1to2[5][14] = -1.49600830514698;
   fWeightMatrix1to2[6][14] = 0.615290796331329;
   fWeightMatrix1to2[7][14] = -3.49358651123394;
   fWeightMatrix1to2[8][14] = 1.77011484659446;
   fWeightMatrix1to2[9][14] = -0.251857634907542;
   fWeightMatrix1to2[10][14] = 1.66113123051823;
   fWeightMatrix1to2[0][15] = 1.51558805686493;
   fWeightMatrix1to2[1][15] = 1.65763716547481;
   fWeightMatrix1to2[2][15] = -0.325912218955575;
   fWeightMatrix1to2[3][15] = -0.00584667642760225;
   fWeightMatrix1to2[4][15] = 0.722578075774484;
   fWeightMatrix1to2[5][15] = 1.48101162382429;
   fWeightMatrix1to2[6][15] = -1.96929392804957;
   fWeightMatrix1to2[7][15] = -1.48643247594788;
   fWeightMatrix1to2[8][15] = 0.515455936591957;
   fWeightMatrix1to2[9][15] = -3.36450506439441;
   fWeightMatrix1to2[10][15] = -1.6935536872639;
   fWeightMatrix1to2[0][16] = -1.38811533682496;
   fWeightMatrix1to2[1][16] = 1.0233320737243;
   fWeightMatrix1to2[2][16] = -0.0957285880740288;
   fWeightMatrix1to2[3][16] = -1.96744761245571;
   fWeightMatrix1to2[4][16] = -2.22555574480464;
   fWeightMatrix1to2[5][16] = -0.254749874535968;
   fWeightMatrix1to2[6][16] = 1.82577514026422;
   fWeightMatrix1to2[7][16] = 0.570273932180246;
   fWeightMatrix1to2[8][16] = 0.662040380696315;
   fWeightMatrix1to2[9][16] = -0.686236012454323;
   fWeightMatrix1to2[10][16] = -1.93714706128257;
   fWeightMatrix1to2[0][17] = -0.612656057979868;
   fWeightMatrix1to2[1][17] = -0.795591556106641;
   fWeightMatrix1to2[2][17] = -1.47113778227587;
   fWeightMatrix1to2[3][17] = 0.0589568486545754;
   fWeightMatrix1to2[4][17] = 1.07529718796022;
   fWeightMatrix1to2[5][17] = -2.06833547082424;
   fWeightMatrix1to2[6][17] = 1.86011924731168;
   fWeightMatrix1to2[7][17] = 0.387888231819893;
   fWeightMatrix1to2[8][17] = 0.449809171512483;
   fWeightMatrix1to2[9][17] = -0.148584639910474;
   fWeightMatrix1to2[10][17] = -0.865566166589028;
   fWeightMatrix1to2[0][18] = 1.92292505757512;
   fWeightMatrix1to2[1][18] = -0.413500828358886;
   fWeightMatrix1to2[2][18] = 0.227108523224337;
   fWeightMatrix1to2[3][18] = 1.74193075050642;
   fWeightMatrix1to2[4][18] = 1.03344073737248;
   fWeightMatrix1to2[5][18] = -1.09222253235542;
   fWeightMatrix1to2[6][18] = 1.46958492628604;
   fWeightMatrix1to2[7][18] = -2.24405130838994;
   fWeightMatrix1to2[8][18] = 1.05628240974206;
   fWeightMatrix1to2[9][18] = 2.14583305698895;
   fWeightMatrix1to2[10][18] = -0.158308050831025;
   fWeightMatrix1to2[0][19] = -1.31672186436244;
   fWeightMatrix1to2[1][19] = 0.67094581897122;
   fWeightMatrix1to2[2][19] = -0.774424981019537;
   fWeightMatrix1to2[3][19] = 1.05312098016367;
   fWeightMatrix1to2[4][19] = -0.384965164945552;
   fWeightMatrix1to2[5][19] = -1.00685949431716;
   fWeightMatrix1to2[6][19] = -1.10083265227426;
   fWeightMatrix1to2[7][19] = -0.276886841642257;
   fWeightMatrix1to2[8][19] = -0.420592074835734;
   fWeightMatrix1to2[9][19] = 0.933892773084239;
   fWeightMatrix1to2[10][19] = -0.738905509199671;
   fWeightMatrix1to2[0][20] = -3.39412410286135;
   fWeightMatrix1to2[1][20] = 2.15108421264193;
   fWeightMatrix1to2[2][20] = 0.989933183304086;
   fWeightMatrix1to2[3][20] = -2.2881117966021;
   fWeightMatrix1to2[4][20] = 0.570908487025264;
   fWeightMatrix1to2[5][20] = -1.94256720774261;
   fWeightMatrix1to2[6][20] = 1.45531241834585;
   fWeightMatrix1to2[7][20] = 3.71154732963609;
   fWeightMatrix1to2[8][20] = -0.489577509730243;
   fWeightMatrix1to2[9][20] = -0.0901091996719723;
   fWeightMatrix1to2[10][20] = 1.59032706877623;
   fWeightMatrix1to2[0][21] = 1.29281334594343;
   fWeightMatrix1to2[1][21] = 0.687135130748595;
   fWeightMatrix1to2[2][21] = 0.19332048527772;
   fWeightMatrix1to2[3][21] = -0.9256499141869;
   fWeightMatrix1to2[4][21] = -2.21226772253209;
   fWeightMatrix1to2[5][21] = 1.26439357867173;
   fWeightMatrix1to2[6][21] = -0.0412815782667605;
   fWeightMatrix1to2[7][21] = -0.0869570148955676;
   fWeightMatrix1to2[8][21] = -2.85738613507173;
   fWeightMatrix1to2[9][21] = -0.827112494087007;
   fWeightMatrix1to2[10][21] = -1.94301175826388;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -3.1903889816305;
   fWeightMatrix2to3[0][1] = -1.60220520767939;
   fWeightMatrix2to3[0][2] = 1.05748601575605;
   fWeightMatrix2to3[0][3] = -2.35787576951713;
   fWeightMatrix2to3[0][4] = 2.11410193518247;
   fWeightMatrix2to3[0][5] = 2.13041962975921;
   fWeightMatrix2to3[0][6] = -2.15227346945633;
   fWeightMatrix2to3[0][7] = 4.73328183602334;
   fWeightMatrix2to3[0][8] = 3.32852909264353;
   fWeightMatrix2to3[0][9] = 4.15893111992592;
   fWeightMatrix2to3[0][10] = -0.478696555532306;
   fWeightMatrix2to3[0][11] = -1.00326962701659;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)11) {
      std::cout << "Input vector needs to be of size " << 11 << std::endl;
      return 0;
   }

   std::array<double, 22> fWeights1 {{}};
   std::array<double, 12> fWeights2 {{}};
   std::array<double, 1> fWeights3 {{}};
   fWeights1.back() = 1.;
   fWeights2.back() = 1.;

   // layer 0 to 1
   for (int o=0; o<21; o++) {
      std::array<double, 12> buffer; // no need to initialise
      for (int i = 0; i<12 - 1; i++) {
         buffer[i] = fWeightMatrix0to1[o][i] * inputValues[i];
      } // loop over i
      buffer.back() = fWeightMatrix0to1[o][11];
      for (int i=0; i<12; i++) {
         fWeights1[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<21; o++) {
      fWeights1[o] = ActivationFnc(fWeights1[o]);
   } // loop over o
   // layer 1 to 2
   for (int o=0; o<11; o++) {
      std::array<double, 22> buffer; // no need to initialise
      for (int i=0; i<22; i++) {
         buffer[i] = fWeightMatrix1to2[o][i] * fWeights1[i];
      } // loop over i
      for (int i=0; i<22; i++) {
         fWeights2[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<11; o++) {
      fWeights2[o] = ActivationFnc(fWeights2[o]);
   } // loop over o
   // layer 2 to 3
   for (int o=0; o<1; o++) {
      std::array<double, 12> buffer; // no need to initialise
      for (int i=0; i<12; i++) {
         buffer[i] = fWeightMatrix2to3[o][i] * fWeights2[i];
      } // loop over i
      for (int i=0; i<12; i++) {
         fWeights3[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<1; o++) {
      fWeights3[o] = OutputActivationFnc(fWeights3[o]);
   } // loop over o

   return fWeights3[0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}

// Clean up
inline void ReadMLP::Clear()
{
}
inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         std::vector<double> iV(inputValues);
         Transform( iV, -1 );
         retval = GetMvaValue__( iV );
   }

   return retval;
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   double fMin_1[3][11];
   double fMax_1[3][11];
   // Normalization transformation, initialisation
   fMin_1[0][0] = 22.7864818573;
   fMax_1[0][0] = 7505.73046875;
   fScal_1[0][0] = 2.0/(fMax_1[0][0]-fMin_1[0][0]);
   fOff_1[0][0] = fMin_1[0][0]*fScal_1[0][0]+1.;
   fMin_1[1][0] = 23.5563087463;
   fMax_1[1][0] = 7838.75537109;
   fScal_1[1][0] = 2.0/(fMax_1[1][0]-fMin_1[1][0]);
   fOff_1[1][0] = fMin_1[1][0]*fScal_1[1][0]+1.;
   fMin_1[2][0] = 22.7864818573;
   fMax_1[2][0] = 7838.75537109;
   fScal_1[2][0] = 2.0/(fMax_1[2][0]-fMin_1[2][0]);
   fOff_1[2][0] = fMin_1[2][0]*fScal_1[2][0]+1.;
   fMin_1[0][1] = 0.000150358115206;
   fMax_1[0][1] = 8.68471050262;
   fScal_1[0][1] = 2.0/(fMax_1[0][1]-fMin_1[0][1]);
   fOff_1[0][1] = fMin_1[0][1]*fScal_1[0][1]+1.;
   fMin_1[1][1] = 2.2119609639e-05;
   fMax_1[1][1] = 8.68384933472;
   fScal_1[1][1] = 2.0/(fMax_1[1][1]-fMin_1[1][1]);
   fOff_1[1][1] = fMin_1[1][1]*fScal_1[1][1]+1.;
   fMin_1[2][1] = 2.2119609639e-05;
   fMax_1[2][1] = 8.68471050262;
   fScal_1[2][1] = 2.0/(fMax_1[2][1]-fMin_1[2][1]);
   fOff_1[2][1] = fMin_1[2][1]*fScal_1[2][1]+1.;
   fMin_1[0][2] = 126.97845459;
   fMax_1[0][2] = 2277.4987793;
   fScal_1[0][2] = 2.0/(fMax_1[0][2]-fMin_1[0][2]);
   fOff_1[0][2] = fMin_1[0][2]*fScal_1[0][2]+1.;
   fMin_1[1][2] = 125.825294495;
   fMax_1[1][2] = 1926.56140137;
   fScal_1[1][2] = 2.0/(fMax_1[1][2]-fMin_1[1][2]);
   fOff_1[1][2] = fMin_1[1][2]*fScal_1[1][2]+1.;
   fMin_1[2][2] = 125.825294495;
   fMax_1[2][2] = 2277.4987793;
   fScal_1[2][2] = 2.0/(fMax_1[2][2]-fMin_1[2][2]);
   fOff_1[2][2] = fMin_1[2][2]*fScal_1[2][2]+1.;
   fMin_1[0][3] = 4.91857872476e-06;
   fMax_1[0][3] = 0.405025333166;
   fScal_1[0][3] = 2.0/(fMax_1[0][3]-fMin_1[0][3]);
   fOff_1[0][3] = fMin_1[0][3]*fScal_1[0][3]+1.;
   fMin_1[1][3] = 5.9500340285e-05;
   fMax_1[1][3] = 0.47649076581;
   fScal_1[1][3] = 2.0/(fMax_1[1][3]-fMin_1[1][3]);
   fOff_1[1][3] = fMin_1[1][3]*fScal_1[1][3]+1.;
   fMin_1[2][3] = 4.91857872476e-06;
   fMax_1[2][3] = 0.47649076581;
   fScal_1[2][3] = 2.0/(fMax_1[2][3]-fMin_1[2][3]);
   fOff_1[2][3] = fMin_1[2][3]*fScal_1[2][3]+1.;
   fMin_1[0][4] = -4.50663423538;
   fMax_1[0][4] = 4.51134681702;
   fScal_1[0][4] = 2.0/(fMax_1[0][4]-fMin_1[0][4]);
   fOff_1[0][4] = fMin_1[0][4]*fScal_1[0][4]+1.;
   fMin_1[1][4] = -4.5036110878;
   fMax_1[1][4] = 4.50834369659;
   fScal_1[1][4] = 2.0/(fMax_1[1][4]-fMin_1[1][4]);
   fOff_1[1][4] = fMin_1[1][4]*fScal_1[1][4]+1.;
   fMin_1[2][4] = -4.50663423538;
   fMax_1[2][4] = 4.51134681702;
   fScal_1[2][4] = 2.0/(fMax_1[2][4]-fMin_1[2][4]);
   fOff_1[2][4] = fMin_1[2][4]*fScal_1[2][4]+1.;
   fMin_1[0][5] = 50.1059684753;
   fMax_1[0][5] = 1964.14489746;
   fScal_1[0][5] = 2.0/(fMax_1[0][5]-fMin_1[0][5]);
   fOff_1[0][5] = fMin_1[0][5]*fScal_1[0][5]+1.;
   fMin_1[1][5] = 50.0584754944;
   fMax_1[1][5] = 2753.2824707;
   fScal_1[1][5] = 2.0/(fMax_1[1][5]-fMin_1[1][5]);
   fOff_1[1][5] = fMin_1[1][5]*fScal_1[1][5]+1.;
   fMin_1[2][5] = 50.0584754944;
   fMax_1[2][5] = 2753.2824707;
   fScal_1[2][5] = 2.0/(fMax_1[2][5]-fMin_1[2][5]);
   fOff_1[2][5] = fMin_1[2][5]*fScal_1[2][5]+1.;
   fMin_1[0][6] = -2.4010925293;
   fMax_1[0][6] = 2.39041256905;
   fScal_1[0][6] = 2.0/(fMax_1[0][6]-fMin_1[0][6]);
   fOff_1[0][6] = fMin_1[0][6]*fScal_1[0][6]+1.;
   fMin_1[1][6] = -2.38632035255;
   fMax_1[1][6] = 2.38307738304;
   fScal_1[1][6] = 2.0/(fMax_1[1][6]-fMin_1[1][6]);
   fOff_1[1][6] = fMin_1[1][6]*fScal_1[1][6]+1.;
   fMin_1[2][6] = -2.4010925293;
   fMax_1[2][6] = 2.39041256905;
   fScal_1[2][6] = 2.0/(fMax_1[2][6]-fMin_1[2][6]);
   fOff_1[2][6] = fMin_1[2][6]*fScal_1[2][6]+1.;
   fMin_1[0][7] = 0.0488347522914;
   fMax_1[0][7] = 0.99988257885;
   fScal_1[0][7] = 2.0/(fMax_1[0][7]-fMin_1[0][7]);
   fOff_1[0][7] = fMin_1[0][7]*fScal_1[0][7]+1.;
   fMin_1[1][7] = 0.0229892414063;
   fMax_1[1][7] = 0.999983787537;
   fScal_1[1][7] = 2.0/(fMax_1[1][7]-fMin_1[1][7]);
   fOff_1[1][7] = fMin_1[1][7]*fScal_1[1][7]+1.;
   fMin_1[2][7] = 0.0229892414063;
   fMax_1[2][7] = 0.999983787537;
   fScal_1[2][7] = 2.0/(fMax_1[2][7]-fMin_1[2][7]);
   fOff_1[2][7] = fMin_1[2][7]*fScal_1[2][7]+1.;
   fMin_1[0][8] = 2;
   fMax_1[0][8] = 8;
   fScal_1[0][8] = 2.0/(fMax_1[0][8]-fMin_1[0][8]);
   fOff_1[0][8] = fMin_1[0][8]*fScal_1[0][8]+1.;
   fMin_1[1][8] = 2;
   fMax_1[1][8] = 9;
   fScal_1[1][8] = 2.0/(fMax_1[1][8]-fMin_1[1][8]);
   fOff_1[1][8] = fMin_1[1][8]*fScal_1[1][8]+1.;
   fMin_1[2][8] = 2;
   fMax_1[2][8] = 9;
   fScal_1[2][8] = 2.0/(fMax_1[2][8]-fMin_1[2][8]);
   fOff_1[2][8] = fMin_1[2][8]*fScal_1[2][8]+1.;
   fMin_1[0][9] = 1.5914440155e-05;
   fMax_1[0][9] = 1;
   fScal_1[0][9] = 2.0/(fMax_1[0][9]-fMin_1[0][9]);
   fOff_1[0][9] = fMin_1[0][9]*fScal_1[0][9]+1.;
   fMin_1[1][9] = 1.93119049072e-05;
   fMax_1[1][9] = 1;
   fScal_1[1][9] = 2.0/(fMax_1[1][9]-fMin_1[1][9]);
   fOff_1[1][9] = fMin_1[1][9]*fScal_1[1][9]+1.;
   fMin_1[2][9] = 1.5914440155e-05;
   fMax_1[2][9] = 1;
   fScal_1[2][9] = 2.0/(fMax_1[2][9]-fMin_1[2][9]);
   fOff_1[2][9] = fMin_1[2][9]*fScal_1[2][9]+1.;
   fMin_1[0][10] = 3.26525550918e-05;
   fMax_1[0][10] = 6.50682735443;
   fScal_1[0][10] = 2.0/(fMax_1[0][10]-fMin_1[0][10]);
   fOff_1[0][10] = fMin_1[0][10]*fScal_1[0][10]+1.;
   fMin_1[1][10] = 1.18112052405e-06;
   fMax_1[1][10] = 6.68952894211;
   fScal_1[1][10] = 2.0/(fMax_1[1][10]-fMin_1[1][10]);
   fOff_1[1][10] = fMin_1[1][10]*fScal_1[1][10]+1.;
   fMin_1[2][10] = 1.18112052405e-06;
   fMax_1[2][10] = 6.68952894211;
   fScal_1[2][10] = 2.0/(fMax_1[2][10]-fMin_1[2][10]);
   fOff_1[2][10] = fMin_1[2][10]*fScal_1[2][10]+1.;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) {
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   }
   if ( indicesPut.empty() ) {
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   }

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fOff_1[cls][ivar];
      double scale  = fScal_1[cls][ivar];
      iv[indicesPut.at(ivar)] = scale*dv[ivar]-offset;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
