// Class: ReadH:!V:VarTransform=N:NCycles=500:HiddenLayers=N,N:TestRate=5:!UseRegulator:NeuronType=tanh
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::H:!V:VarTransform=N:NCycles=500:HiddenLayers=N,N:TestRate=5:!UseRegulator:NeuronType=tanh
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.22/06       [398854]
Creator        : konstantin
Date           : Tue Mar 23 00:50:30 2021
Host           : Linux mach 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/konstantin/Projects/CERN/TMVA_MLP
Training events: 170672
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
# Default:
NCycles: "500" [Number of training cycles]
HiddenLayers: "N,N-1" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
mJJ                           mJJ                           mJJ                           mJJ                                                             'F'    [22.7864818573,7838.75537109]
deltaYJJ                      deltaYJJ                      deltaYJJ                      deltaYJJ                                                        'F'    [2.2119609639e-05,8.68471050262]
metPt                         metPt                         metPt                         metPt                                                           'F'    [125.825294495,2277.4987793]
ptBalance                     ptBalance                     ptBalance                     ptBalance                                                       'F'    [4.91857872476e-06,0.47649076581]
subleadJetEta                 subleadJetEta                 subleadJetEta                 subleadJetEta                                                   'F'    [-4.50663423538,4.51134681702]
leadJetPt                     leadJetPt                     leadJetPt                     leadJetPt                                                       'F'    [50.0584754944,2753.2824707]
photonEta                     photonEta                     photonEta                     photonEta                                                       'F'    [-2.4010925293,2.39041256905]
ptBalanceRed                  ptBalanceRed                  ptBalanceRed                  ptBalanceRed                                                    'F'    [0.0229892414063,0.999983787537]
nJets                         nJets                         nJets                         nJets                                                           'F'    [2,9]
sinDeltaPhiJJOver2            sinDeltaPhiJJOver2            sinDeltaPhiJJOver2            sinDeltaPhiJJOver2                                              'F'    [1.5914440155e-05,1]
deltaYJPh                     deltaYJPh                     deltaYJPh                     deltaYJPh                                                       'F'    [1.18112052405e-06,6.68952894211]
NSpec 1
weightModified                weightModified                weightModified                F                                                               'F'    [-0.191263645887,1.09073340893]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadH:!V:VarTransform=N:NCycles=500:HiddenLayers=N,N:TestRate=5:!UseRegulator:NeuronType=tanh : public IClassifierReader {

 public:

   // constructor
   ReadH:!V:VarTransform=N:NCycles=500:HiddenLayers=N,N:TestRate=5:!UseRegulator:NeuronType=tanh( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadH:!V:VarTransform=N:NCycles=500:HiddenLayers=N,N:TestRate=5:!UseRegulator:NeuronType=tanh" ),
        fNvars( 11 )
   {
      // the training input variables
      const char* inputVars[] = { "mJJ", "deltaYJJ", "metPt", "ptBalance", "subleadJetEta", "leadJetPt", "photonEta", "ptBalanceRed", "nJets", "sinDeltaPhiJJOver2", "deltaYJPh" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadH:!V:VarTransform=N:NCycles=500:HiddenLayers=N,N:TestRate=5:!UseRegulator:NeuronType=tanh() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   double fWeightMatrix0to1[12][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[11][12];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][11];   // weight matrix from layer 2 to 3

};

inline void ReadH:!V:VarTransform=N:NCycles=500:HiddenLayers=N,N:TestRate=5:!UseRegulator:NeuronType=tanh::Initialize()
{
   // build network structure
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -nan;
   fWeightMatrix0to1[1][0] = -nan;
   fWeightMatrix0to1[2][0] = -nan;
   fWeightMatrix0to1[3][0] = -nan;
   fWeightMatrix0to1[4][0] = nan;
   fWeightMatrix0to1[5][0] = nan;
   fWeightMatrix0to1[6][0] = nan;
   fWeightMatrix0to1[7][0] = -nan;
   fWeightMatrix0to1[8][0] = nan;
   fWeightMatrix0to1[9][0] = -nan;
   fWeightMatrix0to1[10][0] = nan;
   fWeightMatrix0to1[0][1] = -nan;
   fWeightMatrix0to1[1][1] = -nan;
   fWeightMatrix0to1[2][1] = -nan;
   fWeightMatrix0to1[3][1] = -nan;
   fWeightMatrix0to1[4][1] = nan;
   fWeightMatrix0to1[5][1] = nan;
   fWeightMatrix0to1[6][1] = nan;
   fWeightMatrix0to1[7][1] = -nan;
   fWeightMatrix0to1[8][1] = nan;
   fWeightMatrix0to1[9][1] = -nan;
   fWeightMatrix0to1[10][1] = nan;
   fWeightMatrix0to1[0][2] = -nan;
   fWeightMatrix0to1[1][2] = -nan;
   fWeightMatrix0to1[2][2] = -nan;
   fWeightMatrix0to1[3][2] = -nan;
   fWeightMatrix0to1[4][2] = nan;
   fWeightMatrix0to1[5][2] = nan;
   fWeightMatrix0to1[6][2] = nan;
   fWeightMatrix0to1[7][2] = -nan;
   fWeightMatrix0to1[8][2] = nan;
   fWeightMatrix0to1[9][2] = -nan;
   fWeightMatrix0to1[10][2] = nan;
   fWeightMatrix0to1[0][3] = -nan;
   fWeightMatrix0to1[1][3] = -nan;
   fWeightMatrix0to1[2][3] = -nan;
   fWeightMatrix0to1[3][3] = -nan;
   fWeightMatrix0to1[4][3] = nan;
   fWeightMatrix0to1[5][3] = nan;
   fWeightMatrix0to1[6][3] = nan;
   fWeightMatrix0to1[7][3] = -nan;
   fWeightMatrix0to1[8][3] = nan;
   fWeightMatrix0to1[9][3] = -nan;
   fWeightMatrix0to1[10][3] = nan;
   fWeightMatrix0to1[0][4] = -nan;
   fWeightMatrix0to1[1][4] = -nan;
   fWeightMatrix0to1[2][4] = -nan;
   fWeightMatrix0to1[3][4] = -nan;
   fWeightMatrix0to1[4][4] = nan;
   fWeightMatrix0to1[5][4] = nan;
   fWeightMatrix0to1[6][4] = nan;
   fWeightMatrix0to1[7][4] = -nan;
   fWeightMatrix0to1[8][4] = nan;
   fWeightMatrix0to1[9][4] = -nan;
   fWeightMatrix0to1[10][4] = nan;
   fWeightMatrix0to1[0][5] = -nan;
   fWeightMatrix0to1[1][5] = -nan;
   fWeightMatrix0to1[2][5] = -nan;
   fWeightMatrix0to1[3][5] = -nan;
   fWeightMatrix0to1[4][5] = nan;
   fWeightMatrix0to1[5][5] = nan;
   fWeightMatrix0to1[6][5] = nan;
   fWeightMatrix0to1[7][5] = -nan;
   fWeightMatrix0to1[8][5] = nan;
   fWeightMatrix0to1[9][5] = -nan;
   fWeightMatrix0to1[10][5] = nan;
   fWeightMatrix0to1[0][6] = -nan;
   fWeightMatrix0to1[1][6] = -nan;
   fWeightMatrix0to1[2][6] = -nan;
   fWeightMatrix0to1[3][6] = -nan;
   fWeightMatrix0to1[4][6] = nan;
   fWeightMatrix0to1[5][6] = nan;
   fWeightMatrix0to1[6][6] = nan;
   fWeightMatrix0to1[7][6] = -nan;
   fWeightMatrix0to1[8][6] = nan;
   fWeightMatrix0to1[9][6] = -nan;
   fWeightMatrix0to1[10][6] = nan;
   fWeightMatrix0to1[0][7] = -nan;
   fWeightMatrix0to1[1][7] = -nan;
   fWeightMatrix0to1[2][7] = -nan;
   fWeightMatrix0to1[3][7] = -nan;
   fWeightMatrix0to1[4][7] = nan;
   fWeightMatrix0to1[5][7] = nan;
   fWeightMatrix0to1[6][7] = nan;
   fWeightMatrix0to1[7][7] = -nan;
   fWeightMatrix0to1[8][7] = nan;
   fWeightMatrix0to1[9][7] = -nan;
   fWeightMatrix0to1[10][7] = nan;
   fWeightMatrix0to1[0][8] = -nan;
   fWeightMatrix0to1[1][8] = -nan;
   fWeightMatrix0to1[2][8] = -nan;
   fWeightMatrix0to1[3][8] = -nan;
   fWeightMatrix0to1[4][8] = nan;
   fWeightMatrix0to1[5][8] = nan;
   fWeightMatrix0to1[6][8] = nan;
   fWeightMatrix0to1[7][8] = -nan;
   fWeightMatrix0to1[8][8] = nan;
   fWeightMatrix0to1[9][8] = -nan;
   fWeightMatrix0to1[10][8] = nan;
   fWeightMatrix0to1[0][9] = -nan;
   fWeightMatrix0to1[1][9] = -nan;
   fWeightMatrix0to1[2][9] = -nan;
   fWeightMatrix0to1[3][9] = -nan;
   fWeightMatrix0to1[4][9] = nan;
   fWeightMatrix0to1[5][9] = nan;
   fWeightMatrix0to1[6][9] = nan;
   fWeightMatrix0to1[7][9] = -nan;
   fWeightMatrix0to1[8][9] = nan;
   fWeightMatrix0to1[9][9] = -nan;
   fWeightMatrix0to1[10][9] = nan;
   fWeightMatrix0to1[0][10] = -nan;
   fWeightMatrix0to1[1][10] = -nan;
   fWeightMatrix0to1[2][10] = -nan;
   fWeightMatrix0to1[3][10] = -nan;
   fWeightMatrix0to1[4][10] = nan;
   fWeightMatrix0to1[5][10] = nan;
   fWeightMatrix0to1[6][10] = nan;
   fWeightMatrix0to1[7][10] = -nan;
   fWeightMatrix0to1[8][10] = nan;
   fWeightMatrix0to1[9][10] = -nan;
   fWeightMatrix0to1[10][10] = nan;
   fWeightMatrix0to1[0][11] = -nan;
   fWeightMatrix0to1[1][11] = -nan;
   fWeightMatrix0to1[2][11] = -nan;
   fWeightMatrix0to1[3][11] = -nan;
   fWeightMatrix0to1[4][11] = nan;
   fWeightMatrix0to1[5][11] = nan;
   fWeightMatrix0to1[6][11] = nan;
   fWeightMatrix0to1[7][11] = -nan;
   fWeightMatrix0to1[8][11] = nan;
   fWeightMatrix0to1[9][11] = -nan;
   fWeightMatrix0to1[10][11] = nan;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -nan;
   fWeightMatrix1to2[1][0] = -nan;
   fWeightMatrix1to2[2][0] = -nan;
   fWeightMatrix1to2[3][0] = -nan;
   fWeightMatrix1to2[4][0] = -nan;
   fWeightMatrix1to2[5][0] = -nan;
   fWeightMatrix1to2[6][0] = -nan;
   fWeightMatrix1to2[7][0] = -nan;
   fWeightMatrix1to2[8][0] = -nan;
   fWeightMatrix1to2[9][0] = -nan;
   fWeightMatrix1to2[0][1] = -nan;
   fWeightMatrix1to2[1][1] = -nan;
   fWeightMatrix1to2[2][1] = -nan;
   fWeightMatrix1to2[3][1] = -nan;
   fWeightMatrix1to2[4][1] = -nan;
   fWeightMatrix1to2[5][1] = -nan;
   fWeightMatrix1to2[6][1] = -nan;
   fWeightMatrix1to2[7][1] = -nan;
   fWeightMatrix1to2[8][1] = -nan;
   fWeightMatrix1to2[9][1] = -nan;
   fWeightMatrix1to2[0][2] = -nan;
   fWeightMatrix1to2[1][2] = -nan;
   fWeightMatrix1to2[2][2] = -nan;
   fWeightMatrix1to2[3][2] = -nan;
   fWeightMatrix1to2[4][2] = -nan;
   fWeightMatrix1to2[5][2] = -nan;
   fWeightMatrix1to2[6][2] = -nan;
   fWeightMatrix1to2[7][2] = -nan;
   fWeightMatrix1to2[8][2] = -nan;
   fWeightMatrix1to2[9][2] = -nan;
   fWeightMatrix1to2[0][3] = -nan;
   fWeightMatrix1to2[1][3] = -nan;
   fWeightMatrix1to2[2][3] = -nan;
   fWeightMatrix1to2[3][3] = -nan;
   fWeightMatrix1to2[4][3] = -nan;
   fWeightMatrix1to2[5][3] = -nan;
   fWeightMatrix1to2[6][3] = -nan;
   fWeightMatrix1to2[7][3] = -nan;
   fWeightMatrix1to2[8][3] = -nan;
   fWeightMatrix1to2[9][3] = -nan;
   fWeightMatrix1to2[0][4] = nan;
   fWeightMatrix1to2[1][4] = nan;
   fWeightMatrix1to2[2][4] = nan;
   fWeightMatrix1to2[3][4] = nan;
   fWeightMatrix1to2[4][4] = nan;
   fWeightMatrix1to2[5][4] = nan;
   fWeightMatrix1to2[6][4] = nan;
   fWeightMatrix1to2[7][4] = nan;
   fWeightMatrix1to2[8][4] = nan;
   fWeightMatrix1to2[9][4] = nan;
   fWeightMatrix1to2[0][5] = nan;
   fWeightMatrix1to2[1][5] = nan;
   fWeightMatrix1to2[2][5] = nan;
   fWeightMatrix1to2[3][5] = nan;
   fWeightMatrix1to2[4][5] = nan;
   fWeightMatrix1to2[5][5] = nan;
   fWeightMatrix1to2[6][5] = nan;
   fWeightMatrix1to2[7][5] = nan;
   fWeightMatrix1to2[8][5] = nan;
   fWeightMatrix1to2[9][5] = nan;
   fWeightMatrix1to2[0][6] = nan;
   fWeightMatrix1to2[1][6] = nan;
   fWeightMatrix1to2[2][6] = nan;
   fWeightMatrix1to2[3][6] = nan;
   fWeightMatrix1to2[4][6] = nan;
   fWeightMatrix1to2[5][6] = nan;
   fWeightMatrix1to2[6][6] = nan;
   fWeightMatrix1to2[7][6] = nan;
   fWeightMatrix1to2[8][6] = nan;
   fWeightMatrix1to2[9][6] = nan;
   fWeightMatrix1to2[0][7] = -nan;
   fWeightMatrix1to2[1][7] = -nan;
   fWeightMatrix1to2[2][7] = -nan;
   fWeightMatrix1to2[3][7] = -nan;
   fWeightMatrix1to2[4][7] = -nan;
   fWeightMatrix1to2[5][7] = -nan;
   fWeightMatrix1to2[6][7] = -nan;
   fWeightMatrix1to2[7][7] = -nan;
   fWeightMatrix1to2[8][7] = -nan;
   fWeightMatrix1to2[9][7] = -nan;
   fWeightMatrix1to2[0][8] = nan;
   fWeightMatrix1to2[1][8] = nan;
   fWeightMatrix1to2[2][8] = nan;
   fWeightMatrix1to2[3][8] = nan;
   fWeightMatrix1to2[4][8] = nan;
   fWeightMatrix1to2[5][8] = nan;
   fWeightMatrix1to2[6][8] = nan;
   fWeightMatrix1to2[7][8] = nan;
   fWeightMatrix1to2[8][8] = nan;
   fWeightMatrix1to2[9][8] = nan;
   fWeightMatrix1to2[0][9] = -nan;
   fWeightMatrix1to2[1][9] = -nan;
   fWeightMatrix1to2[2][9] = -nan;
   fWeightMatrix1to2[3][9] = -nan;
   fWeightMatrix1to2[4][9] = -nan;
   fWeightMatrix1to2[5][9] = -nan;
   fWeightMatrix1to2[6][9] = -nan;
   fWeightMatrix1to2[7][9] = -nan;
   fWeightMatrix1to2[8][9] = -nan;
   fWeightMatrix1to2[9][9] = -nan;
   fWeightMatrix1to2[0][10] = nan;
   fWeightMatrix1to2[1][10] = nan;
   fWeightMatrix1to2[2][10] = nan;
   fWeightMatrix1to2[3][10] = nan;
   fWeightMatrix1to2[4][10] = nan;
   fWeightMatrix1to2[5][10] = nan;
   fWeightMatrix1to2[6][10] = nan;
   fWeightMatrix1to2[7][10] = nan;
   fWeightMatrix1to2[8][10] = nan;
   fWeightMatrix1to2[9][10] = nan;
   fWeightMatrix1to2[0][11] = -nan;
   fWeightMatrix1to2[1][11] = -nan;
   fWeightMatrix1to2[2][11] = -nan;
   fWeightMatrix1to2[3][11] = -nan;
   fWeightMatrix1to2[4][11] = -nan;
   fWeightMatrix1to2[5][11] = -nan;
   fWeightMatrix1to2[6][11] = -nan;
   fWeightMatrix1to2[7][11] = -nan;
   fWeightMatrix1to2[8][11] = -nan;
   fWeightMatrix1to2[9][11] = -nan;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -nan;
   fWeightMatrix2to3[0][1] = -nan;
   fWeightMatrix2to3[0][2] = -nan;
   fWeightMatrix2to3[0][3] = -nan;
   fWeightMatrix2to3[0][4] = -nan;
   fWeightMatrix2to3[0][5] = -nan;
   fWeightMatrix2to3[0][6] = -nan;
   fWeightMatrix2to3[0][7] = -nan;
   fWeightMatrix2to3[0][8] = -nan;
   fWeightMatrix2to3[0][9] = -nan;
   fWeightMatrix2to3[0][10] = nan;
}

inline double ReadH:!V:VarTransform=N:NCycles=500:HiddenLayers=N,N:TestRate=5:!UseRegulator:NeuronType=tanh::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)11) {
      std::cout << "Input vector needs to be of size " << 11 << std::endl;
      return 0;
   }

   std::array<double, 12> fWeights1 {{}};
   std::array<double, 11> fWeights2 {{}};
   std::array<double, 1> fWeights3 {{}};
   fWeights1.back() = 1.;
   fWeights2.back() = 1.;

   // layer 0 to 1
   for (int o=0; o<11; o++) {
      std::array<double, 12> buffer; // no need to initialise
      for (int i = 0; i<12 - 1; i++) {
         buffer[i] = fWeightMatrix0to1[o][i] * inputValues[i];
      } // loop over i
      buffer.back() = fWeightMatrix0to1[o][11];
      for (int i=0; i<12; i++) {
         fWeights1[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<11; o++) {
      fWeights1[o] = ActivationFnc(fWeights1[o]);
   } // loop over o
   // layer 1 to 2
   for (int o=0; o<10; o++) {
      std::array<double, 12> buffer; // no need to initialise
      for (int i=0; i<12; i++) {
         buffer[i] = fWeightMatrix1to2[o][i] * fWeights1[i];
      } // loop over i
      for (int i=0; i<12; i++) {
         fWeights2[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<10; o++) {
      fWeights2[o] = ActivationFnc(fWeights2[o]);
   } // loop over o
   // layer 2 to 3
   for (int o=0; o<1; o++) {
      std::array<double, 11> buffer; // no need to initialise
      for (int i=0; i<11; i++) {
         buffer[i] = fWeightMatrix2to3[o][i] * fWeights2[i];
      } // loop over i
      for (int i=0; i<11; i++) {
         fWeights3[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<1; o++) {
      fWeights3[o] = OutputActivationFnc(fWeights3[o]);
   } // loop over o

   return fWeights3[0];
}

double ReadH:!V:VarTransform=N:NCycles=500:HiddenLayers=N,N:TestRate=5:!UseRegulator:NeuronType=tanh::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadH:!V:VarTransform=N:NCycles=500:HiddenLayers=N,N:TestRate=5:!UseRegulator:NeuronType=tanh::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}

// Clean up
inline void ReadH:!V:VarTransform=N:NCycles=500:HiddenLayers=N,N:TestRate=5:!UseRegulator:NeuronType=tanh::Clear()
{
}
inline double ReadH:!V:VarTransform=N:NCycles=500:HiddenLayers=N,N:TestRate=5:!UseRegulator:NeuronType=tanh::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
