// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.22/06       [398854]
Creator        : konstantin
Date           : Thu Apr  1 19:56:32 2021
Host           : Linux mach 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/konstantin/Projects/CERN/TMVA_MLP
Training events: 170672
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "400" [Number of training cycles]
HiddenLayers: "N+10,N" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
TestRate: "5" [Test for overtraining performed at each #th epochs]
BPMode: "batch" [Back-propagation learning mode: sequential or batch]
BatchSize: "5" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "2.500000e-03" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "5" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
mJJ                           mJJ                           mJJ                           mJJ                                                             'F'    [22.7864818573,7838.75537109]
deltaYJJ                      deltaYJJ                      deltaYJJ                      deltaYJJ                                                        'F'    [2.2119609639e-05,8.68471050262]
metPt                         metPt                         metPt                         metPt                                                           'F'    [125.825294495,2277.4987793]
ptBalance                     ptBalance                     ptBalance                     ptBalance                                                       'F'    [4.91857872476e-06,0.47649076581]
subleadJetEta                 subleadJetEta                 subleadJetEta                 subleadJetEta                                                   'F'    [-4.50663423538,4.51134681702]
leadJetPt                     leadJetPt                     leadJetPt                     leadJetPt                                                       'F'    [50.0584754944,2753.2824707]
photonEta                     photonEta                     photonEta                     photonEta                                                       'F'    [-2.4010925293,2.39041256905]
ptBalanceRed                  ptBalanceRed                  ptBalanceRed                  ptBalanceRed                                                    'F'    [0.0229892414063,0.999983787537]
nJets                         nJets                         nJets                         nJets                                                           'F'    [2,9]
sinDeltaPhiJJOver2            sinDeltaPhiJJOver2            sinDeltaPhiJJOver2            sinDeltaPhiJJOver2                                              'F'    [1.5914440155e-05,1]
deltaYJPh                     deltaYJPh                     deltaYJPh                     deltaYJPh                                                       'F'    [1.18112052405e-06,6.68952894211]
NSpec 1
weightModified                weightModified                weightModified                F                                                               'F'    [-0.191263645887,1.09073340893]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 11 )
   {
      // the training input variables
      const char* inputVars[] = { "mJJ", "deltaYJJ", "metPt", "ptBalance", "subleadJetEta", "leadJetPt", "photonEta", "ptBalanceRed", "nJets", "sinDeltaPhiJJOver2", "deltaYJPh" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fOff_1[3][11];
   double fScal_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   double fWeightMatrix0to1[22][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][22];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][12];   // weight matrix from layer 2 to 3

};

inline void ReadMLP::Initialize()
{
   // build network structure
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.618729838540036;
   fWeightMatrix0to1[1][0] = 2.41779379082991;
   fWeightMatrix0to1[2][0] = 0.889567436479456;
   fWeightMatrix0to1[3][0] = 3.05932717502668;
   fWeightMatrix0to1[4][0] = -2.09106469715851;
   fWeightMatrix0to1[5][0] = 0.0860140653672697;
   fWeightMatrix0to1[6][0] = -0.0134185864565946;
   fWeightMatrix0to1[7][0] = 2.5972153565516;
   fWeightMatrix0to1[8][0] = -2.17700442957474;
   fWeightMatrix0to1[9][0] = -1.7729614237834;
   fWeightMatrix0to1[10][0] = -3.73106954940119;
   fWeightMatrix0to1[11][0] = -4.7742514626846;
   fWeightMatrix0to1[12][0] = -1.36327143414327;
   fWeightMatrix0to1[13][0] = 0.656729644600048;
   fWeightMatrix0to1[14][0] = -1.0259399396914;
   fWeightMatrix0to1[15][0] = -3.2719623680349;
   fWeightMatrix0to1[16][0] = 0.0596958050607786;
   fWeightMatrix0to1[17][0] = 1.64676721051894;
   fWeightMatrix0to1[18][0] = 0.229695998653509;
   fWeightMatrix0to1[19][0] = 1.63705378443286;
   fWeightMatrix0to1[20][0] = 0.642106801281067;
   fWeightMatrix0to1[0][1] = -2.98894346090875;
   fWeightMatrix0to1[1][1] = -0.670344793705572;
   fWeightMatrix0to1[2][1] = 0.1317560066271;
   fWeightMatrix0to1[3][1] = -2.76600813623656;
   fWeightMatrix0to1[4][1] = -1.67090300971479;
   fWeightMatrix0to1[5][1] = 3.81549813990053;
   fWeightMatrix0to1[6][1] = -2.46807328728707;
   fWeightMatrix0to1[7][1] = -1.41553231379535;
   fWeightMatrix0to1[8][1] = 1.31741845793332;
   fWeightMatrix0to1[9][1] = -0.933793153363589;
   fWeightMatrix0to1[10][1] = 3.10250786844848;
   fWeightMatrix0to1[11][1] = -1.24648432196814;
   fWeightMatrix0to1[12][1] = 0.340957838830226;
   fWeightMatrix0to1[13][1] = 0.266601428411495;
   fWeightMatrix0to1[14][1] = -3.49300413042077;
   fWeightMatrix0to1[15][1] = -2.15830185187707;
   fWeightMatrix0to1[16][1] = 1.98982168466554;
   fWeightMatrix0to1[17][1] = -1.42754083055657;
   fWeightMatrix0to1[18][1] = 0.644425591770933;
   fWeightMatrix0to1[19][1] = 1.77264762419008;
   fWeightMatrix0to1[20][1] = 3.16452754875433;
   fWeightMatrix0to1[0][2] = 2.20528716160389;
   fWeightMatrix0to1[1][2] = 2.11917665389357;
   fWeightMatrix0to1[2][2] = -1.27928118617569;
   fWeightMatrix0to1[3][2] = -0.0452657592392106;
   fWeightMatrix0to1[4][2] = 0.437214540050786;
   fWeightMatrix0to1[5][2] = 0.0486954300058082;
   fWeightMatrix0to1[6][2] = 1.50089056466558;
   fWeightMatrix0to1[7][2] = 1.55098475978205;
   fWeightMatrix0to1[8][2] = 1.42655007523655;
   fWeightMatrix0to1[9][2] = 1.38336721422528;
   fWeightMatrix0to1[10][2] = -2.39227556571661;
   fWeightMatrix0to1[11][2] = 1.4826599852556;
   fWeightMatrix0to1[12][2] = -0.800954087180678;
   fWeightMatrix0to1[13][2] = -1.70726177483914;
   fWeightMatrix0to1[14][2] = -2.25782466318261;
   fWeightMatrix0to1[15][2] = -1.43606664288423;
   fWeightMatrix0to1[16][2] = 1.26563500449567;
   fWeightMatrix0to1[17][2] = 1.08207897129392;
   fWeightMatrix0to1[18][2] = -1.37640260404303;
   fWeightMatrix0to1[19][2] = 0.257400012482372;
   fWeightMatrix0to1[20][2] = 1.16605757028956;
   fWeightMatrix0to1[0][3] = 1.0599625929598;
   fWeightMatrix0to1[1][3] = 3.7638922548948;
   fWeightMatrix0to1[2][3] = 0.62265918431145;
   fWeightMatrix0to1[3][3] = 0.413435964008817;
   fWeightMatrix0to1[4][3] = 0.133159728678529;
   fWeightMatrix0to1[5][3] = 0.57040123017003;
   fWeightMatrix0to1[6][3] = -0.993437744191914;
   fWeightMatrix0to1[7][3] = -0.476729163561646;
   fWeightMatrix0to1[8][3] = -1.02672524684693;
   fWeightMatrix0to1[9][3] = 1.08759518410807;
   fWeightMatrix0to1[10][3] = 2.13046084522241;
   fWeightMatrix0to1[11][3] = 1.36347888410801;
   fWeightMatrix0to1[12][3] = -0.148295574176034;
   fWeightMatrix0to1[13][3] = -1.86041813298641;
   fWeightMatrix0to1[14][3] = 0.164848897994773;
   fWeightMatrix0to1[15][3] = 3.1767519253596;
   fWeightMatrix0to1[16][3] = -0.49520313166888;
   fWeightMatrix0to1[17][3] = 2.69305479715412;
   fWeightMatrix0to1[18][3] = 0.700506888148388;
   fWeightMatrix0to1[19][3] = 0.883332277291933;
   fWeightMatrix0to1[20][3] = -0.695534878082012;
   fWeightMatrix0to1[0][4] = -2.42193169438129;
   fWeightMatrix0to1[1][4] = 0.118872669018317;
   fWeightMatrix0to1[2][4] = 1.60377162806998;
   fWeightMatrix0to1[3][4] = -0.318079697606988;
   fWeightMatrix0to1[4][4] = -0.991865563695894;
   fWeightMatrix0to1[5][4] = -0.794262137374771;
   fWeightMatrix0to1[6][4] = -0.291980421304087;
   fWeightMatrix0to1[7][4] = 0.211719628381604;
   fWeightMatrix0to1[8][4] = 1.58175628455801;
   fWeightMatrix0to1[9][4] = -2.06928073948939;
   fWeightMatrix0to1[10][4] = -0.521404494134686;
   fWeightMatrix0to1[11][4] = 1.45541542242809;
   fWeightMatrix0to1[12][4] = -0.824205616402744;
   fWeightMatrix0to1[13][4] = 0.638607475543799;
   fWeightMatrix0to1[14][4] = -3.98478542077132;
   fWeightMatrix0to1[15][4] = -0.29135115631001;
   fWeightMatrix0to1[16][4] = -1.57265123419101;
   fWeightMatrix0to1[17][4] = -1.74432269662627;
   fWeightMatrix0to1[18][4] = 1.17621602162978;
   fWeightMatrix0to1[19][4] = 1.13845555483608;
   fWeightMatrix0to1[20][4] = -3.42847501499449;
   fWeightMatrix0to1[0][5] = 2.13824707995111;
   fWeightMatrix0to1[1][5] = -1.43707139321193;
   fWeightMatrix0to1[2][5] = -0.267994535944763;
   fWeightMatrix0to1[3][5] = 0.933890177832508;
   fWeightMatrix0to1[4][5] = 1.25931978931357;
   fWeightMatrix0to1[5][5] = -1.67789036475062;
   fWeightMatrix0to1[6][5] = -0.533319478907252;
   fWeightMatrix0to1[7][5] = 0.722070829966427;
   fWeightMatrix0to1[8][5] = -0.259431358834387;
   fWeightMatrix0to1[9][5] = -0.453483651521978;
   fWeightMatrix0to1[10][5] = 1.15150807594384;
   fWeightMatrix0to1[11][5] = -0.267068453867308;
   fWeightMatrix0to1[12][5] = -0.644852618957238;
   fWeightMatrix0to1[13][5] = 1.27638002504119;
   fWeightMatrix0to1[14][5] = 0.228223255521303;
   fWeightMatrix0to1[15][5] = -2.64971997788333;
   fWeightMatrix0to1[16][5] = 0.261092561222852;
   fWeightMatrix0to1[17][5] = -0.467934567573967;
   fWeightMatrix0to1[18][5] = 2.44273186848143;
   fWeightMatrix0to1[19][5] = 0.606586057687606;
   fWeightMatrix0to1[20][5] = -1.49274860947523;
   fWeightMatrix0to1[0][6] = -0.309722733565948;
   fWeightMatrix0to1[1][6] = 0.0342121213941856;
   fWeightMatrix0to1[2][6] = -2.64720480005466;
   fWeightMatrix0to1[3][6] = 0.44243478388557;
   fWeightMatrix0to1[4][6] = 0.724341295702712;
   fWeightMatrix0to1[5][6] = -0.463315468095071;
   fWeightMatrix0to1[6][6] = -0.613955066557822;
   fWeightMatrix0to1[7][6] = -1.17616969642516;
   fWeightMatrix0to1[8][6] = 0.622544588546806;
   fWeightMatrix0to1[9][6] = 1.2376832911204;
   fWeightMatrix0to1[10][6] = 0.72937631693123;
   fWeightMatrix0to1[11][6] = -1.02313265448578;
   fWeightMatrix0to1[12][6] = 0.08959650748845;
   fWeightMatrix0to1[13][6] = 1.95881385001165;
   fWeightMatrix0to1[14][6] = 1.7519900548066;
   fWeightMatrix0to1[15][6] = 0.325057042459925;
   fWeightMatrix0to1[16][6] = -1.85039443269005;
   fWeightMatrix0to1[17][6] = -1.33370155021224;
   fWeightMatrix0to1[18][6] = -1.34782815982366;
   fWeightMatrix0to1[19][6] = 0.812419271982022;
   fWeightMatrix0to1[20][6] = 1.83115481058457;
   fWeightMatrix0to1[0][7] = -0.419181692705021;
   fWeightMatrix0to1[1][7] = 0.0289787038421353;
   fWeightMatrix0to1[2][7] = -0.288566096097402;
   fWeightMatrix0to1[3][7] = -0.96234217193685;
   fWeightMatrix0to1[4][7] = 0.227163479468047;
   fWeightMatrix0to1[5][7] = 0.413447463118365;
   fWeightMatrix0to1[6][7] = 0.598586495965846;
   fWeightMatrix0to1[7][7] = -1.47606825268022;
   fWeightMatrix0to1[8][7] = 0.364414799734797;
   fWeightMatrix0to1[9][7] = 0.286205475101805;
   fWeightMatrix0to1[10][7] = -0.412650551536241;
   fWeightMatrix0to1[11][7] = -0.378971981833771;
   fWeightMatrix0to1[12][7] = -0.685682212726896;
   fWeightMatrix0to1[13][7] = 1.12919167991402;
   fWeightMatrix0to1[14][7] = 0.142854246630972;
   fWeightMatrix0to1[15][7] = 0.894757103649828;
   fWeightMatrix0to1[16][7] = 0.0677922141896538;
   fWeightMatrix0to1[17][7] = 1.08214180929566;
   fWeightMatrix0to1[18][7] = 1.04318563955043;
   fWeightMatrix0to1[19][7] = -0.0903370627868182;
   fWeightMatrix0to1[20][7] = 0.0398423304546354;
   fWeightMatrix0to1[0][8] = -0.630788966275372;
   fWeightMatrix0to1[1][8] = 0.147670498112801;
   fWeightMatrix0to1[2][8] = 2.67748680548628;
   fWeightMatrix0to1[3][8] = 1.44947435416151;
   fWeightMatrix0to1[4][8] = -0.209967981231345;
   fWeightMatrix0to1[5][8] = 0.981919538733381;
   fWeightMatrix0to1[6][8] = 1.58240315149137;
   fWeightMatrix0to1[7][8] = -1.50922500261438;
   fWeightMatrix0to1[8][8] = 0.887282121531352;
   fWeightMatrix0to1[9][8] = 0.532745127526746;
   fWeightMatrix0to1[10][8] = -0.0739249033115677;
   fWeightMatrix0to1[11][8] = -2.44975037279531;
   fWeightMatrix0to1[12][8] = -1.65842312366257;
   fWeightMatrix0to1[13][8] = 2.35491292035695;
   fWeightMatrix0to1[14][8] = 2.50027783796232;
   fWeightMatrix0to1[15][8] = -0.639587377997258;
   fWeightMatrix0to1[16][8] = -1.00068410086253;
   fWeightMatrix0to1[17][8] = -0.610520365095497;
   fWeightMatrix0to1[18][8] = 1.14132929004624;
   fWeightMatrix0to1[19][8] = 1.22365999871461;
   fWeightMatrix0to1[20][8] = -2.58981312620067;
   fWeightMatrix0to1[0][9] = -0.168086618689434;
   fWeightMatrix0to1[1][9] = -0.21970784149733;
   fWeightMatrix0to1[2][9] = 1.29671291798757;
   fWeightMatrix0to1[3][9] = 0.753767529297308;
   fWeightMatrix0to1[4][9] = 3.15717893914768;
   fWeightMatrix0to1[5][9] = 0.633572777242109;
   fWeightMatrix0to1[6][9] = -1.97922058095464;
   fWeightMatrix0to1[7][9] = -0.799856773491055;
   fWeightMatrix0to1[8][9] = 0.79930092206994;
   fWeightMatrix0to1[9][9] = 0.526998599981243;
   fWeightMatrix0to1[10][9] = -0.991864433394388;
   fWeightMatrix0to1[11][9] = 0.082092237920592;
   fWeightMatrix0to1[12][9] = 0.185865101490172;
   fWeightMatrix0to1[13][9] = -0.0307054778444863;
   fWeightMatrix0to1[14][9] = 0.000995661947090157;
   fWeightMatrix0to1[15][9] = 0.0473383249493675;
   fWeightMatrix0to1[16][9] = 0.0533180423241661;
   fWeightMatrix0to1[17][9] = -0.823607911818852;
   fWeightMatrix0to1[18][9] = 0.127952351930817;
   fWeightMatrix0to1[19][9] = 1.54715332099902;
   fWeightMatrix0to1[20][9] = -0.00301030079143683;
   fWeightMatrix0to1[0][10] = -0.218798610097722;
   fWeightMatrix0to1[1][10] = 0.522617741969204;
   fWeightMatrix0to1[2][10] = -2.07193797168254;
   fWeightMatrix0to1[3][10] = -0.114411603244983;
   fWeightMatrix0to1[4][10] = 1.25031968429541;
   fWeightMatrix0to1[5][10] = 0.852840270768809;
   fWeightMatrix0to1[6][10] = 0.608794216462296;
   fWeightMatrix0to1[7][10] = 0.423422503311917;
   fWeightMatrix0to1[8][10] = 2.05549057822913;
   fWeightMatrix0to1[9][10] = -3.37358688983724;
   fWeightMatrix0to1[10][10] = -0.843839028776732;
   fWeightMatrix0to1[11][10] = 0.430394798035067;
   fWeightMatrix0to1[12][10] = -1.66433082168528;
   fWeightMatrix0to1[13][10] = -0.560691155346929;
   fWeightMatrix0to1[14][10] = 2.77006048976948;
   fWeightMatrix0to1[15][10] = -0.183393298783315;
   fWeightMatrix0to1[16][10] = -0.241321279393089;
   fWeightMatrix0to1[17][10] = 0.409140448545475;
   fWeightMatrix0to1[18][10] = -1.87982603040179;
   fWeightMatrix0to1[19][10] = -1.57759575224091;
   fWeightMatrix0to1[20][10] = -2.24071471167936;
   fWeightMatrix0to1[0][11] = 0.00529835378652813;
   fWeightMatrix0to1[1][11] = 5.9142405751449;
   fWeightMatrix0to1[2][11] = -1.39732693971522;
   fWeightMatrix0to1[3][11] = 3.77989018253451;
   fWeightMatrix0to1[4][11] = -4.7558403946205;
   fWeightMatrix0to1[5][11] = 3.24659479624632;
   fWeightMatrix0to1[6][11] = 0.367626638526948;
   fWeightMatrix0to1[7][11] = -2.05735851538082;
   fWeightMatrix0to1[8][11] = -1.25831819744004;
   fWeightMatrix0to1[9][11] = -5.21456386503881;
   fWeightMatrix0to1[10][11] = -1.85011806301762;
   fWeightMatrix0to1[11][11] = -5.47142616976392;
   fWeightMatrix0to1[12][11] = -2.78535515555723;
   fWeightMatrix0to1[13][11] = -0.933953802579222;
   fWeightMatrix0to1[14][11] = -1.83195439117342;
   fWeightMatrix0to1[15][11] = -5.44526610031395;
   fWeightMatrix0to1[16][11] = -1.68832520030834;
   fWeightMatrix0to1[17][11] = 0.530613492215387;
   fWeightMatrix0to1[18][11] = -0.8354695822922;
   fWeightMatrix0to1[19][11] = 0.579383620176436;
   fWeightMatrix0to1[20][11] = -0.842298338451498;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.856608820327922;
   fWeightMatrix1to2[1][0] = 2.02431373590359;
   fWeightMatrix1to2[2][0] = 1.65260687470944;
   fWeightMatrix1to2[3][0] = -0.509328465382492;
   fWeightMatrix1to2[4][0] = -0.461746201173328;
   fWeightMatrix1to2[5][0] = -1.89891389068583;
   fWeightMatrix1to2[6][0] = -0.523161289585912;
   fWeightMatrix1to2[7][0] = -3.1120626339876;
   fWeightMatrix1to2[8][0] = 2.12944728834391;
   fWeightMatrix1to2[9][0] = 0.190047950334095;
   fWeightMatrix1to2[10][0] = 1.93135375859473;
   fWeightMatrix1to2[0][1] = -1.29904555227213;
   fWeightMatrix1to2[1][1] = 0.738575860793892;
   fWeightMatrix1to2[2][1] = -0.281227645819982;
   fWeightMatrix1to2[3][1] = -1.44826244623911;
   fWeightMatrix1to2[4][1] = 0.73404391885553;
   fWeightMatrix1to2[5][1] = 1.26309402881444;
   fWeightMatrix1to2[6][1] = -0.881285394102506;
   fWeightMatrix1to2[7][1] = -4.0585743587351;
   fWeightMatrix1to2[8][1] = -0.447487785488791;
   fWeightMatrix1to2[9][1] = 3.54624869352762;
   fWeightMatrix1to2[10][1] = 0.514334309491776;
   fWeightMatrix1to2[0][2] = -0.443313073766519;
   fWeightMatrix1to2[1][2] = 0.262573631836346;
   fWeightMatrix1to2[2][2] = 1.30019043321694;
   fWeightMatrix1to2[3][2] = 1.69404686142888;
   fWeightMatrix1to2[4][2] = 0.97919129229745;
   fWeightMatrix1to2[5][2] = -1.1856592299018;
   fWeightMatrix1to2[6][2] = 1.03876750014867;
   fWeightMatrix1to2[7][2] = -0.363489009751868;
   fWeightMatrix1to2[8][2] = -2.40113210776741;
   fWeightMatrix1to2[9][2] = -0.572643613252516;
   fWeightMatrix1to2[10][2] = -1.74183798311521;
   fWeightMatrix1to2[0][3] = -0.450498399405742;
   fWeightMatrix1to2[1][3] = -0.803463131561333;
   fWeightMatrix1to2[2][3] = 2.13699519265379;
   fWeightMatrix1to2[3][3] = -1.92844226182343;
   fWeightMatrix1to2[4][3] = 0.584123635074967;
   fWeightMatrix1to2[5][3] = -1.51357481301436;
   fWeightMatrix1to2[6][3] = 0.525647365641945;
   fWeightMatrix1to2[7][3] = -1.78844559293123;
   fWeightMatrix1to2[8][3] = 0.830194284938036;
   fWeightMatrix1to2[9][3] = 3.67245784230851;
   fWeightMatrix1to2[10][3] = -1.80683932501818;
   fWeightMatrix1to2[0][4] = 0.718903470866252;
   fWeightMatrix1to2[1][4] = 0.644460490251334;
   fWeightMatrix1to2[2][4] = -2.04924253313039;
   fWeightMatrix1to2[3][4] = -1.31899475888426;
   fWeightMatrix1to2[4][4] = -1.30436117421596;
   fWeightMatrix1to2[5][4] = -0.95066338014715;
   fWeightMatrix1to2[6][4] = 2.25388776712261;
   fWeightMatrix1to2[7][4] = -1.73378434684349;
   fWeightMatrix1to2[8][4] = -0.510413335447637;
   fWeightMatrix1to2[9][4] = -2.19211127890016;
   fWeightMatrix1to2[10][4] = -1.1534041173474;
   fWeightMatrix1to2[0][5] = -1.80496934718578;
   fWeightMatrix1to2[1][5] = -0.333566399207325;
   fWeightMatrix1to2[2][5] = -1.27893215670406;
   fWeightMatrix1to2[3][5] = 1.23088291184159;
   fWeightMatrix1to2[4][5] = -0.0518476131642678;
   fWeightMatrix1to2[5][5] = -1.53279071868666;
   fWeightMatrix1to2[6][5] = 2.28888065833388;
   fWeightMatrix1to2[7][5] = 0.2458685090192;
   fWeightMatrix1to2[8][5] = -0.505372513111852;
   fWeightMatrix1to2[9][5] = 2.3769544472076;
   fWeightMatrix1to2[10][5] = -1.81317029510492;
   fWeightMatrix1to2[0][6] = 1.35312253144582;
   fWeightMatrix1to2[1][6] = 1.19120781134417;
   fWeightMatrix1to2[2][6] = -0.83851654540284;
   fWeightMatrix1to2[3][6] = -0.148120820958575;
   fWeightMatrix1to2[4][6] = 0.277745566703591;
   fWeightMatrix1to2[5][6] = -0.379493456417701;
   fWeightMatrix1to2[6][6] = -0.780293380280726;
   fWeightMatrix1to2[7][6] = 0.458010169426647;
   fWeightMatrix1to2[8][6] = 2.01456323789331;
   fWeightMatrix1to2[9][6] = 2.42277466080995;
   fWeightMatrix1to2[10][6] = -1.35758188159572;
   fWeightMatrix1to2[0][7] = 0.789664356810766;
   fWeightMatrix1to2[1][7] = -1.76906523125979;
   fWeightMatrix1to2[2][7] = 0.606602836051214;
   fWeightMatrix1to2[3][7] = -1.72809493815039;
   fWeightMatrix1to2[4][7] = -1.76120910978755;
   fWeightMatrix1to2[5][7] = 0.0832983711809064;
   fWeightMatrix1to2[6][7] = 1.09395245766726;
   fWeightMatrix1to2[7][7] = 0.34351990937237;
   fWeightMatrix1to2[8][7] = 0.745919058393092;
   fWeightMatrix1to2[9][7] = 0.673970421148711;
   fWeightMatrix1to2[10][7] = -0.190664564440305;
   fWeightMatrix1to2[0][8] = 0.606784997345917;
   fWeightMatrix1to2[1][8] = 0.252685917696816;
   fWeightMatrix1to2[2][8] = 1.82721099070916;
   fWeightMatrix1to2[3][8] = -1.43369073419545;
   fWeightMatrix1to2[4][8] = 0.249512914417648;
   fWeightMatrix1to2[5][8] = -0.711313993014659;
   fWeightMatrix1to2[6][8] = -1.00234447719392;
   fWeightMatrix1to2[7][8] = -0.629525680246466;
   fWeightMatrix1to2[8][8] = -0.0992143566577376;
   fWeightMatrix1to2[9][8] = -1.55520118206178;
   fWeightMatrix1to2[10][8] = 0.975052653628448;
   fWeightMatrix1to2[0][9] = 3.04685011233942;
   fWeightMatrix1to2[1][9] = 0.764049598593681;
   fWeightMatrix1to2[2][9] = 0.386575444711205;
   fWeightMatrix1to2[3][9] = -1.03513160383447;
   fWeightMatrix1to2[4][9] = -1.99211815492435;
   fWeightMatrix1to2[5][9] = -1.85246327322735;
   fWeightMatrix1to2[6][9] = 1.08474867411374;
   fWeightMatrix1to2[7][9] = -2.41162261443091;
   fWeightMatrix1to2[8][9] = 0.153394679864343;
   fWeightMatrix1to2[9][9] = 0.210806355502946;
   fWeightMatrix1to2[10][9] = -1.68912048780633;
   fWeightMatrix1to2[0][10] = -0.91601290342139;
   fWeightMatrix1to2[1][10] = -1.48348825953311;
   fWeightMatrix1to2[2][10] = 1.04119039089903;
   fWeightMatrix1to2[3][10] = -1.13503193743206;
   fWeightMatrix1to2[4][10] = -2.43906703206577;
   fWeightMatrix1to2[5][10] = -0.649428653108615;
   fWeightMatrix1to2[6][10] = -0.291421161954032;
   fWeightMatrix1to2[7][10] = -2.66761878443504;
   fWeightMatrix1to2[8][10] = -0.164957543949697;
   fWeightMatrix1to2[9][10] = -3.04781089918695;
   fWeightMatrix1to2[10][10] = -1.25364035067663;
   fWeightMatrix1to2[0][11] = 3.03901171609101;
   fWeightMatrix1to2[1][11] = 0.489928492129591;
   fWeightMatrix1to2[2][11] = 0.0809523280259507;
   fWeightMatrix1to2[3][11] = 1.10196887032603;
   fWeightMatrix1to2[4][11] = 1.81673737474073;
   fWeightMatrix1to2[5][11] = 2.04052645428238;
   fWeightMatrix1to2[6][11] = -0.173110571841836;
   fWeightMatrix1to2[7][11] = -3.24594302376237;
   fWeightMatrix1to2[8][11] = -0.9084106131442;
   fWeightMatrix1to2[9][11] = -2.15859674413237;
   fWeightMatrix1to2[10][11] = 0.958787929039739;
   fWeightMatrix1to2[0][12] = 0.3810484238819;
   fWeightMatrix1to2[1][12] = 0.0994206971160968;
   fWeightMatrix1to2[2][12] = 1.44141975338753;
   fWeightMatrix1to2[3][12] = 0.464644515304819;
   fWeightMatrix1to2[4][12] = 2.68271325609056;
   fWeightMatrix1to2[5][12] = -1.53255755007023;
   fWeightMatrix1to2[6][12] = 2.0402370143464;
   fWeightMatrix1to2[7][12] = 1.27805990162872;
   fWeightMatrix1to2[8][12] = -2.38242073585707;
   fWeightMatrix1to2[9][12] = 0.516222936469195;
   fWeightMatrix1to2[10][12] = -0.997772203213884;
   fWeightMatrix1to2[0][13] = 1.18099956463402;
   fWeightMatrix1to2[1][13] = 0.736260750089831;
   fWeightMatrix1to2[2][13] = 1.23899032513891;
   fWeightMatrix1to2[3][13] = 1.89255901088169;
   fWeightMatrix1to2[4][13] = -0.916997391538569;
   fWeightMatrix1to2[5][13] = 2.08251517933062;
   fWeightMatrix1to2[6][13] = 1.04228346492559;
   fWeightMatrix1to2[7][13] = 1.27306622303361;
   fWeightMatrix1to2[8][13] = -2.30598240792146;
   fWeightMatrix1to2[9][13] = 1.45216867495322;
   fWeightMatrix1to2[10][13] = -1.9576889514713;
   fWeightMatrix1to2[0][14] = 3.37966010622129;
   fWeightMatrix1to2[1][14] = 2.24687923565383;
   fWeightMatrix1to2[2][14] = -0.0697352125547949;
   fWeightMatrix1to2[3][14] = 0.677697901950209;
   fWeightMatrix1to2[4][14] = -0.849847272703669;
   fWeightMatrix1to2[5][14] = -1.73034388488597;
   fWeightMatrix1to2[6][14] = 0.673056546354041;
   fWeightMatrix1to2[7][14] = -3.44592033279273;
   fWeightMatrix1to2[8][14] = 1.90889872541813;
   fWeightMatrix1to2[9][14] = 0.0182751659356259;
   fWeightMatrix1to2[10][14] = 1.66216838642745;
   fWeightMatrix1to2[0][15] = 1.1916806117637;
   fWeightMatrix1to2[1][15] = 1.59166494310098;
   fWeightMatrix1to2[2][15] = -0.255675605647139;
   fWeightMatrix1to2[3][15] = 0.645474365963576;
   fWeightMatrix1to2[4][15] = 0.511509960059221;
   fWeightMatrix1to2[5][15] = 1.45203837808312;
   fWeightMatrix1to2[6][15] = -1.86303113154199;
   fWeightMatrix1to2[7][15] = -1.89134950002145;
   fWeightMatrix1to2[8][15] = 0.981285351930349;
   fWeightMatrix1to2[9][15] = -3.64557084054485;
   fWeightMatrix1to2[10][15] = -1.66450658409735;
   fWeightMatrix1to2[0][16] = -0.833130664472877;
   fWeightMatrix1to2[1][16] = 0.959342221865043;
   fWeightMatrix1to2[2][16] = -0.134422557016496;
   fWeightMatrix1to2[3][16] = -2.17333137087368;
   fWeightMatrix1to2[4][16] = -2.74898242605961;
   fWeightMatrix1to2[5][16] = -0.253216689740673;
   fWeightMatrix1to2[6][16] = 1.92986408142468;
   fWeightMatrix1to2[7][16] = 0.683176823727997;
   fWeightMatrix1to2[8][16] = 0.18591131000526;
   fWeightMatrix1to2[9][16] = -0.969689910408637;
   fWeightMatrix1to2[10][16] = -1.93450311778865;
   fWeightMatrix1to2[0][17] = -0.558454408493422;
   fWeightMatrix1to2[1][17] = -0.918782577607268;
   fWeightMatrix1to2[2][17] = -1.51949362330331;
   fWeightMatrix1to2[3][17] = 0.0973807938241965;
   fWeightMatrix1to2[4][17] = 0.0995225024183261;
   fWeightMatrix1to2[5][17] = -1.95608771235061;
   fWeightMatrix1to2[6][17] = 1.9434445122037;
   fWeightMatrix1to2[7][17] = 0.248859048414369;
   fWeightMatrix1to2[8][17] = 0.647158422119386;
   fWeightMatrix1to2[9][17] = 0.329816072382571;
   fWeightMatrix1to2[10][17] = -0.852425207390339;
   fWeightMatrix1to2[0][18] = 2.10240757879025;
   fWeightMatrix1to2[1][18] = -0.244654923787687;
   fWeightMatrix1to2[2][18] = 0.199137348878425;
   fWeightMatrix1to2[3][18] = 1.97052090262436;
   fWeightMatrix1to2[4][18] = 1.03102896173806;
   fWeightMatrix1to2[5][18] = -1.18539279957303;
   fWeightMatrix1to2[6][18] = 1.41219092915008;
   fWeightMatrix1to2[7][18] = -2.11557164882126;
   fWeightMatrix1to2[8][18] = 1.01469691437322;
   fWeightMatrix1to2[9][18] = 2.30521193699236;
   fWeightMatrix1to2[10][18] = -0.153626141569218;
   fWeightMatrix1to2[0][19] = -0.749284515658208;
   fWeightMatrix1to2[1][19] = 0.53275053463478;
   fWeightMatrix1to2[2][19] = -0.749232925780003;
   fWeightMatrix1to2[3][19] = 1.04964950890415;
   fWeightMatrix1to2[4][19] = -0.109496099027954;
   fWeightMatrix1to2[5][19] = -0.901185143997973;
   fWeightMatrix1to2[6][19] = -0.981451562192096;
   fWeightMatrix1to2[7][19] = -0.611620482550223;
   fWeightMatrix1to2[8][19] = -0.100975066704911;
   fWeightMatrix1to2[9][19] = 0.752643629187142;
   fWeightMatrix1to2[10][19] = -0.727217325871495;
   fWeightMatrix1to2[0][20] = -3.14146585246371;
   fWeightMatrix1to2[1][20] = 1.63133899880134;
   fWeightMatrix1to2[2][20] = 1.02320762175571;
   fWeightMatrix1to2[3][20] = -2.38001360066166;
   fWeightMatrix1to2[4][20] = 1.98165377035162;
   fWeightMatrix1to2[5][20] = -2.00201108557148;
   fWeightMatrix1to2[6][20] = 2.02115645106698;
   fWeightMatrix1to2[7][20] = 3.73988581080575;
   fWeightMatrix1to2[8][20] = 0.148604798128659;
   fWeightMatrix1to2[9][20] = -0.388880381797052;
   fWeightMatrix1to2[10][20] = 1.63391023089772;
   fWeightMatrix1to2[0][21] = 1.39981459718198;
   fWeightMatrix1to2[1][21] = 0.752379532096262;
   fWeightMatrix1to2[2][21] = 0.360517838935271;
   fWeightMatrix1to2[3][21] = -1.28261947701789;
   fWeightMatrix1to2[4][21] = -1.02424827830688;
   fWeightMatrix1to2[5][21] = 1.46388495360007;
   fWeightMatrix1to2[6][21] = 0.117822494938742;
   fWeightMatrix1to2[7][21] = 0.0453430781013396;
   fWeightMatrix1to2[8][21] = -3.41020774866874;
   fWeightMatrix1to2[9][21] = -0.556410257346825;
   fWeightMatrix1to2[10][21] = -1.87382584009218;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -3.27558463593323;
   fWeightMatrix2to3[0][1] = -1.29452287251009;
   fWeightMatrix2to3[0][2] = 0.691335722509553;
   fWeightMatrix2to3[0][3] = -2.29165943441354;
   fWeightMatrix2to3[0][4] = 2.48252930321133;
   fWeightMatrix2to3[0][5] = 1.77105190987222;
   fWeightMatrix2to3[0][6] = -2.57840849200897;
   fWeightMatrix2to3[0][7] = 4.41278831229164;
   fWeightMatrix2to3[0][8] = 3.54030000397255;
   fWeightMatrix2to3[0][9] = 3.66063906791649;
   fWeightMatrix2to3[0][10] = -0.610512720220397;
   fWeightMatrix2to3[0][11] = -1.34028852329873;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)11) {
      std::cout << "Input vector needs to be of size " << 11 << std::endl;
      return 0;
   }

   std::array<double, 22> fWeights1 {{}};
   std::array<double, 12> fWeights2 {{}};
   std::array<double, 1> fWeights3 {{}};
   fWeights1.back() = 1.;
   fWeights2.back() = 1.;

   // layer 0 to 1
   for (int o=0; o<21; o++) {
      std::array<double, 12> buffer; // no need to initialise
      for (int i = 0; i<12 - 1; i++) {
         buffer[i] = fWeightMatrix0to1[o][i] * inputValues[i];
      } // loop over i
      buffer.back() = fWeightMatrix0to1[o][11];
      for (int i=0; i<12; i++) {
         fWeights1[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<21; o++) {
      fWeights1[o] = ActivationFnc(fWeights1[o]);
   } // loop over o
   // layer 1 to 2
   for (int o=0; o<11; o++) {
      std::array<double, 22> buffer; // no need to initialise
      for (int i=0; i<22; i++) {
         buffer[i] = fWeightMatrix1to2[o][i] * fWeights1[i];
      } // loop over i
      for (int i=0; i<22; i++) {
         fWeights2[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<11; o++) {
      fWeights2[o] = ActivationFnc(fWeights2[o]);
   } // loop over o
   // layer 2 to 3
   for (int o=0; o<1; o++) {
      std::array<double, 12> buffer; // no need to initialise
      for (int i=0; i<12; i++) {
         buffer[i] = fWeightMatrix2to3[o][i] * fWeights2[i];
      } // loop over i
      for (int i=0; i<12; i++) {
         fWeights3[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<1; o++) {
      fWeights3[o] = OutputActivationFnc(fWeights3[o]);
   } // loop over o

   return fWeights3[0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}

// Clean up
inline void ReadMLP::Clear()
{
}
inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         std::vector<double> iV(inputValues);
         Transform( iV, -1 );
         retval = GetMvaValue__( iV );
   }

   return retval;
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   double fMin_1[3][11];
   double fMax_1[3][11];
   // Normalization transformation, initialisation
   fMin_1[0][0] = 22.7864818573;
   fMax_1[0][0] = 7505.73046875;
   fScal_1[0][0] = 2.0/(fMax_1[0][0]-fMin_1[0][0]);
   fOff_1[0][0] = fMin_1[0][0]*fScal_1[0][0]+1.;
   fMin_1[1][0] = 23.5563087463;
   fMax_1[1][0] = 7838.75537109;
   fScal_1[1][0] = 2.0/(fMax_1[1][0]-fMin_1[1][0]);
   fOff_1[1][0] = fMin_1[1][0]*fScal_1[1][0]+1.;
   fMin_1[2][0] = 22.7864818573;
   fMax_1[2][0] = 7838.75537109;
   fScal_1[2][0] = 2.0/(fMax_1[2][0]-fMin_1[2][0]);
   fOff_1[2][0] = fMin_1[2][0]*fScal_1[2][0]+1.;
   fMin_1[0][1] = 0.000150358115206;
   fMax_1[0][1] = 8.68471050262;
   fScal_1[0][1] = 2.0/(fMax_1[0][1]-fMin_1[0][1]);
   fOff_1[0][1] = fMin_1[0][1]*fScal_1[0][1]+1.;
   fMin_1[1][1] = 2.2119609639e-05;
   fMax_1[1][1] = 8.68384933472;
   fScal_1[1][1] = 2.0/(fMax_1[1][1]-fMin_1[1][1]);
   fOff_1[1][1] = fMin_1[1][1]*fScal_1[1][1]+1.;
   fMin_1[2][1] = 2.2119609639e-05;
   fMax_1[2][1] = 8.68471050262;
   fScal_1[2][1] = 2.0/(fMax_1[2][1]-fMin_1[2][1]);
   fOff_1[2][1] = fMin_1[2][1]*fScal_1[2][1]+1.;
   fMin_1[0][2] = 126.97845459;
   fMax_1[0][2] = 2277.4987793;
   fScal_1[0][2] = 2.0/(fMax_1[0][2]-fMin_1[0][2]);
   fOff_1[0][2] = fMin_1[0][2]*fScal_1[0][2]+1.;
   fMin_1[1][2] = 125.825294495;
   fMax_1[1][2] = 1926.56140137;
   fScal_1[1][2] = 2.0/(fMax_1[1][2]-fMin_1[1][2]);
   fOff_1[1][2] = fMin_1[1][2]*fScal_1[1][2]+1.;
   fMin_1[2][2] = 125.825294495;
   fMax_1[2][2] = 2277.4987793;
   fScal_1[2][2] = 2.0/(fMax_1[2][2]-fMin_1[2][2]);
   fOff_1[2][2] = fMin_1[2][2]*fScal_1[2][2]+1.;
   fMin_1[0][3] = 4.91857872476e-06;
   fMax_1[0][3] = 0.405025333166;
   fScal_1[0][3] = 2.0/(fMax_1[0][3]-fMin_1[0][3]);
   fOff_1[0][3] = fMin_1[0][3]*fScal_1[0][3]+1.;
   fMin_1[1][3] = 5.9500340285e-05;
   fMax_1[1][3] = 0.47649076581;
   fScal_1[1][3] = 2.0/(fMax_1[1][3]-fMin_1[1][3]);
   fOff_1[1][3] = fMin_1[1][3]*fScal_1[1][3]+1.;
   fMin_1[2][3] = 4.91857872476e-06;
   fMax_1[2][3] = 0.47649076581;
   fScal_1[2][3] = 2.0/(fMax_1[2][3]-fMin_1[2][3]);
   fOff_1[2][3] = fMin_1[2][3]*fScal_1[2][3]+1.;
   fMin_1[0][4] = -4.50663423538;
   fMax_1[0][4] = 4.51134681702;
   fScal_1[0][4] = 2.0/(fMax_1[0][4]-fMin_1[0][4]);
   fOff_1[0][4] = fMin_1[0][4]*fScal_1[0][4]+1.;
   fMin_1[1][4] = -4.5036110878;
   fMax_1[1][4] = 4.50834369659;
   fScal_1[1][4] = 2.0/(fMax_1[1][4]-fMin_1[1][4]);
   fOff_1[1][4] = fMin_1[1][4]*fScal_1[1][4]+1.;
   fMin_1[2][4] = -4.50663423538;
   fMax_1[2][4] = 4.51134681702;
   fScal_1[2][4] = 2.0/(fMax_1[2][4]-fMin_1[2][4]);
   fOff_1[2][4] = fMin_1[2][4]*fScal_1[2][4]+1.;
   fMin_1[0][5] = 50.1059684753;
   fMax_1[0][5] = 1964.14489746;
   fScal_1[0][5] = 2.0/(fMax_1[0][5]-fMin_1[0][5]);
   fOff_1[0][5] = fMin_1[0][5]*fScal_1[0][5]+1.;
   fMin_1[1][5] = 50.0584754944;
   fMax_1[1][5] = 2753.2824707;
   fScal_1[1][5] = 2.0/(fMax_1[1][5]-fMin_1[1][5]);
   fOff_1[1][5] = fMin_1[1][5]*fScal_1[1][5]+1.;
   fMin_1[2][5] = 50.0584754944;
   fMax_1[2][5] = 2753.2824707;
   fScal_1[2][5] = 2.0/(fMax_1[2][5]-fMin_1[2][5]);
   fOff_1[2][5] = fMin_1[2][5]*fScal_1[2][5]+1.;
   fMin_1[0][6] = -2.4010925293;
   fMax_1[0][6] = 2.39041256905;
   fScal_1[0][6] = 2.0/(fMax_1[0][6]-fMin_1[0][6]);
   fOff_1[0][6] = fMin_1[0][6]*fScal_1[0][6]+1.;
   fMin_1[1][6] = -2.38632035255;
   fMax_1[1][6] = 2.38307738304;
   fScal_1[1][6] = 2.0/(fMax_1[1][6]-fMin_1[1][6]);
   fOff_1[1][6] = fMin_1[1][6]*fScal_1[1][6]+1.;
   fMin_1[2][6] = -2.4010925293;
   fMax_1[2][6] = 2.39041256905;
   fScal_1[2][6] = 2.0/(fMax_1[2][6]-fMin_1[2][6]);
   fOff_1[2][6] = fMin_1[2][6]*fScal_1[2][6]+1.;
   fMin_1[0][7] = 0.0488347522914;
   fMax_1[0][7] = 0.99988257885;
   fScal_1[0][7] = 2.0/(fMax_1[0][7]-fMin_1[0][7]);
   fOff_1[0][7] = fMin_1[0][7]*fScal_1[0][7]+1.;
   fMin_1[1][7] = 0.0229892414063;
   fMax_1[1][7] = 0.999983787537;
   fScal_1[1][7] = 2.0/(fMax_1[1][7]-fMin_1[1][7]);
   fOff_1[1][7] = fMin_1[1][7]*fScal_1[1][7]+1.;
   fMin_1[2][7] = 0.0229892414063;
   fMax_1[2][7] = 0.999983787537;
   fScal_1[2][7] = 2.0/(fMax_1[2][7]-fMin_1[2][7]);
   fOff_1[2][7] = fMin_1[2][7]*fScal_1[2][7]+1.;
   fMin_1[0][8] = 2;
   fMax_1[0][8] = 8;
   fScal_1[0][8] = 2.0/(fMax_1[0][8]-fMin_1[0][8]);
   fOff_1[0][8] = fMin_1[0][8]*fScal_1[0][8]+1.;
   fMin_1[1][8] = 2;
   fMax_1[1][8] = 9;
   fScal_1[1][8] = 2.0/(fMax_1[1][8]-fMin_1[1][8]);
   fOff_1[1][8] = fMin_1[1][8]*fScal_1[1][8]+1.;
   fMin_1[2][8] = 2;
   fMax_1[2][8] = 9;
   fScal_1[2][8] = 2.0/(fMax_1[2][8]-fMin_1[2][8]);
   fOff_1[2][8] = fMin_1[2][8]*fScal_1[2][8]+1.;
   fMin_1[0][9] = 1.5914440155e-05;
   fMax_1[0][9] = 1;
   fScal_1[0][9] = 2.0/(fMax_1[0][9]-fMin_1[0][9]);
   fOff_1[0][9] = fMin_1[0][9]*fScal_1[0][9]+1.;
   fMin_1[1][9] = 1.93119049072e-05;
   fMax_1[1][9] = 1;
   fScal_1[1][9] = 2.0/(fMax_1[1][9]-fMin_1[1][9]);
   fOff_1[1][9] = fMin_1[1][9]*fScal_1[1][9]+1.;
   fMin_1[2][9] = 1.5914440155e-05;
   fMax_1[2][9] = 1;
   fScal_1[2][9] = 2.0/(fMax_1[2][9]-fMin_1[2][9]);
   fOff_1[2][9] = fMin_1[2][9]*fScal_1[2][9]+1.;
   fMin_1[0][10] = 3.26525550918e-05;
   fMax_1[0][10] = 6.50682735443;
   fScal_1[0][10] = 2.0/(fMax_1[0][10]-fMin_1[0][10]);
   fOff_1[0][10] = fMin_1[0][10]*fScal_1[0][10]+1.;
   fMin_1[1][10] = 1.18112052405e-06;
   fMax_1[1][10] = 6.68952894211;
   fScal_1[1][10] = 2.0/(fMax_1[1][10]-fMin_1[1][10]);
   fOff_1[1][10] = fMin_1[1][10]*fScal_1[1][10]+1.;
   fMin_1[2][10] = 1.18112052405e-06;
   fMax_1[2][10] = 6.68952894211;
   fScal_1[2][10] = 2.0/(fMax_1[2][10]-fMin_1[2][10]);
   fOff_1[2][10] = fMin_1[2][10]*fScal_1[2][10]+1.;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) {
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   }
   if ( indicesPut.empty() ) {
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   }

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fOff_1[cls][ivar];
      double scale  = fScal_1[cls][ivar];
      iv[indicesPut.at(ivar)] = scale*dv[ivar]-offset;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
