// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.22/06       [398854]
Creator        : konstantin
Date           : Thu Apr  1 20:21:17 2021
Host           : Linux mach 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/konstantin/Projects/CERN/TMVA_MLP
Training events: 170672
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "400" [Number of training cycles]
HiddenLayers: "N" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
LearningRate: "1.000000e-02" [ANN learning rate parameter]
TestRate: "5" [Test for overtraining performed at each #th epochs]
BPMode: "batch" [Back-propagation learning mode: sequential or batch]
BatchSize: "7" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "2.500000e-03" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "5" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
mJJ                           mJJ                           mJJ                           mJJ                                                             'F'    [22.7864818573,7838.75537109]
deltaYJJ                      deltaYJJ                      deltaYJJ                      deltaYJJ                                                        'F'    [2.2119609639e-05,8.68471050262]
metPt                         metPt                         metPt                         metPt                                                           'F'    [125.825294495,2277.4987793]
ptBalance                     ptBalance                     ptBalance                     ptBalance                                                       'F'    [4.91857872476e-06,0.47649076581]
subleadJetEta                 subleadJetEta                 subleadJetEta                 subleadJetEta                                                   'F'    [-4.50663423538,4.51134681702]
leadJetPt                     leadJetPt                     leadJetPt                     leadJetPt                                                       'F'    [50.0584754944,2753.2824707]
photonEta                     photonEta                     photonEta                     photonEta                                                       'F'    [-2.4010925293,2.39041256905]
ptBalanceRed                  ptBalanceRed                  ptBalanceRed                  ptBalanceRed                                                    'F'    [0.0229892414063,0.999983787537]
nJets                         nJets                         nJets                         nJets                                                           'F'    [2,9]
sinDeltaPhiJJOver2            sinDeltaPhiJJOver2            sinDeltaPhiJJOver2            sinDeltaPhiJJOver2                                              'F'    [1.5914440155e-05,1]
deltaYJPh                     deltaYJPh                     deltaYJPh                     deltaYJPh                                                       'F'    [1.18112052405e-06,6.68952894211]
NSpec 1
weightModified                weightModified                weightModified                F                                                               'F'    [-0.191263645887,1.09073340893]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 11 )
   {
      // the training input variables
      const char* inputVars[] = { "mJJ", "deltaYJJ", "metPt", "ptBalance", "subleadJetEta", "leadJetPt", "photonEta", "ptBalanceRed", "nJets", "sinDeltaPhiJJOver2", "deltaYJPh" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fOff_1[3][11];
   double fScal_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   double fWeightMatrix0to1[12][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][12];   // weight matrix from layer 1 to 2

};

inline void ReadMLP::Initialize()
{
   // build network structure
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.528614905110018;
   fWeightMatrix0to1[1][0] = 1.40898769400088;
   fWeightMatrix0to1[2][0] = 1.08333776539282;
   fWeightMatrix0to1[3][0] = 5.22839296701497;
   fWeightMatrix0to1[4][0] = -1.15492498821695;
   fWeightMatrix0to1[5][0] = -2.0875137878989;
   fWeightMatrix0to1[6][0] = -0.330596279921914;
   fWeightMatrix0to1[7][0] = 2.20107812070452;
   fWeightMatrix0to1[8][0] = 1.71968963980951;
   fWeightMatrix0to1[9][0] = -0.630194540043621;
   fWeightMatrix0to1[10][0] = -4.15825712691658;
   fWeightMatrix0to1[0][1] = -0.315186919779118;
   fWeightMatrix0to1[1][1] = -4.59764504982933;
   fWeightMatrix0to1[2][1] = 0.322356288817164;
   fWeightMatrix0to1[3][1] = 2.8422146837971;
   fWeightMatrix0to1[4][1] = 1.28551740391468;
   fWeightMatrix0to1[5][1] = -1.0306738406756;
   fWeightMatrix0to1[6][1] = 4.57770448083268;
   fWeightMatrix0to1[7][1] = 0.144359430649942;
   fWeightMatrix0to1[8][1] = 5.80684135377622;
   fWeightMatrix0to1[9][1] = -1.03622904108911;
   fWeightMatrix0to1[10][1] = 1.44526725290607;
   fWeightMatrix0to1[0][2] = 2.47887495910634;
   fWeightMatrix0to1[1][2] = -0.405054455766378;
   fWeightMatrix0to1[2][2] = -0.350845544030766;
   fWeightMatrix0to1[3][2] = 0.422792719082158;
   fWeightMatrix0to1[4][2] = 2.12481403950651;
   fWeightMatrix0to1[5][2] = -1.79237613937291;
   fWeightMatrix0to1[6][2] = -0.680307836656233;
   fWeightMatrix0to1[7][2] = 0.591886793076607;
   fWeightMatrix0to1[8][2] = 0.909351636682717;
   fWeightMatrix0to1[9][2] = 2.79692937782506;
   fWeightMatrix0to1[10][2] = -1.05460172919645;
   fWeightMatrix0to1[0][3] = 0.250417243549005;
   fWeightMatrix0to1[1][3] = 0.748824825133693;
   fWeightMatrix0to1[2][3] = 0.374392535446319;
   fWeightMatrix0to1[3][3] = -4.42675308012069;
   fWeightMatrix0to1[4][3] = 2.26455546416648;
   fWeightMatrix0to1[5][3] = -1.80393935917192;
   fWeightMatrix0to1[6][3] = -1.77895452222789;
   fWeightMatrix0to1[7][3] = 1.43994018041838;
   fWeightMatrix0to1[8][3] = 0.15551496989696;
   fWeightMatrix0to1[9][3] = 1.1531759738446;
   fWeightMatrix0to1[10][3] = 0.912188594335153;
   fWeightMatrix0to1[0][4] = -2.17903297074001;
   fWeightMatrix0to1[1][4] = -3.97421442695762;
   fWeightMatrix0to1[2][4] = 1.86628262460651;
   fWeightMatrix0to1[3][4] = -0.291366595384297;
   fWeightMatrix0to1[4][4] = 1.0725687391832;
   fWeightMatrix0to1[5][4] = 1.00916054731809;
   fWeightMatrix0to1[6][4] = 0.426021230328927;
   fWeightMatrix0to1[7][4] = 1.24606592360002;
   fWeightMatrix0to1[8][4] = -2.48290483963277;
   fWeightMatrix0to1[9][4] = 1.74100102824359;
   fWeightMatrix0to1[10][4] = -0.342873740291125;
   fWeightMatrix0to1[0][5] = -0.873176595777081;
   fWeightMatrix0to1[1][5] = -0.853363522476886;
   fWeightMatrix0to1[2][5] = -1.60802091413776;
   fWeightMatrix0to1[3][5] = 1.50984732057934;
   fWeightMatrix0to1[4][5] = 1.33544734336123;
   fWeightMatrix0to1[5][5] = -2.16083063921041;
   fWeightMatrix0to1[6][5] = 0.199231755701448;
   fWeightMatrix0to1[7][5] = 0.0679812471403366;
   fWeightMatrix0to1[8][5] = -0.132994856731528;
   fWeightMatrix0to1[9][5] = 2.75075744731245;
   fWeightMatrix0to1[10][5] = -0.701462082169151;
   fWeightMatrix0to1[0][6] = 1.64560648538461;
   fWeightMatrix0to1[1][6] = 1.04191337770448;
   fWeightMatrix0to1[2][6] = -1.8517749208567;
   fWeightMatrix0to1[3][6] = -0.0904569790399542;
   fWeightMatrix0to1[4][6] = -0.395284130447633;
   fWeightMatrix0to1[5][6] = -0.594888391447332;
   fWeightMatrix0to1[6][6] = 0.166969861591514;
   fWeightMatrix0to1[7][6] = 0.887923392619007;
   fWeightMatrix0to1[8][6] = 0.780396993099812;
   fWeightMatrix0to1[9][6] = -1.48533130061613;
   fWeightMatrix0to1[10][6] = 0.345721160267223;
   fWeightMatrix0to1[0][7] = -0.547200772311104;
   fWeightMatrix0to1[1][7] = 0.00184993537215204;
   fWeightMatrix0to1[2][7] = -0.497621655706682;
   fWeightMatrix0to1[3][7] = -0.34995838000671;
   fWeightMatrix0to1[4][7] = 0.33647778182968;
   fWeightMatrix0to1[5][7] = 0.917124955406731;
   fWeightMatrix0to1[6][7] = -0.236541700670124;
   fWeightMatrix0to1[7][7] = -0.782948482271691;
   fWeightMatrix0to1[8][7] = -0.171636140992929;
   fWeightMatrix0to1[9][7] = -0.0387176285462621;
   fWeightMatrix0to1[10][7] = 0.18658456361456;
   fWeightMatrix0to1[0][8] = -1.31636594336472;
   fWeightMatrix0to1[1][8] = 0.294086984820584;
   fWeightMatrix0to1[2][8] = -0.349963640511698;
   fWeightMatrix0to1[3][8] = -1.73977350272167;
   fWeightMatrix0to1[4][8] = 1.92526822517153;
   fWeightMatrix0to1[5][8] = -1.92416044734295;
   fWeightMatrix0to1[6][8] = 0.0877545534512193;
   fWeightMatrix0to1[7][8] = 1.5698606907152;
   fWeightMatrix0to1[8][8] = -0.793653825927441;
   fWeightMatrix0to1[9][8] = -1.66246519067958;
   fWeightMatrix0to1[10][8] = -0.755051305006513;
   fWeightMatrix0to1[0][9] = -0.273081854994173;
   fWeightMatrix0to1[1][9] = -0.447715823950665;
   fWeightMatrix0to1[2][9] = -1.63449125874495;
   fWeightMatrix0to1[3][9] = 0.212547899821251;
   fWeightMatrix0to1[4][9] = 0.849434581633509;
   fWeightMatrix0to1[5][9] = -0.236845441934833;
   fWeightMatrix0to1[6][9] = 0.567245485534152;
   fWeightMatrix0to1[7][9] = -0.958613621962724;
   fWeightMatrix0to1[8][9] = 0.439323074530631;
   fWeightMatrix0to1[9][9] = 0.760375338082484;
   fWeightMatrix0to1[10][9] = -0.362911946638235;
   fWeightMatrix0to1[0][10] = -1.99495451909994;
   fWeightMatrix0to1[1][10] = 1.53411436440436;
   fWeightMatrix0to1[2][10] = -1.08515599256044;
   fWeightMatrix0to1[3][10] = 0.00754861185280281;
   fWeightMatrix0to1[4][10] = -0.62776001037397;
   fWeightMatrix0to1[5][10] = 0.848015744373802;
   fWeightMatrix0to1[6][10] = -1.45248796438333;
   fWeightMatrix0to1[7][10] = -0.638064264891776;
   fWeightMatrix0to1[8][10] = -2.2587789529921;
   fWeightMatrix0to1[9][10] = -2.46000408704013;
   fWeightMatrix0to1[10][10] = -1.10192163860697;
   fWeightMatrix0to1[0][11] = 0.489745764881798;
   fWeightMatrix0to1[1][11] = -0.635287426704382;
   fWeightMatrix0to1[2][11] = 1.90712559691705;
   fWeightMatrix0to1[3][11] = 0.842129636395613;
   fWeightMatrix0to1[4][11] = -0.961568388778064;
   fWeightMatrix0to1[5][11] = 0.91723672095726;
   fWeightMatrix0to1[6][11] = 1.14579436562903;
   fWeightMatrix0to1[7][11] = -2.40383539875339;
   fWeightMatrix0to1[8][11] = 3.10696935614998;
   fWeightMatrix0to1[9][11] = -0.955445306094877;
   fWeightMatrix0to1[10][11] = -6.01495568941954;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 3.84724452682107;
   fWeightMatrix1to2[0][1] = -3.5392990992516;
   fWeightMatrix1to2[0][2] = 3.19196605027825;
   fWeightMatrix1to2[0][3] = 2.09582136460821;
   fWeightMatrix1to2[0][4] = -0.059523125978385;
   fWeightMatrix1to2[0][5] = -0.636468779271412;
   fWeightMatrix1to2[0][6] = -5.32570903814432;
   fWeightMatrix1to2[0][7] = 0.979175003343606;
   fWeightMatrix1to2[0][8] = 3.59880816367906;
   fWeightMatrix1to2[0][9] = -3.03269229608903;
   fWeightMatrix1to2[0][10] = -4.96495757759562;
   fWeightMatrix1to2[0][11] = -0.309685059260954;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)11) {
      std::cout << "Input vector needs to be of size " << 11 << std::endl;
      return 0;
   }

   std::array<double, 12> fWeights1 {{}};
   std::array<double, 1> fWeights2 {{}};
   fWeights1.back() = 1.;

   // layer 0 to 1
   for (int o=0; o<11; o++) {
      std::array<double, 12> buffer; // no need to initialise
      for (int i = 0; i<12 - 1; i++) {
         buffer[i] = fWeightMatrix0to1[o][i] * inputValues[i];
      } // loop over i
      buffer.back() = fWeightMatrix0to1[o][11];
      for (int i=0; i<12; i++) {
         fWeights1[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<11; o++) {
      fWeights1[o] = ActivationFnc(fWeights1[o]);
   } // loop over o
   // layer 1 to 2
   for (int o=0; o<1; o++) {
      std::array<double, 12> buffer; // no need to initialise
      for (int i=0; i<12; i++) {
         buffer[i] = fWeightMatrix1to2[o][i] * fWeights1[i];
      } // loop over i
      for (int i=0; i<12; i++) {
         fWeights2[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<1; o++) {
      fWeights2[o] = OutputActivationFnc(fWeights2[o]);
   } // loop over o

   return fWeights2[0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}

// Clean up
inline void ReadMLP::Clear()
{
}
inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         std::vector<double> iV(inputValues);
         Transform( iV, -1 );
         retval = GetMvaValue__( iV );
   }

   return retval;
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   double fMin_1[3][11];
   double fMax_1[3][11];
   // Normalization transformation, initialisation
   fMin_1[0][0] = 22.7864818573;
   fMax_1[0][0] = 7505.73046875;
   fScal_1[0][0] = 2.0/(fMax_1[0][0]-fMin_1[0][0]);
   fOff_1[0][0] = fMin_1[0][0]*fScal_1[0][0]+1.;
   fMin_1[1][0] = 23.5563087463;
   fMax_1[1][0] = 7838.75537109;
   fScal_1[1][0] = 2.0/(fMax_1[1][0]-fMin_1[1][0]);
   fOff_1[1][0] = fMin_1[1][0]*fScal_1[1][0]+1.;
   fMin_1[2][0] = 22.7864818573;
   fMax_1[2][0] = 7838.75537109;
   fScal_1[2][0] = 2.0/(fMax_1[2][0]-fMin_1[2][0]);
   fOff_1[2][0] = fMin_1[2][0]*fScal_1[2][0]+1.;
   fMin_1[0][1] = 0.000150358115206;
   fMax_1[0][1] = 8.68471050262;
   fScal_1[0][1] = 2.0/(fMax_1[0][1]-fMin_1[0][1]);
   fOff_1[0][1] = fMin_1[0][1]*fScal_1[0][1]+1.;
   fMin_1[1][1] = 2.2119609639e-05;
   fMax_1[1][1] = 8.68384933472;
   fScal_1[1][1] = 2.0/(fMax_1[1][1]-fMin_1[1][1]);
   fOff_1[1][1] = fMin_1[1][1]*fScal_1[1][1]+1.;
   fMin_1[2][1] = 2.2119609639e-05;
   fMax_1[2][1] = 8.68471050262;
   fScal_1[2][1] = 2.0/(fMax_1[2][1]-fMin_1[2][1]);
   fOff_1[2][1] = fMin_1[2][1]*fScal_1[2][1]+1.;
   fMin_1[0][2] = 126.97845459;
   fMax_1[0][2] = 2277.4987793;
   fScal_1[0][2] = 2.0/(fMax_1[0][2]-fMin_1[0][2]);
   fOff_1[0][2] = fMin_1[0][2]*fScal_1[0][2]+1.;
   fMin_1[1][2] = 125.825294495;
   fMax_1[1][2] = 1926.56140137;
   fScal_1[1][2] = 2.0/(fMax_1[1][2]-fMin_1[1][2]);
   fOff_1[1][2] = fMin_1[1][2]*fScal_1[1][2]+1.;
   fMin_1[2][2] = 125.825294495;
   fMax_1[2][2] = 2277.4987793;
   fScal_1[2][2] = 2.0/(fMax_1[2][2]-fMin_1[2][2]);
   fOff_1[2][2] = fMin_1[2][2]*fScal_1[2][2]+1.;
   fMin_1[0][3] = 4.91857872476e-06;
   fMax_1[0][3] = 0.405025333166;
   fScal_1[0][3] = 2.0/(fMax_1[0][3]-fMin_1[0][3]);
   fOff_1[0][3] = fMin_1[0][3]*fScal_1[0][3]+1.;
   fMin_1[1][3] = 5.9500340285e-05;
   fMax_1[1][3] = 0.47649076581;
   fScal_1[1][3] = 2.0/(fMax_1[1][3]-fMin_1[1][3]);
   fOff_1[1][3] = fMin_1[1][3]*fScal_1[1][3]+1.;
   fMin_1[2][3] = 4.91857872476e-06;
   fMax_1[2][3] = 0.47649076581;
   fScal_1[2][3] = 2.0/(fMax_1[2][3]-fMin_1[2][3]);
   fOff_1[2][3] = fMin_1[2][3]*fScal_1[2][3]+1.;
   fMin_1[0][4] = -4.50663423538;
   fMax_1[0][4] = 4.51134681702;
   fScal_1[0][4] = 2.0/(fMax_1[0][4]-fMin_1[0][4]);
   fOff_1[0][4] = fMin_1[0][4]*fScal_1[0][4]+1.;
   fMin_1[1][4] = -4.5036110878;
   fMax_1[1][4] = 4.50834369659;
   fScal_1[1][4] = 2.0/(fMax_1[1][4]-fMin_1[1][4]);
   fOff_1[1][4] = fMin_1[1][4]*fScal_1[1][4]+1.;
   fMin_1[2][4] = -4.50663423538;
   fMax_1[2][4] = 4.51134681702;
   fScal_1[2][4] = 2.0/(fMax_1[2][4]-fMin_1[2][4]);
   fOff_1[2][4] = fMin_1[2][4]*fScal_1[2][4]+1.;
   fMin_1[0][5] = 50.1059684753;
   fMax_1[0][5] = 1964.14489746;
   fScal_1[0][5] = 2.0/(fMax_1[0][5]-fMin_1[0][5]);
   fOff_1[0][5] = fMin_1[0][5]*fScal_1[0][5]+1.;
   fMin_1[1][5] = 50.0584754944;
   fMax_1[1][5] = 2753.2824707;
   fScal_1[1][5] = 2.0/(fMax_1[1][5]-fMin_1[1][5]);
   fOff_1[1][5] = fMin_1[1][5]*fScal_1[1][5]+1.;
   fMin_1[2][5] = 50.0584754944;
   fMax_1[2][5] = 2753.2824707;
   fScal_1[2][5] = 2.0/(fMax_1[2][5]-fMin_1[2][5]);
   fOff_1[2][5] = fMin_1[2][5]*fScal_1[2][5]+1.;
   fMin_1[0][6] = -2.4010925293;
   fMax_1[0][6] = 2.39041256905;
   fScal_1[0][6] = 2.0/(fMax_1[0][6]-fMin_1[0][6]);
   fOff_1[0][6] = fMin_1[0][6]*fScal_1[0][6]+1.;
   fMin_1[1][6] = -2.38632035255;
   fMax_1[1][6] = 2.38307738304;
   fScal_1[1][6] = 2.0/(fMax_1[1][6]-fMin_1[1][6]);
   fOff_1[1][6] = fMin_1[1][6]*fScal_1[1][6]+1.;
   fMin_1[2][6] = -2.4010925293;
   fMax_1[2][6] = 2.39041256905;
   fScal_1[2][6] = 2.0/(fMax_1[2][6]-fMin_1[2][6]);
   fOff_1[2][6] = fMin_1[2][6]*fScal_1[2][6]+1.;
   fMin_1[0][7] = 0.0488347522914;
   fMax_1[0][7] = 0.99988257885;
   fScal_1[0][7] = 2.0/(fMax_1[0][7]-fMin_1[0][7]);
   fOff_1[0][7] = fMin_1[0][7]*fScal_1[0][7]+1.;
   fMin_1[1][7] = 0.0229892414063;
   fMax_1[1][7] = 0.999983787537;
   fScal_1[1][7] = 2.0/(fMax_1[1][7]-fMin_1[1][7]);
   fOff_1[1][7] = fMin_1[1][7]*fScal_1[1][7]+1.;
   fMin_1[2][7] = 0.0229892414063;
   fMax_1[2][7] = 0.999983787537;
   fScal_1[2][7] = 2.0/(fMax_1[2][7]-fMin_1[2][7]);
   fOff_1[2][7] = fMin_1[2][7]*fScal_1[2][7]+1.;
   fMin_1[0][8] = 2;
   fMax_1[0][8] = 8;
   fScal_1[0][8] = 2.0/(fMax_1[0][8]-fMin_1[0][8]);
   fOff_1[0][8] = fMin_1[0][8]*fScal_1[0][8]+1.;
   fMin_1[1][8] = 2;
   fMax_1[1][8] = 9;
   fScal_1[1][8] = 2.0/(fMax_1[1][8]-fMin_1[1][8]);
   fOff_1[1][8] = fMin_1[1][8]*fScal_1[1][8]+1.;
   fMin_1[2][8] = 2;
   fMax_1[2][8] = 9;
   fScal_1[2][8] = 2.0/(fMax_1[2][8]-fMin_1[2][8]);
   fOff_1[2][8] = fMin_1[2][8]*fScal_1[2][8]+1.;
   fMin_1[0][9] = 1.5914440155e-05;
   fMax_1[0][9] = 1;
   fScal_1[0][9] = 2.0/(fMax_1[0][9]-fMin_1[0][9]);
   fOff_1[0][9] = fMin_1[0][9]*fScal_1[0][9]+1.;
   fMin_1[1][9] = 1.93119049072e-05;
   fMax_1[1][9] = 1;
   fScal_1[1][9] = 2.0/(fMax_1[1][9]-fMin_1[1][9]);
   fOff_1[1][9] = fMin_1[1][9]*fScal_1[1][9]+1.;
   fMin_1[2][9] = 1.5914440155e-05;
   fMax_1[2][9] = 1;
   fScal_1[2][9] = 2.0/(fMax_1[2][9]-fMin_1[2][9]);
   fOff_1[2][9] = fMin_1[2][9]*fScal_1[2][9]+1.;
   fMin_1[0][10] = 3.26525550918e-05;
   fMax_1[0][10] = 6.50682735443;
   fScal_1[0][10] = 2.0/(fMax_1[0][10]-fMin_1[0][10]);
   fOff_1[0][10] = fMin_1[0][10]*fScal_1[0][10]+1.;
   fMin_1[1][10] = 1.18112052405e-06;
   fMax_1[1][10] = 6.68952894211;
   fScal_1[1][10] = 2.0/(fMax_1[1][10]-fMin_1[1][10]);
   fOff_1[1][10] = fMin_1[1][10]*fScal_1[1][10]+1.;
   fMin_1[2][10] = 1.18112052405e-06;
   fMax_1[2][10] = 6.68952894211;
   fScal_1[2][10] = 2.0/(fMax_1[2][10]-fMin_1[2][10]);
   fOff_1[2][10] = fMin_1[2][10]*fScal_1[2][10]+1.;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) {
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   }
   if ( indicesPut.empty() ) {
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   }

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fOff_1[cls][ivar];
      double scale  = fScal_1[cls][ivar];
      iv[indicesPut.at(ivar)] = scale*dv[ivar]-offset;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
