// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.22/06       [398854]
Creator        : konstantin
Date           : Wed Mar 24 00:05:59 2021
Host           : Linux mach 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/konstantin/Projects/CERN/TMVA_MLP
Training events: 170672
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "400" [Number of training cycles]
HiddenLayers: "N+10,N" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
LearningRate: "1.000000e-02" [ANN learning rate parameter]
TestRate: "5" [Test for overtraining performed at each #th epochs]
BPMode: "batch" [Back-propagation learning mode: sequential or batch]
BatchSize: "3" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "2.500000e-03" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "5" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
mJJ                           mJJ                           mJJ                           mJJ                                                             'F'    [22.7864818573,7838.75537109]
deltaYJJ                      deltaYJJ                      deltaYJJ                      deltaYJJ                                                        'F'    [2.2119609639e-05,8.68471050262]
metPt                         metPt                         metPt                         metPt                                                           'F'    [125.825294495,2277.4987793]
ptBalance                     ptBalance                     ptBalance                     ptBalance                                                       'F'    [4.91857872476e-06,0.47649076581]
subleadJetEta                 subleadJetEta                 subleadJetEta                 subleadJetEta                                                   'F'    [-4.50663423538,4.51134681702]
leadJetPt                     leadJetPt                     leadJetPt                     leadJetPt                                                       'F'    [50.0584754944,2753.2824707]
photonEta                     photonEta                     photonEta                     photonEta                                                       'F'    [-2.4010925293,2.39041256905]
ptBalanceRed                  ptBalanceRed                  ptBalanceRed                  ptBalanceRed                                                    'F'    [0.0229892414063,0.999983787537]
nJets                         nJets                         nJets                         nJets                                                           'F'    [2,9]
sinDeltaPhiJJOver2            sinDeltaPhiJJOver2            sinDeltaPhiJJOver2            sinDeltaPhiJJOver2                                              'F'    [1.5914440155e-05,1]
deltaYJPh                     deltaYJPh                     deltaYJPh                     deltaYJPh                                                       'F'    [1.18112052405e-06,6.68952894211]
NSpec 1
weightModified                weightModified                weightModified                F                                                               'F'    [-0.191263645887,1.09073340893]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 11 )
   {
      // the training input variables
      const char* inputVars[] = { "mJJ", "deltaYJJ", "metPt", "ptBalance", "subleadJetEta", "leadJetPt", "photonEta", "ptBalanceRed", "nJets", "sinDeltaPhiJJOver2", "deltaYJPh" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fOff_1[3][11];
   double fScal_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   double fWeightMatrix0to1[22][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][22];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][12];   // weight matrix from layer 2 to 3

};

inline void ReadMLP::Initialize()
{
   // build network structure
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.599778231158271;
   fWeightMatrix0to1[1][0] = 2.32252331156577;
   fWeightMatrix0to1[2][0] = 1.11209592021284;
   fWeightMatrix0to1[3][0] = 2.51744704629134;
   fWeightMatrix0to1[4][0] = -1.99091081649984;
   fWeightMatrix0to1[5][0] = 0.0314144051288901;
   fWeightMatrix0to1[6][0] = -0.167786389912773;
   fWeightMatrix0to1[7][0] = 2.31657199966415;
   fWeightMatrix0to1[8][0] = -1.91985450430376;
   fWeightMatrix0to1[9][0] = -1.82233938600566;
   fWeightMatrix0to1[10][0] = -3.16741847423133;
   fWeightMatrix0to1[11][0] = -4.67827570628176;
   fWeightMatrix0to1[12][0] = -1.4924166104746;
   fWeightMatrix0to1[13][0] = 0.517977808192332;
   fWeightMatrix0to1[14][0] = -1.22641647619012;
   fWeightMatrix0to1[15][0] = -2.46869371061556;
   fWeightMatrix0to1[16][0] = 0.19482362999342;
   fWeightMatrix0to1[17][0] = 1.46528980627501;
   fWeightMatrix0to1[18][0] = 0.217373866636557;
   fWeightMatrix0to1[19][0] = 1.71746071664267;
   fWeightMatrix0to1[20][0] = 0.899575784501925;
   fWeightMatrix0to1[0][1] = -2.74332689447481;
   fWeightMatrix0to1[1][1] = -0.863688515616358;
   fWeightMatrix0to1[2][1] = 0.29472996221209;
   fWeightMatrix0to1[3][1] = -2.69315169422281;
   fWeightMatrix0to1[4][1] = -1.45109340136471;
   fWeightMatrix0to1[5][1] = 3.48258505410804;
   fWeightMatrix0to1[6][1] = -2.46701442912274;
   fWeightMatrix0to1[7][1] = -1.88987055040502;
   fWeightMatrix0to1[8][1] = 1.3077560271112;
   fWeightMatrix0to1[9][1] = -0.601205913668865;
   fWeightMatrix0to1[10][1] = 2.81124226817414;
   fWeightMatrix0to1[11][1] = -1.53285472943545;
   fWeightMatrix0to1[12][1] = -0.167648846029854;
   fWeightMatrix0to1[13][1] = 0.262977643797333;
   fWeightMatrix0to1[14][1] = -3.01482157225349;
   fWeightMatrix0to1[15][1] = -1.81610993166431;
   fWeightMatrix0to1[16][1] = 1.81578970223849;
   fWeightMatrix0to1[17][1] = -1.69219168255407;
   fWeightMatrix0to1[18][1] = 0.789506259766664;
   fWeightMatrix0to1[19][1] = 1.70986555380438;
   fWeightMatrix0to1[20][1] = 2.97032890442269;
   fWeightMatrix0to1[0][2] = 2.18668469104603;
   fWeightMatrix0to1[1][2] = 1.99575673377453;
   fWeightMatrix0to1[2][2] = -1.33392344265;
   fWeightMatrix0to1[3][2] = -0.214824942766454;
   fWeightMatrix0to1[4][2] = 0.137050679566142;
   fWeightMatrix0to1[5][2] = 0.00118189555430218;
   fWeightMatrix0to1[6][2] = 1.79823976375027;
   fWeightMatrix0to1[7][2] = 1.10763071325001;
   fWeightMatrix0to1[8][2] = 1.31040681499964;
   fWeightMatrix0to1[9][2] = 1.52053128701326;
   fWeightMatrix0to1[10][2] = -2.18083651348729;
   fWeightMatrix0to1[11][2] = 1.22637311399087;
   fWeightMatrix0to1[12][2] = -1.10420892604786;
   fWeightMatrix0to1[13][2] = -1.69153079576883;
   fWeightMatrix0to1[14][2] = -1.90516890514057;
   fWeightMatrix0to1[15][2] = -1.88010198861129;
   fWeightMatrix0to1[16][2] = 1.59945706849525;
   fWeightMatrix0to1[17][2] = 1.11387660360392;
   fWeightMatrix0to1[18][2] = -1.53482975597796;
   fWeightMatrix0to1[19][2] = 0.287789298720652;
   fWeightMatrix0to1[20][2] = 0.716566389720105;
   fWeightMatrix0to1[0][3] = 0.892570287801156;
   fWeightMatrix0to1[1][3] = 3.57579503195468;
   fWeightMatrix0to1[2][3] = 0.459994956196364;
   fWeightMatrix0to1[3][3] = 0.835177932612282;
   fWeightMatrix0to1[4][3] = 0.580481146256876;
   fWeightMatrix0to1[5][3] = 0.647364087955148;
   fWeightMatrix0to1[6][3] = -1.13927483747074;
   fWeightMatrix0to1[7][3] = -1.14126337178767;
   fWeightMatrix0to1[8][3] = -1.03499253737608;
   fWeightMatrix0to1[9][3] = 1.15688419113089;
   fWeightMatrix0to1[10][3] = 1.537612318123;
   fWeightMatrix0to1[11][3] = 1.50516446914207;
   fWeightMatrix0to1[12][3] = 0.0328104036237173;
   fWeightMatrix0to1[13][3] = -1.79150007515422;
   fWeightMatrix0to1[14][3] = 0.228100215682549;
   fWeightMatrix0to1[15][3] = 3.08696163289214;
   fWeightMatrix0to1[16][3] = 0.0560692932922712;
   fWeightMatrix0to1[17][3] = 2.72540912580125;
   fWeightMatrix0to1[18][3] = 0.617575977768858;
   fWeightMatrix0to1[19][3] = 0.548106829918971;
   fWeightMatrix0to1[20][3] = -0.709581467043979;
   fWeightMatrix0to1[0][4] = -1.96803826183436;
   fWeightMatrix0to1[1][4] = 0.147491938676547;
   fWeightMatrix0to1[2][4] = 1.16155064276375;
   fWeightMatrix0to1[3][4] = -0.317130482896168;
   fWeightMatrix0to1[4][4] = -1.11207947764501;
   fWeightMatrix0to1[5][4] = -1.03826810411245;
   fWeightMatrix0to1[6][4] = -0.513813104410967;
   fWeightMatrix0to1[7][4] = 0.775040707341558;
   fWeightMatrix0to1[8][4] = 1.66151924123785;
   fWeightMatrix0to1[9][4] = -1.80911840875879;
   fWeightMatrix0to1[10][4] = -0.687367841585282;
   fWeightMatrix0to1[11][4] = 1.49380559299105;
   fWeightMatrix0to1[12][4] = -0.81813047629155;
   fWeightMatrix0to1[13][4] = 0.288554176729599;
   fWeightMatrix0to1[14][4] = -3.98500862078664;
   fWeightMatrix0to1[15][4] = -0.429771489854672;
   fWeightMatrix0to1[16][4] = -1.06354172952079;
   fWeightMatrix0to1[17][4] = -1.94120843804982;
   fWeightMatrix0to1[18][4] = 0.940617520076134;
   fWeightMatrix0to1[19][4] = 1.29949717933696;
   fWeightMatrix0to1[20][4] = -3.50898028507287;
   fWeightMatrix0to1[0][5] = 2.12134972020381;
   fWeightMatrix0to1[1][5] = -1.50009507471133;
   fWeightMatrix0to1[2][5] = -0.366267261399377;
   fWeightMatrix0to1[3][5] = 0.523713869538686;
   fWeightMatrix0to1[4][5] = 1.07386587790956;
   fWeightMatrix0to1[5][5] = -1.58536660328517;
   fWeightMatrix0to1[6][5] = -0.124096389521205;
   fWeightMatrix0to1[7][5] = 0.385636013393247;
   fWeightMatrix0to1[8][5] = -0.261525490880471;
   fWeightMatrix0to1[9][5] = -0.437584091405083;
   fWeightMatrix0to1[10][5] = 1.34559817174433;
   fWeightMatrix0to1[11][5] = -0.732606013617458;
   fWeightMatrix0to1[12][5] = -0.627993509591353;
   fWeightMatrix0to1[13][5] = 1.30605729755776;
   fWeightMatrix0to1[14][5] = -0.202394074038564;
   fWeightMatrix0to1[15][5] = -2.46589113634395;
   fWeightMatrix0to1[16][5] = 0.506467400520315;
   fWeightMatrix0to1[17][5] = -0.550378168814076;
   fWeightMatrix0to1[18][5] = 2.37904536275824;
   fWeightMatrix0to1[19][5] = 0.666939699448689;
   fWeightMatrix0to1[20][5] = -1.32785053813376;
   fWeightMatrix0to1[0][6] = -0.0956318674273104;
   fWeightMatrix0to1[1][6] = 0.082615591493089;
   fWeightMatrix0to1[2][6] = -2.83563030699114;
   fWeightMatrix0to1[3][6] = 0.584500980630853;
   fWeightMatrix0to1[4][6] = 0.956033111116219;
   fWeightMatrix0to1[5][6] = -0.510174517254925;
   fWeightMatrix0to1[6][6] = -0.321596724804048;
   fWeightMatrix0to1[7][6] = -1.36671556608599;
   fWeightMatrix0to1[8][6] = 0.63713111985173;
   fWeightMatrix0to1[9][6] = 1.05921777321131;
   fWeightMatrix0to1[10][6] = 0.794717183514429;
   fWeightMatrix0to1[11][6] = -0.711860835786455;
   fWeightMatrix0to1[12][6] = 0.204540549278735;
   fWeightMatrix0to1[13][6] = 2.29297281474187;
   fWeightMatrix0to1[14][6] = 1.61988124094867;
   fWeightMatrix0to1[15][6] = 0.308401122478429;
   fWeightMatrix0to1[16][6] = -1.59516660924212;
   fWeightMatrix0to1[17][6] = -1.14084644381116;
   fWeightMatrix0to1[18][6] = -1.24199165402166;
   fWeightMatrix0to1[19][6] = 0.94181891538202;
   fWeightMatrix0to1[20][6] = 1.9427418384932;
   fWeightMatrix0to1[0][7] = -0.319077326149248;
   fWeightMatrix0to1[1][7] = 0.038669836732118;
   fWeightMatrix0to1[2][7] = -0.0625691921868941;
   fWeightMatrix0to1[3][7] = -0.917765228664615;
   fWeightMatrix0to1[4][7] = 0.158874881148569;
   fWeightMatrix0to1[5][7] = 0.600669757731557;
   fWeightMatrix0to1[6][7] = 0.480743085371481;
   fWeightMatrix0to1[7][7] = -1.4959755163725;
   fWeightMatrix0to1[8][7] = 0.202192513481357;
   fWeightMatrix0to1[9][7] = 0.260982920700768;
   fWeightMatrix0to1[10][7] = -0.606723005597847;
   fWeightMatrix0to1[11][7] = 0.285565018844703;
   fWeightMatrix0to1[12][7] = -0.907909330644911;
   fWeightMatrix0to1[13][7] = 1.15583032403153;
   fWeightMatrix0to1[14][7] = 0.183847822698951;
   fWeightMatrix0to1[15][7] = 0.915759191107499;
   fWeightMatrix0to1[16][7] = 0.180503903195073;
   fWeightMatrix0to1[17][7] = 1.21861331227836;
   fWeightMatrix0to1[18][7] = 0.424182766506425;
   fWeightMatrix0to1[19][7] = -0.153073891629952;
   fWeightMatrix0to1[20][7] = 0.502238214071333;
   fWeightMatrix0to1[0][8] = -1.01294011630956;
   fWeightMatrix0to1[1][8] = -0.153220646988872;
   fWeightMatrix0to1[2][8] = 2.53017981431968;
   fWeightMatrix0to1[3][8] = 1.84031019713518;
   fWeightMatrix0to1[4][8] = -0.170285233716093;
   fWeightMatrix0to1[5][8] = 1.08313108043759;
   fWeightMatrix0to1[6][8] = 1.15169687258791;
   fWeightMatrix0to1[7][8] = -2.85478551102943;
   fWeightMatrix0to1[8][8] = 0.755123525648161;
   fWeightMatrix0to1[9][8] = 0.264848834686465;
   fWeightMatrix0to1[10][8] = -0.706320974280307;
   fWeightMatrix0to1[11][8] = -1.50357452570516;
   fWeightMatrix0to1[12][8] = -1.29407045172042;
   fWeightMatrix0to1[13][8] = 2.28420496426196;
   fWeightMatrix0to1[14][8] = 2.888345419641;
   fWeightMatrix0to1[15][8] = -0.653982059405289;
   fWeightMatrix0to1[16][8] = -0.599125756479654;
   fWeightMatrix0to1[17][8] = -0.353259291069258;
   fWeightMatrix0to1[18][8] = 0.94490516689419;
   fWeightMatrix0to1[19][8] = 1.02387025786964;
   fWeightMatrix0to1[20][8] = -1.96503551143122;
   fWeightMatrix0to1[0][9] = -0.182321866511181;
   fWeightMatrix0to1[1][9] = -0.179610339022926;
   fWeightMatrix0to1[2][9] = 1.23516383811546;
   fWeightMatrix0to1[3][9] = 0.575324495383736;
   fWeightMatrix0to1[4][9] = 2.83533956861203;
   fWeightMatrix0to1[5][9] = 0.686325576251266;
   fWeightMatrix0to1[6][9] = -1.4043983205855;
   fWeightMatrix0to1[7][9] = -0.558298922045842;
   fWeightMatrix0to1[8][9] = 1.06070611954507;
   fWeightMatrix0to1[9][9] = 0.61591380774762;
   fWeightMatrix0to1[10][9] = -1.29665171839737;
   fWeightMatrix0to1[11][9] = 0.451530721625116;
   fWeightMatrix0to1[12][9] = 0.217165224085252;
   fWeightMatrix0to1[13][9] = -0.0244225024077831;
   fWeightMatrix0to1[14][9] = -0.0708647832576871;
   fWeightMatrix0to1[15][9] = 0.00585615824298751;
   fWeightMatrix0to1[16][9] = 0.420615942198316;
   fWeightMatrix0to1[17][9] = -0.966954943655195;
   fWeightMatrix0to1[18][9] = -0.0231120522054704;
   fWeightMatrix0to1[19][9] = 1.65979796883861;
   fWeightMatrix0to1[20][9] = 0.272432932396681;
   fWeightMatrix0to1[0][10] = -0.163496493143287;
   fWeightMatrix0to1[1][10] = 0.576923993686183;
   fWeightMatrix0to1[2][10] = -1.96860461860467;
   fWeightMatrix0to1[3][10] = -0.0506457896361993;
   fWeightMatrix0to1[4][10] = 1.45440667643369;
   fWeightMatrix0to1[5][10] = 0.836439667178723;
   fWeightMatrix0to1[6][10] = 0.894151653992891;
   fWeightMatrix0to1[7][10] = 0.0386464786911028;
   fWeightMatrix0to1[8][10] = 1.89787083848154;
   fWeightMatrix0to1[9][10] = -3.17310992645512;
   fWeightMatrix0to1[10][10] = -0.369393063625463;
   fWeightMatrix0to1[11][10] = 0.310246402438324;
   fWeightMatrix0to1[12][10] = -2.16667808671242;
   fWeightMatrix0to1[13][10] = -0.4213523175959;
   fWeightMatrix0to1[14][10] = 2.40847925254648;
   fWeightMatrix0to1[15][10] = -0.142052668155027;
   fWeightMatrix0to1[16][10] = 0.383431962463763;
   fWeightMatrix0to1[17][10] = 0.472559495834464;
   fWeightMatrix0to1[18][10] = -1.7115346923114;
   fWeightMatrix0to1[19][10] = -1.74954105508993;
   fWeightMatrix0to1[20][10] = -2.15267351007954;
   fWeightMatrix0to1[0][11] = 0.0307835556369098;
   fWeightMatrix0to1[1][11] = 5.24076320378654;
   fWeightMatrix0to1[2][11] = -1.26766840926199;
   fWeightMatrix0to1[3][11] = 3.46666380416372;
   fWeightMatrix0to1[4][11] = -4.22334126937372;
   fWeightMatrix0to1[5][11] = 2.95887596370629;
   fWeightMatrix0to1[6][11] = 0.387627534013408;
   fWeightMatrix0to1[7][11] = -1.772344514695;
   fWeightMatrix0to1[8][11] = -1.2160656139498;
   fWeightMatrix0to1[9][11] = -4.88670831286484;
   fWeightMatrix0to1[10][11] = -2.04394111349118;
   fWeightMatrix0to1[11][11] = -5.43969230838597;
   fWeightMatrix0to1[12][11] = -2.63009769232316;
   fWeightMatrix0to1[13][11] = -0.821554380877158;
   fWeightMatrix0to1[14][11] = -1.65515037898988;
   fWeightMatrix0to1[15][11] = -4.86209613446285;
   fWeightMatrix0to1[16][11] = -1.99417959895182;
   fWeightMatrix0to1[17][11] = 0.444640760415145;
   fWeightMatrix0to1[18][11] = -0.571115580385992;
   fWeightMatrix0to1[19][11] = 0.681187110077099;
   fWeightMatrix0to1[20][11] = -0.578754197641526;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.664428934949284;
   fWeightMatrix1to2[1][0] = 2.12721077251006;
   fWeightMatrix1to2[2][0] = 1.60755971167697;
   fWeightMatrix1to2[3][0] = -0.607334721807214;
   fWeightMatrix1to2[4][0] = -0.647144885199009;
   fWeightMatrix1to2[5][0] = -1.58644192146682;
   fWeightMatrix1to2[6][0] = -0.725573829830165;
   fWeightMatrix1to2[7][0] = -2.97666502942146;
   fWeightMatrix1to2[8][0] = 1.99935429679503;
   fWeightMatrix1to2[9][0] = 0.461840929540487;
   fWeightMatrix1to2[10][0] = 1.87906888289468;
   fWeightMatrix1to2[0][1] = -1.37770390758664;
   fWeightMatrix1to2[1][1] = 0.751562024561132;
   fWeightMatrix1to2[2][1] = -0.389205259016204;
   fWeightMatrix1to2[3][1] = -1.39820339852131;
   fWeightMatrix1to2[4][1] = 0.299055842766796;
   fWeightMatrix1to2[5][1] = 1.28327501447399;
   fWeightMatrix1to2[6][1] = -1.00167937302172;
   fWeightMatrix1to2[7][1] = -3.44711801037459;
   fWeightMatrix1to2[8][1] = -0.617030600602769;
   fWeightMatrix1to2[9][1] = 3.44431673834382;
   fWeightMatrix1to2[10][1] = 0.46485884624838;
   fWeightMatrix1to2[0][2] = -0.329438740666834;
   fWeightMatrix1to2[1][2] = 0.219609240643117;
   fWeightMatrix1to2[2][2] = 1.25570464764293;
   fWeightMatrix1to2[3][2] = 1.77387757300618;
   fWeightMatrix1to2[4][2] = 0.800189450905574;
   fWeightMatrix1to2[5][2] = -1.20370027098514;
   fWeightMatrix1to2[6][2] = 0.9813407401653;
   fWeightMatrix1to2[7][2] = -0.507823656734641;
   fWeightMatrix1to2[8][2] = -2.50119087088282;
   fWeightMatrix1to2[9][2] = -0.735572071998002;
   fWeightMatrix1to2[10][2] = -1.75542665884058;
   fWeightMatrix1to2[0][3] = -0.489590984837589;
   fWeightMatrix1to2[1][3] = -0.593103750870779;
   fWeightMatrix1to2[2][3] = 1.90287556116032;
   fWeightMatrix1to2[3][3] = -1.24182921288782;
   fWeightMatrix1to2[4][3] = 0.737834236110273;
   fWeightMatrix1to2[5][3] = -1.39135322893261;
   fWeightMatrix1to2[6][3] = 0.644641989068619;
   fWeightMatrix1to2[7][3] = -1.94223027605926;
   fWeightMatrix1to2[8][3] = 0.985561221175423;
   fWeightMatrix1to2[9][3] = 3.04223267424389;
   fWeightMatrix1to2[10][3] = -1.8706499142463;
   fWeightMatrix1to2[0][4] = 0.818014612170305;
   fWeightMatrix1to2[1][4] = 0.784510146065948;
   fWeightMatrix1to2[2][4] = -2.08433399900922;
   fWeightMatrix1to2[3][4] = -1.58081051394015;
   fWeightMatrix1to2[4][4] = -1.76123642280829;
   fWeightMatrix1to2[5][4] = -0.942949069384465;
   fWeightMatrix1to2[6][4] = 2.07235568348909;
   fWeightMatrix1to2[7][4] = -1.68926426678609;
   fWeightMatrix1to2[8][4] = -0.527351345743245;
   fWeightMatrix1to2[9][4] = -1.61807845280305;
   fWeightMatrix1to2[10][4] = -1.17999189629077;
   fWeightMatrix1to2[0][5] = -1.56814260560332;
   fWeightMatrix1to2[1][5] = -0.32803979544051;
   fWeightMatrix1to2[2][5] = -1.31000462167608;
   fWeightMatrix1to2[3][5] = 1.46368597806234;
   fWeightMatrix1to2[4][5] = 0.618986541389085;
   fWeightMatrix1to2[5][5] = -1.86017275591129;
   fWeightMatrix1to2[6][5] = 2.25707283264147;
   fWeightMatrix1to2[7][5] = 0.139786424249862;
   fWeightMatrix1to2[8][5] = -0.810607624431466;
   fWeightMatrix1to2[9][5] = 2.32330041719013;
   fWeightMatrix1to2[10][5] = -1.81885832812513;
   fWeightMatrix1to2[0][6] = 1.4908938276686;
   fWeightMatrix1to2[1][6] = 1.00255657376749;
   fWeightMatrix1to2[2][6] = -0.817477584117598;
   fWeightMatrix1to2[3][6] = -0.128321383714364;
   fWeightMatrix1to2[4][6] = 0.190014496379951;
   fWeightMatrix1to2[5][6] = -0.391953226048095;
   fWeightMatrix1to2[6][6] = -0.755105864551279;
   fWeightMatrix1to2[7][6] = 0.635404725360422;
   fWeightMatrix1to2[8][6] = 2.30109228084598;
   fWeightMatrix1to2[9][6] = 2.49352611462717;
   fWeightMatrix1to2[10][6] = -1.38273851629929;
   fWeightMatrix1to2[0][7] = 0.424009748688219;
   fWeightMatrix1to2[1][7] = -2.28405243259997;
   fWeightMatrix1to2[2][7] = 0.22700117606604;
   fWeightMatrix1to2[3][7] = -2.20868990822403;
   fWeightMatrix1to2[4][7] = -2.99154200524535;
   fWeightMatrix1to2[5][7] = 0.168058365268926;
   fWeightMatrix1to2[6][7] = 1.06814009458951;
   fWeightMatrix1to2[7][7] = 0.490850185236495;
   fWeightMatrix1to2[8][7] = 0.407652899990797;
   fWeightMatrix1to2[9][7] = 0.613278580733822;
   fWeightMatrix1to2[10][7] = -0.188856687853037;
   fWeightMatrix1to2[0][8] = 0.652085075704028;
   fWeightMatrix1to2[1][8] = 0.0669431172825176;
   fWeightMatrix1to2[2][8] = 1.8147291712723;
   fWeightMatrix1to2[3][8] = -1.28625241594909;
   fWeightMatrix1to2[4][8] = 0.305416695593706;
   fWeightMatrix1to2[5][8] = -0.833628698447493;
   fWeightMatrix1to2[6][8] = -0.881345985170905;
   fWeightMatrix1to2[7][8] = -0.644309416442571;
   fWeightMatrix1to2[8][8] = 0.204601165927578;
   fWeightMatrix1to2[9][8] = -1.32571440697356;
   fWeightMatrix1to2[10][8] = 0.966236146972425;
   fWeightMatrix1to2[0][9] = 3.19693915972495;
   fWeightMatrix1to2[1][9] = 0.794146795454431;
   fWeightMatrix1to2[2][9] = 0.210938719994517;
   fWeightMatrix1to2[3][9] = -0.848460428068238;
   fWeightMatrix1to2[4][9] = -1.42821501564657;
   fWeightMatrix1to2[5][9] = -1.86344522635059;
   fWeightMatrix1to2[6][9] = 1.14325801319469;
   fWeightMatrix1to2[7][9] = -2.41557831661399;
   fWeightMatrix1to2[8][9] = -0.441252066804981;
   fWeightMatrix1to2[9][9] = -0.143579721097784;
   fWeightMatrix1to2[10][9] = -1.69982238832578;
   fWeightMatrix1to2[0][10] = -0.960450758482856;
   fWeightMatrix1to2[1][10] = -1.6537420694738;
   fWeightMatrix1to2[2][10] = 0.995058559649493;
   fWeightMatrix1to2[3][10] = -1.0330026703204;
   fWeightMatrix1to2[4][10] = -2.21974058228373;
   fWeightMatrix1to2[5][10] = -0.535683235443329;
   fWeightMatrix1to2[6][10] = -0.585704516270696;
   fWeightMatrix1to2[7][10] = -2.48518579981322;
   fWeightMatrix1to2[8][10] = 0.014228568497321;
   fWeightMatrix1to2[9][10] = -2.93744945288358;
   fWeightMatrix1to2[10][10] = -1.2374518351652;
   fWeightMatrix1to2[0][11] = 3.05748393883119;
   fWeightMatrix1to2[1][11] = 0.402481496057629;
   fWeightMatrix1to2[2][11] = 0.187264472001894;
   fWeightMatrix1to2[3][11] = 1.05397629469802;
   fWeightMatrix1to2[4][11] = 0.60257183817876;
   fWeightMatrix1to2[5][11] = 1.83934640900953;
   fWeightMatrix1to2[6][11] = -0.269369119058678;
   fWeightMatrix1to2[7][11] = -3.59371459869414;
   fWeightMatrix1to2[8][11] = -0.481746366974942;
   fWeightMatrix1to2[9][11] = -2.5181991807907;
   fWeightMatrix1to2[10][11] = 0.917378345629252;
   fWeightMatrix1to2[0][12] = -0.122155663754572;
   fWeightMatrix1to2[1][12] = -0.0403587488058206;
   fWeightMatrix1to2[2][12] = 1.41352963728696;
   fWeightMatrix1to2[3][12] = 0.416887402871399;
   fWeightMatrix1to2[4][12] = 1.81265713449285;
   fWeightMatrix1to2[5][12] = -1.47824134144094;
   fWeightMatrix1to2[6][12] = 1.61913563685278;
   fWeightMatrix1to2[7][12] = 1.37665465769455;
   fWeightMatrix1to2[8][12] = -2.16826073590244;
   fWeightMatrix1to2[9][12] = 0.435422530533453;
   fWeightMatrix1to2[10][12] = -1.06458476817186;
   fWeightMatrix1to2[0][13] = 1.10701194637268;
   fWeightMatrix1to2[1][13] = 0.737309598342755;
   fWeightMatrix1to2[2][13] = 1.20563278305363;
   fWeightMatrix1to2[3][13] = 2.17946140736166;
   fWeightMatrix1to2[4][13] = -1.30776035847579;
   fWeightMatrix1to2[5][13] = 2.13057134075939;
   fWeightMatrix1to2[6][13] = 1.18166554462715;
   fWeightMatrix1to2[7][13] = 1.26401986161755;
   fWeightMatrix1to2[8][13] = -1.96257340370032;
   fWeightMatrix1to2[9][13] = 1.72982904206111;
   fWeightMatrix1to2[10][13] = -1.96686958517573;
   fWeightMatrix1to2[0][14] = 3.55268614191603;
   fWeightMatrix1to2[1][14] = 2.16852738223502;
   fWeightMatrix1to2[2][14] = -0.194280343509162;
   fWeightMatrix1to2[3][14] = 1.29206610500114;
   fWeightMatrix1to2[4][14] = -0.0972110375131788;
   fWeightMatrix1to2[5][14] = -1.59513194799779;
   fWeightMatrix1to2[6][14] = 0.73741512719162;
   fWeightMatrix1to2[7][14] = -3.5375616077874;
   fWeightMatrix1to2[8][14] = 1.89257462646979;
   fWeightMatrix1to2[9][14] = -0.13043780787184;
   fWeightMatrix1to2[10][14] = 1.65647969878438;
   fWeightMatrix1to2[0][15] = 1.4627988878023;
   fWeightMatrix1to2[1][15] = 1.6401923496044;
   fWeightMatrix1to2[2][15] = -0.266835567112873;
   fWeightMatrix1to2[3][15] = -0.0181375466275255;
   fWeightMatrix1to2[4][15] = 0.616846529304295;
   fWeightMatrix1to2[5][15] = 1.3994889524099;
   fWeightMatrix1to2[6][15] = -1.85894368008623;
   fWeightMatrix1to2[7][15] = -1.64205867959075;
   fWeightMatrix1to2[8][15] = 0.535266022183764;
   fWeightMatrix1to2[9][15] = -3.37332492769038;
   fWeightMatrix1to2[10][15] = -1.69180786455771;
   fWeightMatrix1to2[0][16] = -1.32189580308386;
   fWeightMatrix1to2[1][16] = 1.06933316297136;
   fWeightMatrix1to2[2][16] = -0.143804906347967;
   fWeightMatrix1to2[3][16] = -1.99103745199106;
   fWeightMatrix1to2[4][16] = -2.2918431522783;
   fWeightMatrix1to2[5][16] = -0.26266787753489;
   fWeightMatrix1to2[6][16] = 1.84609829379424;
   fWeightMatrix1to2[7][16] = 0.364637773810112;
   fWeightMatrix1to2[8][16] = 0.574694718634619;
   fWeightMatrix1to2[9][16] = -0.813462190620837;
   fWeightMatrix1to2[10][16] = -1.9370241341572;
   fWeightMatrix1to2[0][17] = -0.467467576519005;
   fWeightMatrix1to2[1][17] = -0.746376729545034;
   fWeightMatrix1to2[2][17] = -1.52136335700343;
   fWeightMatrix1to2[3][17] = 0.0239308146298071;
   fWeightMatrix1to2[4][17] = 0.987250527802498;
   fWeightMatrix1to2[5][17] = -2.06328154329193;
   fWeightMatrix1to2[6][17] = 1.95697114632746;
   fWeightMatrix1to2[7][17] = 0.258804492156189;
   fWeightMatrix1to2[8][17] = 0.417282316320989;
   fWeightMatrix1to2[9][17] = -0.0325014576809115;
   fWeightMatrix1to2[10][17] = -0.866046980394479;
   fWeightMatrix1to2[0][18] = 1.98757192464015;
   fWeightMatrix1to2[1][18] = -0.351821219045316;
   fWeightMatrix1to2[2][18] = 0.199821500623965;
   fWeightMatrix1to2[3][18] = 1.79493242663933;
   fWeightMatrix1to2[4][18] = 0.955080668845639;
   fWeightMatrix1to2[5][18] = -1.12471201049161;
   fWeightMatrix1to2[6][18] = 1.49783261099217;
   fWeightMatrix1to2[7][18] = -2.26325889950972;
   fWeightMatrix1to2[8][18] = 0.995958520807312;
   fWeightMatrix1to2[9][18] = 2.16878998532786;
   fWeightMatrix1to2[10][18] = -0.15836986785571;
   fWeightMatrix1to2[0][19] = -1.13545276235505;
   fWeightMatrix1to2[1][19] = 0.67239343146176;
   fWeightMatrix1to2[2][19] = -0.768819628883068;
   fWeightMatrix1to2[3][19] = 1.05853791392836;
   fWeightMatrix1to2[4][19] = -0.0720157708990739;
   fWeightMatrix1to2[5][19] = -0.966872279650284;
   fWeightMatrix1to2[6][19] = -1.00847333542213;
   fWeightMatrix1to2[7][19] = -0.389800104282824;
   fWeightMatrix1to2[8][19] = -0.301374409954979;
   fWeightMatrix1to2[9][19] = 0.799079602203897;
   fWeightMatrix1to2[10][19] = -0.740015014986642;
   fWeightMatrix1to2[0][20] = -3.3213622617628;
   fWeightMatrix1to2[1][20] = 2.07327654819557;
   fWeightMatrix1to2[2][20] = 1.0306390610732;
   fWeightMatrix1to2[3][20] = -2.31462140626923;
   fWeightMatrix1to2[4][20] = 0.749679314356056;
   fWeightMatrix1to2[5][20] = -2.01134298931888;
   fWeightMatrix1to2[6][20] = 1.68757052642648;
   fWeightMatrix1to2[7][20] = 3.7060473645663;
   fWeightMatrix1to2[8][20] = -0.131901225274558;
   fWeightMatrix1to2[9][20] = -0.157794907910167;
   fWeightMatrix1to2[10][20] = 1.58635243181622;
   fWeightMatrix1to2[0][21] = 1.18949569487332;
   fWeightMatrix1to2[1][21] = 0.618130631617644;
   fWeightMatrix1to2[2][21] = 0.254057197731994;
   fWeightMatrix1to2[3][21] = -1.01417480609039;
   fWeightMatrix1to2[4][21] = -2.17221135065576;
   fWeightMatrix1to2[5][21] = 1.34278732113126;
   fWeightMatrix1to2[6][21] = -0.0686328892424539;
   fWeightMatrix1to2[7][21] = -0.0339987143401664;
   fWeightMatrix1to2[8][21] = -2.94783888902757;
   fWeightMatrix1to2[9][21] = -0.81481414599681;
   fWeightMatrix1to2[10][21] = -1.9454927475932;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -3.14461113427487;
   fWeightMatrix2to3[0][1] = -1.47148030445376;
   fWeightMatrix2to3[0][2] = 1.09252708110843;
   fWeightMatrix2to3[0][3] = -2.36587558322166;
   fWeightMatrix2to3[0][4] = 1.91740317933182;
   fWeightMatrix2to3[0][5] = 2.05317647144574;
   fWeightMatrix2to3[0][6] = -2.2949112247903;
   fWeightMatrix2to3[0][7] = 4.63491600411426;
   fWeightMatrix2to3[0][8] = 3.42596611455129;
   fWeightMatrix2to3[0][9] = 4.06021310649857;
   fWeightMatrix2to3[0][10] = -0.473379443261573;
   fWeightMatrix2to3[0][11] = -0.866444739039826;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)11) {
      std::cout << "Input vector needs to be of size " << 11 << std::endl;
      return 0;
   }

   std::array<double, 22> fWeights1 {{}};
   std::array<double, 12> fWeights2 {{}};
   std::array<double, 1> fWeights3 {{}};
   fWeights1.back() = 1.;
   fWeights2.back() = 1.;

   // layer 0 to 1
   for (int o=0; o<21; o++) {
      std::array<double, 12> buffer; // no need to initialise
      for (int i = 0; i<12 - 1; i++) {
         buffer[i] = fWeightMatrix0to1[o][i] * inputValues[i];
      } // loop over i
      buffer.back() = fWeightMatrix0to1[o][11];
      for (int i=0; i<12; i++) {
         fWeights1[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<21; o++) {
      fWeights1[o] = ActivationFnc(fWeights1[o]);
   } // loop over o
   // layer 1 to 2
   for (int o=0; o<11; o++) {
      std::array<double, 22> buffer; // no need to initialise
      for (int i=0; i<22; i++) {
         buffer[i] = fWeightMatrix1to2[o][i] * fWeights1[i];
      } // loop over i
      for (int i=0; i<22; i++) {
         fWeights2[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<11; o++) {
      fWeights2[o] = ActivationFnc(fWeights2[o]);
   } // loop over o
   // layer 2 to 3
   for (int o=0; o<1; o++) {
      std::array<double, 12> buffer; // no need to initialise
      for (int i=0; i<12; i++) {
         buffer[i] = fWeightMatrix2to3[o][i] * fWeights2[i];
      } // loop over i
      for (int i=0; i<12; i++) {
         fWeights3[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<1; o++) {
      fWeights3[o] = OutputActivationFnc(fWeights3[o]);
   } // loop over o

   return fWeights3[0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}

// Clean up
inline void ReadMLP::Clear()
{
}
inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         std::vector<double> iV(inputValues);
         Transform( iV, -1 );
         retval = GetMvaValue__( iV );
   }

   return retval;
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   double fMin_1[3][11];
   double fMax_1[3][11];
   // Normalization transformation, initialisation
   fMin_1[0][0] = 22.7864818573;
   fMax_1[0][0] = 7505.73046875;
   fScal_1[0][0] = 2.0/(fMax_1[0][0]-fMin_1[0][0]);
   fOff_1[0][0] = fMin_1[0][0]*fScal_1[0][0]+1.;
   fMin_1[1][0] = 23.5563087463;
   fMax_1[1][0] = 7838.75537109;
   fScal_1[1][0] = 2.0/(fMax_1[1][0]-fMin_1[1][0]);
   fOff_1[1][0] = fMin_1[1][0]*fScal_1[1][0]+1.;
   fMin_1[2][0] = 22.7864818573;
   fMax_1[2][0] = 7838.75537109;
   fScal_1[2][0] = 2.0/(fMax_1[2][0]-fMin_1[2][0]);
   fOff_1[2][0] = fMin_1[2][0]*fScal_1[2][0]+1.;
   fMin_1[0][1] = 0.000150358115206;
   fMax_1[0][1] = 8.68471050262;
   fScal_1[0][1] = 2.0/(fMax_1[0][1]-fMin_1[0][1]);
   fOff_1[0][1] = fMin_1[0][1]*fScal_1[0][1]+1.;
   fMin_1[1][1] = 2.2119609639e-05;
   fMax_1[1][1] = 8.68384933472;
   fScal_1[1][1] = 2.0/(fMax_1[1][1]-fMin_1[1][1]);
   fOff_1[1][1] = fMin_1[1][1]*fScal_1[1][1]+1.;
   fMin_1[2][1] = 2.2119609639e-05;
   fMax_1[2][1] = 8.68471050262;
   fScal_1[2][1] = 2.0/(fMax_1[2][1]-fMin_1[2][1]);
   fOff_1[2][1] = fMin_1[2][1]*fScal_1[2][1]+1.;
   fMin_1[0][2] = 126.97845459;
   fMax_1[0][2] = 2277.4987793;
   fScal_1[0][2] = 2.0/(fMax_1[0][2]-fMin_1[0][2]);
   fOff_1[0][2] = fMin_1[0][2]*fScal_1[0][2]+1.;
   fMin_1[1][2] = 125.825294495;
   fMax_1[1][2] = 1926.56140137;
   fScal_1[1][2] = 2.0/(fMax_1[1][2]-fMin_1[1][2]);
   fOff_1[1][2] = fMin_1[1][2]*fScal_1[1][2]+1.;
   fMin_1[2][2] = 125.825294495;
   fMax_1[2][2] = 2277.4987793;
   fScal_1[2][2] = 2.0/(fMax_1[2][2]-fMin_1[2][2]);
   fOff_1[2][2] = fMin_1[2][2]*fScal_1[2][2]+1.;
   fMin_1[0][3] = 4.91857872476e-06;
   fMax_1[0][3] = 0.405025333166;
   fScal_1[0][3] = 2.0/(fMax_1[0][3]-fMin_1[0][3]);
   fOff_1[0][3] = fMin_1[0][3]*fScal_1[0][3]+1.;
   fMin_1[1][3] = 5.9500340285e-05;
   fMax_1[1][3] = 0.47649076581;
   fScal_1[1][3] = 2.0/(fMax_1[1][3]-fMin_1[1][3]);
   fOff_1[1][3] = fMin_1[1][3]*fScal_1[1][3]+1.;
   fMin_1[2][3] = 4.91857872476e-06;
   fMax_1[2][3] = 0.47649076581;
   fScal_1[2][3] = 2.0/(fMax_1[2][3]-fMin_1[2][3]);
   fOff_1[2][3] = fMin_1[2][3]*fScal_1[2][3]+1.;
   fMin_1[0][4] = -4.50663423538;
   fMax_1[0][4] = 4.51134681702;
   fScal_1[0][4] = 2.0/(fMax_1[0][4]-fMin_1[0][4]);
   fOff_1[0][4] = fMin_1[0][4]*fScal_1[0][4]+1.;
   fMin_1[1][4] = -4.5036110878;
   fMax_1[1][4] = 4.50834369659;
   fScal_1[1][4] = 2.0/(fMax_1[1][4]-fMin_1[1][4]);
   fOff_1[1][4] = fMin_1[1][4]*fScal_1[1][4]+1.;
   fMin_1[2][4] = -4.50663423538;
   fMax_1[2][4] = 4.51134681702;
   fScal_1[2][4] = 2.0/(fMax_1[2][4]-fMin_1[2][4]);
   fOff_1[2][4] = fMin_1[2][4]*fScal_1[2][4]+1.;
   fMin_1[0][5] = 50.1059684753;
   fMax_1[0][5] = 1964.14489746;
   fScal_1[0][5] = 2.0/(fMax_1[0][5]-fMin_1[0][5]);
   fOff_1[0][5] = fMin_1[0][5]*fScal_1[0][5]+1.;
   fMin_1[1][5] = 50.0584754944;
   fMax_1[1][5] = 2753.2824707;
   fScal_1[1][5] = 2.0/(fMax_1[1][5]-fMin_1[1][5]);
   fOff_1[1][5] = fMin_1[1][5]*fScal_1[1][5]+1.;
   fMin_1[2][5] = 50.0584754944;
   fMax_1[2][5] = 2753.2824707;
   fScal_1[2][5] = 2.0/(fMax_1[2][5]-fMin_1[2][5]);
   fOff_1[2][5] = fMin_1[2][5]*fScal_1[2][5]+1.;
   fMin_1[0][6] = -2.4010925293;
   fMax_1[0][6] = 2.39041256905;
   fScal_1[0][6] = 2.0/(fMax_1[0][6]-fMin_1[0][6]);
   fOff_1[0][6] = fMin_1[0][6]*fScal_1[0][6]+1.;
   fMin_1[1][6] = -2.38632035255;
   fMax_1[1][6] = 2.38307738304;
   fScal_1[1][6] = 2.0/(fMax_1[1][6]-fMin_1[1][6]);
   fOff_1[1][6] = fMin_1[1][6]*fScal_1[1][6]+1.;
   fMin_1[2][6] = -2.4010925293;
   fMax_1[2][6] = 2.39041256905;
   fScal_1[2][6] = 2.0/(fMax_1[2][6]-fMin_1[2][6]);
   fOff_1[2][6] = fMin_1[2][6]*fScal_1[2][6]+1.;
   fMin_1[0][7] = 0.0488347522914;
   fMax_1[0][7] = 0.99988257885;
   fScal_1[0][7] = 2.0/(fMax_1[0][7]-fMin_1[0][7]);
   fOff_1[0][7] = fMin_1[0][7]*fScal_1[0][7]+1.;
   fMin_1[1][7] = 0.0229892414063;
   fMax_1[1][7] = 0.999983787537;
   fScal_1[1][7] = 2.0/(fMax_1[1][7]-fMin_1[1][7]);
   fOff_1[1][7] = fMin_1[1][7]*fScal_1[1][7]+1.;
   fMin_1[2][7] = 0.0229892414063;
   fMax_1[2][7] = 0.999983787537;
   fScal_1[2][7] = 2.0/(fMax_1[2][7]-fMin_1[2][7]);
   fOff_1[2][7] = fMin_1[2][7]*fScal_1[2][7]+1.;
   fMin_1[0][8] = 2;
   fMax_1[0][8] = 8;
   fScal_1[0][8] = 2.0/(fMax_1[0][8]-fMin_1[0][8]);
   fOff_1[0][8] = fMin_1[0][8]*fScal_1[0][8]+1.;
   fMin_1[1][8] = 2;
   fMax_1[1][8] = 9;
   fScal_1[1][8] = 2.0/(fMax_1[1][8]-fMin_1[1][8]);
   fOff_1[1][8] = fMin_1[1][8]*fScal_1[1][8]+1.;
   fMin_1[2][8] = 2;
   fMax_1[2][8] = 9;
   fScal_1[2][8] = 2.0/(fMax_1[2][8]-fMin_1[2][8]);
   fOff_1[2][8] = fMin_1[2][8]*fScal_1[2][8]+1.;
   fMin_1[0][9] = 1.5914440155e-05;
   fMax_1[0][9] = 1;
   fScal_1[0][9] = 2.0/(fMax_1[0][9]-fMin_1[0][9]);
   fOff_1[0][9] = fMin_1[0][9]*fScal_1[0][9]+1.;
   fMin_1[1][9] = 1.93119049072e-05;
   fMax_1[1][9] = 1;
   fScal_1[1][9] = 2.0/(fMax_1[1][9]-fMin_1[1][9]);
   fOff_1[1][9] = fMin_1[1][9]*fScal_1[1][9]+1.;
   fMin_1[2][9] = 1.5914440155e-05;
   fMax_1[2][9] = 1;
   fScal_1[2][9] = 2.0/(fMax_1[2][9]-fMin_1[2][9]);
   fOff_1[2][9] = fMin_1[2][9]*fScal_1[2][9]+1.;
   fMin_1[0][10] = 3.26525550918e-05;
   fMax_1[0][10] = 6.50682735443;
   fScal_1[0][10] = 2.0/(fMax_1[0][10]-fMin_1[0][10]);
   fOff_1[0][10] = fMin_1[0][10]*fScal_1[0][10]+1.;
   fMin_1[1][10] = 1.18112052405e-06;
   fMax_1[1][10] = 6.68952894211;
   fScal_1[1][10] = 2.0/(fMax_1[1][10]-fMin_1[1][10]);
   fOff_1[1][10] = fMin_1[1][10]*fScal_1[1][10]+1.;
   fMin_1[2][10] = 1.18112052405e-06;
   fMax_1[2][10] = 6.68952894211;
   fScal_1[2][10] = 2.0/(fMax_1[2][10]-fMin_1[2][10]);
   fOff_1[2][10] = fMin_1[2][10]*fScal_1[2][10]+1.;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) {
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   }
   if ( indicesPut.empty() ) {
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   }

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fOff_1[cls][ivar];
      double scale  = fScal_1[cls][ivar];
      iv[indicesPut.at(ivar)] = scale*dv[ivar]-offset;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
