// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.22/06       [398854]
Creator        : konstantin
Date           : Wed Mar 24 00:18:42 2021
Host           : Linux mach 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/konstantin/Projects/CERN/TMVA_MLP
Training events: 170672
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "400" [Number of training cycles]
HiddenLayers: "N+10,N+5" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
TestRate: "5" [Test for overtraining performed at each #th epochs]
BPMode: "batch" [Back-propagation learning mode: sequential or batch]
BatchSize: "7" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "2.500000e-03" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "5" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
mJJ                           mJJ                           mJJ                           mJJ                                                             'F'    [22.7864818573,7838.75537109]
deltaYJJ                      deltaYJJ                      deltaYJJ                      deltaYJJ                                                        'F'    [2.2119609639e-05,8.68471050262]
metPt                         metPt                         metPt                         metPt                                                           'F'    [125.825294495,2277.4987793]
ptBalance                     ptBalance                     ptBalance                     ptBalance                                                       'F'    [4.91857872476e-06,0.47649076581]
subleadJetEta                 subleadJetEta                 subleadJetEta                 subleadJetEta                                                   'F'    [-4.50663423538,4.51134681702]
leadJetPt                     leadJetPt                     leadJetPt                     leadJetPt                                                       'F'    [50.0584754944,2753.2824707]
photonEta                     photonEta                     photonEta                     photonEta                                                       'F'    [-2.4010925293,2.39041256905]
ptBalanceRed                  ptBalanceRed                  ptBalanceRed                  ptBalanceRed                                                    'F'    [0.0229892414063,0.999983787537]
nJets                         nJets                         nJets                         nJets                                                           'F'    [2,9]
sinDeltaPhiJJOver2            sinDeltaPhiJJOver2            sinDeltaPhiJJOver2            sinDeltaPhiJJOver2                                              'F'    [1.5914440155e-05,1]
deltaYJPh                     deltaYJPh                     deltaYJPh                     deltaYJPh                                                       'F'    [1.18112052405e-06,6.68952894211]
NSpec 1
weightModified                weightModified                weightModified                F                                                               'F'    [-0.191263645887,1.09073340893]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 11 )
   {
      // the training input variables
      const char* inputVars[] = { "mJJ", "deltaYJJ", "metPt", "ptBalance", "subleadJetEta", "leadJetPt", "photonEta", "ptBalanceRed", "nJets", "sinDeltaPhiJJOver2", "deltaYJPh" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fOff_1[3][11];
   double fScal_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   double fWeightMatrix0to1[22][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[17][22];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][17];   // weight matrix from layer 2 to 3

};

inline void ReadMLP::Initialize()
{
   // build network structure
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.0135147378116516;
   fWeightMatrix0to1[1][0] = 2.61693280091616;
   fWeightMatrix0to1[2][0] = -0.10008869773891;
   fWeightMatrix0to1[3][0] = 3.12213502487438;
   fWeightMatrix0to1[4][0] = -3.15041596967438;
   fWeightMatrix0to1[5][0] = -1.71860854028907;
   fWeightMatrix0to1[6][0] = -0.95327126587977;
   fWeightMatrix0to1[7][0] = 2.04408603192184;
   fWeightMatrix0to1[8][0] = -3.63154176903384;
   fWeightMatrix0to1[9][0] = -1.52608885031913;
   fWeightMatrix0to1[10][0] = -2.58641994203468;
   fWeightMatrix0to1[11][0] = -0.0638694435051156;
   fWeightMatrix0to1[12][0] = -1.90281779485001;
   fWeightMatrix0to1[13][0] = -0.157091668875721;
   fWeightMatrix0to1[14][0] = -0.918554238074152;
   fWeightMatrix0to1[15][0] = 0.125975390506725;
   fWeightMatrix0to1[16][0] = 0.149247796093001;
   fWeightMatrix0to1[17][0] = -1.21763542808941;
   fWeightMatrix0to1[18][0] = 0.136782388146951;
   fWeightMatrix0to1[19][0] = 1.30316455539726;
   fWeightMatrix0to1[20][0] = 1.43682703006244;
   fWeightMatrix0to1[0][1] = -0.152629571212785;
   fWeightMatrix0to1[1][1] = 0.831152397445456;
   fWeightMatrix0to1[2][1] = -2.19691038659551;
   fWeightMatrix0to1[3][1] = -0.3872899426266;
   fWeightMatrix0to1[4][1] = -2.4878117226349;
   fWeightMatrix0to1[5][1] = 0.194021040304694;
   fWeightMatrix0to1[6][1] = -3.8029389857286;
   fWeightMatrix0to1[7][1] = -1.49410571493411;
   fWeightMatrix0to1[8][1] = 0.323814931071306;
   fWeightMatrix0to1[9][1] = -0.210942088359374;
   fWeightMatrix0to1[10][1] = 1.34979488179339;
   fWeightMatrix0to1[11][1] = -0.368246898106525;
   fWeightMatrix0to1[12][1] = -0.28482320494815;
   fWeightMatrix0to1[13][1] = 1.25391460204128;
   fWeightMatrix0to1[14][1] = -0.788180403140453;
   fWeightMatrix0to1[15][1] = -0.916546445119904;
   fWeightMatrix0to1[16][1] = 2.25072202650168;
   fWeightMatrix0to1[17][1] = -2.05016175462716;
   fWeightMatrix0to1[18][1] = 1.49914817538258;
   fWeightMatrix0to1[19][1] = 0.23418006490727;
   fWeightMatrix0to1[20][1] = 3.75002699104007;
   fWeightMatrix0to1[0][2] = 3.46546999592135;
   fWeightMatrix0to1[1][2] = 1.06830684166885;
   fWeightMatrix0to1[2][2] = 0.320587106493298;
   fWeightMatrix0to1[3][2] = -0.970789906130346;
   fWeightMatrix0to1[4][2] = -0.248508892761249;
   fWeightMatrix0to1[5][2] = 0.10434106770882;
   fWeightMatrix0to1[6][2] = 1.02457720427643;
   fWeightMatrix0to1[7][2] = 1.91340722618324;
   fWeightMatrix0to1[8][2] = 0.385218036571236;
   fWeightMatrix0to1[9][2] = 1.79346199850071;
   fWeightMatrix0to1[10][2] = -2.57912879972713;
   fWeightMatrix0to1[11][2] = 1.65407634552262;
   fWeightMatrix0to1[12][2] = -0.947070853820597;
   fWeightMatrix0to1[13][2] = -1.76468580164398;
   fWeightMatrix0to1[14][2] = -0.906295467321624;
   fWeightMatrix0to1[15][2] = -0.926603931306773;
   fWeightMatrix0to1[16][2] = 1.58145964201696;
   fWeightMatrix0to1[17][2] = -1.55925466320504;
   fWeightMatrix0to1[18][2] = -1.95596001229131;
   fWeightMatrix0to1[19][2] = -0.127811653468867;
   fWeightMatrix0to1[20][2] = 0.120297752228893;
   fWeightMatrix0to1[0][3] = -0.176798956310444;
   fWeightMatrix0to1[1][3] = 1.77015604998913;
   fWeightMatrix0to1[2][3] = -0.127487792475095;
   fWeightMatrix0to1[3][3] = -0.389563221781807;
   fWeightMatrix0to1[4][3] = 0.486096639842556;
   fWeightMatrix0to1[5][3] = 1.73230131631247;
   fWeightMatrix0to1[6][3] = -0.793344460609642;
   fWeightMatrix0to1[7][3] = -0.696083362687611;
   fWeightMatrix0to1[8][3] = 0.0382701558154863;
   fWeightMatrix0to1[9][3] = 0.234208596063967;
   fWeightMatrix0to1[10][3] = 0.984737857758142;
   fWeightMatrix0to1[11][3] = 1.55281656080799;
   fWeightMatrix0to1[12][3] = 0.269175613755665;
   fWeightMatrix0to1[13][3] = -2.96430288242752;
   fWeightMatrix0to1[14][3] = -1.15268942525748;
   fWeightMatrix0to1[15][3] = 1.93037528746381;
   fWeightMatrix0to1[16][3] = -0.765999113537469;
   fWeightMatrix0to1[17][3] = 5.45118233930239;
   fWeightMatrix0to1[18][3] = 0.721058410839056;
   fWeightMatrix0to1[19][3] = 1.67629891013772;
   fWeightMatrix0to1[20][3] = -0.865942918427076;
   fWeightMatrix0to1[0][4] = -0.0343692105430439;
   fWeightMatrix0to1[1][4] = -0.696094600703958;
   fWeightMatrix0to1[2][4] = 1.84917679036926;
   fWeightMatrix0to1[3][4] = -0.226551350533872;
   fWeightMatrix0to1[4][4] = -3.93098428495185;
   fWeightMatrix0to1[5][4] = -2.67873952504286;
   fWeightMatrix0to1[6][4] = -1.12482872683156;
   fWeightMatrix0to1[7][4] = -1.22972723675494;
   fWeightMatrix0to1[8][4] = 1.28128884705419;
   fWeightMatrix0to1[9][4] = -1.78804243048655;
   fWeightMatrix0to1[10][4] = -0.584531462614088;
   fWeightMatrix0to1[11][4] = 1.56332016316805;
   fWeightMatrix0to1[12][4] = -0.520355975480827;
   fWeightMatrix0to1[13][4] = -0.616351457712641;
   fWeightMatrix0to1[14][4] = -0.771333125113118;
   fWeightMatrix0to1[15][4] = 0.691395169821688;
   fWeightMatrix0to1[16][4] = -1.81869500155965;
   fWeightMatrix0to1[17][4] = -0.00142251797093869;
   fWeightMatrix0to1[18][4] = 0.0509057639579771;
   fWeightMatrix0to1[19][4] = 0.649845487038452;
   fWeightMatrix0to1[20][4] = -3.5836480801585;
   fWeightMatrix0to1[0][5] = 1.23392856975948;
   fWeightMatrix0to1[1][5] = -0.419854863801596;
   fWeightMatrix0to1[2][5] = 0.44752496857498;
   fWeightMatrix0to1[3][5] = 0.613639330860622;
   fWeightMatrix0to1[4][5] = 0.847520094129851;
   fWeightMatrix0to1[5][5] = -1.22493695663442;
   fWeightMatrix0to1[6][5] = 1.57561871357644;
   fWeightMatrix0to1[7][5] = 0.0177248007126703;
   fWeightMatrix0to1[8][5] = -0.76730410515349;
   fWeightMatrix0to1[9][5] = -1.04741621426925;
   fWeightMatrix0to1[10][5] = 1.752844625973;
   fWeightMatrix0to1[11][5] = 0.65986777381306;
   fWeightMatrix0to1[12][5] = -1.23383065559753;
   fWeightMatrix0to1[13][5] = 0.755901786028737;
   fWeightMatrix0to1[14][5] = -0.953582722373853;
   fWeightMatrix0to1[15][5] = -2.23038222644993;
   fWeightMatrix0to1[16][5] = -0.491805249470063;
   fWeightMatrix0to1[17][5] = -1.39932436244151;
   fWeightMatrix0to1[18][5] = 1.47806739675945;
   fWeightMatrix0to1[19][5] = 0.414098765587717;
   fWeightMatrix0to1[20][5] = -0.899858691762327;
   fWeightMatrix0to1[0][6] = 0.0922686622187091;
   fWeightMatrix0to1[1][6] = 0.445862184548043;
   fWeightMatrix0to1[2][6] = -0.936737190981814;
   fWeightMatrix0to1[3][6] = 0.789157609288154;
   fWeightMatrix0to1[4][6] = 1.84907804557832;
   fWeightMatrix0to1[5][6] = -1.76808177159318;
   fWeightMatrix0to1[6][6] = -0.759747092097599;
   fWeightMatrix0to1[7][6] = -1.00226080708017;
   fWeightMatrix0to1[8][6] = -0.560051727531171;
   fWeightMatrix0to1[9][6] = 0.769355758987285;
   fWeightMatrix0to1[10][6] = 0.582373210777402;
   fWeightMatrix0to1[11][6] = -0.601263399086691;
   fWeightMatrix0to1[12][6] = 0.66990985084981;
   fWeightMatrix0to1[13][6] = 0.553169398654397;
   fWeightMatrix0to1[14][6] = 1.81000510608518;
   fWeightMatrix0to1[15][6] = -0.534014213875433;
   fWeightMatrix0to1[16][6] = -0.262691008905274;
   fWeightMatrix0to1[17][6] = -0.13251380844544;
   fWeightMatrix0to1[18][6] = -1.34783985469246;
   fWeightMatrix0to1[19][6] = 1.25504760316609;
   fWeightMatrix0to1[20][6] = 1.50326966873302;
   fWeightMatrix0to1[0][7] = 0.013255626887184;
   fWeightMatrix0to1[1][7] = -0.211396571227448;
   fWeightMatrix0to1[2][7] = 0.773070527467212;
   fWeightMatrix0to1[3][7] = -0.958382162498101;
   fWeightMatrix0to1[4][7] = -0.318060872800383;
   fWeightMatrix0to1[5][7] = 0.996606680883654;
   fWeightMatrix0to1[6][7] = -0.422926146085981;
   fWeightMatrix0to1[7][7] = 0.274128277207465;
   fWeightMatrix0to1[8][7] = 0.260612932288461;
   fWeightMatrix0to1[9][7] = 0.482682352688391;
   fWeightMatrix0to1[10][7] = -0.465196428894628;
   fWeightMatrix0to1[11][7] = 0.411875470487093;
   fWeightMatrix0to1[12][7] = -0.909838367249009;
   fWeightMatrix0to1[13][7] = 1.35002733327068;
   fWeightMatrix0to1[14][7] = 0.852161381643468;
   fWeightMatrix0to1[15][7] = 0.722601251531654;
   fWeightMatrix0to1[16][7] = 0.370973743857618;
   fWeightMatrix0to1[17][7] = 0.341498524625022;
   fWeightMatrix0to1[18][7] = 0.179234872093555;
   fWeightMatrix0to1[19][7] = -0.270998624244879;
   fWeightMatrix0to1[20][7] = 0.669052375700455;
   fWeightMatrix0to1[0][8] = -0.734602988737269;
   fWeightMatrix0to1[1][8] = -0.480990378055326;
   fWeightMatrix0to1[2][8] = 0.43431425683859;
   fWeightMatrix0to1[3][8] = 1.58279267581281;
   fWeightMatrix0to1[4][8] = -1.0935434225504;
   fWeightMatrix0to1[5][8] = 2.33819445147432;
   fWeightMatrix0to1[6][8] = 2.29225404064074;
   fWeightMatrix0to1[7][8] = -2.16378017428388;
   fWeightMatrix0to1[8][8] = -0.587359514423022;
   fWeightMatrix0to1[9][8] = -0.000895828926481009;
   fWeightMatrix0to1[10][8] = -0.0174657164251345;
   fWeightMatrix0to1[11][8] = -1.18409663642227;
   fWeightMatrix0to1[12][8] = -2.18327160376695;
   fWeightMatrix0to1[13][8] = -0.333364556258202;
   fWeightMatrix0to1[14][8] = 2.10423095383442;
   fWeightMatrix0to1[15][8] = -3.10138848820966;
   fWeightMatrix0to1[16][8] = -0.418209169972796;
   fWeightMatrix0to1[17][8] = 0.528174838963551;
   fWeightMatrix0to1[18][8] = 0.355327965844285;
   fWeightMatrix0to1[19][8] = 2.67336929359982;
   fWeightMatrix0to1[20][8] = 0.754825878777287;
   fWeightMatrix0to1[0][9] = -0.761870786751474;
   fWeightMatrix0to1[1][9] = -0.633941734916177;
   fWeightMatrix0to1[2][9] = 0.210479967566931;
   fWeightMatrix0to1[3][9] = 0.736159958010104;
   fWeightMatrix0to1[4][9] = 0.227774936143855;
   fWeightMatrix0to1[5][9] = -0.149162669999914;
   fWeightMatrix0to1[6][9] = -0.557394629980816;
   fWeightMatrix0to1[7][9] = -1.81749391896414;
   fWeightMatrix0to1[8][9] = 1.08354513930753;
   fWeightMatrix0to1[9][9] = 0.964729379769023;
   fWeightMatrix0to1[10][9] = -2.0662983787925;
   fWeightMatrix0to1[11][9] = -1.41556520428396;
   fWeightMatrix0to1[12][9] = -0.109601517521045;
   fWeightMatrix0to1[13][9] = -0.157789929850043;
   fWeightMatrix0to1[14][9] = -2.42080138406691;
   fWeightMatrix0to1[15][9] = 0.0526237446637018;
   fWeightMatrix0to1[16][9] = -0.110086718780272;
   fWeightMatrix0to1[17][9] = 0.293463704279144;
   fWeightMatrix0to1[18][9] = -1.29342252450811;
   fWeightMatrix0to1[19][9] = 0.361822364234191;
   fWeightMatrix0to1[20][9] = 0.340640036717621;
   fWeightMatrix0to1[0][10] = -0.0201678609606939;
   fWeightMatrix0to1[1][10] = 0.602193617225864;
   fWeightMatrix0to1[2][10] = -2.64425069206476;
   fWeightMatrix0to1[3][10] = -0.532368672295835;
   fWeightMatrix0to1[4][10] = 1.01563743628656;
   fWeightMatrix0to1[5][10] = 1.38662086250305;
   fWeightMatrix0to1[6][10] = 1.10480462600476;
   fWeightMatrix0to1[7][10] = -0.0867013715938962;
   fWeightMatrix0to1[8][10] = 2.11127590544687;
   fWeightMatrix0to1[9][10] = -1.63935402988858;
   fWeightMatrix0to1[10][10] = -1.0415161048866;
   fWeightMatrix0to1[11][10] = 0.150989117767175;
   fWeightMatrix0to1[12][10] = -1.16855996280514;
   fWeightMatrix0to1[13][10] = -0.472795967394577;
   fWeightMatrix0to1[14][10] = 1.46623502628741;
   fWeightMatrix0to1[15][10] = -1.15867991469963;
   fWeightMatrix0to1[16][10] = -0.38719458492894;
   fWeightMatrix0to1[17][10] = -0.410658831485208;
   fWeightMatrix0to1[18][10] = -2.72610476421374;
   fWeightMatrix0to1[19][10] = -1.18880908311033;
   fWeightMatrix0to1[20][10] = -1.29312343108849;
   fWeightMatrix0to1[0][11] = 3.66345534966934;
   fWeightMatrix0to1[1][11] = 1.01346420642825;
   fWeightMatrix0to1[2][11] = -3.67043725232521;
   fWeightMatrix0to1[3][11] = 2.71467743758509;
   fWeightMatrix0to1[4][11] = -4.5554677999578;
   fWeightMatrix0to1[5][11] = 0.0914987090870604;
   fWeightMatrix0to1[6][11] = -0.824506482185232;
   fWeightMatrix0to1[7][11] = -1.68705118720805;
   fWeightMatrix0to1[8][11] = -4.09926253328595;
   fWeightMatrix0to1[9][11] = -4.31098109870358;
   fWeightMatrix0to1[10][11] = -2.28445389877324;
   fWeightMatrix0to1[11][11] = -1.99317761557239;
   fWeightMatrix0to1[12][11] = -2.86276354383577;
   fWeightMatrix0to1[13][11] = -2.89510944346867;
   fWeightMatrix0to1[14][11] = -0.359179520689027;
   fWeightMatrix0to1[15][11] = -2.6005656316217;
   fWeightMatrix0to1[16][11] = 0.274256197333965;
   fWeightMatrix0to1[17][11] = 2.23144823665297;
   fWeightMatrix0to1[18][11] = -0.879709835112606;
   fWeightMatrix0to1[19][11] = 1.09063546917495;
   fWeightMatrix0to1[20][11] = 1.95255806685674;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.1510810663518;
   fWeightMatrix1to2[1][0] = 1.58437515437187;
   fWeightMatrix1to2[2][0] = 1.52883401650168;
   fWeightMatrix1to2[3][0] = -0.458291390387557;
   fWeightMatrix1to2[4][0] = -2.64127817001636;
   fWeightMatrix1to2[5][0] = -0.875475745797553;
   fWeightMatrix1to2[6][0] = -1.84721314620541;
   fWeightMatrix1to2[7][0] = -0.768366220230556;
   fWeightMatrix1to2[8][0] = 0.365759935436091;
   fWeightMatrix1to2[9][0] = 0.267408557807931;
   fWeightMatrix1to2[10][0] = 1.80241799670997;
   fWeightMatrix1to2[11][0] = -0.441951666887991;
   fWeightMatrix1to2[12][0] = 1.12177241173267;
   fWeightMatrix1to2[13][0] = -0.713033130109829;
   fWeightMatrix1to2[14][0] = -1.9642249408124;
   fWeightMatrix1to2[15][0] = 1.31560105871805;
   fWeightMatrix1to2[0][1] = 1.21977818333443;
   fWeightMatrix1to2[1][1] = -0.896724262993753;
   fWeightMatrix1to2[2][1] = -0.942798818049313;
   fWeightMatrix1to2[3][1] = 0.219835909308437;
   fWeightMatrix1to2[4][1] = 1.14850030020326;
   fWeightMatrix1to2[5][1] = 0.528200633796825;
   fWeightMatrix1to2[6][1] = -0.5438679963779;
   fWeightMatrix1to2[7][1] = -0.259726665464178;
   fWeightMatrix1to2[8][1] = 1.54241630425555;
   fWeightMatrix1to2[9][1] = 1.07781959128959;
   fWeightMatrix1to2[10][1] = 0.990114126118697;
   fWeightMatrix1to2[11][1] = -0.286525393078873;
   fWeightMatrix1to2[12][1] = 0.407709096603697;
   fWeightMatrix1to2[13][1] = -0.338216013860824;
   fWeightMatrix1to2[14][1] = -1.616365929455;
   fWeightMatrix1to2[15][1] = -0.543606725324807;
   fWeightMatrix1to2[0][2] = -1.88473399423775;
   fWeightMatrix1to2[1][2] = -1.26748554404029;
   fWeightMatrix1to2[2][2] = -1.91011724194695;
   fWeightMatrix1to2[3][2] = 3.04511800872989;
   fWeightMatrix1to2[4][2] = -1.78865681483054;
   fWeightMatrix1to2[5][2] = 1.70020647620717;
   fWeightMatrix1to2[6][2] = -1.54158335474914;
   fWeightMatrix1to2[7][2] = 1.48320252613882;
   fWeightMatrix1to2[8][2] = -1.7653236009507;
   fWeightMatrix1to2[9][2] = 0.388076879892912;
   fWeightMatrix1to2[10][2] = 0.787500160794738;
   fWeightMatrix1to2[11][2] = -2.01298873226792;
   fWeightMatrix1to2[12][2] = 0.113150180616033;
   fWeightMatrix1to2[13][2] = 0.3612620721251;
   fWeightMatrix1to2[14][2] = -2.27119631327261;
   fWeightMatrix1to2[15][2] = -1.48868959062415;
   fWeightMatrix1to2[0][3] = -1.61530046467479;
   fWeightMatrix1to2[1][3] = -1.03872313243668;
   fWeightMatrix1to2[2][3] = 2.11441935325333;
   fWeightMatrix1to2[3][3] = -1.79234358752434;
   fWeightMatrix1to2[4][3] = -0.235423957573956;
   fWeightMatrix1to2[5][3] = -0.502915843396762;
   fWeightMatrix1to2[6][3] = -2.27936643781776;
   fWeightMatrix1to2[7][3] = -1.61444670930712;
   fWeightMatrix1to2[8][3] = -1.01433481260459;
   fWeightMatrix1to2[9][3] = -1.25946072602703;
   fWeightMatrix1to2[10][3] = 1.02070153033223;
   fWeightMatrix1to2[11][3] = -1.42316150607701;
   fWeightMatrix1to2[12][3] = 0.894547507114385;
   fWeightMatrix1to2[13][3] = 1.41718571589586;
   fWeightMatrix1to2[14][3] = 0.685938128776013;
   fWeightMatrix1to2[15][3] = -0.471050673358443;
   fWeightMatrix1to2[0][4] = 2.17433231357199;
   fWeightMatrix1to2[1][4] = -2.7754005978223;
   fWeightMatrix1to2[2][4] = 0.675190389664092;
   fWeightMatrix1to2[3][4] = 3.94725427936472;
   fWeightMatrix1to2[4][4] = -1.24302110098469;
   fWeightMatrix1to2[5][4] = -0.627991390224574;
   fWeightMatrix1to2[6][4] = 0.0806096493609481;
   fWeightMatrix1to2[7][4] = -1.39639298812131;
   fWeightMatrix1to2[8][4] = 1.01636534528035;
   fWeightMatrix1to2[9][4] = 1.96005641008104;
   fWeightMatrix1to2[10][4] = 1.33886195794716;
   fWeightMatrix1to2[11][4] = 1.4405537107139;
   fWeightMatrix1to2[12][4] = -2.4573572421172;
   fWeightMatrix1to2[13][4] = 0.765644907659799;
   fWeightMatrix1to2[14][4] = -2.02146562325921;
   fWeightMatrix1to2[15][4] = 0.61957217080792;
   fWeightMatrix1to2[0][5] = -1.2713892009242;
   fWeightMatrix1to2[1][5] = -1.71652924438191;
   fWeightMatrix1to2[2][5] = -1.12645032677651;
   fWeightMatrix1to2[3][5] = 0.301194088923926;
   fWeightMatrix1to2[4][5] = 1.06230013472542;
   fWeightMatrix1to2[5][5] = 1.64061179985661;
   fWeightMatrix1to2[6][5] = 0.303934098608941;
   fWeightMatrix1to2[7][5] = -0.61802815458046;
   fWeightMatrix1to2[8][5] = -0.865316138874931;
   fWeightMatrix1to2[9][5] = 0.309405277191182;
   fWeightMatrix1to2[10][5] = 1.93711880181794;
   fWeightMatrix1to2[11][5] = -1.67566115296376;
   fWeightMatrix1to2[12][5] = 1.48881703093455;
   fWeightMatrix1to2[13][5] = -1.4531746816006;
   fWeightMatrix1to2[14][5] = -1.0584251118534;
   fWeightMatrix1to2[15][5] = 0.0120498979419931;
   fWeightMatrix1to2[0][6] = 0.594092211712413;
   fWeightMatrix1to2[1][6] = -1.41251214704634;
   fWeightMatrix1to2[2][6] = 1.39205943274873;
   fWeightMatrix1to2[3][6] = 2.91542123116204;
   fWeightMatrix1to2[4][6] = 0.495961049016695;
   fWeightMatrix1to2[5][6] = 0.29290628278445;
   fWeightMatrix1to2[6][6] = -1.31144022211254;
   fWeightMatrix1to2[7][6] = -0.961312782061144;
   fWeightMatrix1to2[8][6] = -2.54927367640304;
   fWeightMatrix1to2[9][6] = 1.0363649504289;
   fWeightMatrix1to2[10][6] = -0.58730317444089;
   fWeightMatrix1to2[11][6] = -1.17033557810067;
   fWeightMatrix1to2[12][6] = 1.60565998845014;
   fWeightMatrix1to2[13][6] = -2.15631538988685;
   fWeightMatrix1to2[14][6] = -2.22103742318767;
   fWeightMatrix1to2[15][6] = -1.59000140339892;
   fWeightMatrix1to2[0][7] = 1.03956963502206;
   fWeightMatrix1to2[1][7] = -1.63195159822462;
   fWeightMatrix1to2[2][7] = -1.92116708480756;
   fWeightMatrix1to2[3][7] = 0.329107391792991;
   fWeightMatrix1to2[4][7] = -0.931250418073592;
   fWeightMatrix1to2[5][7] = -1.63684967678571;
   fWeightMatrix1to2[6][7] = 1.05481687305205;
   fWeightMatrix1to2[7][7] = -1.29611447500338;
   fWeightMatrix1to2[8][7] = -1.01268708619693;
   fWeightMatrix1to2[9][7] = 1.69692473406;
   fWeightMatrix1to2[10][7] = 0.522415957754397;
   fWeightMatrix1to2[11][7] = 0.284236764660544;
   fWeightMatrix1to2[12][7] = 0.143044142852172;
   fWeightMatrix1to2[13][7] = 1.24690643564597;
   fWeightMatrix1to2[14][7] = 1.74615952380554;
   fWeightMatrix1to2[15][7] = 0.504296927350476;
   fWeightMatrix1to2[0][8] = -0.959195622315186;
   fWeightMatrix1to2[1][8] = -0.104332304704254;
   fWeightMatrix1to2[2][8] = -1.38518899371512;
   fWeightMatrix1to2[3][8] = 2.49577978977026;
   fWeightMatrix1to2[4][8] = 1.22203199517309;
   fWeightMatrix1to2[5][8] = 0.0412634843834481;
   fWeightMatrix1to2[6][8] = 1.7069407090531;
   fWeightMatrix1to2[7][8] = 1.15291813653394;
   fWeightMatrix1to2[8][8] = 1.13492675098114;
   fWeightMatrix1to2[9][8] = -1.46757783443897;
   fWeightMatrix1to2[10][8] = 1.64091563260941;
   fWeightMatrix1to2[11][8] = 0.681894912539552;
   fWeightMatrix1to2[12][8] = -2.61902884134664;
   fWeightMatrix1to2[13][8] = 0.0509006490420845;
   fWeightMatrix1to2[14][8] = -1.34383972928613;
   fWeightMatrix1to2[15][8] = 0.858690404064695;
   fWeightMatrix1to2[0][9] = 0.35459864513451;
   fWeightMatrix1to2[1][9] = 0.784162607507213;
   fWeightMatrix1to2[2][9] = 1.67271460131551;
   fWeightMatrix1to2[3][9] = 1.97547504698429;
   fWeightMatrix1to2[4][9] = 1.34194089141081;
   fWeightMatrix1to2[5][9] = 1.71551280070488;
   fWeightMatrix1to2[6][9] = 0.177069755627689;
   fWeightMatrix1to2[7][9] = -1.2337065804015;
   fWeightMatrix1to2[8][9] = 1.85967220229847;
   fWeightMatrix1to2[9][9] = -2.07976265118556;
   fWeightMatrix1to2[10][9] = 0.576566093278334;
   fWeightMatrix1to2[11][9] = 1.60766581383121;
   fWeightMatrix1to2[12][9] = -1.09890061743022;
   fWeightMatrix1to2[13][9] = -1.01844281338789;
   fWeightMatrix1to2[14][9] = -0.269613416085211;
   fWeightMatrix1to2[15][9] = -1.33284536177485;
   fWeightMatrix1to2[0][10] = 0.380141488648301;
   fWeightMatrix1to2[1][10] = -1.90930350402237;
   fWeightMatrix1to2[2][10] = 0.0597343756827778;
   fWeightMatrix1to2[3][10] = 0.731343204532935;
   fWeightMatrix1to2[4][10] = 1.99806780360681;
   fWeightMatrix1to2[5][10] = 1.49126800993442;
   fWeightMatrix1to2[6][10] = 1.52998538616721;
   fWeightMatrix1to2[7][10] = -0.354612491821164;
   fWeightMatrix1to2[8][10] = -0.0560616784587124;
   fWeightMatrix1to2[9][10] = 0.267352041366639;
   fWeightMatrix1to2[10][10] = 1.85877328802449;
   fWeightMatrix1to2[11][10] = -1.91826061652027;
   fWeightMatrix1to2[12][10] = -2.10142177430238;
   fWeightMatrix1to2[13][10] = -0.728770685361666;
   fWeightMatrix1to2[14][10] = -1.41183772779826;
   fWeightMatrix1to2[15][10] = -1.69765909787257;
   fWeightMatrix1to2[0][11] = -1.4591173223078;
   fWeightMatrix1to2[1][11] = 0.841278201739326;
   fWeightMatrix1to2[2][11] = 0.0410945948463973;
   fWeightMatrix1to2[3][11] = -1.56871212559211;
   fWeightMatrix1to2[4][11] = -1.92986836031493;
   fWeightMatrix1to2[5][11] = -0.178728504660995;
   fWeightMatrix1to2[6][11] = 1.76910488782912;
   fWeightMatrix1to2[7][11] = 1.95220720335418;
   fWeightMatrix1to2[8][11] = 1.24475995416306;
   fWeightMatrix1to2[9][11] = -0.688868657467676;
   fWeightMatrix1to2[10][11] = -1.96012927920209;
   fWeightMatrix1to2[11][11] = -0.131666981741595;
   fWeightMatrix1to2[12][11] = -1.30767272795704;
   fWeightMatrix1to2[13][11] = -1.60828037951813;
   fWeightMatrix1to2[14][11] = -0.757108427816481;
   fWeightMatrix1to2[15][11] = 0.0139441729672199;
   fWeightMatrix1to2[0][12] = -1.45259869018715;
   fWeightMatrix1to2[1][12] = 2.12559618396637;
   fWeightMatrix1to2[2][12] = 1.35194012773089;
   fWeightMatrix1to2[3][12] = -0.633271152282453;
   fWeightMatrix1to2[4][12] = -1.58455836950229;
   fWeightMatrix1to2[5][12] = -0.805346445136346;
   fWeightMatrix1to2[6][12] = 2.20545110943552;
   fWeightMatrix1to2[7][12] = -0.177105870492583;
   fWeightMatrix1to2[8][12] = -0.581810785727329;
   fWeightMatrix1to2[9][12] = 1.34533942003961;
   fWeightMatrix1to2[10][12] = 1.43041021091995;
   fWeightMatrix1to2[11][12] = -1.24016941249696;
   fWeightMatrix1to2[12][12] = 2.33169912578419;
   fWeightMatrix1to2[13][12] = -1.75439216888044;
   fWeightMatrix1to2[14][12] = 1.52668377747369;
   fWeightMatrix1to2[15][12] = 1.8306909015148;
   fWeightMatrix1to2[0][13] = -0.254052553853989;
   fWeightMatrix1to2[1][13] = -0.261246548918479;
   fWeightMatrix1to2[2][13] = 0.314177524008979;
   fWeightMatrix1to2[3][13] = -0.103951846050791;
   fWeightMatrix1to2[4][13] = 1.38163834113137;
   fWeightMatrix1to2[5][13] = 0.177617691120959;
   fWeightMatrix1to2[6][13] = -0.292429455651066;
   fWeightMatrix1to2[7][13] = -1.40593915097222;
   fWeightMatrix1to2[8][13] = 0.0369341950594788;
   fWeightMatrix1to2[9][13] = 1.75626039405534;
   fWeightMatrix1to2[10][13] = 0.395711762443751;
   fWeightMatrix1to2[11][13] = -0.776033150837449;
   fWeightMatrix1to2[12][13] = -2.50847445371042;
   fWeightMatrix1to2[13][13] = 2.26026144237103;
   fWeightMatrix1to2[14][13] = 1.04002986544626;
   fWeightMatrix1to2[15][13] = -1.20763062490569;
   fWeightMatrix1to2[0][14] = -0.141860637774293;
   fWeightMatrix1to2[1][14] = -0.867335070405654;
   fWeightMatrix1to2[2][14] = 1.63079896338701;
   fWeightMatrix1to2[3][14] = 1.30589129750147;
   fWeightMatrix1to2[4][14] = -0.012004892948191;
   fWeightMatrix1to2[5][14] = -0.592453074300164;
   fWeightMatrix1to2[6][14] = 1.01745371296393;
   fWeightMatrix1to2[7][14] = 2.17169287340758;
   fWeightMatrix1to2[8][14] = 0.717541065439722;
   fWeightMatrix1to2[9][14] = 0.0497652835986406;
   fWeightMatrix1to2[10][14] = -1.32241574332665;
   fWeightMatrix1to2[11][14] = -1.22747714857366;
   fWeightMatrix1to2[12][14] = 1.25024119001591;
   fWeightMatrix1to2[13][14] = 0.159059805424172;
   fWeightMatrix1to2[14][14] = 0.00267079290904198;
   fWeightMatrix1to2[15][14] = -1.85889028860211;
   fWeightMatrix1to2[0][15] = -1.8527567447718;
   fWeightMatrix1to2[1][15] = -1.35690116250581;
   fWeightMatrix1to2[2][15] = -0.355389062422005;
   fWeightMatrix1to2[3][15] = -2.53944268329125;
   fWeightMatrix1to2[4][15] = -0.361500924314146;
   fWeightMatrix1to2[5][15] = -0.375392392622599;
   fWeightMatrix1to2[6][15] = 2.51914596532144;
   fWeightMatrix1to2[7][15] = 0.697950187784362;
   fWeightMatrix1to2[8][15] = -2.941732374646;
   fWeightMatrix1to2[9][15] = 1.20145666915239;
   fWeightMatrix1to2[10][15] = 1.81709278632352;
   fWeightMatrix1to2[11][15] = 0.921706026726505;
   fWeightMatrix1to2[12][15] = 0.044012402643332;
   fWeightMatrix1to2[13][15] = -0.782265221762049;
   fWeightMatrix1to2[14][15] = 2.15440450961223;
   fWeightMatrix1to2[15][15] = -1.7267359354655;
   fWeightMatrix1to2[0][16] = 0.404803355860795;
   fWeightMatrix1to2[1][16] = -0.864393513035101;
   fWeightMatrix1to2[2][16] = 1.18556461101215;
   fWeightMatrix1to2[3][16] = -0.644812449003381;
   fWeightMatrix1to2[4][16] = -0.457278953068088;
   fWeightMatrix1to2[5][16] = -0.507828255467427;
   fWeightMatrix1to2[6][16] = 0.849591508056585;
   fWeightMatrix1to2[7][16] = -0.933585621372741;
   fWeightMatrix1to2[8][16] = -1.04251598418779;
   fWeightMatrix1to2[9][16] = 0.9111332643725;
   fWeightMatrix1to2[10][16] = 0.347491473920297;
   fWeightMatrix1to2[11][16] = 0.710054254688609;
   fWeightMatrix1to2[12][16] = 1.07035333987353;
   fWeightMatrix1to2[13][16] = -1.20698212096086;
   fWeightMatrix1to2[14][16] = 1.80592594067022;
   fWeightMatrix1to2[15][16] = -1.88820476868636;
   fWeightMatrix1to2[0][17] = 1.12784063709349;
   fWeightMatrix1to2[1][17] = 0.595449314014458;
   fWeightMatrix1to2[2][17] = 0.109258245461091;
   fWeightMatrix1to2[3][17] = 2.41666553891155;
   fWeightMatrix1to2[4][17] = 2.01930821630882;
   fWeightMatrix1to2[5][17] = -1.64470590163158;
   fWeightMatrix1to2[6][17] = -0.905812143908471;
   fWeightMatrix1to2[7][17] = -0.250382185939773;
   fWeightMatrix1to2[8][17] = 0.941735633084564;
   fWeightMatrix1to2[9][17] = -0.397551612952183;
   fWeightMatrix1to2[10][17] = -0.287947076069085;
   fWeightMatrix1to2[11][17] = -0.821367486289761;
   fWeightMatrix1to2[12][17] = -1.31647587177985;
   fWeightMatrix1to2[13][17] = -1.83215821912445;
   fWeightMatrix1to2[14][17] = -1.58785566787885;
   fWeightMatrix1to2[15][17] = -1.82768500780099;
   fWeightMatrix1to2[0][18] = -0.410525051708406;
   fWeightMatrix1to2[1][18] = 0.35735314250953;
   fWeightMatrix1to2[2][18] = -0.972634227194845;
   fWeightMatrix1to2[3][18] = -1.11302186877161;
   fWeightMatrix1to2[4][18] = 0.729122192201161;
   fWeightMatrix1to2[5][18] = 0.369303518757226;
   fWeightMatrix1to2[6][18] = -0.493411455275432;
   fWeightMatrix1to2[7][18] = -1.42183771827868;
   fWeightMatrix1to2[8][18] = 1.84915046408576;
   fWeightMatrix1to2[9][18] = -0.321897368456588;
   fWeightMatrix1to2[10][18] = 0.695292826492388;
   fWeightMatrix1to2[11][18] = 0.62137514142032;
   fWeightMatrix1to2[12][18] = -1.2136522700467;
   fWeightMatrix1to2[13][18] = -0.848748269113596;
   fWeightMatrix1to2[14][18] = -0.250252162889066;
   fWeightMatrix1to2[15][18] = -1.97910234019751;
   fWeightMatrix1to2[0][19] = -0.666704956827026;
   fWeightMatrix1to2[1][19] = -1.33557121699788;
   fWeightMatrix1to2[2][19] = 1.43625088689779;
   fWeightMatrix1to2[3][19] = -1.88574932973378;
   fWeightMatrix1to2[4][19] = 1.75179311231136;
   fWeightMatrix1to2[5][19] = 2.0623602140836;
   fWeightMatrix1to2[6][19] = 1.14028666292293;
   fWeightMatrix1to2[7][19] = 1.27831511440625;
   fWeightMatrix1to2[8][19] = 1.11997645676311;
   fWeightMatrix1to2[9][19] = 0.25052276606035;
   fWeightMatrix1to2[10][19] = -0.915022573437352;
   fWeightMatrix1to2[11][19] = -1.92700289778004;
   fWeightMatrix1to2[12][19] = -0.682138443734582;
   fWeightMatrix1to2[13][19] = -0.889650482754865;
   fWeightMatrix1to2[14][19] = 1.67352948265617;
   fWeightMatrix1to2[15][19] = 0.177715656592355;
   fWeightMatrix1to2[0][20] = 0.214996493240298;
   fWeightMatrix1to2[1][20] = 1.40497631786535;
   fWeightMatrix1to2[2][20] = 1.85182819418522;
   fWeightMatrix1to2[3][20] = -2.55913326679968;
   fWeightMatrix1to2[4][20] = -0.523045559076531;
   fWeightMatrix1to2[5][20] = -1.63962453729191;
   fWeightMatrix1to2[6][20] = 0.924240354030757;
   fWeightMatrix1to2[7][20] = -2.13104227184738;
   fWeightMatrix1to2[8][20] = 0.271566805610699;
   fWeightMatrix1to2[9][20] = -0.0117741778800266;
   fWeightMatrix1to2[10][20] = 1.13794893553386;
   fWeightMatrix1to2[11][20] = -1.95548682579865;
   fWeightMatrix1to2[12][20] = 0.788867030296423;
   fWeightMatrix1to2[13][20] = -1.35941022448016;
   fWeightMatrix1to2[14][20] = -0.0175166128539128;
   fWeightMatrix1to2[15][20] = 1.19267561868236;
   fWeightMatrix1to2[0][21] = -0.624868159411658;
   fWeightMatrix1to2[1][21] = 0.847024691687078;
   fWeightMatrix1to2[2][21] = -1.56814284196544;
   fWeightMatrix1to2[3][21] = 0.824134653898158;
   fWeightMatrix1to2[4][21] = -1.07668057708656;
   fWeightMatrix1to2[5][21] = 1.0864243461562;
   fWeightMatrix1to2[6][21] = -1.8020647053102;
   fWeightMatrix1to2[7][21] = -0.488767531620989;
   fWeightMatrix1to2[8][21] = 1.50500159939612;
   fWeightMatrix1to2[9][21] = -1.92919676349625;
   fWeightMatrix1to2[10][21] = -1.36462500768312;
   fWeightMatrix1to2[11][21] = -1.08798402274466;
   fWeightMatrix1to2[12][21] = 1.92945604900072;
   fWeightMatrix1to2[13][21] = 1.46847222082394;
   fWeightMatrix1to2[14][21] = 1.69735288665222;
   fWeightMatrix1to2[15][21] = -1.72969339730728;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = 0.87064765013429;
   fWeightMatrix2to3[0][1] = 0.82885793473383;
   fWeightMatrix2to3[0][2] = 1.75436627324899;
   fWeightMatrix2to3[0][3] = -4.64069612239512;
   fWeightMatrix2to3[0][4] = -2.44335002530852;
   fWeightMatrix2to3[0][5] = -1.08294499444985;
   fWeightMatrix2to3[0][6] = 2.41194425529608;
   fWeightMatrix2to3[0][7] = 2.25725984629899;
   fWeightMatrix2to3[0][8] = -1.91678309443876;
   fWeightMatrix2to3[0][9] = -0.204653720731965;
   fWeightMatrix2to3[0][10] = -1.58665322411352;
   fWeightMatrix2to3[0][11] = 1.21947247554128;
   fWeightMatrix2to3[0][12] = 2.90975007208506;
   fWeightMatrix2to3[0][13] = 1.36775377569475;
   fWeightMatrix2to3[0][14] = -2.94058684893085;
   fWeightMatrix2to3[0][15] = -1.42889876383669;
   fWeightMatrix2to3[0][16] = 1.24353410147585;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)11) {
      std::cout << "Input vector needs to be of size " << 11 << std::endl;
      return 0;
   }

   std::array<double, 22> fWeights1 {{}};
   std::array<double, 17> fWeights2 {{}};
   std::array<double, 1> fWeights3 {{}};
   fWeights1.back() = 1.;
   fWeights2.back() = 1.;

   // layer 0 to 1
   for (int o=0; o<21; o++) {
      std::array<double, 12> buffer; // no need to initialise
      for (int i = 0; i<12 - 1; i++) {
         buffer[i] = fWeightMatrix0to1[o][i] * inputValues[i];
      } // loop over i
      buffer.back() = fWeightMatrix0to1[o][11];
      for (int i=0; i<12; i++) {
         fWeights1[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<21; o++) {
      fWeights1[o] = ActivationFnc(fWeights1[o]);
   } // loop over o
   // layer 1 to 2
   for (int o=0; o<16; o++) {
      std::array<double, 22> buffer; // no need to initialise
      for (int i=0; i<22; i++) {
         buffer[i] = fWeightMatrix1to2[o][i] * fWeights1[i];
      } // loop over i
      for (int i=0; i<22; i++) {
         fWeights2[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<16; o++) {
      fWeights2[o] = ActivationFnc(fWeights2[o]);
   } // loop over o
   // layer 2 to 3
   for (int o=0; o<1; o++) {
      std::array<double, 17> buffer; // no need to initialise
      for (int i=0; i<17; i++) {
         buffer[i] = fWeightMatrix2to3[o][i] * fWeights2[i];
      } // loop over i
      for (int i=0; i<17; i++) {
         fWeights3[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<1; o++) {
      fWeights3[o] = OutputActivationFnc(fWeights3[o]);
   } // loop over o

   return fWeights3[0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}

// Clean up
inline void ReadMLP::Clear()
{
}
inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         std::vector<double> iV(inputValues);
         Transform( iV, -1 );
         retval = GetMvaValue__( iV );
   }

   return retval;
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   double fMin_1[3][11];
   double fMax_1[3][11];
   // Normalization transformation, initialisation
   fMin_1[0][0] = 22.7864818573;
   fMax_1[0][0] = 7505.73046875;
   fScal_1[0][0] = 2.0/(fMax_1[0][0]-fMin_1[0][0]);
   fOff_1[0][0] = fMin_1[0][0]*fScal_1[0][0]+1.;
   fMin_1[1][0] = 23.5563087463;
   fMax_1[1][0] = 7838.75537109;
   fScal_1[1][0] = 2.0/(fMax_1[1][0]-fMin_1[1][0]);
   fOff_1[1][0] = fMin_1[1][0]*fScal_1[1][0]+1.;
   fMin_1[2][0] = 22.7864818573;
   fMax_1[2][0] = 7838.75537109;
   fScal_1[2][0] = 2.0/(fMax_1[2][0]-fMin_1[2][0]);
   fOff_1[2][0] = fMin_1[2][0]*fScal_1[2][0]+1.;
   fMin_1[0][1] = 0.000150358115206;
   fMax_1[0][1] = 8.68471050262;
   fScal_1[0][1] = 2.0/(fMax_1[0][1]-fMin_1[0][1]);
   fOff_1[0][1] = fMin_1[0][1]*fScal_1[0][1]+1.;
   fMin_1[1][1] = 2.2119609639e-05;
   fMax_1[1][1] = 8.68384933472;
   fScal_1[1][1] = 2.0/(fMax_1[1][1]-fMin_1[1][1]);
   fOff_1[1][1] = fMin_1[1][1]*fScal_1[1][1]+1.;
   fMin_1[2][1] = 2.2119609639e-05;
   fMax_1[2][1] = 8.68471050262;
   fScal_1[2][1] = 2.0/(fMax_1[2][1]-fMin_1[2][1]);
   fOff_1[2][1] = fMin_1[2][1]*fScal_1[2][1]+1.;
   fMin_1[0][2] = 126.97845459;
   fMax_1[0][2] = 2277.4987793;
   fScal_1[0][2] = 2.0/(fMax_1[0][2]-fMin_1[0][2]);
   fOff_1[0][2] = fMin_1[0][2]*fScal_1[0][2]+1.;
   fMin_1[1][2] = 125.825294495;
   fMax_1[1][2] = 1926.56140137;
   fScal_1[1][2] = 2.0/(fMax_1[1][2]-fMin_1[1][2]);
   fOff_1[1][2] = fMin_1[1][2]*fScal_1[1][2]+1.;
   fMin_1[2][2] = 125.825294495;
   fMax_1[2][2] = 2277.4987793;
   fScal_1[2][2] = 2.0/(fMax_1[2][2]-fMin_1[2][2]);
   fOff_1[2][2] = fMin_1[2][2]*fScal_1[2][2]+1.;
   fMin_1[0][3] = 4.91857872476e-06;
   fMax_1[0][3] = 0.405025333166;
   fScal_1[0][3] = 2.0/(fMax_1[0][3]-fMin_1[0][3]);
   fOff_1[0][3] = fMin_1[0][3]*fScal_1[0][3]+1.;
   fMin_1[1][3] = 5.9500340285e-05;
   fMax_1[1][3] = 0.47649076581;
   fScal_1[1][3] = 2.0/(fMax_1[1][3]-fMin_1[1][3]);
   fOff_1[1][3] = fMin_1[1][3]*fScal_1[1][3]+1.;
   fMin_1[2][3] = 4.91857872476e-06;
   fMax_1[2][3] = 0.47649076581;
   fScal_1[2][3] = 2.0/(fMax_1[2][3]-fMin_1[2][3]);
   fOff_1[2][3] = fMin_1[2][3]*fScal_1[2][3]+1.;
   fMin_1[0][4] = -4.50663423538;
   fMax_1[0][4] = 4.51134681702;
   fScal_1[0][4] = 2.0/(fMax_1[0][4]-fMin_1[0][4]);
   fOff_1[0][4] = fMin_1[0][4]*fScal_1[0][4]+1.;
   fMin_1[1][4] = -4.5036110878;
   fMax_1[1][4] = 4.50834369659;
   fScal_1[1][4] = 2.0/(fMax_1[1][4]-fMin_1[1][4]);
   fOff_1[1][4] = fMin_1[1][4]*fScal_1[1][4]+1.;
   fMin_1[2][4] = -4.50663423538;
   fMax_1[2][4] = 4.51134681702;
   fScal_1[2][4] = 2.0/(fMax_1[2][4]-fMin_1[2][4]);
   fOff_1[2][4] = fMin_1[2][4]*fScal_1[2][4]+1.;
   fMin_1[0][5] = 50.1059684753;
   fMax_1[0][5] = 1964.14489746;
   fScal_1[0][5] = 2.0/(fMax_1[0][5]-fMin_1[0][5]);
   fOff_1[0][5] = fMin_1[0][5]*fScal_1[0][5]+1.;
   fMin_1[1][5] = 50.0584754944;
   fMax_1[1][5] = 2753.2824707;
   fScal_1[1][5] = 2.0/(fMax_1[1][5]-fMin_1[1][5]);
   fOff_1[1][5] = fMin_1[1][5]*fScal_1[1][5]+1.;
   fMin_1[2][5] = 50.0584754944;
   fMax_1[2][5] = 2753.2824707;
   fScal_1[2][5] = 2.0/(fMax_1[2][5]-fMin_1[2][5]);
   fOff_1[2][5] = fMin_1[2][5]*fScal_1[2][5]+1.;
   fMin_1[0][6] = -2.4010925293;
   fMax_1[0][6] = 2.39041256905;
   fScal_1[0][6] = 2.0/(fMax_1[0][6]-fMin_1[0][6]);
   fOff_1[0][6] = fMin_1[0][6]*fScal_1[0][6]+1.;
   fMin_1[1][6] = -2.38632035255;
   fMax_1[1][6] = 2.38307738304;
   fScal_1[1][6] = 2.0/(fMax_1[1][6]-fMin_1[1][6]);
   fOff_1[1][6] = fMin_1[1][6]*fScal_1[1][6]+1.;
   fMin_1[2][6] = -2.4010925293;
   fMax_1[2][6] = 2.39041256905;
   fScal_1[2][6] = 2.0/(fMax_1[2][6]-fMin_1[2][6]);
   fOff_1[2][6] = fMin_1[2][6]*fScal_1[2][6]+1.;
   fMin_1[0][7] = 0.0488347522914;
   fMax_1[0][7] = 0.99988257885;
   fScal_1[0][7] = 2.0/(fMax_1[0][7]-fMin_1[0][7]);
   fOff_1[0][7] = fMin_1[0][7]*fScal_1[0][7]+1.;
   fMin_1[1][7] = 0.0229892414063;
   fMax_1[1][7] = 0.999983787537;
   fScal_1[1][7] = 2.0/(fMax_1[1][7]-fMin_1[1][7]);
   fOff_1[1][7] = fMin_1[1][7]*fScal_1[1][7]+1.;
   fMin_1[2][7] = 0.0229892414063;
   fMax_1[2][7] = 0.999983787537;
   fScal_1[2][7] = 2.0/(fMax_1[2][7]-fMin_1[2][7]);
   fOff_1[2][7] = fMin_1[2][7]*fScal_1[2][7]+1.;
   fMin_1[0][8] = 2;
   fMax_1[0][8] = 8;
   fScal_1[0][8] = 2.0/(fMax_1[0][8]-fMin_1[0][8]);
   fOff_1[0][8] = fMin_1[0][8]*fScal_1[0][8]+1.;
   fMin_1[1][8] = 2;
   fMax_1[1][8] = 9;
   fScal_1[1][8] = 2.0/(fMax_1[1][8]-fMin_1[1][8]);
   fOff_1[1][8] = fMin_1[1][8]*fScal_1[1][8]+1.;
   fMin_1[2][8] = 2;
   fMax_1[2][8] = 9;
   fScal_1[2][8] = 2.0/(fMax_1[2][8]-fMin_1[2][8]);
   fOff_1[2][8] = fMin_1[2][8]*fScal_1[2][8]+1.;
   fMin_1[0][9] = 1.5914440155e-05;
   fMax_1[0][9] = 1;
   fScal_1[0][9] = 2.0/(fMax_1[0][9]-fMin_1[0][9]);
   fOff_1[0][9] = fMin_1[0][9]*fScal_1[0][9]+1.;
   fMin_1[1][9] = 1.93119049072e-05;
   fMax_1[1][9] = 1;
   fScal_1[1][9] = 2.0/(fMax_1[1][9]-fMin_1[1][9]);
   fOff_1[1][9] = fMin_1[1][9]*fScal_1[1][9]+1.;
   fMin_1[2][9] = 1.5914440155e-05;
   fMax_1[2][9] = 1;
   fScal_1[2][9] = 2.0/(fMax_1[2][9]-fMin_1[2][9]);
   fOff_1[2][9] = fMin_1[2][9]*fScal_1[2][9]+1.;
   fMin_1[0][10] = 3.26525550918e-05;
   fMax_1[0][10] = 6.50682735443;
   fScal_1[0][10] = 2.0/(fMax_1[0][10]-fMin_1[0][10]);
   fOff_1[0][10] = fMin_1[0][10]*fScal_1[0][10]+1.;
   fMin_1[1][10] = 1.18112052405e-06;
   fMax_1[1][10] = 6.68952894211;
   fScal_1[1][10] = 2.0/(fMax_1[1][10]-fMin_1[1][10]);
   fOff_1[1][10] = fMin_1[1][10]*fScal_1[1][10]+1.;
   fMin_1[2][10] = 1.18112052405e-06;
   fMax_1[2][10] = 6.68952894211;
   fScal_1[2][10] = 2.0/(fMax_1[2][10]-fMin_1[2][10]);
   fOff_1[2][10] = fMin_1[2][10]*fScal_1[2][10]+1.;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) {
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   }
   if ( indicesPut.empty() ) {
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   }

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fOff_1[cls][ivar];
      double scale  = fScal_1[cls][ivar];
      iv[indicesPut.at(ivar)] = scale*dv[ivar]-offset;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
