// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.22/06       [398854]
Creator        : konstantin
Date           : Wed Mar 24 00:18:17 2021
Host           : Linux mach 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/konstantin/Projects/CERN/TMVA_MLP
Training events: 170672
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "400" [Number of training cycles]
HiddenLayers: "N+10,N+5" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
LearningRate: "1.000000e-02" [ANN learning rate parameter]
TestRate: "5" [Test for overtraining performed at each #th epochs]
BPMode: "batch" [Back-propagation learning mode: sequential or batch]
BatchSize: "5" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "2.500000e-03" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "5" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
mJJ                           mJJ                           mJJ                           mJJ                                                             'F'    [22.7864818573,7838.75537109]
deltaYJJ                      deltaYJJ                      deltaYJJ                      deltaYJJ                                                        'F'    [2.2119609639e-05,8.68471050262]
metPt                         metPt                         metPt                         metPt                                                           'F'    [125.825294495,2277.4987793]
ptBalance                     ptBalance                     ptBalance                     ptBalance                                                       'F'    [4.91857872476e-06,0.47649076581]
subleadJetEta                 subleadJetEta                 subleadJetEta                 subleadJetEta                                                   'F'    [-4.50663423538,4.51134681702]
leadJetPt                     leadJetPt                     leadJetPt                     leadJetPt                                                       'F'    [50.0584754944,2753.2824707]
photonEta                     photonEta                     photonEta                     photonEta                                                       'F'    [-2.4010925293,2.39041256905]
ptBalanceRed                  ptBalanceRed                  ptBalanceRed                  ptBalanceRed                                                    'F'    [0.0229892414063,0.999983787537]
nJets                         nJets                         nJets                         nJets                                                           'F'    [2,9]
sinDeltaPhiJJOver2            sinDeltaPhiJJOver2            sinDeltaPhiJJOver2            sinDeltaPhiJJOver2                                              'F'    [1.5914440155e-05,1]
deltaYJPh                     deltaYJPh                     deltaYJPh                     deltaYJPh                                                       'F'    [1.18112052405e-06,6.68952894211]
NSpec 1
weightModified                weightModified                weightModified                F                                                               'F'    [-0.191263645887,1.09073340893]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 11 )
   {
      // the training input variables
      const char* inputVars[] = { "mJJ", "deltaYJJ", "metPt", "ptBalance", "subleadJetEta", "leadJetPt", "photonEta", "ptBalanceRed", "nJets", "sinDeltaPhiJJOver2", "deltaYJPh" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fOff_1[3][11];
   double fScal_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   double fWeightMatrix0to1[22][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[17][22];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][17];   // weight matrix from layer 2 to 3

};

inline void ReadMLP::Initialize()
{
   // build network structure
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.150577334302312;
   fWeightMatrix0to1[1][0] = 2.54897029063929;
   fWeightMatrix0to1[2][0] = 0.0699030032238443;
   fWeightMatrix0to1[3][0] = 2.97016293871012;
   fWeightMatrix0to1[4][0] = -2.87877527984945;
   fWeightMatrix0to1[5][0] = -1.6815169494196;
   fWeightMatrix0to1[6][0] = -0.838773076326365;
   fWeightMatrix0to1[7][0] = 2.04392515746888;
   fWeightMatrix0to1[8][0] = -3.70425386790676;
   fWeightMatrix0to1[9][0] = -1.73196975908681;
   fWeightMatrix0to1[10][0] = -2.61335283662066;
   fWeightMatrix0to1[11][0] = -0.13495470460465;
   fWeightMatrix0to1[12][0] = -1.90661499772113;
   fWeightMatrix0to1[13][0] = 0.0673970649892397;
   fWeightMatrix0to1[14][0] = -0.880177016686667;
   fWeightMatrix0to1[15][0] = -0.0625484539839751;
   fWeightMatrix0to1[16][0] = -0.0197671145529154;
   fWeightMatrix0to1[17][0] = -0.844229749582436;
   fWeightMatrix0to1[18][0] = 0.0602651608428704;
   fWeightMatrix0to1[19][0] = 1.35650765115466;
   fWeightMatrix0to1[20][0] = 1.22177236316263;
   fWeightMatrix0to1[0][1] = -0.0177434939806087;
   fWeightMatrix0to1[1][1] = 0.724834925416247;
   fWeightMatrix0to1[2][1] = -2.23834062693357;
   fWeightMatrix0to1[3][1] = -0.454149912694273;
   fWeightMatrix0to1[4][1] = -2.43941889929944;
   fWeightMatrix0to1[5][1] = 0.254974130561231;
   fWeightMatrix0to1[6][1] = -3.59584806524894;
   fWeightMatrix0to1[7][1] = -1.56324579268383;
   fWeightMatrix0to1[8][1] = 0.493825796997961;
   fWeightMatrix0to1[9][1] = -0.21322299040392;
   fWeightMatrix0to1[10][1] = 1.35199597451883;
   fWeightMatrix0to1[11][1] = -0.435112125125076;
   fWeightMatrix0to1[12][1] = -0.150843688173683;
   fWeightMatrix0to1[13][1] = 1.307375060386;
   fWeightMatrix0to1[14][1] = -0.74020114620564;
   fWeightMatrix0to1[15][1] = -0.905491522829573;
   fWeightMatrix0to1[16][1] = 2.2404876591235;
   fWeightMatrix0to1[17][1] = -1.87564091097257;
   fWeightMatrix0to1[18][1] = 1.49219897557853;
   fWeightMatrix0to1[19][1] = 0.193981788765632;
   fWeightMatrix0to1[20][1] = 3.56593420274526;
   fWeightMatrix0to1[0][2] = 3.42353995755768;
   fWeightMatrix0to1[1][2] = 1.02087675175246;
   fWeightMatrix0to1[2][2] = 0.170752458274268;
   fWeightMatrix0to1[3][2] = -1.0461662140498;
   fWeightMatrix0to1[4][2] = -0.196117494286939;
   fWeightMatrix0to1[5][2] = 0.0612246031972783;
   fWeightMatrix0to1[6][2] = 0.828537954435524;
   fWeightMatrix0to1[7][2] = 1.93690063708278;
   fWeightMatrix0to1[8][2] = 0.684648468301998;
   fWeightMatrix0to1[9][2] = 1.8590380769176;
   fWeightMatrix0to1[10][2] = -2.38839729867268;
   fWeightMatrix0to1[11][2] = 1.64473530891251;
   fWeightMatrix0to1[12][2] = -0.733033414294997;
   fWeightMatrix0to1[13][2] = -1.52837268764862;
   fWeightMatrix0to1[14][2] = -0.958221781399579;
   fWeightMatrix0to1[15][2] = -0.767445360465973;
   fWeightMatrix0to1[16][2] = 1.44990603885715;
   fWeightMatrix0to1[17][2] = -1.37661372607897;
   fWeightMatrix0to1[18][2] = -1.77743378530532;
   fWeightMatrix0to1[19][2] = 0.00299494211934855;
   fWeightMatrix0to1[20][2] = 0.00153545460140299;
   fWeightMatrix0to1[0][3] = -0.43566988879755;
   fWeightMatrix0to1[1][3] = 1.68986856466686;
   fWeightMatrix0to1[2][3] = -0.154128606450579;
   fWeightMatrix0to1[3][3] = -0.350445017428182;
   fWeightMatrix0to1[4][3] = 0.532722656694717;
   fWeightMatrix0to1[5][3] = 1.72945262709439;
   fWeightMatrix0to1[6][3] = -0.729082886657884;
   fWeightMatrix0to1[7][3] = -0.608152468664591;
   fWeightMatrix0to1[8][3] = 0.0802581578408178;
   fWeightMatrix0to1[9][3] = 0.140592195490117;
   fWeightMatrix0to1[10][3] = 0.945599153965462;
   fWeightMatrix0to1[11][3] = 1.48492841591749;
   fWeightMatrix0to1[12][3] = 0.336312867508863;
   fWeightMatrix0to1[13][3] = -3.06192308068073;
   fWeightMatrix0to1[14][3] = -1.15454219304048;
   fWeightMatrix0to1[15][3] = 1.92694846899278;
   fWeightMatrix0to1[16][3] = -0.766450620872314;
   fWeightMatrix0to1[17][3] = 5.3379490008857;
   fWeightMatrix0to1[18][3] = 0.78449059510403;
   fWeightMatrix0to1[19][3] = 1.67361455309518;
   fWeightMatrix0to1[20][3] = -0.850051025213409;
   fWeightMatrix0to1[0][4] = -0.0272827537282555;
   fWeightMatrix0to1[1][4] = -0.73910700033433;
   fWeightMatrix0to1[2][4] = 1.60318708052169;
   fWeightMatrix0to1[3][4] = -0.230337057701588;
   fWeightMatrix0to1[4][4] = -3.84076970853431;
   fWeightMatrix0to1[5][4] = -2.57468366509519;
   fWeightMatrix0to1[6][4] = -1.18037711797929;
   fWeightMatrix0to1[7][4] = -1.26737236319746;
   fWeightMatrix0to1[8][4] = 1.12305541345709;
   fWeightMatrix0to1[9][4] = -1.32101345685895;
   fWeightMatrix0to1[10][4] = -0.497040412504936;
   fWeightMatrix0to1[11][4] = 1.62001305419306;
   fWeightMatrix0to1[12][4] = -0.363875925423106;
   fWeightMatrix0to1[13][4] = -0.559505473344046;
   fWeightMatrix0to1[14][4] = -0.82848432938736;
   fWeightMatrix0to1[15][4] = 0.694476707570615;
   fWeightMatrix0to1[16][4] = -1.83735029690807;
   fWeightMatrix0to1[17][4] = -0.0500749313805808;
   fWeightMatrix0to1[18][4] = 0.0615672705999834;
   fWeightMatrix0to1[19][4] = 0.654626089693142;
   fWeightMatrix0to1[20][4] = -3.44520556600147;
   fWeightMatrix0to1[0][5] = 1.41212189698588;
   fWeightMatrix0to1[1][5] = -0.346045046314177;
   fWeightMatrix0to1[2][5] = 0.403183898464639;
   fWeightMatrix0to1[3][5] = 0.573751330555878;
   fWeightMatrix0to1[4][5] = 0.865882630367449;
   fWeightMatrix0to1[5][5] = -1.23289295612817;
   fWeightMatrix0to1[6][5] = 1.57401105986335;
   fWeightMatrix0to1[7][5] = -0.00879741558235732;
   fWeightMatrix0to1[8][5] = -0.891753792234833;
   fWeightMatrix0to1[9][5] = -1.32770919979342;
   fWeightMatrix0to1[10][5] = 1.78185661061087;
   fWeightMatrix0to1[11][5] = 0.672105334999088;
   fWeightMatrix0to1[12][5] = -1.26021422125978;
   fWeightMatrix0to1[13][5] = 0.898154037036979;
   fWeightMatrix0to1[14][5] = -0.944979361809399;
   fWeightMatrix0to1[15][5] = -2.28779377687596;
   fWeightMatrix0to1[16][5] = -0.612702005092612;
   fWeightMatrix0to1[17][5] = -1.2966722021956;
   fWeightMatrix0to1[18][5] = 1.45650728046587;
   fWeightMatrix0to1[19][5] = 0.599737568207634;
   fWeightMatrix0to1[20][5] = -0.856508745386386;
   fWeightMatrix0to1[0][6] = 0.0119250754415651;
   fWeightMatrix0to1[1][6] = 0.501586507840286;
   fWeightMatrix0to1[2][6] = -0.901057788076488;
   fWeightMatrix0to1[3][6] = 0.882678481808864;
   fWeightMatrix0to1[4][6] = 1.76364067278432;
   fWeightMatrix0to1[5][6] = -1.82019910678478;
   fWeightMatrix0to1[6][6] = -0.798020311376311;
   fWeightMatrix0to1[7][6] = -1.01139696520769;
   fWeightMatrix0to1[8][6] = -0.484084431620302;
   fWeightMatrix0to1[9][6] = 0.614603069788757;
   fWeightMatrix0to1[10][6] = 0.591985221186909;
   fWeightMatrix0to1[11][6] = -0.561293894382006;
   fWeightMatrix0to1[12][6] = 0.45245362389103;
   fWeightMatrix0to1[13][6] = 0.464157248419613;
   fWeightMatrix0to1[14][6] = 1.83769559884443;
   fWeightMatrix0to1[15][6] = -0.459335430475647;
   fWeightMatrix0to1[16][6] = -0.302397690531055;
   fWeightMatrix0to1[17][6] = -0.105354785756221;
   fWeightMatrix0to1[18][6] = -1.31359891281228;
   fWeightMatrix0to1[19][6] = 1.36330804434717;
   fWeightMatrix0to1[20][6] = 1.51316233777652;
   fWeightMatrix0to1[0][7] = -0.222435008819254;
   fWeightMatrix0to1[1][7] = -0.155797183939875;
   fWeightMatrix0to1[2][7] = 0.841167580969322;
   fWeightMatrix0to1[3][7] = -0.770782746779772;
   fWeightMatrix0to1[4][7] = -0.274207634396172;
   fWeightMatrix0to1[5][7] = 1.03632275806031;
   fWeightMatrix0to1[6][7] = -0.392009156326182;
   fWeightMatrix0to1[7][7] = 0.328664594708586;
   fWeightMatrix0to1[8][7] = 0.171418148074733;
   fWeightMatrix0to1[9][7] = 0.28632531074878;
   fWeightMatrix0to1[10][7] = -0.580916720087541;
   fWeightMatrix0to1[11][7] = 0.343015385919851;
   fWeightMatrix0to1[12][7] = -0.809535022108538;
   fWeightMatrix0to1[13][7] = 1.06620477307167;
   fWeightMatrix0to1[14][7] = 0.871351079943065;
   fWeightMatrix0to1[15][7] = 0.652690434362574;
   fWeightMatrix0to1[16][7] = 0.356786552549641;
   fWeightMatrix0to1[17][7] = 0.357569312293853;
   fWeightMatrix0to1[18][7] = 0.203866782039773;
   fWeightMatrix0to1[19][7] = -0.275871352614891;
   fWeightMatrix0to1[20][7] = 0.644416145744808;
   fWeightMatrix0to1[0][8] = -0.928738092902743;
   fWeightMatrix0to1[1][8] = -0.60947343134317;
   fWeightMatrix0to1[2][8] = 0.511681729388931;
   fWeightMatrix0to1[3][8] = 1.62187974472134;
   fWeightMatrix0to1[4][8] = -1.06368687305072;
   fWeightMatrix0to1[5][8] = 2.31626908764509;
   fWeightMatrix0to1[6][8] = 2.28400159473396;
   fWeightMatrix0to1[7][8] = -2.07256620049686;
   fWeightMatrix0to1[8][8] = -0.778113131830911;
   fWeightMatrix0to1[9][8] = -0.115395879802059;
   fWeightMatrix0to1[10][8] = -0.1162879416845;
   fWeightMatrix0to1[11][8] = -1.22138923736566;
   fWeightMatrix0to1[12][8] = -2.21572912274179;
   fWeightMatrix0to1[13][8] = -0.639027848982569;
   fWeightMatrix0to1[14][8] = 2.13358226340099;
   fWeightMatrix0to1[15][8] = -2.94220695019235;
   fWeightMatrix0to1[16][8] = -0.404892085051439;
   fWeightMatrix0to1[17][8] = 0.299095859372971;
   fWeightMatrix0to1[18][8] = 0.233911463740746;
   fWeightMatrix0to1[19][8] = 2.57592180154789;
   fWeightMatrix0to1[20][8] = 0.702098848844828;
   fWeightMatrix0to1[0][9] = -0.700631870859356;
   fWeightMatrix0to1[1][9] = -0.556549933115879;
   fWeightMatrix0to1[2][9] = 0.189661513834417;
   fWeightMatrix0to1[3][9] = 0.73652116390454;
   fWeightMatrix0to1[4][9] = 0.244756912301092;
   fWeightMatrix0to1[5][9] = -0.0725568689022321;
   fWeightMatrix0to1[6][9] = -0.568854027632741;
   fWeightMatrix0to1[7][9] = -1.89683075168332;
   fWeightMatrix0to1[8][9] = 0.943776328924123;
   fWeightMatrix0to1[9][9] = 0.725003073286618;
   fWeightMatrix0to1[10][9] = -2.05892105529969;
   fWeightMatrix0to1[11][9] = -1.44087099278539;
   fWeightMatrix0to1[12][9] = -0.0570240203418546;
   fWeightMatrix0to1[13][9] = -0.114141776797499;
   fWeightMatrix0to1[14][9] = -2.27802485057571;
   fWeightMatrix0to1[15][9] = 0.0757722148502736;
   fWeightMatrix0to1[16][9] = -0.117276899653876;
   fWeightMatrix0to1[17][9] = 0.257953914468614;
   fWeightMatrix0to1[18][9] = -1.2059267235008;
   fWeightMatrix0to1[19][9] = 0.367303970836246;
   fWeightMatrix0to1[20][9] = 0.362143523901523;
   fWeightMatrix0to1[0][10] = -0.208478246239415;
   fWeightMatrix0to1[1][10] = 0.622871001901261;
   fWeightMatrix0to1[2][10] = -2.60106472010539;
   fWeightMatrix0to1[3][10] = -0.510589098069014;
   fWeightMatrix0to1[4][10] = 1.0151590853625;
   fWeightMatrix0to1[5][10] = 1.35898520735142;
   fWeightMatrix0to1[6][10] = 1.03348508771375;
   fWeightMatrix0to1[7][10] = -0.0677984286610478;
   fWeightMatrix0to1[8][10] = 1.86234345711607;
   fWeightMatrix0to1[9][10] = -1.61097954130701;
   fWeightMatrix0to1[10][10] = -1.07530215208099;
   fWeightMatrix0to1[11][10] = 0.0911662217573434;
   fWeightMatrix0to1[12][10] = -0.919614377026854;
   fWeightMatrix0to1[13][10] = -0.629219559359263;
   fWeightMatrix0to1[14][10] = 1.42906409608988;
   fWeightMatrix0to1[15][10] = -1.17613696718933;
   fWeightMatrix0to1[16][10] = -0.413738318655952;
   fWeightMatrix0to1[17][10] = -0.466361573859085;
   fWeightMatrix0to1[18][10] = -2.68661958884165;
   fWeightMatrix0to1[19][10] = -1.13251568030316;
   fWeightMatrix0to1[20][10] = -1.32965988329238;
   fWeightMatrix0to1[0][11] = 3.82988243853926;
   fWeightMatrix0to1[1][11] = 1.0636443704361;
   fWeightMatrix0to1[2][11] = -3.55143226741352;
   fWeightMatrix0to1[3][11] = 2.58988371940553;
   fWeightMatrix0to1[4][11] = -4.19750954855213;
   fWeightMatrix0to1[5][11] = 0.175620871771155;
   fWeightMatrix0to1[6][11] = -0.873644688115254;
   fWeightMatrix0to1[7][11] = -1.66878947787657;
   fWeightMatrix0to1[8][11] = -4.13367740410355;
   fWeightMatrix0to1[9][11] = -4.30593221072272;
   fWeightMatrix0to1[10][11] = -2.24060054535866;
   fWeightMatrix0to1[11][11] = -1.91764602725999;
   fWeightMatrix0to1[12][11] = -3.00469939330964;
   fWeightMatrix0to1[13][11] = -2.68531441250066;
   fWeightMatrix0to1[14][11] = -0.306970046800037;
   fWeightMatrix0to1[15][11] = -2.62675385143531;
   fWeightMatrix0to1[16][11] = 0.178861801912088;
   fWeightMatrix0to1[17][11] = 2.46548731360639;
   fWeightMatrix0to1[18][11] = -0.772354716560188;
   fWeightMatrix0to1[19][11] = 0.951735801928333;
   fWeightMatrix0to1[20][11] = 1.68289666371047;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.188545942234935;
   fWeightMatrix1to2[1][0] = 1.70456601722298;
   fWeightMatrix1to2[2][0] = 1.51133118929023;
   fWeightMatrix1to2[3][0] = -0.594898484633954;
   fWeightMatrix1to2[4][0] = -2.68910381044995;
   fWeightMatrix1to2[5][0] = -0.935632021700667;
   fWeightMatrix1to2[6][0] = -1.82052861431935;
   fWeightMatrix1to2[7][0] = -0.798183888301667;
   fWeightMatrix1to2[8][0] = 0.304530785802751;
   fWeightMatrix1to2[9][0] = 0.361340133131103;
   fWeightMatrix1to2[10][0] = 1.80602277811195;
   fWeightMatrix1to2[11][0] = -0.445299093391988;
   fWeightMatrix1to2[12][0] = 1.18235845531901;
   fWeightMatrix1to2[13][0] = -0.650281353910655;
   fWeightMatrix1to2[14][0] = -2.04645046841655;
   fWeightMatrix1to2[15][0] = 1.3091631684738;
   fWeightMatrix1to2[0][1] = 1.22792200817486;
   fWeightMatrix1to2[1][1] = -0.866682483049467;
   fWeightMatrix1to2[2][1] = -0.943220163984456;
   fWeightMatrix1to2[3][1] = 0.315417701123158;
   fWeightMatrix1to2[4][1] = 1.10287034286553;
   fWeightMatrix1to2[5][1] = 0.498474107895472;
   fWeightMatrix1to2[6][1] = -0.480737091956912;
   fWeightMatrix1to2[7][1] = -0.259952829923351;
   fWeightMatrix1to2[8][1] = 1.51315636469898;
   fWeightMatrix1to2[9][1] = 1.07644588005941;
   fWeightMatrix1to2[10][1] = 0.988497587135284;
   fWeightMatrix1to2[11][1] = -0.287396784606668;
   fWeightMatrix1to2[12][1] = 0.360990477610064;
   fWeightMatrix1to2[13][1] = -0.315224921680079;
   fWeightMatrix1to2[14][1] = -1.60383519517501;
   fWeightMatrix1to2[15][1] = -0.54577503062701;
   fWeightMatrix1to2[0][2] = -1.86506168095689;
   fWeightMatrix1to2[1][2] = -1.27503049563941;
   fWeightMatrix1to2[2][2] = -1.89814394889762;
   fWeightMatrix1to2[3][2] = 3.06195536565451;
   fWeightMatrix1to2[4][2] = -1.78460366723179;
   fWeightMatrix1to2[5][2] = 1.7040238039723;
   fWeightMatrix1to2[6][2] = -1.45751123295029;
   fWeightMatrix1to2[7][2] = 1.51581551394185;
   fWeightMatrix1to2[8][2] = -1.79196532541981;
   fWeightMatrix1to2[9][2] = 0.4130997190406;
   fWeightMatrix1to2[10][2] = 0.793008839890253;
   fWeightMatrix1to2[11][2] = -2.00550353178879;
   fWeightMatrix1to2[12][2] = 0.191219790877997;
   fWeightMatrix1to2[13][2] = 0.416617441003155;
   fWeightMatrix1to2[14][2] = -2.30301634052491;
   fWeightMatrix1to2[15][2] = -1.49237689419197;
   fWeightMatrix1to2[0][3] = -1.57708702967684;
   fWeightMatrix1to2[1][3] = -0.93095416977708;
   fWeightMatrix1to2[2][3] = 2.04998216324757;
   fWeightMatrix1to2[3][3] = -1.57957005190087;
   fWeightMatrix1to2[4][3] = -0.0212297393050342;
   fWeightMatrix1to2[5][3] = -0.528400427112517;
   fWeightMatrix1to2[6][3] = -2.24681174886115;
   fWeightMatrix1to2[7][3] = -1.54068857961705;
   fWeightMatrix1to2[8][3] = -0.976607417471521;
   fWeightMatrix1to2[9][3] = -1.16830141322905;
   fWeightMatrix1to2[10][3] = 1.00329542968169;
   fWeightMatrix1to2[11][3] = -1.42463004002078;
   fWeightMatrix1to2[12][3] = 1.00057990409433;
   fWeightMatrix1to2[13][3] = 1.38786206847915;
   fWeightMatrix1to2[14][3] = 0.737876207944236;
   fWeightMatrix1to2[15][3] = -0.481414448927702;
   fWeightMatrix1to2[0][4] = 2.19973043603869;
   fWeightMatrix1to2[1][4] = -2.82766865531907;
   fWeightMatrix1to2[2][4] = 0.725788075101498;
   fWeightMatrix1to2[3][4] = 3.88207041195086;
   fWeightMatrix1to2[4][4] = -1.21437591700862;
   fWeightMatrix1to2[5][4] = -0.633294003655872;
   fWeightMatrix1to2[6][4] = 0.132020791790858;
   fWeightMatrix1to2[7][4] = -1.32522410326599;
   fWeightMatrix1to2[8][4] = 0.994898195253004;
   fWeightMatrix1to2[9][4] = 2.05108487593183;
   fWeightMatrix1to2[10][4] = 1.33477246947884;
   fWeightMatrix1to2[11][4] = 1.44799165993826;
   fWeightMatrix1to2[12][4] = -2.37444748765993;
   fWeightMatrix1to2[13][4] = 0.795344251094516;
   fWeightMatrix1to2[14][4] = -2.15266914984835;
   fWeightMatrix1to2[15][4] = 0.614596619970841;
   fWeightMatrix1to2[0][5] = -1.25376852570771;
   fWeightMatrix1to2[1][5] = -1.82338211442237;
   fWeightMatrix1to2[2][5] = -1.05195543977862;
   fWeightMatrix1to2[3][5] = 0.310724360339309;
   fWeightMatrix1to2[4][5] = 0.920333821161801;
   fWeightMatrix1to2[5][5] = 1.56770558968317;
   fWeightMatrix1to2[6][5] = 0.176150514753124;
   fWeightMatrix1to2[7][5] = -0.566489410737902;
   fWeightMatrix1to2[8][5] = -0.921058388315943;
   fWeightMatrix1to2[9][5] = 0.368165785643011;
   fWeightMatrix1to2[10][5] = 1.93442390327474;
   fWeightMatrix1to2[11][5] = -1.67304042522602;
   fWeightMatrix1to2[12][5] = 1.38897428902766;
   fWeightMatrix1to2[13][5] = -1.46373112974024;
   fWeightMatrix1to2[14][5] = -0.982732805584346;
   fWeightMatrix1to2[15][5] = 0.0159067239979597;
   fWeightMatrix1to2[0][6] = 0.612055718130436;
   fWeightMatrix1to2[1][6] = -1.43571877930973;
   fWeightMatrix1to2[2][6] = 1.33263348207963;
   fWeightMatrix1to2[3][6] = 2.76335083555374;
   fWeightMatrix1to2[4][6] = 0.439653150153578;
   fWeightMatrix1to2[5][6] = 0.23111634225242;
   fWeightMatrix1to2[6][6] = -1.29952804128079;
   fWeightMatrix1to2[7][6] = -1.03651178296038;
   fWeightMatrix1to2[8][6] = -2.5897900710273;
   fWeightMatrix1to2[9][6] = 1.06678365680625;
   fWeightMatrix1to2[10][6] = -0.574069513682716;
   fWeightMatrix1to2[11][6] = -1.17148935567186;
   fWeightMatrix1to2[12][6] = 1.6671180549019;
   fWeightMatrix1to2[13][6] = -2.12265764404591;
   fWeightMatrix1to2[14][6] = -2.13797543886789;
   fWeightMatrix1to2[15][6] = -1.595863597509;
   fWeightMatrix1to2[0][7] = 1.03973818637845;
   fWeightMatrix1to2[1][7] = -1.59002702759253;
   fWeightMatrix1to2[2][7] = -1.9308877646093;
   fWeightMatrix1to2[3][7] = 0.250464064214478;
   fWeightMatrix1to2[4][7] = -0.880690839114297;
   fWeightMatrix1to2[5][7] = -1.63287080638177;
   fWeightMatrix1to2[6][7] = 1.0922415112681;
   fWeightMatrix1to2[7][7] = -1.33556635216802;
   fWeightMatrix1to2[8][7] = -1.0062967609032;
   fWeightMatrix1to2[9][7] = 1.71580550623064;
   fWeightMatrix1to2[10][7] = 0.528848665495836;
   fWeightMatrix1to2[11][7] = 0.280771430839763;
   fWeightMatrix1to2[12][7] = 0.162619837151885;
   fWeightMatrix1to2[13][7] = 1.26661727660287;
   fWeightMatrix1to2[14][7] = 1.73376771291198;
   fWeightMatrix1to2[15][7] = 0.501288787381789;
   fWeightMatrix1to2[0][8] = -0.954774307871381;
   fWeightMatrix1to2[1][8] = -0.161881728414448;
   fWeightMatrix1to2[2][8] = -1.34734551846664;
   fWeightMatrix1to2[3][8] = 2.61157903516437;
   fWeightMatrix1to2[4][8] = 1.18981326576452;
   fWeightMatrix1to2[5][8] = 0.0829195206296001;
   fWeightMatrix1to2[6][8] = 1.8486107276038;
   fWeightMatrix1to2[7][8] = 1.14889517557668;
   fWeightMatrix1to2[8][8] = 1.15418257458533;
   fWeightMatrix1to2[9][8] = -1.42805753817309;
   fWeightMatrix1to2[10][8] = 1.65493071056665;
   fWeightMatrix1to2[11][8] = 0.688452413546133;
   fWeightMatrix1to2[12][8] = -2.76899518485527;
   fWeightMatrix1to2[13][8] = 0.0486558280575528;
   fWeightMatrix1to2[14][8] = -1.39967436742375;
   fWeightMatrix1to2[15][8] = 0.857963537564514;
   fWeightMatrix1to2[0][9] = 0.358199633779197;
   fWeightMatrix1to2[1][9] = 0.708372745599211;
   fWeightMatrix1to2[2][9] = 1.6418417325341;
   fWeightMatrix1to2[3][9] = 1.96071179545179;
   fWeightMatrix1to2[4][9] = 1.40360724692492;
   fWeightMatrix1to2[5][9] = 1.71992291317506;
   fWeightMatrix1to2[6][9] = 0.229053668273376;
   fWeightMatrix1to2[7][9] = -1.25330878185293;
   fWeightMatrix1to2[8][9] = 1.90000504420181;
   fWeightMatrix1to2[9][9] = -2.06511941537593;
   fWeightMatrix1to2[10][9] = 0.573153242334156;
   fWeightMatrix1to2[11][9] = 1.6080060773362;
   fWeightMatrix1to2[12][9] = -1.22343830246643;
   fWeightMatrix1to2[13][9] = -0.996333573662053;
   fWeightMatrix1to2[14][9] = -0.20148020758241;
   fWeightMatrix1to2[15][9] = -1.33658140149884;
   fWeightMatrix1to2[0][10] = 0.390117822283801;
   fWeightMatrix1to2[1][10] = -1.78539814599386;
   fWeightMatrix1to2[2][10] = 0.0938495607227098;
   fWeightMatrix1to2[3][10] = 0.757189371723588;
   fWeightMatrix1to2[4][10] = 2.10022800273418;
   fWeightMatrix1to2[5][10] = 1.48189201863494;
   fWeightMatrix1to2[6][10] = 1.53213161787435;
   fWeightMatrix1to2[7][10] = -0.373065230446298;
   fWeightMatrix1to2[8][10] = -0.130524981081061;
   fWeightMatrix1to2[9][10] = 0.312988500774081;
   fWeightMatrix1to2[10][10] = 1.85846001867324;
   fWeightMatrix1to2[11][10] = -1.91891999808653;
   fWeightMatrix1to2[12][10] = -2.0275112363105;
   fWeightMatrix1to2[13][10] = -0.711485366549891;
   fWeightMatrix1to2[14][10] = -1.48839395014923;
   fWeightMatrix1to2[15][10] = -1.69776860565663;
   fWeightMatrix1to2[0][11] = -1.46003732357074;
   fWeightMatrix1to2[1][11] = 0.869768204087018;
   fWeightMatrix1to2[2][11] = 0.0369166755394667;
   fWeightMatrix1to2[3][11] = -1.56829365773657;
   fWeightMatrix1to2[4][11] = -1.95400584438378;
   fWeightMatrix1to2[5][11] = -0.180009947055299;
   fWeightMatrix1to2[6][11] = 1.77874594030726;
   fWeightMatrix1to2[7][11] = 1.94647399018217;
   fWeightMatrix1to2[8][11] = 1.24344556589784;
   fWeightMatrix1to2[9][11] = -0.693055334652515;
   fWeightMatrix1to2[10][11] = -1.9596850939746;
   fWeightMatrix1to2[11][11] = -0.13187450084873;
   fWeightMatrix1to2[12][11] = -1.34401283849739;
   fWeightMatrix1to2[13][11] = -1.60141462411721;
   fWeightMatrix1to2[14][11] = -0.734216339685394;
   fWeightMatrix1to2[15][11] = 0.0134620019669161;
   fWeightMatrix1to2[0][12] = -1.42500613783291;
   fWeightMatrix1to2[1][12] = 2.18258808780284;
   fWeightMatrix1to2[2][12] = 1.32269096051626;
   fWeightMatrix1to2[3][12] = -0.702964310632153;
   fWeightMatrix1to2[4][12] = -1.44315481755233;
   fWeightMatrix1to2[5][12] = -0.717148199513382;
   fWeightMatrix1to2[6][12] = 2.2990904689398;
   fWeightMatrix1to2[7][12] = -0.163105967675225;
   fWeightMatrix1to2[8][12] = -0.534062973386445;
   fWeightMatrix1to2[9][12] = 1.52654819966584;
   fWeightMatrix1to2[10][12] = 1.44561728515339;
   fWeightMatrix1to2[11][12] = -1.23797225920266;
   fWeightMatrix1to2[12][12] = 2.30528645341547;
   fWeightMatrix1to2[13][12] = -1.79778777706938;
   fWeightMatrix1to2[14][12] = 1.56244229067966;
   fWeightMatrix1to2[15][12] = 1.82524976477849;
   fWeightMatrix1to2[0][13] = -0.242028991583174;
   fWeightMatrix1to2[1][13] = -0.324631570538734;
   fWeightMatrix1to2[2][13] = 0.280942804051804;
   fWeightMatrix1to2[3][13] = 0.0175885651247366;
   fWeightMatrix1to2[4][13] = 1.32495186719357;
   fWeightMatrix1to2[5][13] = 0.219876375827339;
   fWeightMatrix1to2[6][13] = -0.267044118654918;
   fWeightMatrix1to2[7][13] = -1.40793248799582;
   fWeightMatrix1to2[8][13] = 0.0284189547083687;
   fWeightMatrix1to2[9][13] = 1.90679692156342;
   fWeightMatrix1to2[10][13] = 0.395816262220276;
   fWeightMatrix1to2[11][13] = -0.784212796309637;
   fWeightMatrix1to2[12][13] = -2.52504434462134;
   fWeightMatrix1to2[13][13] = 2.14167727286844;
   fWeightMatrix1to2[14][13] = 0.866133742057655;
   fWeightMatrix1to2[15][13] = -1.19795256042449;
   fWeightMatrix1to2[0][14] = -0.112644248035792;
   fWeightMatrix1to2[1][14] = -0.903111490869378;
   fWeightMatrix1to2[2][14] = 1.61434542412538;
   fWeightMatrix1to2[3][14] = 1.25744954515399;
   fWeightMatrix1to2[4][14] = -0.00635653010581934;
   fWeightMatrix1to2[5][14] = -0.640268744974299;
   fWeightMatrix1to2[6][14] = 0.872385840904898;
   fWeightMatrix1to2[7][14] = 2.08669350985597;
   fWeightMatrix1to2[8][14] = 0.62190303675069;
   fWeightMatrix1to2[9][14] = 0.126222694724861;
   fWeightMatrix1to2[10][14] = -1.3137437976992;
   fWeightMatrix1to2[11][14] = -1.22988374111879;
   fWeightMatrix1to2[12][14] = 1.38217479520576;
   fWeightMatrix1to2[13][14] = 0.229111395493414;
   fWeightMatrix1to2[14][14] = -0.0954357474368796;
   fWeightMatrix1to2[15][14] = -1.86539565006927;
   fWeightMatrix1to2[0][15] = -1.8296846847393;
   fWeightMatrix1to2[1][15] = -1.35189413800214;
   fWeightMatrix1to2[2][15] = -0.384627926859464;
   fWeightMatrix1to2[3][15] = -2.57441257682918;
   fWeightMatrix1to2[4][15] = -0.229678583328153;
   fWeightMatrix1to2[5][15] = -0.267828799640521;
   fWeightMatrix1to2[6][15] = 2.57606829450463;
   fWeightMatrix1to2[7][15] = 0.722994467962808;
   fWeightMatrix1to2[8][15] = -2.86553840889643;
   fWeightMatrix1to2[9][15] = 1.36510226581907;
   fWeightMatrix1to2[10][15] = 1.83234914258438;
   fWeightMatrix1to2[11][15] = 0.925449260386031;
   fWeightMatrix1to2[12][15] = -0.0331400124869413;
   fWeightMatrix1to2[13][15] = -0.81103136556398;
   fWeightMatrix1to2[14][15] = 2.25788087226663;
   fWeightMatrix1to2[15][15] = -1.72902929939894;
   fWeightMatrix1to2[0][16] = 0.440685346493633;
   fWeightMatrix1to2[1][16] = -0.838365231619569;
   fWeightMatrix1to2[2][16] = 1.18800678708898;
   fWeightMatrix1to2[3][16] = -0.782910364157747;
   fWeightMatrix1to2[4][16] = -0.559157386624972;
   fWeightMatrix1to2[5][16] = -0.506535230777872;
   fWeightMatrix1to2[6][16] = 0.957438088598107;
   fWeightMatrix1to2[7][16] = -0.922160768382142;
   fWeightMatrix1to2[8][16] = -1.10196820566605;
   fWeightMatrix1to2[9][16] = 0.989420228728138;
   fWeightMatrix1to2[10][16] = 0.343626894298646;
   fWeightMatrix1to2[11][16] = 0.70321330793324;
   fWeightMatrix1to2[12][16] = 0.877205435025316;
   fWeightMatrix1to2[13][16] = -1.297433997898;
   fWeightMatrix1to2[14][16] = 1.80530832698158;
   fWeightMatrix1to2[15][16] = -1.8848590328557;
   fWeightMatrix1to2[0][17] = 1.15655885088145;
   fWeightMatrix1to2[1][17] = 0.619105820739341;
   fWeightMatrix1to2[2][17] = 0.165297006725431;
   fWeightMatrix1to2[3][17] = 2.45958875776586;
   fWeightMatrix1to2[4][17] = 2.11087417802484;
   fWeightMatrix1to2[5][17] = -1.61597702477493;
   fWeightMatrix1to2[6][17] = -1.00805655944751;
   fWeightMatrix1to2[7][17] = -0.222737055686342;
   fWeightMatrix1to2[8][17] = 0.973398865984983;
   fWeightMatrix1to2[9][17] = -0.297793926956124;
   fWeightMatrix1to2[10][17] = -0.278413033992344;
   fWeightMatrix1to2[11][17] = -0.807168826084591;
   fWeightMatrix1to2[12][17] = -1.33034565226211;
   fWeightMatrix1to2[13][17] = -1.72336530813458;
   fWeightMatrix1to2[14][17] = -1.48586638662202;
   fWeightMatrix1to2[15][17] = -1.83422267095702;
   fWeightMatrix1to2[0][18] = -0.377173516371615;
   fWeightMatrix1to2[1][18] = 0.479752576913762;
   fWeightMatrix1to2[2][18] = -1.00347562489841;
   fWeightMatrix1to2[3][18] = -1.07157150393595;
   fWeightMatrix1to2[4][18] = 0.698836056732174;
   fWeightMatrix1to2[5][18] = 0.377083945627085;
   fWeightMatrix1to2[6][18] = -0.533642718530663;
   fWeightMatrix1to2[7][18] = -1.41575249744769;
   fWeightMatrix1to2[8][18] = 1.78189515627691;
   fWeightMatrix1to2[9][18] = -0.272807393578621;
   fWeightMatrix1to2[10][18] = 0.696887647308922;
   fWeightMatrix1to2[11][18] = 0.618373554666523;
   fWeightMatrix1to2[12][18] = -1.13332949343242;
   fWeightMatrix1to2[13][18] = -0.873683287115993;
   fWeightMatrix1to2[14][18] = -0.175893757578133;
   fWeightMatrix1to2[15][18] = -1.97784936933946;
   fWeightMatrix1to2[0][19] = -0.668990486038296;
   fWeightMatrix1to2[1][19] = -1.34868775143305;
   fWeightMatrix1to2[2][19] = 1.40714094369439;
   fWeightMatrix1to2[3][19] = -1.77178037536562;
   fWeightMatrix1to2[4][19] = 1.73702698578356;
   fWeightMatrix1to2[5][19] = 1.96898636961892;
   fWeightMatrix1to2[6][19] = 1.23266112619182;
   fWeightMatrix1to2[7][19] = 1.2805463358642;
   fWeightMatrix1to2[8][19] = 1.09403919204759;
   fWeightMatrix1to2[9][19] = 0.19776176338193;
   fWeightMatrix1to2[10][19] = -0.924059718760175;
   fWeightMatrix1to2[11][19] = -1.92784589506346;
   fWeightMatrix1to2[12][19] = -0.788519950319352;
   fWeightMatrix1to2[13][19] = -0.865031063917259;
   fWeightMatrix1to2[14][19] = 1.63932680934925;
   fWeightMatrix1to2[15][19] = 0.171659431205486;
   fWeightMatrix1to2[0][20] = 0.253170770232018;
   fWeightMatrix1to2[1][20] = 1.37936960766685;
   fWeightMatrix1to2[2][20] = 1.83283525833957;
   fWeightMatrix1to2[3][20] = -2.65135312003226;
   fWeightMatrix1to2[4][20] = -0.477792768777662;
   fWeightMatrix1to2[5][20] = -1.63673938542511;
   fWeightMatrix1to2[6][20] = 0.998395531652407;
   fWeightMatrix1to2[7][20] = -2.10288395257271;
   fWeightMatrix1to2[8][20] = 0.279210172481887;
   fWeightMatrix1to2[9][20] = 0.114785661099514;
   fWeightMatrix1to2[10][20] = 1.12068597755103;
   fWeightMatrix1to2[11][20] = -1.96072876990511;
   fWeightMatrix1to2[12][20] = 0.771675580465457;
   fWeightMatrix1to2[13][20] = -1.43220278458964;
   fWeightMatrix1to2[14][20] = -0.00949526527092981;
   fWeightMatrix1to2[15][20] = 1.18775004960028;
   fWeightMatrix1to2[0][21] = -0.585275841275617;
   fWeightMatrix1to2[1][21] = 0.90388013438358;
   fWeightMatrix1to2[2][21] = -1.56665575411132;
   fWeightMatrix1to2[3][21] = 0.837136871711061;
   fWeightMatrix1to2[4][21] = -0.989101135878996;
   fWeightMatrix1to2[5][21] = 1.10110847544637;
   fWeightMatrix1to2[6][21] = -1.72157341713;
   fWeightMatrix1to2[7][21] = -0.425150664810146;
   fWeightMatrix1to2[8][21] = 1.49002601386195;
   fWeightMatrix1to2[9][21] = -1.7605671283712;
   fWeightMatrix1to2[10][21] = -1.35820281957546;
   fWeightMatrix1to2[11][21] = -1.08292013685135;
   fWeightMatrix1to2[12][21] = 1.87618217896966;
   fWeightMatrix1to2[13][21] = 1.45323764471145;
   fWeightMatrix1to2[14][21] = 1.7221623985896;
   fWeightMatrix1to2[15][21] = -1.7382995649886;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = 0.922268509652011;
   fWeightMatrix2to3[0][1] = 0.97333632756763;
   fWeightMatrix2to3[0][2] = 1.83971699357077;
   fWeightMatrix2to3[0][3] = -5.03081776820801;
   fWeightMatrix2to3[0][4] = -2.6310598656409;
   fWeightMatrix2to3[0][5] = -0.918834245216976;
   fWeightMatrix2to3[0][6] = 2.79395801428368;
   fWeightMatrix2to3[0][7] = 2.26052258678531;
   fWeightMatrix2to3[0][8] = -2.13446792364894;
   fWeightMatrix2to3[0][9] = -0.625762289291463;
   fWeightMatrix2to3[0][10] = -1.42166671844859;
   fWeightMatrix2to3[0][11] = 1.22407977477101;
   fWeightMatrix2to3[0][12] = 3.42006416305715;
   fWeightMatrix2to3[0][13] = 1.31192348168701;
   fWeightMatrix2to3[0][14] = -3.23576338165328;
   fWeightMatrix2to3[0][15] = -1.42220585310777;
   fWeightMatrix2to3[0][16] = 1.40895158698223;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)11) {
      std::cout << "Input vector needs to be of size " << 11 << std::endl;
      return 0;
   }

   std::array<double, 22> fWeights1 {{}};
   std::array<double, 17> fWeights2 {{}};
   std::array<double, 1> fWeights3 {{}};
   fWeights1.back() = 1.;
   fWeights2.back() = 1.;

   // layer 0 to 1
   for (int o=0; o<21; o++) {
      std::array<double, 12> buffer; // no need to initialise
      for (int i = 0; i<12 - 1; i++) {
         buffer[i] = fWeightMatrix0to1[o][i] * inputValues[i];
      } // loop over i
      buffer.back() = fWeightMatrix0to1[o][11];
      for (int i=0; i<12; i++) {
         fWeights1[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<21; o++) {
      fWeights1[o] = ActivationFnc(fWeights1[o]);
   } // loop over o
   // layer 1 to 2
   for (int o=0; o<16; o++) {
      std::array<double, 22> buffer; // no need to initialise
      for (int i=0; i<22; i++) {
         buffer[i] = fWeightMatrix1to2[o][i] * fWeights1[i];
      } // loop over i
      for (int i=0; i<22; i++) {
         fWeights2[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<16; o++) {
      fWeights2[o] = ActivationFnc(fWeights2[o]);
   } // loop over o
   // layer 2 to 3
   for (int o=0; o<1; o++) {
      std::array<double, 17> buffer; // no need to initialise
      for (int i=0; i<17; i++) {
         buffer[i] = fWeightMatrix2to3[o][i] * fWeights2[i];
      } // loop over i
      for (int i=0; i<17; i++) {
         fWeights3[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<1; o++) {
      fWeights3[o] = OutputActivationFnc(fWeights3[o]);
   } // loop over o

   return fWeights3[0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}

// Clean up
inline void ReadMLP::Clear()
{
}
inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         std::vector<double> iV(inputValues);
         Transform( iV, -1 );
         retval = GetMvaValue__( iV );
   }

   return retval;
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   double fMin_1[3][11];
   double fMax_1[3][11];
   // Normalization transformation, initialisation
   fMin_1[0][0] = 22.7864818573;
   fMax_1[0][0] = 7505.73046875;
   fScal_1[0][0] = 2.0/(fMax_1[0][0]-fMin_1[0][0]);
   fOff_1[0][0] = fMin_1[0][0]*fScal_1[0][0]+1.;
   fMin_1[1][0] = 23.5563087463;
   fMax_1[1][0] = 7838.75537109;
   fScal_1[1][0] = 2.0/(fMax_1[1][0]-fMin_1[1][0]);
   fOff_1[1][0] = fMin_1[1][0]*fScal_1[1][0]+1.;
   fMin_1[2][0] = 22.7864818573;
   fMax_1[2][0] = 7838.75537109;
   fScal_1[2][0] = 2.0/(fMax_1[2][0]-fMin_1[2][0]);
   fOff_1[2][0] = fMin_1[2][0]*fScal_1[2][0]+1.;
   fMin_1[0][1] = 0.000150358115206;
   fMax_1[0][1] = 8.68471050262;
   fScal_1[0][1] = 2.0/(fMax_1[0][1]-fMin_1[0][1]);
   fOff_1[0][1] = fMin_1[0][1]*fScal_1[0][1]+1.;
   fMin_1[1][1] = 2.2119609639e-05;
   fMax_1[1][1] = 8.68384933472;
   fScal_1[1][1] = 2.0/(fMax_1[1][1]-fMin_1[1][1]);
   fOff_1[1][1] = fMin_1[1][1]*fScal_1[1][1]+1.;
   fMin_1[2][1] = 2.2119609639e-05;
   fMax_1[2][1] = 8.68471050262;
   fScal_1[2][1] = 2.0/(fMax_1[2][1]-fMin_1[2][1]);
   fOff_1[2][1] = fMin_1[2][1]*fScal_1[2][1]+1.;
   fMin_1[0][2] = 126.97845459;
   fMax_1[0][2] = 2277.4987793;
   fScal_1[0][2] = 2.0/(fMax_1[0][2]-fMin_1[0][2]);
   fOff_1[0][2] = fMin_1[0][2]*fScal_1[0][2]+1.;
   fMin_1[1][2] = 125.825294495;
   fMax_1[1][2] = 1926.56140137;
   fScal_1[1][2] = 2.0/(fMax_1[1][2]-fMin_1[1][2]);
   fOff_1[1][2] = fMin_1[1][2]*fScal_1[1][2]+1.;
   fMin_1[2][2] = 125.825294495;
   fMax_1[2][2] = 2277.4987793;
   fScal_1[2][2] = 2.0/(fMax_1[2][2]-fMin_1[2][2]);
   fOff_1[2][2] = fMin_1[2][2]*fScal_1[2][2]+1.;
   fMin_1[0][3] = 4.91857872476e-06;
   fMax_1[0][3] = 0.405025333166;
   fScal_1[0][3] = 2.0/(fMax_1[0][3]-fMin_1[0][3]);
   fOff_1[0][3] = fMin_1[0][3]*fScal_1[0][3]+1.;
   fMin_1[1][3] = 5.9500340285e-05;
   fMax_1[1][3] = 0.47649076581;
   fScal_1[1][3] = 2.0/(fMax_1[1][3]-fMin_1[1][3]);
   fOff_1[1][3] = fMin_1[1][3]*fScal_1[1][3]+1.;
   fMin_1[2][3] = 4.91857872476e-06;
   fMax_1[2][3] = 0.47649076581;
   fScal_1[2][3] = 2.0/(fMax_1[2][3]-fMin_1[2][3]);
   fOff_1[2][3] = fMin_1[2][3]*fScal_1[2][3]+1.;
   fMin_1[0][4] = -4.50663423538;
   fMax_1[0][4] = 4.51134681702;
   fScal_1[0][4] = 2.0/(fMax_1[0][4]-fMin_1[0][4]);
   fOff_1[0][4] = fMin_1[0][4]*fScal_1[0][4]+1.;
   fMin_1[1][4] = -4.5036110878;
   fMax_1[1][4] = 4.50834369659;
   fScal_1[1][4] = 2.0/(fMax_1[1][4]-fMin_1[1][4]);
   fOff_1[1][4] = fMin_1[1][4]*fScal_1[1][4]+1.;
   fMin_1[2][4] = -4.50663423538;
   fMax_1[2][4] = 4.51134681702;
   fScal_1[2][4] = 2.0/(fMax_1[2][4]-fMin_1[2][4]);
   fOff_1[2][4] = fMin_1[2][4]*fScal_1[2][4]+1.;
   fMin_1[0][5] = 50.1059684753;
   fMax_1[0][5] = 1964.14489746;
   fScal_1[0][5] = 2.0/(fMax_1[0][5]-fMin_1[0][5]);
   fOff_1[0][5] = fMin_1[0][5]*fScal_1[0][5]+1.;
   fMin_1[1][5] = 50.0584754944;
   fMax_1[1][5] = 2753.2824707;
   fScal_1[1][5] = 2.0/(fMax_1[1][5]-fMin_1[1][5]);
   fOff_1[1][5] = fMin_1[1][5]*fScal_1[1][5]+1.;
   fMin_1[2][5] = 50.0584754944;
   fMax_1[2][5] = 2753.2824707;
   fScal_1[2][5] = 2.0/(fMax_1[2][5]-fMin_1[2][5]);
   fOff_1[2][5] = fMin_1[2][5]*fScal_1[2][5]+1.;
   fMin_1[0][6] = -2.4010925293;
   fMax_1[0][6] = 2.39041256905;
   fScal_1[0][6] = 2.0/(fMax_1[0][6]-fMin_1[0][6]);
   fOff_1[0][6] = fMin_1[0][6]*fScal_1[0][6]+1.;
   fMin_1[1][6] = -2.38632035255;
   fMax_1[1][6] = 2.38307738304;
   fScal_1[1][6] = 2.0/(fMax_1[1][6]-fMin_1[1][6]);
   fOff_1[1][6] = fMin_1[1][6]*fScal_1[1][6]+1.;
   fMin_1[2][6] = -2.4010925293;
   fMax_1[2][6] = 2.39041256905;
   fScal_1[2][6] = 2.0/(fMax_1[2][6]-fMin_1[2][6]);
   fOff_1[2][6] = fMin_1[2][6]*fScal_1[2][6]+1.;
   fMin_1[0][7] = 0.0488347522914;
   fMax_1[0][7] = 0.99988257885;
   fScal_1[0][7] = 2.0/(fMax_1[0][7]-fMin_1[0][7]);
   fOff_1[0][7] = fMin_1[0][7]*fScal_1[0][7]+1.;
   fMin_1[1][7] = 0.0229892414063;
   fMax_1[1][7] = 0.999983787537;
   fScal_1[1][7] = 2.0/(fMax_1[1][7]-fMin_1[1][7]);
   fOff_1[1][7] = fMin_1[1][7]*fScal_1[1][7]+1.;
   fMin_1[2][7] = 0.0229892414063;
   fMax_1[2][7] = 0.999983787537;
   fScal_1[2][7] = 2.0/(fMax_1[2][7]-fMin_1[2][7]);
   fOff_1[2][7] = fMin_1[2][7]*fScal_1[2][7]+1.;
   fMin_1[0][8] = 2;
   fMax_1[0][8] = 8;
   fScal_1[0][8] = 2.0/(fMax_1[0][8]-fMin_1[0][8]);
   fOff_1[0][8] = fMin_1[0][8]*fScal_1[0][8]+1.;
   fMin_1[1][8] = 2;
   fMax_1[1][8] = 9;
   fScal_1[1][8] = 2.0/(fMax_1[1][8]-fMin_1[1][8]);
   fOff_1[1][8] = fMin_1[1][8]*fScal_1[1][8]+1.;
   fMin_1[2][8] = 2;
   fMax_1[2][8] = 9;
   fScal_1[2][8] = 2.0/(fMax_1[2][8]-fMin_1[2][8]);
   fOff_1[2][8] = fMin_1[2][8]*fScal_1[2][8]+1.;
   fMin_1[0][9] = 1.5914440155e-05;
   fMax_1[0][9] = 1;
   fScal_1[0][9] = 2.0/(fMax_1[0][9]-fMin_1[0][9]);
   fOff_1[0][9] = fMin_1[0][9]*fScal_1[0][9]+1.;
   fMin_1[1][9] = 1.93119049072e-05;
   fMax_1[1][9] = 1;
   fScal_1[1][9] = 2.0/(fMax_1[1][9]-fMin_1[1][9]);
   fOff_1[1][9] = fMin_1[1][9]*fScal_1[1][9]+1.;
   fMin_1[2][9] = 1.5914440155e-05;
   fMax_1[2][9] = 1;
   fScal_1[2][9] = 2.0/(fMax_1[2][9]-fMin_1[2][9]);
   fOff_1[2][9] = fMin_1[2][9]*fScal_1[2][9]+1.;
   fMin_1[0][10] = 3.26525550918e-05;
   fMax_1[0][10] = 6.50682735443;
   fScal_1[0][10] = 2.0/(fMax_1[0][10]-fMin_1[0][10]);
   fOff_1[0][10] = fMin_1[0][10]*fScal_1[0][10]+1.;
   fMin_1[1][10] = 1.18112052405e-06;
   fMax_1[1][10] = 6.68952894211;
   fScal_1[1][10] = 2.0/(fMax_1[1][10]-fMin_1[1][10]);
   fOff_1[1][10] = fMin_1[1][10]*fScal_1[1][10]+1.;
   fMin_1[2][10] = 1.18112052405e-06;
   fMax_1[2][10] = 6.68952894211;
   fScal_1[2][10] = 2.0/(fMax_1[2][10]-fMin_1[2][10]);
   fOff_1[2][10] = fMin_1[2][10]*fScal_1[2][10]+1.;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) {
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   }
   if ( indicesPut.empty() ) {
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   }

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fOff_1[cls][ivar];
      double scale  = fScal_1[cls][ivar];
      iv[indicesPut.at(ivar)] = scale*dv[ivar]-offset;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
