// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.22/06       [398854]
Creator        : konstantin
Date           : Thu Apr  1 19:51:45 2021
Host           : Linux mach 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/konstantin/Projects/CERN/TMVA_MLP
Training events: 170672
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "400" [Number of training cycles]
HiddenLayers: "N+5,N+5" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
LearningRate: "1.000000e-02" [ANN learning rate parameter]
TestRate: "5" [Test for overtraining performed at each #th epochs]
BPMode: "batch" [Back-propagation learning mode: sequential or batch]
BatchSize: "3" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "2.500000e-03" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "5" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
mJJ                           mJJ                           mJJ                           mJJ                                                             'F'    [22.7864818573,7838.75537109]
deltaYJJ                      deltaYJJ                      deltaYJJ                      deltaYJJ                                                        'F'    [2.2119609639e-05,8.68471050262]
metPt                         metPt                         metPt                         metPt                                                           'F'    [125.825294495,2277.4987793]
ptBalance                     ptBalance                     ptBalance                     ptBalance                                                       'F'    [4.91857872476e-06,0.47649076581]
subleadJetEta                 subleadJetEta                 subleadJetEta                 subleadJetEta                                                   'F'    [-4.50663423538,4.51134681702]
leadJetPt                     leadJetPt                     leadJetPt                     leadJetPt                                                       'F'    [50.0584754944,2753.2824707]
photonEta                     photonEta                     photonEta                     photonEta                                                       'F'    [-2.4010925293,2.39041256905]
ptBalanceRed                  ptBalanceRed                  ptBalanceRed                  ptBalanceRed                                                    'F'    [0.0229892414063,0.999983787537]
nJets                         nJets                         nJets                         nJets                                                           'F'    [2,9]
sinDeltaPhiJJOver2            sinDeltaPhiJJOver2            sinDeltaPhiJJOver2            sinDeltaPhiJJOver2                                              'F'    [1.5914440155e-05,1]
deltaYJPh                     deltaYJPh                     deltaYJPh                     deltaYJPh                                                       'F'    [1.18112052405e-06,6.68952894211]
NSpec 1
weightModified                weightModified                weightModified                F                                                               'F'    [-0.191263645887,1.09073340893]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 11 )
   {
      // the training input variables
      const char* inputVars[] = { "mJJ", "deltaYJJ", "metPt", "ptBalance", "subleadJetEta", "leadJetPt", "photonEta", "ptBalanceRed", "nJets", "sinDeltaPhiJJOver2", "deltaYJPh" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fOff_1[3][11];
   double fScal_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   double fWeightMatrix0to1[17][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[17][17];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][17];   // weight matrix from layer 2 to 3

};

inline void ReadMLP::Initialize()
{
   // build network structure
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.265251188482921;
   fWeightMatrix0to1[1][0] = 2.27883584060135;
   fWeightMatrix0to1[2][0] = 2.08100920369986;
   fWeightMatrix0to1[3][0] = 2.43815856635088;
   fWeightMatrix0to1[4][0] = -5.29654774914477;
   fWeightMatrix0to1[5][0] = -1.56360040026351;
   fWeightMatrix0to1[6][0] = 1.86687730344339;
   fWeightMatrix0to1[7][0] = 2.31988048925746;
   fWeightMatrix0to1[8][0] = -1.22378240190908;
   fWeightMatrix0to1[9][0] = -0.904844276594281;
   fWeightMatrix0to1[10][0] = -2.09502683762242;
   fWeightMatrix0to1[11][0] = -4.00772775951736;
   fWeightMatrix0to1[12][0] = -2.10405531998419;
   fWeightMatrix0to1[13][0] = -0.474382116938337;
   fWeightMatrix0to1[14][0] = 1.93135395065212;
   fWeightMatrix0to1[15][0] = 1.48199127692559;
   fWeightMatrix0to1[0][1] = -2.44030318254761;
   fWeightMatrix0to1[1][1] = 1.75528309206422;
   fWeightMatrix0to1[2][1] = -0.639006600808253;
   fWeightMatrix0to1[3][1] = 1.11208838794946;
   fWeightMatrix0to1[4][1] = -3.93674529645754;
   fWeightMatrix0to1[5][1] = 0.325742687008527;
   fWeightMatrix0to1[6][1] = -1.20183510025946;
   fWeightMatrix0to1[7][1] = 0.668684982796903;
   fWeightMatrix0to1[8][1] = -2.09761166561715;
   fWeightMatrix0to1[9][1] = 0.50782661017574;
   fWeightMatrix0to1[10][1] = 3.06680603279781;
   fWeightMatrix0to1[11][1] = -0.893344776700991;
   fWeightMatrix0to1[12][1] = -2.63462573612368;
   fWeightMatrix0to1[13][1] = 1.50936246067684;
   fWeightMatrix0to1[14][1] = 2.74695512105347;
   fWeightMatrix0to1[15][1] = 3.04498688651008;
   fWeightMatrix0to1[0][2] = 0.467247360679898;
   fWeightMatrix0to1[1][2] = 0.16826982836902;
   fWeightMatrix0to1[2][2] = -0.13600916026123;
   fWeightMatrix0to1[3][2] = 0.564596889925869;
   fWeightMatrix0to1[4][2] = -1.05777191550426;
   fWeightMatrix0to1[5][2] = 2.77881865246061;
   fWeightMatrix0to1[6][2] = 0.673304501460723;
   fWeightMatrix0to1[7][2] = 0.970370085723172;
   fWeightMatrix0to1[8][2] = 3.17415355768307;
   fWeightMatrix0to1[9][2] = 2.19004963923349;
   fWeightMatrix0to1[10][2] = 1.4335667111191;
   fWeightMatrix0to1[11][2] = -0.167564300463653;
   fWeightMatrix0to1[12][2] = -0.217683912747838;
   fWeightMatrix0to1[13][2] = -1.92293980981655;
   fWeightMatrix0to1[14][2] = 0.284426720786782;
   fWeightMatrix0to1[15][2] = -0.139673519228898;
   fWeightMatrix0to1[0][3] = 1.68456193141243;
   fWeightMatrix0to1[1][3] = 1.61235431910941;
   fWeightMatrix0to1[2][3] = 0.743959130695902;
   fWeightMatrix0to1[3][3] = 1.2800314378814;
   fWeightMatrix0to1[4][3] = 0.0204400753086681;
   fWeightMatrix0to1[5][3] = 1.06479899722768;
   fWeightMatrix0to1[6][3] = -0.16515392117847;
   fWeightMatrix0to1[7][3] = -1.28306629757388;
   fWeightMatrix0to1[8][3] = -1.59702740012976;
   fWeightMatrix0to1[9][3] = -0.18504268398506;
   fWeightMatrix0to1[10][3] = 0.875451023507663;
   fWeightMatrix0to1[11][3] = 5.48834129078586;
   fWeightMatrix0to1[12][3] = -0.390032207075233;
   fWeightMatrix0to1[13][3] = -0.0714256655456907;
   fWeightMatrix0to1[14][3] = -0.435329571543279;
   fWeightMatrix0to1[15][3] = -0.467278375010804;
   fWeightMatrix0to1[0][4] = 2.39903340873682;
   fWeightMatrix0to1[1][4] = -0.217725090592666;
   fWeightMatrix0to1[2][4] = 0.026502204730959;
   fWeightMatrix0to1[3][4] = -1.10006826363443;
   fWeightMatrix0to1[4][4] = 2.95029755003603;
   fWeightMatrix0to1[5][4] = -1.25841116663014;
   fWeightMatrix0to1[6][4] = 0.258941007490668;
   fWeightMatrix0to1[7][4] = -0.550846051803659;
   fWeightMatrix0to1[8][4] = 0.311247269213118;
   fWeightMatrix0to1[9][4] = 0.348957941539803;
   fWeightMatrix0to1[10][4] = 1.02365902876848;
   fWeightMatrix0to1[11][4] = 0.833326430001651;
   fWeightMatrix0to1[12][4] = -1.99720711747177;
   fWeightMatrix0to1[13][4] = -1.78065516802821;
   fWeightMatrix0to1[14][4] = 5.02480142272894;
   fWeightMatrix0to1[15][4] = 0.68384493776935;
   fWeightMatrix0to1[0][5] = 2.24915353973074;
   fWeightMatrix0to1[1][5] = 0.92338556383528;
   fWeightMatrix0to1[2][5] = 2.13717250629296;
   fWeightMatrix0to1[3][5] = 0.00488928819581543;
   fWeightMatrix0to1[4][5] = 0.974273302906023;
   fWeightMatrix0to1[5][5] = -0.0785898596523038;
   fWeightMatrix0to1[6][5] = 1.95903486752543;
   fWeightMatrix0to1[7][5] = -1.38580475491853;
   fWeightMatrix0to1[8][5] = -1.43669796490908;
   fWeightMatrix0to1[9][5] = -1.83971617295495;
   fWeightMatrix0to1[10][5] = 0.409175398049854;
   fWeightMatrix0to1[11][5] = -1.49601496109798;
   fWeightMatrix0to1[12][5] = 1.26298307665822;
   fWeightMatrix0to1[13][5] = -2.69368110301604;
   fWeightMatrix0to1[14][5] = -1.22150849279646;
   fWeightMatrix0to1[15][5] = 0.447893948649231;
   fWeightMatrix0to1[0][6] = 0.171154678515802;
   fWeightMatrix0to1[1][6] = -1.23917358050828;
   fWeightMatrix0to1[2][6] = -0.17428741592664;
   fWeightMatrix0to1[3][6] = 0.175935523244186;
   fWeightMatrix0to1[4][6] = -1.08257000496979;
   fWeightMatrix0to1[5][6] = -1.25867287656952;
   fWeightMatrix0to1[6][6] = 0.1077898732115;
   fWeightMatrix0to1[7][6] = 0.880224209316397;
   fWeightMatrix0to1[8][6] = -0.748659141787034;
   fWeightMatrix0to1[9][6] = 1.13912511108376;
   fWeightMatrix0to1[10][6] = -0.708217052376421;
   fWeightMatrix0to1[11][6] = -0.221909358421243;
   fWeightMatrix0to1[12][6] = 2.07177538284471;
   fWeightMatrix0to1[13][6] = 1.19859561242454;
   fWeightMatrix0to1[14][6] = -1.92860188218912;
   fWeightMatrix0to1[15][6] = 1.00427542301138;
   fWeightMatrix0to1[0][7] = 0.277000304174506;
   fWeightMatrix0to1[1][7] = 0.386209850850618;
   fWeightMatrix0to1[2][7] = -1.41217817558792;
   fWeightMatrix0to1[3][7] = 1.37247621601874;
   fWeightMatrix0to1[4][7] = -0.218430212162233;
   fWeightMatrix0to1[5][7] = -0.975478105703274;
   fWeightMatrix0to1[6][7] = 0.108694955551888;
   fWeightMatrix0to1[7][7] = -1.84699022183794;
   fWeightMatrix0to1[8][7] = -0.62890257483464;
   fWeightMatrix0to1[9][7] = -0.685701217860172;
   fWeightMatrix0to1[10][7] = 0.480529355185964;
   fWeightMatrix0to1[11][7] = -0.130742663423121;
   fWeightMatrix0to1[12][7] = 0.0509163721251107;
   fWeightMatrix0to1[13][7] = 0.000289528534803215;
   fWeightMatrix0to1[14][7] = 0.386272576519953;
   fWeightMatrix0to1[15][7] = 0.273181956692248;
   fWeightMatrix0to1[0][8] = 0.325208672816838;
   fWeightMatrix0to1[1][8] = 1.21096704725476;
   fWeightMatrix0to1[2][8] = 0.320980925505209;
   fWeightMatrix0to1[3][8] = -1.07595447259267;
   fWeightMatrix0to1[4][8] = 0.791110704501718;
   fWeightMatrix0to1[5][8] = -2.091634214127;
   fWeightMatrix0to1[6][8] = 2.61522302893827;
   fWeightMatrix0to1[7][8] = 0.230099484742945;
   fWeightMatrix0to1[8][8] = 1.95230829668333;
   fWeightMatrix0to1[9][8] = -3.09588534971783;
   fWeightMatrix0to1[10][8] = 0.697134228227983;
   fWeightMatrix0to1[11][8] = 1.98765772458258;
   fWeightMatrix0to1[12][8] = 1.78929505427931;
   fWeightMatrix0to1[13][8] = 0.90741229546141;
   fWeightMatrix0to1[14][8] = 0.146019920597544;
   fWeightMatrix0to1[15][8] = -0.800849113475121;
   fWeightMatrix0to1[0][9] = -0.701425173775936;
   fWeightMatrix0to1[1][9] = 1.22601155848151;
   fWeightMatrix0to1[2][9] = 0.979801986539073;
   fWeightMatrix0to1[3][9] = -0.533207699644908;
   fWeightMatrix0to1[4][9] = -0.151912407822845;
   fWeightMatrix0to1[5][9] = -0.809013340955225;
   fWeightMatrix0to1[6][9] = -0.983025465372245;
   fWeightMatrix0to1[7][9] = 0.148244542798975;
   fWeightMatrix0to1[8][9] = 1.96013754617016;
   fWeightMatrix0to1[9][9] = 0.521113291897497;
   fWeightMatrix0to1[10][9] = 0.293784627184848;
   fWeightMatrix0to1[11][9] = 0.0247857059231376;
   fWeightMatrix0to1[12][9] = 0.368020413338332;
   fWeightMatrix0to1[13][9] = -0.628309972025569;
   fWeightMatrix0to1[14][9] = 0.0364452679107984;
   fWeightMatrix0to1[15][9] = 0.221966915136983;
   fWeightMatrix0to1[0][10] = 1.29027676100442;
   fWeightMatrix0to1[1][10] = 0.48561353769095;
   fWeightMatrix0to1[2][10] = 0.169215325735128;
   fWeightMatrix0to1[3][10] = 0.181979307020262;
   fWeightMatrix0to1[4][10] = 1.56155842298019;
   fWeightMatrix0to1[5][10] = -0.18304645663298;
   fWeightMatrix0to1[6][10] = -0.126086181640555;
   fWeightMatrix0to1[7][10] = 0.383587999351797;
   fWeightMatrix0to1[8][10] = -0.438204074157924;
   fWeightMatrix0to1[9][10] = -0.207064293488629;
   fWeightMatrix0to1[10][10] = 0.665116613638966;
   fWeightMatrix0to1[11][10] = 0.088863825867884;
   fWeightMatrix0to1[12][10] = 1.3446804579526;
   fWeightMatrix0to1[13][10] = 3.09229382864613;
   fWeightMatrix0to1[14][10] = -0.808977363945986;
   fWeightMatrix0to1[15][10] = -3.00722341425672;
   fWeightMatrix0to1[0][11] = -0.144122590702542;
   fWeightMatrix0to1[1][11] = -0.385925948620831;
   fWeightMatrix0to1[2][11] = 3.70453251926366;
   fWeightMatrix0to1[3][11] = -1.95450974360146;
   fWeightMatrix0to1[4][11] = -4.8309906554196;
   fWeightMatrix0to1[5][11] = 0.051452894073614;
   fWeightMatrix0to1[6][11] = 6.86959524033196;
   fWeightMatrix0to1[7][11] = -1.35524294476321;
   fWeightMatrix0to1[8][11] = 0.803584091002475;
   fWeightMatrix0to1[9][11] = -1.53613460650558;
   fWeightMatrix0to1[10][11] = 0.162789595214487;
   fWeightMatrix0to1[11][11] = 2.67151450449704;
   fWeightMatrix0to1[12][11] = -0.420344762806178;
   fWeightMatrix0to1[13][11] = 1.13433107927173;
   fWeightMatrix0to1[14][11] = 2.70040966988935;
   fWeightMatrix0to1[15][11] = 0.827069102375534;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 1.77862397486952;
   fWeightMatrix1to2[1][0] = 0.986733459538459;
   fWeightMatrix1to2[2][0] = 0.0460766446782839;
   fWeightMatrix1to2[3][0] = -0.399463338999257;
   fWeightMatrix1to2[4][0] = -2.1484243738688;
   fWeightMatrix1to2[5][0] = 0.548502978594107;
   fWeightMatrix1to2[6][0] = 0.468181454396747;
   fWeightMatrix1to2[7][0] = -1.53601421650033;
   fWeightMatrix1to2[8][0] = -0.317166356994052;
   fWeightMatrix1to2[9][0] = 1.75051864553813;
   fWeightMatrix1to2[10][0] = 0.0441808726574882;
   fWeightMatrix1to2[11][0] = -2.11021033388294;
   fWeightMatrix1to2[12][0] = 1.69421616858512;
   fWeightMatrix1to2[13][0] = 0.871131095056668;
   fWeightMatrix1to2[14][0] = 1.63358793652256;
   fWeightMatrix1to2[15][0] = -0.191093366720433;
   fWeightMatrix1to2[0][1] = 1.52393153022584;
   fWeightMatrix1to2[1][1] = 0.928274389201041;
   fWeightMatrix1to2[2][1] = 0.572905161651767;
   fWeightMatrix1to2[3][1] = -0.0149094267820567;
   fWeightMatrix1to2[4][1] = -1.97908132192698;
   fWeightMatrix1to2[5][1] = -0.94958357274769;
   fWeightMatrix1to2[6][1] = 1.71774266969212;
   fWeightMatrix1to2[7][1] = 1.29873340078828;
   fWeightMatrix1to2[8][1] = 0.813820589056744;
   fWeightMatrix1to2[9][1] = 0.0757716588013143;
   fWeightMatrix1to2[10][1] = 2.0149385442313;
   fWeightMatrix1to2[11][1] = -1.54527604430338;
   fWeightMatrix1to2[12][1] = -1.3227350060548;
   fWeightMatrix1to2[13][1] = -0.10459921360983;
   fWeightMatrix1to2[14][1] = -1.21710258859705;
   fWeightMatrix1to2[15][1] = 1.09006713999063;
   fWeightMatrix1to2[0][2] = 1.99980302946401;
   fWeightMatrix1to2[1][2] = -1.42538033291966;
   fWeightMatrix1to2[2][2] = 0.850046541522883;
   fWeightMatrix1to2[3][2] = 0.0323586020348236;
   fWeightMatrix1to2[4][2] = -2.64748632995888;
   fWeightMatrix1to2[5][2] = -0.959497275186305;
   fWeightMatrix1to2[6][2] = 1.02075767532488;
   fWeightMatrix1to2[7][2] = -1.24586734670575;
   fWeightMatrix1to2[8][2] = 1.17406671598674;
   fWeightMatrix1to2[9][2] = -2.27037296416673;
   fWeightMatrix1to2[10][2] = 1.91448781710337;
   fWeightMatrix1to2[11][2] = -3.67421698875416;
   fWeightMatrix1to2[12][2] = 1.15749306837696;
   fWeightMatrix1to2[13][2] = 0.118632365828225;
   fWeightMatrix1to2[14][2] = -0.109311988346167;
   fWeightMatrix1to2[15][2] = -2.47520557696346;
   fWeightMatrix1to2[0][3] = -2.07284512553956;
   fWeightMatrix1to2[1][3] = -0.697555419488299;
   fWeightMatrix1to2[2][3] = -1.86229645617531;
   fWeightMatrix1to2[3][3] = -1.46350501108586;
   fWeightMatrix1to2[4][3] = -1.8458202715055;
   fWeightMatrix1to2[5][3] = -0.109486711444569;
   fWeightMatrix1to2[6][3] = -1.01570790812228;
   fWeightMatrix1to2[7][3] = -1.43723518640613;
   fWeightMatrix1to2[8][3] = 1.38211742951169;
   fWeightMatrix1to2[9][3] = -0.900253078322326;
   fWeightMatrix1to2[10][3] = 0.135379523850781;
   fWeightMatrix1to2[11][3] = -0.907878706159181;
   fWeightMatrix1to2[12][3] = 0.25295615869263;
   fWeightMatrix1to2[13][3] = 1.85692673910315;
   fWeightMatrix1to2[14][3] = 1.17623420793398;
   fWeightMatrix1to2[15][3] = -0.782859126466586;
   fWeightMatrix1to2[0][4] = -2.36742757220629;
   fWeightMatrix1to2[1][4] = -1.54367619212846;
   fWeightMatrix1to2[2][4] = -0.730886201929856;
   fWeightMatrix1to2[3][4] = -1.18842441795154;
   fWeightMatrix1to2[4][4] = 0.58213584355111;
   fWeightMatrix1to2[5][4] = -0.0532846736133828;
   fWeightMatrix1to2[6][4] = 1.87724071915887;
   fWeightMatrix1to2[7][4] = -0.474476738267022;
   fWeightMatrix1to2[8][4] = 1.3366939458397;
   fWeightMatrix1to2[9][4] = 1.07133957103194;
   fWeightMatrix1to2[10][4] = -2.03970884620031;
   fWeightMatrix1to2[11][4] = 3.69442981339891;
   fWeightMatrix1to2[12][4] = 1.2645046606773;
   fWeightMatrix1to2[13][4] = -0.882289623862454;
   fWeightMatrix1to2[14][4] = -3.61619372039911;
   fWeightMatrix1to2[15][4] = 0.872848432749907;
   fWeightMatrix1to2[0][5] = 0.917301173754247;
   fWeightMatrix1to2[1][5] = -0.160507817805132;
   fWeightMatrix1to2[2][5] = -1.12778048157768;
   fWeightMatrix1to2[3][5] = 0.475238710460919;
   fWeightMatrix1to2[4][5] = 1.21593161446964;
   fWeightMatrix1to2[5][5] = 1.75840616074644;
   fWeightMatrix1to2[6][5] = 0.984723917745348;
   fWeightMatrix1to2[7][5] = -1.5751230104438;
   fWeightMatrix1to2[8][5] = 0.764735312589941;
   fWeightMatrix1to2[9][5] = -0.089281373219266;
   fWeightMatrix1to2[10][5] = -1.36147878205483;
   fWeightMatrix1to2[11][5] = 0.53518880073042;
   fWeightMatrix1to2[12][5] = -1.71328565897063;
   fWeightMatrix1to2[13][5] = -1.26811162803065;
   fWeightMatrix1to2[14][5] = -0.918442237268468;
   fWeightMatrix1to2[15][5] = 2.34904912389002;
   fWeightMatrix1to2[0][6] = -1.3090802316023;
   fWeightMatrix1to2[1][6] = 0.69362873236544;
   fWeightMatrix1to2[2][6] = -2.00841835367815;
   fWeightMatrix1to2[3][6] = 1.55587809776822;
   fWeightMatrix1to2[4][6] = -2.9535444485762;
   fWeightMatrix1to2[5][6] = 0.564976659787781;
   fWeightMatrix1to2[6][6] = 0.848702800594691;
   fWeightMatrix1to2[7][6] = -3.85745853892282;
   fWeightMatrix1to2[8][6] = 0.412767566651972;
   fWeightMatrix1to2[9][6] = 1.35735530181644;
   fWeightMatrix1to2[10][6] = -1.80525911077066;
   fWeightMatrix1to2[11][6] = -2.53787090009207;
   fWeightMatrix1to2[12][6] = -1.82863425691416;
   fWeightMatrix1to2[13][6] = -0.842839676116073;
   fWeightMatrix1to2[14][6] = 2.80421679713888;
   fWeightMatrix1to2[15][6] = -1.72311951629134;
   fWeightMatrix1to2[0][7] = 0.204365935127548;
   fWeightMatrix1to2[1][7] = -1.00889928349331;
   fWeightMatrix1to2[2][7] = -1.22566078791902;
   fWeightMatrix1to2[3][7] = -1.70296605719622;
   fWeightMatrix1to2[4][7] = -1.14570041175379;
   fWeightMatrix1to2[5][7] = -1.48896154951142;
   fWeightMatrix1to2[6][7] = 0.97479470291051;
   fWeightMatrix1to2[7][7] = -1.32044862756221;
   fWeightMatrix1to2[8][7] = -1.08824970948266;
   fWeightMatrix1to2[9][7] = 1.49730081438766;
   fWeightMatrix1to2[10][7] = 0.353630987850072;
   fWeightMatrix1to2[11][7] = -0.171400134748261;
   fWeightMatrix1to2[12][7] = 1.87087136311298;
   fWeightMatrix1to2[13][7] = -1.81482502311665;
   fWeightMatrix1to2[14][7] = 1.67761844593043;
   fWeightMatrix1to2[15][7] = 0.970420159778074;
   fWeightMatrix1to2[0][8] = -0.925633482384178;
   fWeightMatrix1to2[1][8] = -0.402772619630551;
   fWeightMatrix1to2[2][8] = -0.391861409092013;
   fWeightMatrix1to2[3][8] = -0.972173487440768;
   fWeightMatrix1to2[4][8] = -0.243176974921257;
   fWeightMatrix1to2[5][8] = 2.38674422542679;
   fWeightMatrix1to2[6][8] = 1.31417637756124;
   fWeightMatrix1to2[7][8] = 1.5231835767934;
   fWeightMatrix1to2[8][8] = -1.23043487931872;
   fWeightMatrix1to2[9][8] = 1.12203904580788;
   fWeightMatrix1to2[10][8] = -1.83279455101925;
   fWeightMatrix1to2[11][8] = 0.12189268891737;
   fWeightMatrix1to2[12][8] = -1.5516220334552;
   fWeightMatrix1to2[13][8] = -1.83136480823594;
   fWeightMatrix1to2[14][8] = 1.35622948714114;
   fWeightMatrix1to2[15][8] = 0.744868622127675;
   fWeightMatrix1to2[0][9] = 0.531377967587788;
   fWeightMatrix1to2[1][9] = 0.844032868216016;
   fWeightMatrix1to2[2][9] = 0.395103255116817;
   fWeightMatrix1to2[3][9] = -0.0179731140804854;
   fWeightMatrix1to2[4][9] = -0.903997384599593;
   fWeightMatrix1to2[5][9] = 0.475925171789396;
   fWeightMatrix1to2[6][9] = 1.94942295173552;
   fWeightMatrix1to2[7][9] = -1.17866442721801;
   fWeightMatrix1to2[8][9] = 0.325197435218499;
   fWeightMatrix1to2[9][9] = -0.925457302701104;
   fWeightMatrix1to2[10][9] = -0.561270068143758;
   fWeightMatrix1to2[11][9] = 0.10306761787755;
   fWeightMatrix1to2[12][9] = 0.667448854169256;
   fWeightMatrix1to2[13][9] = -1.0764733999612;
   fWeightMatrix1to2[14][9] = 0.526789523958045;
   fWeightMatrix1to2[15][9] = 3.21877036458125;
   fWeightMatrix1to2[0][10] = 0.212096298341865;
   fWeightMatrix1to2[1][10] = -0.810667825821806;
   fWeightMatrix1to2[2][10] = -0.661460831698741;
   fWeightMatrix1to2[3][10] = -1.04041838839573;
   fWeightMatrix1to2[4][10] = -1.52788127482199;
   fWeightMatrix1to2[5][10] = 0.762975231694852;
   fWeightMatrix1to2[6][10] = -0.520860775119441;
   fWeightMatrix1to2[7][10] = -0.784223078686266;
   fWeightMatrix1to2[8][10] = 2.07279047288546;
   fWeightMatrix1to2[9][10] = -1.79779270777033;
   fWeightMatrix1to2[10][10] = -1.1295698296055;
   fWeightMatrix1to2[11][10] = 0.529608783536103;
   fWeightMatrix1to2[12][10] = 1.10121079659194;
   fWeightMatrix1to2[13][10] = -1.2631197253947;
   fWeightMatrix1to2[14][10] = -2.34757933369008;
   fWeightMatrix1to2[15][10] = -0.567377085098467;
   fWeightMatrix1to2[0][11] = -0.835312590806547;
   fWeightMatrix1to2[1][11] = -3.27997532626042;
   fWeightMatrix1to2[2][11] = 0.601979801450365;
   fWeightMatrix1to2[3][11] = -1.45643976340174;
   fWeightMatrix1to2[4][11] = -0.686009885916135;
   fWeightMatrix1to2[5][11] = 0.984766682794929;
   fWeightMatrix1to2[6][11] = 0.554532906258616;
   fWeightMatrix1to2[7][11] = 0.609465538383978;
   fWeightMatrix1to2[8][11] = 3.37599457724207;
   fWeightMatrix1to2[9][11] = 2.83228330847196;
   fWeightMatrix1to2[10][11] = 1.84406707269016;
   fWeightMatrix1to2[11][11] = 2.93841595142492;
   fWeightMatrix1to2[12][11] = -0.616314565354721;
   fWeightMatrix1to2[13][11] = -0.602900703706712;
   fWeightMatrix1to2[14][11] = -1.27052379660311;
   fWeightMatrix1to2[15][11] = 1.79062885832629;
   fWeightMatrix1to2[0][12] = 0.663501709703644;
   fWeightMatrix1to2[1][12] = -0.272847398357003;
   fWeightMatrix1to2[2][12] = -0.385832899619468;
   fWeightMatrix1to2[3][12] = 0.577336189422006;
   fWeightMatrix1to2[4][12] = 1.03050433060515;
   fWeightMatrix1to2[5][12] = -1.57534417700098;
   fWeightMatrix1to2[6][12] = 1.7262844811386;
   fWeightMatrix1to2[7][12] = 1.01027472379277;
   fWeightMatrix1to2[8][12] = 0.405310021838253;
   fWeightMatrix1to2[9][12] = 0.81318574456365;
   fWeightMatrix1to2[10][12] = -1.14178819581877;
   fWeightMatrix1to2[11][12] = 1.94518150465453;
   fWeightMatrix1to2[12][12] = 0.588879928722938;
   fWeightMatrix1to2[13][12] = 1.0237577118219;
   fWeightMatrix1to2[14][12] = 2.42705206452189;
   fWeightMatrix1to2[15][12] = -1.4364298391545;
   fWeightMatrix1to2[0][13] = 2.61528297688487;
   fWeightMatrix1to2[1][13] = 1.24039017402768;
   fWeightMatrix1to2[2][13] = 0.593125034313848;
   fWeightMatrix1to2[3][13] = -2.27642882837861;
   fWeightMatrix1to2[4][13] = 1.13626655170663;
   fWeightMatrix1to2[5][13] = -2.06525172028971;
   fWeightMatrix1to2[6][13] = 0.561270267945376;
   fWeightMatrix1to2[7][13] = 1.9516411283166;
   fWeightMatrix1to2[8][13] = -1.05445979918006;
   fWeightMatrix1to2[9][13] = -1.83006152353981;
   fWeightMatrix1to2[10][13] = -0.0506686043916969;
   fWeightMatrix1to2[11][13] = -1.75590864098632;
   fWeightMatrix1to2[12][13] = 0.781170498134378;
   fWeightMatrix1to2[13][13] = -1.88851953813464;
   fWeightMatrix1to2[14][13] = 0.503240613023781;
   fWeightMatrix1to2[15][13] = -0.0691958627825988;
   fWeightMatrix1to2[0][14] = 2.77532288016225;
   fWeightMatrix1to2[1][14] = 1.7680978631738;
   fWeightMatrix1to2[2][14] = 2.99211800978016;
   fWeightMatrix1to2[3][14] = -0.535556220204826;
   fWeightMatrix1to2[4][14] = -0.859405605393088;
   fWeightMatrix1to2[5][14] = 0.392588269858348;
   fWeightMatrix1to2[6][14] = 1.85118807039309;
   fWeightMatrix1to2[7][14] = -0.783850885113909;
   fWeightMatrix1to2[8][14] = -2.40951703313683;
   fWeightMatrix1to2[9][14] = -0.851171490180684;
   fWeightMatrix1to2[10][14] = -1.48421415213948;
   fWeightMatrix1to2[11][14] = -3.82727762560962;
   fWeightMatrix1to2[12][14] = -1.29000730474614;
   fWeightMatrix1to2[13][14] = 0.783124267728587;
   fWeightMatrix1to2[14][14] = -0.099920959434003;
   fWeightMatrix1to2[15][14] = -1.6406379934067;
   fWeightMatrix1to2[0][15] = -1.70697235269865;
   fWeightMatrix1to2[1][15] = -0.486456295408534;
   fWeightMatrix1to2[2][15] = 3.0912823758605;
   fWeightMatrix1to2[3][15] = 2.24823675033404;
   fWeightMatrix1to2[4][15] = 1.46842687508917;
   fWeightMatrix1to2[5][15] = -0.301348108591498;
   fWeightMatrix1to2[6][15] = -1.94478957708965;
   fWeightMatrix1to2[7][15] = 0.144916460760819;
   fWeightMatrix1to2[8][15] = -2.16393718888938;
   fWeightMatrix1to2[9][15] = -2.24394096868493;
   fWeightMatrix1to2[10][15] = -0.58776132098602;
   fWeightMatrix1to2[11][15] = -0.883747622481245;
   fWeightMatrix1to2[12][15] = -1.22082066430227;
   fWeightMatrix1to2[13][15] = 1.60361245158725;
   fWeightMatrix1to2[14][15] = 0.732506444725911;
   fWeightMatrix1to2[15][15] = 1.67342027117466;
   fWeightMatrix1to2[0][16] = -0.813271204247756;
   fWeightMatrix1to2[1][16] = -1.84268290341503;
   fWeightMatrix1to2[2][16] = 1.88582891157046;
   fWeightMatrix1to2[3][16] = -0.187981841105707;
   fWeightMatrix1to2[4][16] = -0.137327073961066;
   fWeightMatrix1to2[5][16] = 1.45206606668919;
   fWeightMatrix1to2[6][16] = 1.50972509260099;
   fWeightMatrix1to2[7][16] = -0.909428536826231;
   fWeightMatrix1to2[8][16] = 2.45509573926749;
   fWeightMatrix1to2[9][16] = -2.30778711447213;
   fWeightMatrix1to2[10][16] = 1.61676521379822;
   fWeightMatrix1to2[11][16] = 2.79424042822172;
   fWeightMatrix1to2[12][16] = 0.293764006842231;
   fWeightMatrix1to2[13][16] = -0.165628712046041;
   fWeightMatrix1to2[14][16] = -0.477920709103938;
   fWeightMatrix1to2[15][16] = -0.87928265890105;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = 1.48711119232005;
   fWeightMatrix2to3[0][1] = 1.81763940665607;
   fWeightMatrix2to3[0][2] = -2.54463730007162;
   fWeightMatrix2to3[0][3] = -1.44000695485114;
   fWeightMatrix2to3[0][4] = -1.94063576588231;
   fWeightMatrix2to3[0][5] = 1.60431777266369;
   fWeightMatrix2to3[0][6] = 0.186898056463493;
   fWeightMatrix2to3[0][7] = -2.50952696373148;
   fWeightMatrix2to3[0][8] = -3.49831363519894;
   fWeightMatrix2to3[0][9] = 2.98102074623695;
   fWeightMatrix2to3[0][10] = 0.621454622738301;
   fWeightMatrix2to3[0][11] = -3.11816366907544;
   fWeightMatrix2to3[0][12] = -1.41770126691606;
   fWeightMatrix2to3[0][13] = -1.11895813680008;
   fWeightMatrix2to3[0][14] = 2.81097696416958;
   fWeightMatrix2to3[0][15] = 3.4936749469872;
   fWeightMatrix2to3[0][16] = -0.972270330447068;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)11) {
      std::cout << "Input vector needs to be of size " << 11 << std::endl;
      return 0;
   }

   std::array<double, 17> fWeights1 {{}};
   std::array<double, 17> fWeights2 {{}};
   std::array<double, 1> fWeights3 {{}};
   fWeights1.back() = 1.;
   fWeights2.back() = 1.;

   // layer 0 to 1
   for (int o=0; o<16; o++) {
      std::array<double, 12> buffer; // no need to initialise
      for (int i = 0; i<12 - 1; i++) {
         buffer[i] = fWeightMatrix0to1[o][i] * inputValues[i];
      } // loop over i
      buffer.back() = fWeightMatrix0to1[o][11];
      for (int i=0; i<12; i++) {
         fWeights1[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<16; o++) {
      fWeights1[o] = ActivationFnc(fWeights1[o]);
   } // loop over o
   // layer 1 to 2
   for (int o=0; o<16; o++) {
      std::array<double, 17> buffer; // no need to initialise
      for (int i=0; i<17; i++) {
         buffer[i] = fWeightMatrix1to2[o][i] * fWeights1[i];
      } // loop over i
      for (int i=0; i<17; i++) {
         fWeights2[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<16; o++) {
      fWeights2[o] = ActivationFnc(fWeights2[o]);
   } // loop over o
   // layer 2 to 3
   for (int o=0; o<1; o++) {
      std::array<double, 17> buffer; // no need to initialise
      for (int i=0; i<17; i++) {
         buffer[i] = fWeightMatrix2to3[o][i] * fWeights2[i];
      } // loop over i
      for (int i=0; i<17; i++) {
         fWeights3[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<1; o++) {
      fWeights3[o] = OutputActivationFnc(fWeights3[o]);
   } // loop over o

   return fWeights3[0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}

// Clean up
inline void ReadMLP::Clear()
{
}
inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         std::vector<double> iV(inputValues);
         Transform( iV, -1 );
         retval = GetMvaValue__( iV );
   }

   return retval;
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   double fMin_1[3][11];
   double fMax_1[3][11];
   // Normalization transformation, initialisation
   fMin_1[0][0] = 22.7864818573;
   fMax_1[0][0] = 7505.73046875;
   fScal_1[0][0] = 2.0/(fMax_1[0][0]-fMin_1[0][0]);
   fOff_1[0][0] = fMin_1[0][0]*fScal_1[0][0]+1.;
   fMin_1[1][0] = 23.5563087463;
   fMax_1[1][0] = 7838.75537109;
   fScal_1[1][0] = 2.0/(fMax_1[1][0]-fMin_1[1][0]);
   fOff_1[1][0] = fMin_1[1][0]*fScal_1[1][0]+1.;
   fMin_1[2][0] = 22.7864818573;
   fMax_1[2][0] = 7838.75537109;
   fScal_1[2][0] = 2.0/(fMax_1[2][0]-fMin_1[2][0]);
   fOff_1[2][0] = fMin_1[2][0]*fScal_1[2][0]+1.;
   fMin_1[0][1] = 0.000150358115206;
   fMax_1[0][1] = 8.68471050262;
   fScal_1[0][1] = 2.0/(fMax_1[0][1]-fMin_1[0][1]);
   fOff_1[0][1] = fMin_1[0][1]*fScal_1[0][1]+1.;
   fMin_1[1][1] = 2.2119609639e-05;
   fMax_1[1][1] = 8.68384933472;
   fScal_1[1][1] = 2.0/(fMax_1[1][1]-fMin_1[1][1]);
   fOff_1[1][1] = fMin_1[1][1]*fScal_1[1][1]+1.;
   fMin_1[2][1] = 2.2119609639e-05;
   fMax_1[2][1] = 8.68471050262;
   fScal_1[2][1] = 2.0/(fMax_1[2][1]-fMin_1[2][1]);
   fOff_1[2][1] = fMin_1[2][1]*fScal_1[2][1]+1.;
   fMin_1[0][2] = 126.97845459;
   fMax_1[0][2] = 2277.4987793;
   fScal_1[0][2] = 2.0/(fMax_1[0][2]-fMin_1[0][2]);
   fOff_1[0][2] = fMin_1[0][2]*fScal_1[0][2]+1.;
   fMin_1[1][2] = 125.825294495;
   fMax_1[1][2] = 1926.56140137;
   fScal_1[1][2] = 2.0/(fMax_1[1][2]-fMin_1[1][2]);
   fOff_1[1][2] = fMin_1[1][2]*fScal_1[1][2]+1.;
   fMin_1[2][2] = 125.825294495;
   fMax_1[2][2] = 2277.4987793;
   fScal_1[2][2] = 2.0/(fMax_1[2][2]-fMin_1[2][2]);
   fOff_1[2][2] = fMin_1[2][2]*fScal_1[2][2]+1.;
   fMin_1[0][3] = 4.91857872476e-06;
   fMax_1[0][3] = 0.405025333166;
   fScal_1[0][3] = 2.0/(fMax_1[0][3]-fMin_1[0][3]);
   fOff_1[0][3] = fMin_1[0][3]*fScal_1[0][3]+1.;
   fMin_1[1][3] = 5.9500340285e-05;
   fMax_1[1][3] = 0.47649076581;
   fScal_1[1][3] = 2.0/(fMax_1[1][3]-fMin_1[1][3]);
   fOff_1[1][3] = fMin_1[1][3]*fScal_1[1][3]+1.;
   fMin_1[2][3] = 4.91857872476e-06;
   fMax_1[2][3] = 0.47649076581;
   fScal_1[2][3] = 2.0/(fMax_1[2][3]-fMin_1[2][3]);
   fOff_1[2][3] = fMin_1[2][3]*fScal_1[2][3]+1.;
   fMin_1[0][4] = -4.50663423538;
   fMax_1[0][4] = 4.51134681702;
   fScal_1[0][4] = 2.0/(fMax_1[0][4]-fMin_1[0][4]);
   fOff_1[0][4] = fMin_1[0][4]*fScal_1[0][4]+1.;
   fMin_1[1][4] = -4.5036110878;
   fMax_1[1][4] = 4.50834369659;
   fScal_1[1][4] = 2.0/(fMax_1[1][4]-fMin_1[1][4]);
   fOff_1[1][4] = fMin_1[1][4]*fScal_1[1][4]+1.;
   fMin_1[2][4] = -4.50663423538;
   fMax_1[2][4] = 4.51134681702;
   fScal_1[2][4] = 2.0/(fMax_1[2][4]-fMin_1[2][4]);
   fOff_1[2][4] = fMin_1[2][4]*fScal_1[2][4]+1.;
   fMin_1[0][5] = 50.1059684753;
   fMax_1[0][5] = 1964.14489746;
   fScal_1[0][5] = 2.0/(fMax_1[0][5]-fMin_1[0][5]);
   fOff_1[0][5] = fMin_1[0][5]*fScal_1[0][5]+1.;
   fMin_1[1][5] = 50.0584754944;
   fMax_1[1][5] = 2753.2824707;
   fScal_1[1][5] = 2.0/(fMax_1[1][5]-fMin_1[1][5]);
   fOff_1[1][5] = fMin_1[1][5]*fScal_1[1][5]+1.;
   fMin_1[2][5] = 50.0584754944;
   fMax_1[2][5] = 2753.2824707;
   fScal_1[2][5] = 2.0/(fMax_1[2][5]-fMin_1[2][5]);
   fOff_1[2][5] = fMin_1[2][5]*fScal_1[2][5]+1.;
   fMin_1[0][6] = -2.4010925293;
   fMax_1[0][6] = 2.39041256905;
   fScal_1[0][6] = 2.0/(fMax_1[0][6]-fMin_1[0][6]);
   fOff_1[0][6] = fMin_1[0][6]*fScal_1[0][6]+1.;
   fMin_1[1][6] = -2.38632035255;
   fMax_1[1][6] = 2.38307738304;
   fScal_1[1][6] = 2.0/(fMax_1[1][6]-fMin_1[1][6]);
   fOff_1[1][6] = fMin_1[1][6]*fScal_1[1][6]+1.;
   fMin_1[2][6] = -2.4010925293;
   fMax_1[2][6] = 2.39041256905;
   fScal_1[2][6] = 2.0/(fMax_1[2][6]-fMin_1[2][6]);
   fOff_1[2][6] = fMin_1[2][6]*fScal_1[2][6]+1.;
   fMin_1[0][7] = 0.0488347522914;
   fMax_1[0][7] = 0.99988257885;
   fScal_1[0][7] = 2.0/(fMax_1[0][7]-fMin_1[0][7]);
   fOff_1[0][7] = fMin_1[0][7]*fScal_1[0][7]+1.;
   fMin_1[1][7] = 0.0229892414063;
   fMax_1[1][7] = 0.999983787537;
   fScal_1[1][7] = 2.0/(fMax_1[1][7]-fMin_1[1][7]);
   fOff_1[1][7] = fMin_1[1][7]*fScal_1[1][7]+1.;
   fMin_1[2][7] = 0.0229892414063;
   fMax_1[2][7] = 0.999983787537;
   fScal_1[2][7] = 2.0/(fMax_1[2][7]-fMin_1[2][7]);
   fOff_1[2][7] = fMin_1[2][7]*fScal_1[2][7]+1.;
   fMin_1[0][8] = 2;
   fMax_1[0][8] = 8;
   fScal_1[0][8] = 2.0/(fMax_1[0][8]-fMin_1[0][8]);
   fOff_1[0][8] = fMin_1[0][8]*fScal_1[0][8]+1.;
   fMin_1[1][8] = 2;
   fMax_1[1][8] = 9;
   fScal_1[1][8] = 2.0/(fMax_1[1][8]-fMin_1[1][8]);
   fOff_1[1][8] = fMin_1[1][8]*fScal_1[1][8]+1.;
   fMin_1[2][8] = 2;
   fMax_1[2][8] = 9;
   fScal_1[2][8] = 2.0/(fMax_1[2][8]-fMin_1[2][8]);
   fOff_1[2][8] = fMin_1[2][8]*fScal_1[2][8]+1.;
   fMin_1[0][9] = 1.5914440155e-05;
   fMax_1[0][9] = 1;
   fScal_1[0][9] = 2.0/(fMax_1[0][9]-fMin_1[0][9]);
   fOff_1[0][9] = fMin_1[0][9]*fScal_1[0][9]+1.;
   fMin_1[1][9] = 1.93119049072e-05;
   fMax_1[1][9] = 1;
   fScal_1[1][9] = 2.0/(fMax_1[1][9]-fMin_1[1][9]);
   fOff_1[1][9] = fMin_1[1][9]*fScal_1[1][9]+1.;
   fMin_1[2][9] = 1.5914440155e-05;
   fMax_1[2][9] = 1;
   fScal_1[2][9] = 2.0/(fMax_1[2][9]-fMin_1[2][9]);
   fOff_1[2][9] = fMin_1[2][9]*fScal_1[2][9]+1.;
   fMin_1[0][10] = 3.26525550918e-05;
   fMax_1[0][10] = 6.50682735443;
   fScal_1[0][10] = 2.0/(fMax_1[0][10]-fMin_1[0][10]);
   fOff_1[0][10] = fMin_1[0][10]*fScal_1[0][10]+1.;
   fMin_1[1][10] = 1.18112052405e-06;
   fMax_1[1][10] = 6.68952894211;
   fScal_1[1][10] = 2.0/(fMax_1[1][10]-fMin_1[1][10]);
   fOff_1[1][10] = fMin_1[1][10]*fScal_1[1][10]+1.;
   fMin_1[2][10] = 1.18112052405e-06;
   fMax_1[2][10] = 6.68952894211;
   fScal_1[2][10] = 2.0/(fMax_1[2][10]-fMin_1[2][10]);
   fOff_1[2][10] = fMin_1[2][10]*fScal_1[2][10]+1.;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) {
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   }
   if ( indicesPut.empty() ) {
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   }

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fOff_1[cls][ivar];
      double scale  = fScal_1[cls][ivar];
      iv[indicesPut.at(ivar)] = scale*dv[ivar]-offset;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
