// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.22/06       [398854]
Creator        : konstantin
Date           : Thu Apr  1 19:48:11 2021
Host           : Linux mach 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/konstantin/Projects/CERN/TMVA_MLP
Training events: 170672
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "400" [Number of training cycles]
HiddenLayers: "N,N" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
LearningRate: "1.000000e-02" [ANN learning rate parameter]
TestRate: "5" [Test for overtraining performed at each #th epochs]
BPMode: "batch" [Back-propagation learning mode: sequential or batch]
BatchSize: "3" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "2.500000e-03" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "5" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
mJJ                           mJJ                           mJJ                           mJJ                                                             'F'    [22.7864818573,7838.75537109]
deltaYJJ                      deltaYJJ                      deltaYJJ                      deltaYJJ                                                        'F'    [2.2119609639e-05,8.68471050262]
metPt                         metPt                         metPt                         metPt                                                           'F'    [125.825294495,2277.4987793]
ptBalance                     ptBalance                     ptBalance                     ptBalance                                                       'F'    [4.91857872476e-06,0.47649076581]
subleadJetEta                 subleadJetEta                 subleadJetEta                 subleadJetEta                                                   'F'    [-4.50663423538,4.51134681702]
leadJetPt                     leadJetPt                     leadJetPt                     leadJetPt                                                       'F'    [50.0584754944,2753.2824707]
photonEta                     photonEta                     photonEta                     photonEta                                                       'F'    [-2.4010925293,2.39041256905]
ptBalanceRed                  ptBalanceRed                  ptBalanceRed                  ptBalanceRed                                                    'F'    [0.0229892414063,0.999983787537]
nJets                         nJets                         nJets                         nJets                                                           'F'    [2,9]
sinDeltaPhiJJOver2            sinDeltaPhiJJOver2            sinDeltaPhiJJOver2            sinDeltaPhiJJOver2                                              'F'    [1.5914440155e-05,1]
deltaYJPh                     deltaYJPh                     deltaYJPh                     deltaYJPh                                                       'F'    [1.18112052405e-06,6.68952894211]
NSpec 1
weightModified                weightModified                weightModified                F                                                               'F'    [-0.191263645887,1.09073340893]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 11 )
   {
      // the training input variables
      const char* inputVars[] = { "mJJ", "deltaYJJ", "metPt", "ptBalance", "subleadJetEta", "leadJetPt", "photonEta", "ptBalanceRed", "nJets", "sinDeltaPhiJJOver2", "deltaYJPh" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fOff_1[3][11];
   double fScal_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   double fWeightMatrix0to1[12][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][12];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][12];   // weight matrix from layer 2 to 3

};

inline void ReadMLP::Initialize()
{
   // build network structure
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -1.2965406013938;
   fWeightMatrix0to1[1][0] = 1.89270251355278;
   fWeightMatrix0to1[2][0] = 0.854705199063094;
   fWeightMatrix0to1[3][0] = 5.10645647576012;
   fWeightMatrix0to1[4][0] = -2.92417824674515;
   fWeightMatrix0to1[5][0] = -1.83480012522407;
   fWeightMatrix0to1[6][0] = 1.16392875051208;
   fWeightMatrix0to1[7][0] = 1.38785544756694;
   fWeightMatrix0to1[8][0] = 1.97530905900026;
   fWeightMatrix0to1[9][0] = -3.87819848774753;
   fWeightMatrix0to1[10][0] = -4.93482865429399;
   fWeightMatrix0to1[0][1] = 0.1544849135122;
   fWeightMatrix0to1[1][1] = -0.0654336537042388;
   fWeightMatrix0to1[2][1] = -0.436361723330008;
   fWeightMatrix0to1[3][1] = -0.90665285055881;
   fWeightMatrix0to1[4][1] = -0.7727465251965;
   fWeightMatrix0to1[5][1] = 1.83079122228251;
   fWeightMatrix0to1[6][1] = 2.00980450640056;
   fWeightMatrix0to1[7][1] = -0.845918367571127;
   fWeightMatrix0to1[8][1] = 3.77338765463967;
   fWeightMatrix0to1[9][1] = -3.45204478114486;
   fWeightMatrix0to1[10][1] = -1.81765347153315;
   fWeightMatrix0to1[0][2] = 3.70268362224398;
   fWeightMatrix0to1[1][2] = -0.575479588367386;
   fWeightMatrix0to1[2][2] = -1.34915955893018;
   fWeightMatrix0to1[3][2] = 1.48097132253253;
   fWeightMatrix0to1[4][2] = 0.494255253615251;
   fWeightMatrix0to1[5][2] = 0.0175305904706592;
   fWeightMatrix0to1[6][2] = -1.44979180353516;
   fWeightMatrix0to1[7][2] = -0.352336770651834;
   fWeightMatrix0to1[8][2] = 0.0671671711030807;
   fWeightMatrix0to1[9][2] = 1.39999806811836;
   fWeightMatrix0to1[10][2] = -0.226374720352282;
   fWeightMatrix0to1[0][3] = 0.30676196776547;
   fWeightMatrix0to1[1][3] = -2.35293348640846;
   fWeightMatrix0to1[2][3] = -0.859661373056188;
   fWeightMatrix0to1[3][3] = -3.68169859346341;
   fWeightMatrix0to1[4][3] = 1.57480930536267;
   fWeightMatrix0to1[5][3] = 0.535388433668056;
   fWeightMatrix0to1[6][3] = -2.65097416566113;
   fWeightMatrix0to1[7][3] = 1.01302689041133;
   fWeightMatrix0to1[8][3] = -0.569922307065007;
   fWeightMatrix0to1[9][3] = 0.203938835336251;
   fWeightMatrix0to1[10][3] = 0.733932737372871;
   fWeightMatrix0to1[0][4] = -0.523436326977238;
   fWeightMatrix0to1[1][4] = -0.117904382677395;
   fWeightMatrix0to1[2][4] = 0.689901551666425;
   fWeightMatrix0to1[3][4] = 0.17768829489532;
   fWeightMatrix0to1[4][4] = 0.223409439146881;
   fWeightMatrix0to1[5][4] = 3.18911267411961;
   fWeightMatrix0to1[6][4] = 0.0523222124601537;
   fWeightMatrix0to1[7][4] = 0.839096329677005;
   fWeightMatrix0to1[8][4] = -5.21002107183528;
   fWeightMatrix0to1[9][4] = -0.415040535593627;
   fWeightMatrix0to1[10][4] = -2.10360559333139;
   fWeightMatrix0to1[0][5] = -2.20076001915511;
   fWeightMatrix0to1[1][5] = -0.872419111966564;
   fWeightMatrix0to1[2][5] = -1.817706965142;
   fWeightMatrix0to1[3][5] = 2.65145053690619;
   fWeightMatrix0to1[4][5] = 0.912745681184699;
   fWeightMatrix0to1[5][5] = -1.96753991209313;
   fWeightMatrix0to1[6][5] = 1.6512164259841;
   fWeightMatrix0to1[7][5] = -0.742172536968662;
   fWeightMatrix0to1[8][5] = -0.970720695673952;
   fWeightMatrix0to1[9][5] = 1.61297498744603;
   fWeightMatrix0to1[10][5] = -0.379071821346633;
   fWeightMatrix0to1[0][6] = 0.793655239925357;
   fWeightMatrix0to1[1][6] = 0.29885423401754;
   fWeightMatrix0to1[2][6] = 0.563186666070932;
   fWeightMatrix0to1[3][6] = -0.459613699747742;
   fWeightMatrix0to1[4][6] = -0.259816187903044;
   fWeightMatrix0to1[5][6] = -1.39217986313447;
   fWeightMatrix0to1[6][6] = 0.419292924408325;
   fWeightMatrix0to1[7][6] = 2.3168944644249;
   fWeightMatrix0to1[8][6] = 2.53670243468628;
   fWeightMatrix0to1[9][6] = 0.638280293048805;
   fWeightMatrix0to1[10][6] = 0.196643588920279;
   fWeightMatrix0to1[0][7] = -0.507191997669012;
   fWeightMatrix0to1[1][7] = 1.28665456413646;
   fWeightMatrix0to1[2][7] = 0.352114038628711;
   fWeightMatrix0to1[3][7] = -0.637409027209178;
   fWeightMatrix0to1[4][7] = -0.00667097583341639;
   fWeightMatrix0to1[5][7] = 0.00715558231366664;
   fWeightMatrix0to1[6][7] = -0.0453151685794443;
   fWeightMatrix0to1[7][7] = 0.151663902302605;
   fWeightMatrix0to1[8][7] = 0.155849626547917;
   fWeightMatrix0to1[9][7] = -0.461773244289908;
   fWeightMatrix0to1[10][7] = -0.217621326599241;
   fWeightMatrix0to1[0][8] = -3.24821096068537;
   fWeightMatrix0to1[1][8] = -3.13789418222145;
   fWeightMatrix0to1[2][8] = -0.683997473782966;
   fWeightMatrix0to1[3][8] = -0.332038053675188;
   fWeightMatrix0to1[4][8] = 1.18568435260822;
   fWeightMatrix0to1[5][8] = -2.87288506190201;
   fWeightMatrix0to1[6][8] = -3.34983453527343;
   fWeightMatrix0to1[7][8] = 1.62749262721667;
   fWeightMatrix0to1[8][8] = -0.322611741034811;
   fWeightMatrix0to1[9][8] = 0.126173618983492;
   fWeightMatrix0to1[10][8] = -0.577735129944307;
   fWeightMatrix0to1[0][9] = 0.146501604141438;
   fWeightMatrix0to1[1][9] = -1.73267426558572;
   fWeightMatrix0to1[2][9] = -1.34337364768742;
   fWeightMatrix0to1[3][9] = 0.0600934059360657;
   fWeightMatrix0to1[4][9] = 3.77585020894161;
   fWeightMatrix0to1[5][9] = 0.073363533160186;
   fWeightMatrix0to1[6][9] = 0.200103849888359;
   fWeightMatrix0to1[7][9] = -0.312718292690545;
   fWeightMatrix0to1[8][9] = 0.161871491784554;
   fWeightMatrix0to1[9][9] = 0.0293003643631551;
   fWeightMatrix0to1[10][9] = -0.143278087153585;
   fWeightMatrix0to1[0][10] = -2.02046041481279;
   fWeightMatrix0to1[1][10] = 0.432136075180399;
   fWeightMatrix0to1[2][10] = 0.118834885698784;
   fWeightMatrix0to1[3][10] = 0.415096474285833;
   fWeightMatrix0to1[4][10] = 0.343000889798672;
   fWeightMatrix0to1[5][10] = 0.885474993130293;
   fWeightMatrix0to1[6][10] = 0.16869793492415;
   fWeightMatrix0to1[7][10] = -1.59843311176411;
   fWeightMatrix0to1[8][10] = -0.55747720336209;
   fWeightMatrix0to1[9][10] = 2.17289106454413;
   fWeightMatrix0to1[10][10] = -0.126942375649676;
   fWeightMatrix0to1[0][11] = -1.42917058211212;
   fWeightMatrix0to1[1][11] = -1.57468708347738;
   fWeightMatrix0to1[2][11] = 2.33211487140829;
   fWeightMatrix0to1[3][11] = 4.34614512008921;
   fWeightMatrix0to1[4][11] = -2.45731290956862;
   fWeightMatrix0to1[5][11] = -1.36584916982006;
   fWeightMatrix0to1[6][11] = -2.49662234190829;
   fWeightMatrix0to1[7][11] = -0.91547406938425;
   fWeightMatrix0to1[8][11] = 3.37574647626131;
   fWeightMatrix0to1[9][11] = -2.08746424423575;
   fWeightMatrix0to1[10][11] = -7.00076415493329;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.0465047866684791;
   fWeightMatrix1to2[1][0] = -1.72767262980822;
   fWeightMatrix1to2[2][0] = 0.439336937539947;
   fWeightMatrix1to2[3][0] = 0.559470091918952;
   fWeightMatrix1to2[4][0] = 2.611954429106;
   fWeightMatrix1to2[5][0] = -1.89117695331614;
   fWeightMatrix1to2[6][0] = -0.349048122610695;
   fWeightMatrix1to2[7][0] = 1.33766456209082;
   fWeightMatrix1to2[8][0] = 2.07579054324842;
   fWeightMatrix1to2[9][0] = -0.083616064958524;
   fWeightMatrix1to2[10][0] = -1.79035637161185;
   fWeightMatrix1to2[0][1] = -0.0596981426555616;
   fWeightMatrix1to2[1][1] = -1.86064468958802;
   fWeightMatrix1to2[2][1] = 0.885099545077594;
   fWeightMatrix1to2[3][1] = 0.850097093244077;
   fWeightMatrix1to2[4][1] = -1.3733419568759;
   fWeightMatrix1to2[5][1] = -0.625444817007128;
   fWeightMatrix1to2[6][1] = -0.715703798429568;
   fWeightMatrix1to2[7][1] = -3.72403010320981;
   fWeightMatrix1to2[8][1] = -0.686590458494045;
   fWeightMatrix1to2[9][1] = 2.29018400778758;
   fWeightMatrix1to2[10][1] = -0.774798045435084;
   fWeightMatrix1to2[0][2] = -1.60499676237695;
   fWeightMatrix1to2[1][2] = 0.591885790167869;
   fWeightMatrix1to2[2][2] = 1.51288552109562;
   fWeightMatrix1to2[3][2] = -0.155186427320224;
   fWeightMatrix1to2[4][2] = -2.11435958852046;
   fWeightMatrix1to2[5][2] = -1.43417043967173;
   fWeightMatrix1to2[6][2] = 1.3612238447923;
   fWeightMatrix1to2[7][2] = -0.403796175918307;
   fWeightMatrix1to2[8][2] = 0.945199906411747;
   fWeightMatrix1to2[9][2] = 0.0995334850233108;
   fWeightMatrix1to2[10][2] = 0.819976752474911;
   fWeightMatrix1to2[0][3] = -1.29570658904205;
   fWeightMatrix1to2[1][3] = 0.806383814536192;
   fWeightMatrix1to2[2][3] = -0.473379701338391;
   fWeightMatrix1to2[3][3] = -0.344210858384012;
   fWeightMatrix1to2[4][3] = 0.577460336157989;
   fWeightMatrix1to2[5][3] = 1.72144620728128;
   fWeightMatrix1to2[6][3] = 0.853942128083801;
   fWeightMatrix1to2[7][3] = 2.62159261812191;
   fWeightMatrix1to2[8][3] = 3.9336048718454;
   fWeightMatrix1to2[9][3] = 2.86169261348347;
   fWeightMatrix1to2[10][3] = -4.41481945867828;
   fWeightMatrix1to2[0][4] = 0.053627879864536;
   fWeightMatrix1to2[1][4] = -0.0708984878532279;
   fWeightMatrix1to2[2][4] = 0.705059395606741;
   fWeightMatrix1to2[3][4] = -2.396593264498;
   fWeightMatrix1to2[4][4] = -0.891237664544143;
   fWeightMatrix1to2[5][4] = 1.27637860935597;
   fWeightMatrix1to2[6][4] = 1.98890083526845;
   fWeightMatrix1to2[7][4] = -0.653908812694811;
   fWeightMatrix1to2[8][4] = 0.305317173529146;
   fWeightMatrix1to2[9][4] = -1.16853447754993;
   fWeightMatrix1to2[10][4] = 0.631437917618413;
   fWeightMatrix1to2[0][5] = 1.7533931861656;
   fWeightMatrix1to2[1][5] = -0.683057639355167;
   fWeightMatrix1to2[2][5] = -1.92345185529273;
   fWeightMatrix1to2[3][5] = -1.95507677772357;
   fWeightMatrix1to2[4][5] = 3.01539391129609;
   fWeightMatrix1to2[5][5] = 1.72313858369282;
   fWeightMatrix1to2[6][5] = 1.29589911372873;
   fWeightMatrix1to2[7][5] = 1.08777765042247;
   fWeightMatrix1to2[8][5] = -0.232492390461993;
   fWeightMatrix1to2[9][5] = -1.17710915998883;
   fWeightMatrix1to2[10][5] = 0.0386459631701235;
   fWeightMatrix1to2[0][6] = 0.543580435080841;
   fWeightMatrix1to2[1][6] = -1.07809926436245;
   fWeightMatrix1to2[2][6] = 0.00620080083613314;
   fWeightMatrix1to2[3][6] = -0.482309075650589;
   fWeightMatrix1to2[4][6] = 0.539365321566484;
   fWeightMatrix1to2[5][6] = -1.81077545848824;
   fWeightMatrix1to2[6][6] = 2.36093032878279;
   fWeightMatrix1to2[7][6] = 1.42581128509785;
   fWeightMatrix1to2[8][6] = -2.67225006226998;
   fWeightMatrix1to2[9][6] = 1.08702117104573;
   fWeightMatrix1to2[10][6] = 4.23405303918046;
   fWeightMatrix1to2[0][7] = 1.91261784451092;
   fWeightMatrix1to2[1][7] = 1.14766885026361;
   fWeightMatrix1to2[2][7] = -0.432593388954059;
   fWeightMatrix1to2[3][7] = -2.05584358597391;
   fWeightMatrix1to2[4][7] = -0.937075630538425;
   fWeightMatrix1to2[5][7] = 1.71692359120875;
   fWeightMatrix1to2[6][7] = 1.38845378549157;
   fWeightMatrix1to2[7][7] = 0.127332389618275;
   fWeightMatrix1to2[8][7] = 0.0362424770078761;
   fWeightMatrix1to2[9][7] = 2.2893635056179;
   fWeightMatrix1to2[10][7] = -1.22417430410809;
   fWeightMatrix1to2[0][8] = -2.74750900297799;
   fWeightMatrix1to2[1][8] = 0.450475747587963;
   fWeightMatrix1to2[2][8] = -3.99852729800316;
   fWeightMatrix1to2[3][8] = 0.950374827382353;
   fWeightMatrix1to2[4][8] = 3.79880558507778;
   fWeightMatrix1to2[5][8] = -0.904494254759461;
   fWeightMatrix1to2[6][8] = 0.577863101484735;
   fWeightMatrix1to2[7][8] = 2.29265462239585;
   fWeightMatrix1to2[8][8] = -1.1001154565584;
   fWeightMatrix1to2[9][8] = -1.19793059085148;
   fWeightMatrix1to2[10][8] = -1.49582774723642;
   fWeightMatrix1to2[0][9] = 0.919637029160544;
   fWeightMatrix1to2[1][9] = 0.66152257473283;
   fWeightMatrix1to2[2][9] = -3.59069616660477;
   fWeightMatrix1to2[3][9] = 2.07844059445807;
   fWeightMatrix1to2[4][9] = -4.56907072252529;
   fWeightMatrix1to2[5][9] = 0.49309819799712;
   fWeightMatrix1to2[6][9] = -2.18251811988835;
   fWeightMatrix1to2[7][9] = -3.3304175530719;
   fWeightMatrix1to2[8][9] = -0.500521540584985;
   fWeightMatrix1to2[9][9] = -1.84652185755599;
   fWeightMatrix1to2[10][9] = 0.213050793070222;
   fWeightMatrix1to2[0][10] = -4.42575826337095;
   fWeightMatrix1to2[1][10] = -1.85531236075261;
   fWeightMatrix1to2[2][10] = 0.244013456278024;
   fWeightMatrix1to2[3][10] = 0.0974072136139233;
   fWeightMatrix1to2[4][10] = -3.2141280614968;
   fWeightMatrix1to2[5][10] = -1.54486081428947;
   fWeightMatrix1to2[6][10] = 0.166695687145272;
   fWeightMatrix1to2[7][10] = -3.29931642718264;
   fWeightMatrix1to2[8][10] = -0.355156597288081;
   fWeightMatrix1to2[9][10] = -1.60971617578427;
   fWeightMatrix1to2[10][10] = 1.54377036189884;
   fWeightMatrix1to2[0][11] = 0.810627266408978;
   fWeightMatrix1to2[1][11] = 1.66387826961981;
   fWeightMatrix1to2[2][11] = -0.247244310794095;
   fWeightMatrix1to2[3][11] = -2.18879052832764;
   fWeightMatrix1to2[4][11] = -4.34504510496678;
   fWeightMatrix1to2[5][11] = -0.818816623876734;
   fWeightMatrix1to2[6][11] = -1.80643227193979;
   fWeightMatrix1to2[7][11] = -0.755260526415945;
   fWeightMatrix1to2[8][11] = 0.875720587825479;
   fWeightMatrix1to2[9][11] = 1.35699332080602;
   fWeightMatrix1to2[10][11] = -0.472479309090036;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = 2.98443477865622;
   fWeightMatrix2to3[0][1] = -1.66299681721832;
   fWeightMatrix2to3[0][2] = -3.95530903175507;
   fWeightMatrix2to3[0][3] = 2.2002307374911;
   fWeightMatrix2to3[0][4] = 4.30901850406096;
   fWeightMatrix2to3[0][5] = -0.809789709605719;
   fWeightMatrix2to3[0][6] = -2.61523399028078;
   fWeightMatrix2to3[0][7] = 2.45892053437645;
   fWeightMatrix2to3[0][8] = 2.36313442182886;
   fWeightMatrix2to3[0][9] = -1.51837894624831;
   fWeightMatrix2to3[0][10] = -3.27785570074072;
   fWeightMatrix2to3[0][11] = -0.715654435945627;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)11) {
      std::cout << "Input vector needs to be of size " << 11 << std::endl;
      return 0;
   }

   std::array<double, 12> fWeights1 {{}};
   std::array<double, 12> fWeights2 {{}};
   std::array<double, 1> fWeights3 {{}};
   fWeights1.back() = 1.;
   fWeights2.back() = 1.;

   // layer 0 to 1
   for (int o=0; o<11; o++) {
      std::array<double, 12> buffer; // no need to initialise
      for (int i = 0; i<12 - 1; i++) {
         buffer[i] = fWeightMatrix0to1[o][i] * inputValues[i];
      } // loop over i
      buffer.back() = fWeightMatrix0to1[o][11];
      for (int i=0; i<12; i++) {
         fWeights1[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<11; o++) {
      fWeights1[o] = ActivationFnc(fWeights1[o]);
   } // loop over o
   // layer 1 to 2
   for (int o=0; o<11; o++) {
      std::array<double, 12> buffer; // no need to initialise
      for (int i=0; i<12; i++) {
         buffer[i] = fWeightMatrix1to2[o][i] * fWeights1[i];
      } // loop over i
      for (int i=0; i<12; i++) {
         fWeights2[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<11; o++) {
      fWeights2[o] = ActivationFnc(fWeights2[o]);
   } // loop over o
   // layer 2 to 3
   for (int o=0; o<1; o++) {
      std::array<double, 12> buffer; // no need to initialise
      for (int i=0; i<12; i++) {
         buffer[i] = fWeightMatrix2to3[o][i] * fWeights2[i];
      } // loop over i
      for (int i=0; i<12; i++) {
         fWeights3[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<1; o++) {
      fWeights3[o] = OutputActivationFnc(fWeights3[o]);
   } // loop over o

   return fWeights3[0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}

// Clean up
inline void ReadMLP::Clear()
{
}
inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         std::vector<double> iV(inputValues);
         Transform( iV, -1 );
         retval = GetMvaValue__( iV );
   }

   return retval;
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   double fMin_1[3][11];
   double fMax_1[3][11];
   // Normalization transformation, initialisation
   fMin_1[0][0] = 22.7864818573;
   fMax_1[0][0] = 7505.73046875;
   fScal_1[0][0] = 2.0/(fMax_1[0][0]-fMin_1[0][0]);
   fOff_1[0][0] = fMin_1[0][0]*fScal_1[0][0]+1.;
   fMin_1[1][0] = 23.5563087463;
   fMax_1[1][0] = 7838.75537109;
   fScal_1[1][0] = 2.0/(fMax_1[1][0]-fMin_1[1][0]);
   fOff_1[1][0] = fMin_1[1][0]*fScal_1[1][0]+1.;
   fMin_1[2][0] = 22.7864818573;
   fMax_1[2][0] = 7838.75537109;
   fScal_1[2][0] = 2.0/(fMax_1[2][0]-fMin_1[2][0]);
   fOff_1[2][0] = fMin_1[2][0]*fScal_1[2][0]+1.;
   fMin_1[0][1] = 0.000150358115206;
   fMax_1[0][1] = 8.68471050262;
   fScal_1[0][1] = 2.0/(fMax_1[0][1]-fMin_1[0][1]);
   fOff_1[0][1] = fMin_1[0][1]*fScal_1[0][1]+1.;
   fMin_1[1][1] = 2.2119609639e-05;
   fMax_1[1][1] = 8.68384933472;
   fScal_1[1][1] = 2.0/(fMax_1[1][1]-fMin_1[1][1]);
   fOff_1[1][1] = fMin_1[1][1]*fScal_1[1][1]+1.;
   fMin_1[2][1] = 2.2119609639e-05;
   fMax_1[2][1] = 8.68471050262;
   fScal_1[2][1] = 2.0/(fMax_1[2][1]-fMin_1[2][1]);
   fOff_1[2][1] = fMin_1[2][1]*fScal_1[2][1]+1.;
   fMin_1[0][2] = 126.97845459;
   fMax_1[0][2] = 2277.4987793;
   fScal_1[0][2] = 2.0/(fMax_1[0][2]-fMin_1[0][2]);
   fOff_1[0][2] = fMin_1[0][2]*fScal_1[0][2]+1.;
   fMin_1[1][2] = 125.825294495;
   fMax_1[1][2] = 1926.56140137;
   fScal_1[1][2] = 2.0/(fMax_1[1][2]-fMin_1[1][2]);
   fOff_1[1][2] = fMin_1[1][2]*fScal_1[1][2]+1.;
   fMin_1[2][2] = 125.825294495;
   fMax_1[2][2] = 2277.4987793;
   fScal_1[2][2] = 2.0/(fMax_1[2][2]-fMin_1[2][2]);
   fOff_1[2][2] = fMin_1[2][2]*fScal_1[2][2]+1.;
   fMin_1[0][3] = 4.91857872476e-06;
   fMax_1[0][3] = 0.405025333166;
   fScal_1[0][3] = 2.0/(fMax_1[0][3]-fMin_1[0][3]);
   fOff_1[0][3] = fMin_1[0][3]*fScal_1[0][3]+1.;
   fMin_1[1][3] = 5.9500340285e-05;
   fMax_1[1][3] = 0.47649076581;
   fScal_1[1][3] = 2.0/(fMax_1[1][3]-fMin_1[1][3]);
   fOff_1[1][3] = fMin_1[1][3]*fScal_1[1][3]+1.;
   fMin_1[2][3] = 4.91857872476e-06;
   fMax_1[2][3] = 0.47649076581;
   fScal_1[2][3] = 2.0/(fMax_1[2][3]-fMin_1[2][3]);
   fOff_1[2][3] = fMin_1[2][3]*fScal_1[2][3]+1.;
   fMin_1[0][4] = -4.50663423538;
   fMax_1[0][4] = 4.51134681702;
   fScal_1[0][4] = 2.0/(fMax_1[0][4]-fMin_1[0][4]);
   fOff_1[0][4] = fMin_1[0][4]*fScal_1[0][4]+1.;
   fMin_1[1][4] = -4.5036110878;
   fMax_1[1][4] = 4.50834369659;
   fScal_1[1][4] = 2.0/(fMax_1[1][4]-fMin_1[1][4]);
   fOff_1[1][4] = fMin_1[1][4]*fScal_1[1][4]+1.;
   fMin_1[2][4] = -4.50663423538;
   fMax_1[2][4] = 4.51134681702;
   fScal_1[2][4] = 2.0/(fMax_1[2][4]-fMin_1[2][4]);
   fOff_1[2][4] = fMin_1[2][4]*fScal_1[2][4]+1.;
   fMin_1[0][5] = 50.1059684753;
   fMax_1[0][5] = 1964.14489746;
   fScal_1[0][5] = 2.0/(fMax_1[0][5]-fMin_1[0][5]);
   fOff_1[0][5] = fMin_1[0][5]*fScal_1[0][5]+1.;
   fMin_1[1][5] = 50.0584754944;
   fMax_1[1][5] = 2753.2824707;
   fScal_1[1][5] = 2.0/(fMax_1[1][5]-fMin_1[1][5]);
   fOff_1[1][5] = fMin_1[1][5]*fScal_1[1][5]+1.;
   fMin_1[2][5] = 50.0584754944;
   fMax_1[2][5] = 2753.2824707;
   fScal_1[2][5] = 2.0/(fMax_1[2][5]-fMin_1[2][5]);
   fOff_1[2][5] = fMin_1[2][5]*fScal_1[2][5]+1.;
   fMin_1[0][6] = -2.4010925293;
   fMax_1[0][6] = 2.39041256905;
   fScal_1[0][6] = 2.0/(fMax_1[0][6]-fMin_1[0][6]);
   fOff_1[0][6] = fMin_1[0][6]*fScal_1[0][6]+1.;
   fMin_1[1][6] = -2.38632035255;
   fMax_1[1][6] = 2.38307738304;
   fScal_1[1][6] = 2.0/(fMax_1[1][6]-fMin_1[1][6]);
   fOff_1[1][6] = fMin_1[1][6]*fScal_1[1][6]+1.;
   fMin_1[2][6] = -2.4010925293;
   fMax_1[2][6] = 2.39041256905;
   fScal_1[2][6] = 2.0/(fMax_1[2][6]-fMin_1[2][6]);
   fOff_1[2][6] = fMin_1[2][6]*fScal_1[2][6]+1.;
   fMin_1[0][7] = 0.0488347522914;
   fMax_1[0][7] = 0.99988257885;
   fScal_1[0][7] = 2.0/(fMax_1[0][7]-fMin_1[0][7]);
   fOff_1[0][7] = fMin_1[0][7]*fScal_1[0][7]+1.;
   fMin_1[1][7] = 0.0229892414063;
   fMax_1[1][7] = 0.999983787537;
   fScal_1[1][7] = 2.0/(fMax_1[1][7]-fMin_1[1][7]);
   fOff_1[1][7] = fMin_1[1][7]*fScal_1[1][7]+1.;
   fMin_1[2][7] = 0.0229892414063;
   fMax_1[2][7] = 0.999983787537;
   fScal_1[2][7] = 2.0/(fMax_1[2][7]-fMin_1[2][7]);
   fOff_1[2][7] = fMin_1[2][7]*fScal_1[2][7]+1.;
   fMin_1[0][8] = 2;
   fMax_1[0][8] = 8;
   fScal_1[0][8] = 2.0/(fMax_1[0][8]-fMin_1[0][8]);
   fOff_1[0][8] = fMin_1[0][8]*fScal_1[0][8]+1.;
   fMin_1[1][8] = 2;
   fMax_1[1][8] = 9;
   fScal_1[1][8] = 2.0/(fMax_1[1][8]-fMin_1[1][8]);
   fOff_1[1][8] = fMin_1[1][8]*fScal_1[1][8]+1.;
   fMin_1[2][8] = 2;
   fMax_1[2][8] = 9;
   fScal_1[2][8] = 2.0/(fMax_1[2][8]-fMin_1[2][8]);
   fOff_1[2][8] = fMin_1[2][8]*fScal_1[2][8]+1.;
   fMin_1[0][9] = 1.5914440155e-05;
   fMax_1[0][9] = 1;
   fScal_1[0][9] = 2.0/(fMax_1[0][9]-fMin_1[0][9]);
   fOff_1[0][9] = fMin_1[0][9]*fScal_1[0][9]+1.;
   fMin_1[1][9] = 1.93119049072e-05;
   fMax_1[1][9] = 1;
   fScal_1[1][9] = 2.0/(fMax_1[1][9]-fMin_1[1][9]);
   fOff_1[1][9] = fMin_1[1][9]*fScal_1[1][9]+1.;
   fMin_1[2][9] = 1.5914440155e-05;
   fMax_1[2][9] = 1;
   fScal_1[2][9] = 2.0/(fMax_1[2][9]-fMin_1[2][9]);
   fOff_1[2][9] = fMin_1[2][9]*fScal_1[2][9]+1.;
   fMin_1[0][10] = 3.26525550918e-05;
   fMax_1[0][10] = 6.50682735443;
   fScal_1[0][10] = 2.0/(fMax_1[0][10]-fMin_1[0][10]);
   fOff_1[0][10] = fMin_1[0][10]*fScal_1[0][10]+1.;
   fMin_1[1][10] = 1.18112052405e-06;
   fMax_1[1][10] = 6.68952894211;
   fScal_1[1][10] = 2.0/(fMax_1[1][10]-fMin_1[1][10]);
   fOff_1[1][10] = fMin_1[1][10]*fScal_1[1][10]+1.;
   fMin_1[2][10] = 1.18112052405e-06;
   fMax_1[2][10] = 6.68952894211;
   fScal_1[2][10] = 2.0/(fMax_1[2][10]-fMin_1[2][10]);
   fOff_1[2][10] = fMin_1[2][10]*fScal_1[2][10]+1.;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) {
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   }
   if ( indicesPut.empty() ) {
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   }

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fOff_1[cls][ivar];
      double scale  = fScal_1[cls][ivar];
      iv[indicesPut.at(ivar)] = scale*dv[ivar]-offset;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
