// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.22/06       [398854]
Creator        : konstantin
Date           : Thu Apr  1 20:02:29 2021
Host           : Linux mach 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/konstantin/Projects/CERN/TMVA_MLP
Training events: 170672
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "400" [Number of training cycles]
HiddenLayers: "N+10,N" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
LearningRate: "1.000000e-02" [ANN learning rate parameter]
TestRate: "5" [Test for overtraining performed at each #th epochs]
BPMode: "batch" [Back-propagation learning mode: sequential or batch]
BatchSize: "5" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "2.500000e-03" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "5" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
mJJ                           mJJ                           mJJ                           mJJ                                                             'F'    [22.7864818573,7838.75537109]
deltaYJJ                      deltaYJJ                      deltaYJJ                      deltaYJJ                                                        'F'    [2.2119609639e-05,8.68471050262]
metPt                         metPt                         metPt                         metPt                                                           'F'    [125.825294495,2277.4987793]
ptBalance                     ptBalance                     ptBalance                     ptBalance                                                       'F'    [4.91857872476e-06,0.47649076581]
subleadJetEta                 subleadJetEta                 subleadJetEta                 subleadJetEta                                                   'F'    [-4.50663423538,4.51134681702]
leadJetPt                     leadJetPt                     leadJetPt                     leadJetPt                                                       'F'    [50.0584754944,2753.2824707]
photonEta                     photonEta                     photonEta                     photonEta                                                       'F'    [-2.4010925293,2.39041256905]
ptBalanceRed                  ptBalanceRed                  ptBalanceRed                  ptBalanceRed                                                    'F'    [0.0229892414063,0.999983787537]
nJets                         nJets                         nJets                         nJets                                                           'F'    [2,9]
sinDeltaPhiJJOver2            sinDeltaPhiJJOver2            sinDeltaPhiJJOver2            sinDeltaPhiJJOver2                                              'F'    [1.5914440155e-05,1]
deltaYJPh                     deltaYJPh                     deltaYJPh                     deltaYJPh                                                       'F'    [1.18112052405e-06,6.68952894211]
NSpec 1
weightModified                weightModified                weightModified                F                                                               'F'    [-0.191263645887,1.09073340893]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 11 )
   {
      // the training input variables
      const char* inputVars[] = { "mJJ", "deltaYJJ", "metPt", "ptBalance", "subleadJetEta", "leadJetPt", "photonEta", "ptBalanceRed", "nJets", "sinDeltaPhiJJOver2", "deltaYJPh" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fOff_1[3][11];
   double fScal_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   double fWeightMatrix0to1[22][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][22];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][12];   // weight matrix from layer 2 to 3

};

inline void ReadMLP::Initialize()
{
   // build network structure
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.333969289146328;
   fWeightMatrix0to1[1][0] = 1.97151170607557;
   fWeightMatrix0to1[2][0] = 1.36620241003871;
   fWeightMatrix0to1[3][0] = 2.29526123626122;
   fWeightMatrix0to1[4][0] = -1.98332537112376;
   fWeightMatrix0to1[5][0] = -0.420321728678514;
   fWeightMatrix0to1[6][0] = -0.63537860679646;
   fWeightMatrix0to1[7][0] = 1.80432193110284;
   fWeightMatrix0to1[8][0] = -1.58154266291879;
   fWeightMatrix0to1[9][0] = -1.79808676446874;
   fWeightMatrix0to1[10][0] = -2.17301418413269;
   fWeightMatrix0to1[11][0] = -3.82634680434164;
   fWeightMatrix0to1[12][0] = -1.91951034287786;
   fWeightMatrix0to1[13][0] = 0.00540165092288486;
   fWeightMatrix0to1[14][0] = -1.49597133865944;
   fWeightMatrix0to1[15][0] = -0.85410826284601;
   fWeightMatrix0to1[16][0] = 0.0885389545429723;
   fWeightMatrix0to1[17][0] = 1.37257397056991;
   fWeightMatrix0to1[18][0] = 0.328080522490946;
   fWeightMatrix0to1[19][0] = 1.58875128897926;
   fWeightMatrix0to1[20][0] = 0.753915753320527;
   fWeightMatrix0to1[0][1] = -2.23136668056824;
   fWeightMatrix0to1[1][1] = -1.01290387689439;
   fWeightMatrix0to1[2][1] = 0.0543673699537636;
   fWeightMatrix0to1[3][1] = -2.83221000197304;
   fWeightMatrix0to1[4][1] = -1.07350746431932;
   fWeightMatrix0to1[5][1] = 2.67001417169984;
   fWeightMatrix0to1[6][1] = -2.31544986603497;
   fWeightMatrix0to1[7][1] = -2.25049894210411;
   fWeightMatrix0to1[8][1] = 1.07001166616747;
   fWeightMatrix0to1[9][1] = 0.117618728469595;
   fWeightMatrix0to1[10][1] = 2.40972161072633;
   fWeightMatrix0to1[11][1] = -1.80885590038895;
   fWeightMatrix0to1[12][1] = -0.636615364762186;
   fWeightMatrix0to1[13][1] = 0.566766052283259;
   fWeightMatrix0to1[14][1] = -3.85387227398818;
   fWeightMatrix0to1[15][1] = -1.15793663913791;
   fWeightMatrix0to1[16][1] = 1.68867092189655;
   fWeightMatrix0to1[17][1] = -2.05720759313832;
   fWeightMatrix0to1[18][1] = 0.829250926547826;
   fWeightMatrix0to1[19][1] = 1.97738052299227;
   fWeightMatrix0to1[20][1] = 2.75447269377483;
   fWeightMatrix0to1[0][2] = 2.07881623232063;
   fWeightMatrix0to1[1][2] = 1.71335346386211;
   fWeightMatrix0to1[2][2] = -0.945855676697771;
   fWeightMatrix0to1[3][2] = -0.566018507958173;
   fWeightMatrix0to1[4][2] = 0.254353060194345;
   fWeightMatrix0to1[5][2] = 0.0999867570982685;
   fWeightMatrix0to1[6][2] = 1.90864017226624;
   fWeightMatrix0to1[7][2] = 1.0708077682974;
   fWeightMatrix0to1[8][2] = 1.19479657332414;
   fWeightMatrix0to1[9][2] = 1.90764341062031;
   fWeightMatrix0to1[10][2] = -2.28367566008748;
   fWeightMatrix0to1[11][2] = 0.988665419684156;
   fWeightMatrix0to1[12][2] = -1.15685036918092;
   fWeightMatrix0to1[13][2] = -0.996496417276041;
   fWeightMatrix0to1[14][2] = -1.03899330020708;
   fWeightMatrix0to1[15][2] = -2.5617386802215;
   fWeightMatrix0to1[16][2] = 1.62945580654835;
   fWeightMatrix0to1[17][2] = 1.04537410345654;
   fWeightMatrix0to1[18][2] = -1.3322201359186;
   fWeightMatrix0to1[19][2] = 0.273809820135187;
   fWeightMatrix0to1[20][2] = 0.171915997463868;
   fWeightMatrix0to1[0][3] = 0.684718794139783;
   fWeightMatrix0to1[1][3] = 2.90944401693449;
   fWeightMatrix0to1[2][3] = -0.206015741862803;
   fWeightMatrix0to1[3][3] = 0.632683394333342;
   fWeightMatrix0to1[4][3] = 0.5864336801856;
   fWeightMatrix0to1[5][3] = 0.510964179510667;
   fWeightMatrix0to1[6][3] = -0.845875865319221;
   fWeightMatrix0to1[7][3] = -1.18527908601488;
   fWeightMatrix0to1[8][3] = -1.36564017870773;
   fWeightMatrix0to1[9][3] = 0.760295031261574;
   fWeightMatrix0to1[10][3] = 1.1466837520369;
   fWeightMatrix0to1[11][3] = 1.60702263388838;
   fWeightMatrix0to1[12][3] = 0.209387041808461;
   fWeightMatrix0to1[13][3] = -2.16457856973298;
   fWeightMatrix0to1[14][3] = -0.19088254695598;
   fWeightMatrix0to1[15][3] = 2.74910350653491;
   fWeightMatrix0to1[16][3] = 0.124587721583662;
   fWeightMatrix0to1[17][3] = 2.64493558068675;
   fWeightMatrix0to1[18][3] = 0.733142642052239;
   fWeightMatrix0to1[19][3] = 0.462947667053937;
   fWeightMatrix0to1[20][3] = -0.81780500085363;
   fWeightMatrix0to1[0][4] = -1.67553883213705;
   fWeightMatrix0to1[1][4] = 0.381855898309729;
   fWeightMatrix0to1[2][4] = 0.982782609295459;
   fWeightMatrix0to1[3][4] = -0.450148458047801;
   fWeightMatrix0to1[4][4] = -1.00214448503546;
   fWeightMatrix0to1[5][4] = -1.51258321073844;
   fWeightMatrix0to1[6][4] = -0.348306042245002;
   fWeightMatrix0to1[7][4] = 0.563690392515222;
   fWeightMatrix0to1[8][4] = 1.83285722401052;
   fWeightMatrix0to1[9][4] = -1.26454970056636;
   fWeightMatrix0to1[10][4] = -1.12368277264918;
   fWeightMatrix0to1[11][4] = 1.90918770244754;
   fWeightMatrix0to1[12][4] = -0.526706680967978;
   fWeightMatrix0to1[13][4] = -0.0358571983470952;
   fWeightMatrix0to1[14][4] = -3.06465313158305;
   fWeightMatrix0to1[15][4] = -0.218555040211595;
   fWeightMatrix0to1[16][4] = -0.991178684598786;
   fWeightMatrix0to1[17][4] = -1.82954829876677;
   fWeightMatrix0to1[18][4] = 0.869883797885637;
   fWeightMatrix0to1[19][4] = 1.65979811804498;
   fWeightMatrix0to1[20][4] = -3.388841338901;
   fWeightMatrix0to1[0][5] = 2.15799670338607;
   fWeightMatrix0to1[1][5] = -1.9003786651366;
   fWeightMatrix0to1[2][5] = -0.286914458175212;
   fWeightMatrix0to1[3][5] = 0.515925354248805;
   fWeightMatrix0to1[4][5] = 1.02828429782211;
   fWeightMatrix0to1[5][5] = -1.57743722629728;
   fWeightMatrix0to1[6][5] = 0.0938643937853215;
   fWeightMatrix0to1[7][5] = 0.030901594416511;
   fWeightMatrix0to1[8][5] = -0.0163633860553815;
   fWeightMatrix0to1[9][5] = -0.620066671321053;
   fWeightMatrix0to1[10][5] = 1.55169925683722;
   fWeightMatrix0to1[11][5] = -0.389819972695276;
   fWeightMatrix0to1[12][5] = -0.678736437812689;
   fWeightMatrix0to1[13][5] = 1.08758759656009;
   fWeightMatrix0to1[14][5] = -0.320999478300305;
   fWeightMatrix0to1[15][5] = -2.18315151463651;
   fWeightMatrix0to1[16][5] = 0.492310610191892;
   fWeightMatrix0to1[17][5] = -0.46454815614015;
   fWeightMatrix0to1[18][5] = 2.28052133344235;
   fWeightMatrix0to1[19][5] = 0.473546874216133;
   fWeightMatrix0to1[20][5] = -0.839709851826638;
   fWeightMatrix0to1[0][6] = -0.122847880390419;
   fWeightMatrix0to1[1][6] = -0.406757085591663;
   fWeightMatrix0to1[2][6] = -2.65735104437795;
   fWeightMatrix0to1[3][6] = 0.806797599265753;
   fWeightMatrix0to1[4][6] = 1.04415806584603;
   fWeightMatrix0to1[5][6] = -0.748623354991763;
   fWeightMatrix0to1[6][6] = 0.42298734064217;
   fWeightMatrix0to1[7][6] = -0.953113940651257;
   fWeightMatrix0to1[8][6] = 0.523595562797077;
   fWeightMatrix0to1[9][6] = 0.972885373982087;
   fWeightMatrix0to1[10][6] = 1.20481332871622;
   fWeightMatrix0to1[11][6] = -1.05838834389019;
   fWeightMatrix0to1[12][6] = 0.171498158913606;
   fWeightMatrix0to1[13][6] = 1.95182859388887;
   fWeightMatrix0to1[14][6] = 0.93417326489057;
   fWeightMatrix0to1[15][6] = 0.230620063696187;
   fWeightMatrix0to1[16][6] = -1.66025119892651;
   fWeightMatrix0to1[17][6] = -0.747794157602398;
   fWeightMatrix0to1[18][6] = -1.00654821507226;
   fWeightMatrix0to1[19][6] = 1.36123945581494;
   fWeightMatrix0to1[20][6] = 1.67198382903609;
   fWeightMatrix0to1[0][7] = -0.363464992243528;
   fWeightMatrix0to1[1][7] = 0.142289100077249;
   fWeightMatrix0to1[2][7] = 0.129260628438667;
   fWeightMatrix0to1[3][7] = -0.9377404269823;
   fWeightMatrix0to1[4][7] = 0.103546747060448;
   fWeightMatrix0to1[5][7] = 0.400349264184677;
   fWeightMatrix0to1[6][7] = 0.728529995396263;
   fWeightMatrix0to1[7][7] = -1.05867204169206;
   fWeightMatrix0to1[8][7] = 0.0853064858969926;
   fWeightMatrix0to1[9][7] = -0.00593818740163227;
   fWeightMatrix0to1[10][7] = -0.274291763643027;
   fWeightMatrix0to1[11][7] = 0.297369455175258;
   fWeightMatrix0to1[12][7] = -0.902096320119038;
   fWeightMatrix0to1[13][7] = 1.47747800979893;
   fWeightMatrix0to1[14][7] = 0.00296990463683674;
   fWeightMatrix0to1[15][7] = 1.23858201376737;
   fWeightMatrix0to1[16][7] = 0.186011313690792;
   fWeightMatrix0to1[17][7] = 1.09223551940843;
   fWeightMatrix0to1[18][7] = -0.0954402214594792;
   fWeightMatrix0to1[19][7] = -0.518189818965961;
   fWeightMatrix0to1[20][7] = 0.790183152046668;
   fWeightMatrix0to1[0][8] = -1.31385481823332;
   fWeightMatrix0to1[1][8] = -0.543429497092343;
   fWeightMatrix0to1[2][8] = 2.2800740731279;
   fWeightMatrix0to1[3][8] = 1.83621002652656;
   fWeightMatrix0to1[4][8] = -0.0566162753144501;
   fWeightMatrix0to1[5][8] = 1.37335286192254;
   fWeightMatrix0to1[6][8] = 1.19272063672144;
   fWeightMatrix0to1[7][8] = -2.66458056118656;
   fWeightMatrix0to1[8][8] = 0.435591382703516;
   fWeightMatrix0to1[9][8] = 0.151743427409941;
   fWeightMatrix0to1[10][8] = -0.546055918716864;
   fWeightMatrix0to1[11][8] = -1.58062060677765;
   fWeightMatrix0to1[12][8] = -1.24335672746551;
   fWeightMatrix0to1[13][8] = 1.99135837607491;
   fWeightMatrix0to1[14][8] = 2.98327974608148;
   fWeightMatrix0to1[15][8] = -1.2060610608981;
   fWeightMatrix0to1[16][8] = -0.381817251282606;
   fWeightMatrix0to1[17][8] = -0.112867836455001;
   fWeightMatrix0to1[18][8] = 0.91346659177523;
   fWeightMatrix0to1[19][8] = 1.01594886000779;
   fWeightMatrix0to1[20][8] = -1.98724405647622;
   fWeightMatrix0to1[0][9] = -0.25153408411271;
   fWeightMatrix0to1[1][9] = -0.539961333220561;
   fWeightMatrix0to1[2][9] = 0.985208481334383;
   fWeightMatrix0to1[3][9] = 0.678979608018529;
   fWeightMatrix0to1[4][9] = 2.62914634387724;
   fWeightMatrix0to1[5][9] = 0.287033271445986;
   fWeightMatrix0to1[6][9] = -0.571037048126548;
   fWeightMatrix0to1[7][9] = -1.56569648493125;
   fWeightMatrix0to1[8][9] = 1.281999781692;
   fWeightMatrix0to1[9][9] = 0.496771718496136;
   fWeightMatrix0to1[10][9] = -1.15615910159182;
   fWeightMatrix0to1[11][9] = 0.354658548933229;
   fWeightMatrix0to1[12][9] = 0.102962431284519;
   fWeightMatrix0to1[13][9] = 0.102325788308484;
   fWeightMatrix0to1[14][9] = -0.280351868519545;
   fWeightMatrix0to1[15][9] = -0.0370419917719746;
   fWeightMatrix0to1[16][9] = 0.583655339766112;
   fWeightMatrix0to1[17][9] = -1.11670406045812;
   fWeightMatrix0to1[18][9] = -0.218518784400177;
   fWeightMatrix0to1[19][9] = 1.65515098507451;
   fWeightMatrix0to1[20][9] = 0.41788907573306;
   fWeightMatrix0to1[0][10] = 0.161181897498349;
   fWeightMatrix0to1[1][10] = 0.600928074042327;
   fWeightMatrix0to1[2][10] = -1.96845669666055;
   fWeightMatrix0to1[3][10] = -0.347720429116027;
   fWeightMatrix0to1[4][10] = 1.54852067806955;
   fWeightMatrix0to1[5][10] = 1.30130638328273;
   fWeightMatrix0to1[6][10] = 1.25576301489652;
   fWeightMatrix0to1[7][10] = -0.0833248419651143;
   fWeightMatrix0to1[8][10] = 2.11616454141881;
   fWeightMatrix0to1[9][10] = -2.95597179199543;
   fWeightMatrix0to1[10][10] = -0.0116547730762294;
   fWeightMatrix0to1[11][10] = 0.508334777416485;
   fWeightMatrix0to1[12][10] = -1.64398541626627;
   fWeightMatrix0to1[13][10] = 0.180386603523226;
   fWeightMatrix0to1[14][10] = 1.94676431622647;
   fWeightMatrix0to1[15][10] = -0.0610263743328773;
   fWeightMatrix0to1[16][10] = 0.56442690030742;
   fWeightMatrix0to1[17][10] = 0.692141564041094;
   fWeightMatrix0to1[18][10] = -1.50738592257478;
   fWeightMatrix0to1[19][10] = -1.78749399723071;
   fWeightMatrix0to1[20][10] = -1.51950295722991;
   fWeightMatrix0to1[0][11] = 0.138319644293673;
   fWeightMatrix0to1[1][11] = 3.54557097935323;
   fWeightMatrix0to1[2][11] = -0.998216997586425;
   fWeightMatrix0to1[3][11] = 2.7597530432939;
   fWeightMatrix0to1[4][11] = -3.63846871081707;
   fWeightMatrix0to1[5][11] = 2.50055061707639;
   fWeightMatrix0to1[6][11] = 0.0536583331182199;
   fWeightMatrix0to1[7][11] = -1.32129122239022;
   fWeightMatrix0to1[8][11] = -1.08584813361673;
   fWeightMatrix0to1[9][11] = -4.151306464614;
   fWeightMatrix0to1[10][11] = -1.5093681306551;
   fWeightMatrix0to1[11][11] = -4.66999496983076;
   fWeightMatrix0to1[12][11] = -2.71434956055702;
   fWeightMatrix0to1[13][11] = -1.01107326050291;
   fWeightMatrix0to1[14][11] = -1.40632915060156;
   fWeightMatrix0to1[15][11] = -4.10369886813622;
   fWeightMatrix0to1[16][11] = -2.0244069375338;
   fWeightMatrix0to1[17][11] = 0.428226744149821;
   fWeightMatrix0to1[18][11] = -0.811242389448702;
   fWeightMatrix0to1[19][11] = 0.499818185192317;
   fWeightMatrix0to1[20][11] = -0.608893068877352;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.033055507571538;
   fWeightMatrix1to2[1][0] = 2.0621684817683;
   fWeightMatrix1to2[2][0] = 1.58588810055302;
   fWeightMatrix1to2[3][0] = -0.593450456570328;
   fWeightMatrix1to2[4][0] = -0.799664905493006;
   fWeightMatrix1to2[5][0] = -1.40489860049897;
   fWeightMatrix1to2[6][0] = -0.723503204688994;
   fWeightMatrix1to2[7][0] = -3.05230528774606;
   fWeightMatrix1to2[8][0] = 1.41734209700806;
   fWeightMatrix1to2[9][0] = 0.475666407608091;
   fWeightMatrix1to2[10][0] = 1.88173475600832;
   fWeightMatrix1to2[0][1] = -1.33879726827438;
   fWeightMatrix1to2[1][1] = 0.505507382687905;
   fWeightMatrix1to2[2][1] = -0.540869037500264;
   fWeightMatrix1to2[3][1] = -1.42595095351654;
   fWeightMatrix1to2[4][1] = 0.865529629336593;
   fWeightMatrix1to2[5][1] = 1.3460804662629;
   fWeightMatrix1to2[6][1] = -0.933166937899394;
   fWeightMatrix1to2[7][1] = -2.25449795456478;
   fWeightMatrix1to2[8][1] = -0.159202093518532;
   fWeightMatrix1to2[9][1] = 2.97550465178744;
   fWeightMatrix1to2[10][1] = 0.471694056710003;
   fWeightMatrix1to2[0][2] = -0.14182343209233;
   fWeightMatrix1to2[1][2] = 0.304502190123413;
   fWeightMatrix1to2[2][2] = 1.24282851629725;
   fWeightMatrix1to2[3][2] = 1.6982505351162;
   fWeightMatrix1to2[4][2] = 0.517315831806445;
   fWeightMatrix1to2[5][2] = -0.761268766351502;
   fWeightMatrix1to2[6][2] = 0.528621417947248;
   fWeightMatrix1to2[7][2] = -0.447599288224462;
   fWeightMatrix1to2[8][2] = -2.65005390364685;
   fWeightMatrix1to2[9][2] = -0.593192600196066;
   fWeightMatrix1to2[10][2] = -1.75582100866418;
   fWeightMatrix1to2[0][3] = -1.04331842901872;
   fWeightMatrix1to2[1][3] = -0.744384017095974;
   fWeightMatrix1to2[2][3] = 1.8049363704538;
   fWeightMatrix1to2[3][3] = -1.2450772893892;
   fWeightMatrix1to2[4][3] = 1.04361730612027;
   fWeightMatrix1to2[5][3] = -1.39240005420171;
   fWeightMatrix1to2[6][3] = 0.94432337200171;
   fWeightMatrix1to2[7][3] = -1.96229844483183;
   fWeightMatrix1to2[8][3] = 0.91991257016472;
   fWeightMatrix1to2[9][3] = 2.50203831238074;
   fWeightMatrix1to2[10][3] = -1.86658230929662;
   fWeightMatrix1to2[0][4] = 0.911391705497975;
   fWeightMatrix1to2[1][4] = 0.710422897233902;
   fWeightMatrix1to2[2][4] = -2.05783594094109;
   fWeightMatrix1to2[3][4] = -1.47556163435109;
   fWeightMatrix1to2[4][4] = -2.00607580940846;
   fWeightMatrix1to2[5][4] = -0.916554653990312;
   fWeightMatrix1to2[6][4] = 1.92283199976542;
   fWeightMatrix1to2[7][4] = -1.71952224394425;
   fWeightMatrix1to2[8][4] = -0.0729787710555976;
   fWeightMatrix1to2[9][4] = -1.3085051384717;
   fWeightMatrix1to2[10][4] = -1.18411277724691;
   fWeightMatrix1to2[0][5] = -1.44448567957357;
   fWeightMatrix1to2[1][5] = -0.271736158627849;
   fWeightMatrix1to2[2][5] = -1.45552364469608;
   fWeightMatrix1to2[3][5] = 1.76199388254371;
   fWeightMatrix1to2[4][5] = -0.127952619070949;
   fWeightMatrix1to2[5][5] = -1.63559809372389;
   fWeightMatrix1to2[6][5] = 1.86472255157657;
   fWeightMatrix1to2[7][5] = -0.121938907416707;
   fWeightMatrix1to2[8][5] = -0.525891304481866;
   fWeightMatrix1to2[9][5] = 2.36251303734031;
   fWeightMatrix1to2[10][5] = -1.81273517727538;
   fWeightMatrix1to2[0][6] = 1.04847829770787;
   fWeightMatrix1to2[1][6] = 1.14553173081984;
   fWeightMatrix1to2[2][6] = -0.87049252459283;
   fWeightMatrix1to2[3][6] = -0.25896918908245;
   fWeightMatrix1to2[4][6] = 0.505941431364883;
   fWeightMatrix1to2[5][6] = -0.857776146370919;
   fWeightMatrix1to2[6][6] = 0.0944811053604267;
   fWeightMatrix1to2[7][6] = 0.902667016469562;
   fWeightMatrix1to2[8][6] = 2.19412032116884;
   fWeightMatrix1to2[9][6] = 2.70414249471572;
   fWeightMatrix1to2[10][6] = -1.37471045310604;
   fWeightMatrix1to2[0][7] = 0.134010218665039;
   fWeightMatrix1to2[1][7] = -2.11814309370386;
   fWeightMatrix1to2[2][7] = 0.601067785475527;
   fWeightMatrix1to2[3][7] = -2.03172159356504;
   fWeightMatrix1to2[4][7] = -2.26953198773853;
   fWeightMatrix1to2[5][7] = -0.0756539743441101;
   fWeightMatrix1to2[6][7] = 0.884685303244893;
   fWeightMatrix1to2[7][7] = -0.0558791034277177;
   fWeightMatrix1to2[8][7] = 1.48819114403409;
   fWeightMatrix1to2[9][7] = 0.65666905012542;
   fWeightMatrix1to2[10][7] = -0.173587152642977;
   fWeightMatrix1to2[0][8] = 0.0575359244444459;
   fWeightMatrix1to2[1][8] = 0.1680056982043;
   fWeightMatrix1to2[2][8] = 1.86042800951416;
   fWeightMatrix1to2[3][8] = -1.44409974736786;
   fWeightMatrix1to2[4][8] = 0.181127700333144;
   fWeightMatrix1to2[5][8] = -1.13030590496172;
   fWeightMatrix1to2[6][8] = -0.611563432809586;
   fWeightMatrix1to2[7][8] = -0.953955141910582;
   fWeightMatrix1to2[8][8] = 0.33626266440201;
   fWeightMatrix1to2[9][8] = -0.91980114412212;
   fWeightMatrix1to2[10][8] = 0.96789604372984;
   fWeightMatrix1to2[0][9] = 2.95472039808448;
   fWeightMatrix1to2[1][9] = 0.79411808705856;
   fWeightMatrix1to2[2][9] = 0.0701498465179794;
   fWeightMatrix1to2[3][9] = -0.860627764891513;
   fWeightMatrix1to2[4][9] = -1.22032906074652;
   fWeightMatrix1to2[5][9] = -1.72981533543463;
   fWeightMatrix1to2[6][9] = 1.0636443835759;
   fWeightMatrix1to2[7][9] = -2.50693492198843;
   fWeightMatrix1to2[8][9] = -0.804776256777032;
   fWeightMatrix1to2[9][9] = -0.0954984608418793;
   fWeightMatrix1to2[10][9] = -1.69593775036157;
   fWeightMatrix1to2[0][10] = -0.708896092532956;
   fWeightMatrix1to2[1][10] = -1.64281997947637;
   fWeightMatrix1to2[2][10] = 0.916786853178556;
   fWeightMatrix1to2[3][10] = -1.01637918488427;
   fWeightMatrix1to2[4][10] = -2.42787133030469;
   fWeightMatrix1to2[5][10] = -0.443717745899225;
   fWeightMatrix1to2[6][10] = -0.932696265935169;
   fWeightMatrix1to2[7][10] = -1.95361589714589;
   fWeightMatrix1to2[8][10] = 0.398320363280601;
   fWeightMatrix1to2[9][10] = -2.63217412343652;
   fWeightMatrix1to2[10][10] = -1.22778899476455;
   fWeightMatrix1to2[0][11] = 3.18464067009752;
   fWeightMatrix1to2[1][11] = 0.515218011973017;
   fWeightMatrix1to2[2][11] = 0.265894030716476;
   fWeightMatrix1to2[3][11] = 0.873644337652681;
   fWeightMatrix1to2[4][11] = 1.1869354288215;
   fWeightMatrix1to2[5][11] = 1.59718074611705;
   fWeightMatrix1to2[6][11] = 0.163364760751042;
   fWeightMatrix1to2[7][11] = -3.31518596498757;
   fWeightMatrix1to2[8][11] = -0.078782066331795;
   fWeightMatrix1to2[9][11] = -2.5767203251813;
   fWeightMatrix1to2[10][11] = 0.911716197777325;
   fWeightMatrix1to2[0][12] = 0.168900641317479;
   fWeightMatrix1to2[1][12] = 0.0571844253567618;
   fWeightMatrix1to2[2][12] = 1.28196992520664;
   fWeightMatrix1to2[3][12] = 0.760537288667148;
   fWeightMatrix1to2[4][12] = 1.99524502005328;
   fWeightMatrix1to2[5][12] = -1.2520617399491;
   fWeightMatrix1to2[6][12] = 1.27760043291992;
   fWeightMatrix1to2[7][12] = 2.04690083349394;
   fWeightMatrix1to2[8][12] = -1.87176082460477;
   fWeightMatrix1to2[9][12] = 0.761414165071489;
   fWeightMatrix1to2[10][12] = -1.05978290303888;
   fWeightMatrix1to2[0][13] = 1.17009388623041;
   fWeightMatrix1to2[1][13] = 0.690707623868018;
   fWeightMatrix1to2[2][13] = 1.13233749036252;
   fWeightMatrix1to2[3][13] = 2.11378510718877;
   fWeightMatrix1to2[4][13] = -0.910970472782735;
   fWeightMatrix1to2[5][13] = 2.09996096730575;
   fWeightMatrix1to2[6][13] = 1.52279098124218;
   fWeightMatrix1to2[7][13] = 0.897936677124213;
   fWeightMatrix1to2[8][13] = -1.30576993123922;
   fWeightMatrix1to2[9][13] = 1.50321754736737;
   fWeightMatrix1to2[10][13] = -1.96207918657545;
   fWeightMatrix1to2[0][14] = 2.78505984841764;
   fWeightMatrix1to2[1][14] = 2.09884283120259;
   fWeightMatrix1to2[2][14] = -0.345005571069163;
   fWeightMatrix1to2[3][14] = 0.810475274370112;
   fWeightMatrix1to2[4][14] = 0.0893023430622363;
   fWeightMatrix1to2[5][14] = -1.40048283218857;
   fWeightMatrix1to2[6][14] = 0.636377011026205;
   fWeightMatrix1to2[7][14] = -3.25176131645565;
   fWeightMatrix1to2[8][14] = 1.19878363083814;
   fWeightMatrix1to2[9][14] = -0.630372424164234;
   fWeightMatrix1to2[10][14] = 1.67170760269533;
   fWeightMatrix1to2[0][15] = 1.5008897600854;
   fWeightMatrix1to2[1][15] = 1.69240124056024;
   fWeightMatrix1to2[2][15] = -0.471827456397775;
   fWeightMatrix1to2[3][15] = 0.000511618074864917;
   fWeightMatrix1to2[4][15] = 0.860677050222315;
   fWeightMatrix1to2[5][15] = 1.7785419987958;
   fWeightMatrix1to2[6][15] = -2.07873132644664;
   fWeightMatrix1to2[7][15] = -1.64792151329427;
   fWeightMatrix1to2[8][15] = 0.437860938346429;
   fWeightMatrix1to2[9][15] = -3.09939472906996;
   fWeightMatrix1to2[10][15] = -1.69286119562267;
   fWeightMatrix1to2[0][16] = -1.46462251625525;
   fWeightMatrix1to2[1][16] = 0.965985254382948;
   fWeightMatrix1to2[2][16] = -0.0189267392703872;
   fWeightMatrix1to2[3][16] = -1.96601717955869;
   fWeightMatrix1to2[4][16] = -2.11842325531539;
   fWeightMatrix1to2[5][16] = -0.22080305764094;
   fWeightMatrix1to2[6][16] = 1.80783666970611;
   fWeightMatrix1to2[7][16] = 0.924107987327909;
   fWeightMatrix1to2[8][16] = 0.794025167953187;
   fWeightMatrix1to2[9][16] = -0.613752038663774;
   fWeightMatrix1to2[10][16] = -1.93772168526772;
   fWeightMatrix1to2[0][17] = -1.15371686923665;
   fWeightMatrix1to2[1][17] = -0.888743449722678;
   fWeightMatrix1to2[2][17] = -1.43901578780233;
   fWeightMatrix1to2[3][17] = -0.0356645242329609;
   fWeightMatrix1to2[4][17] = 1.22041264912145;
   fWeightMatrix1to2[5][17] = -1.83935885850253;
   fWeightMatrix1to2[6][17] = 1.74449623405882;
   fWeightMatrix1to2[7][17] = 0.4922028327891;
   fWeightMatrix1to2[8][17] = 0.413756096861121;
   fWeightMatrix1to2[9][17] = -0.2187407785176;
   fWeightMatrix1to2[10][17] = -0.863356988481311;
   fWeightMatrix1to2[0][18] = 1.84122016448137;
   fWeightMatrix1to2[1][18] = -0.427242323998053;
   fWeightMatrix1to2[2][18] = 0.252134711130134;
   fWeightMatrix1to2[3][18] = 1.70583858512343;
   fWeightMatrix1to2[4][18] = 1.17502921644463;
   fWeightMatrix1to2[5][18] = -1.03742366184839;
   fWeightMatrix1to2[6][18] = 1.42169994399793;
   fWeightMatrix1to2[7][18] = -2.07276692325009;
   fWeightMatrix1to2[8][18] = 1.20217679629641;
   fWeightMatrix1to2[9][18] = 2.0721646999254;
   fWeightMatrix1to2[10][18] = -0.159094793710104;
   fWeightMatrix1to2[0][19] = -1.38107243888058;
   fWeightMatrix1to2[1][19] = 0.646178519731337;
   fWeightMatrix1to2[2][19] = -0.78075791580376;
   fWeightMatrix1to2[3][19] = 1.1095585818475;
   fWeightMatrix1to2[4][19] = -0.650233113274454;
   fWeightMatrix1to2[5][19] = -0.851257592240442;
   fWeightMatrix1to2[6][19] = -1.27550155874694;
   fWeightMatrix1to2[7][19] = -0.239108883138605;
   fWeightMatrix1to2[8][19] = -0.247423059695644;
   fWeightMatrix1to2[9][19] = 1.39377914440288;
   fWeightMatrix1to2[10][19] = -0.736692785106405;
   fWeightMatrix1to2[0][20] = -3.36978208932997;
   fWeightMatrix1to2[1][20] = 2.07659446434949;
   fWeightMatrix1to2[2][20] = 0.765491661105699;
   fWeightMatrix1to2[3][20] = -1.98804058395035;
   fWeightMatrix1to2[4][20] = 0.212319968767096;
   fWeightMatrix1to2[5][20] = -1.42835256483785;
   fWeightMatrix1to2[6][20] = 1.23529851332459;
   fWeightMatrix1to2[7][20] = 3.52860765320757;
   fWeightMatrix1to2[8][20] = -1.00767136226655;
   fWeightMatrix1to2[9][20] = -0.328467164265113;
   fWeightMatrix1to2[10][20] = 1.59935377570127;
   fWeightMatrix1to2[0][21] = 1.4702762057398;
   fWeightMatrix1to2[1][21] = 0.750838198296143;
   fWeightMatrix1to2[2][21] = 0.130506545245909;
   fWeightMatrix1to2[3][21] = -0.801680588195773;
   fWeightMatrix1to2[4][21] = -2.13325463521531;
   fWeightMatrix1to2[5][21] = 1.22409872454629;
   fWeightMatrix1to2[6][21] = 0.0561423166867133;
   fWeightMatrix1to2[7][21] = -0.0832100936636355;
   fWeightMatrix1to2[8][21] = -2.60401979125677;
   fWeightMatrix1to2[9][21] = -0.848982829100476;
   fWeightMatrix1to2[10][21] = -1.9340989742829;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -3.34945634655743;
   fWeightMatrix2to3[0][1] = -1.68465999951298;
   fWeightMatrix2to3[0][2] = 0.975085637345964;
   fWeightMatrix2to3[0][3] = -2.12407237452649;
   fWeightMatrix2to3[0][4] = 2.47777860506733;
   fWeightMatrix2to3[0][5] = 1.46995443133935;
   fWeightMatrix2to3[0][6] = -2.2405415679212;
   fWeightMatrix2to3[0][7] = 4.8527731860586;
   fWeightMatrix2to3[0][8] = 2.96242997213091;
   fWeightMatrix2to3[0][9] = 4.28150942602317;
   fWeightMatrix2to3[0][10] = -0.498034820620947;
   fWeightMatrix2to3[0][11] = -1.16298098521826;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)11) {
      std::cout << "Input vector needs to be of size " << 11 << std::endl;
      return 0;
   }

   std::array<double, 22> fWeights1 {{}};
   std::array<double, 12> fWeights2 {{}};
   std::array<double, 1> fWeights3 {{}};
   fWeights1.back() = 1.;
   fWeights2.back() = 1.;

   // layer 0 to 1
   for (int o=0; o<21; o++) {
      std::array<double, 12> buffer; // no need to initialise
      for (int i = 0; i<12 - 1; i++) {
         buffer[i] = fWeightMatrix0to1[o][i] * inputValues[i];
      } // loop over i
      buffer.back() = fWeightMatrix0to1[o][11];
      for (int i=0; i<12; i++) {
         fWeights1[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<21; o++) {
      fWeights1[o] = ActivationFnc(fWeights1[o]);
   } // loop over o
   // layer 1 to 2
   for (int o=0; o<11; o++) {
      std::array<double, 22> buffer; // no need to initialise
      for (int i=0; i<22; i++) {
         buffer[i] = fWeightMatrix1to2[o][i] * fWeights1[i];
      } // loop over i
      for (int i=0; i<22; i++) {
         fWeights2[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<11; o++) {
      fWeights2[o] = ActivationFnc(fWeights2[o]);
   } // loop over o
   // layer 2 to 3
   for (int o=0; o<1; o++) {
      std::array<double, 12> buffer; // no need to initialise
      for (int i=0; i<12; i++) {
         buffer[i] = fWeightMatrix2to3[o][i] * fWeights2[i];
      } // loop over i
      for (int i=0; i<12; i++) {
         fWeights3[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<1; o++) {
      fWeights3[o] = OutputActivationFnc(fWeights3[o]);
   } // loop over o

   return fWeights3[0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}

// Clean up
inline void ReadMLP::Clear()
{
}
inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         std::vector<double> iV(inputValues);
         Transform( iV, -1 );
         retval = GetMvaValue__( iV );
   }

   return retval;
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   double fMin_1[3][11];
   double fMax_1[3][11];
   // Normalization transformation, initialisation
   fMin_1[0][0] = 22.7864818573;
   fMax_1[0][0] = 7505.73046875;
   fScal_1[0][0] = 2.0/(fMax_1[0][0]-fMin_1[0][0]);
   fOff_1[0][0] = fMin_1[0][0]*fScal_1[0][0]+1.;
   fMin_1[1][0] = 23.5563087463;
   fMax_1[1][0] = 7838.75537109;
   fScal_1[1][0] = 2.0/(fMax_1[1][0]-fMin_1[1][0]);
   fOff_1[1][0] = fMin_1[1][0]*fScal_1[1][0]+1.;
   fMin_1[2][0] = 22.7864818573;
   fMax_1[2][0] = 7838.75537109;
   fScal_1[2][0] = 2.0/(fMax_1[2][0]-fMin_1[2][0]);
   fOff_1[2][0] = fMin_1[2][0]*fScal_1[2][0]+1.;
   fMin_1[0][1] = 0.000150358115206;
   fMax_1[0][1] = 8.68471050262;
   fScal_1[0][1] = 2.0/(fMax_1[0][1]-fMin_1[0][1]);
   fOff_1[0][1] = fMin_1[0][1]*fScal_1[0][1]+1.;
   fMin_1[1][1] = 2.2119609639e-05;
   fMax_1[1][1] = 8.68384933472;
   fScal_1[1][1] = 2.0/(fMax_1[1][1]-fMin_1[1][1]);
   fOff_1[1][1] = fMin_1[1][1]*fScal_1[1][1]+1.;
   fMin_1[2][1] = 2.2119609639e-05;
   fMax_1[2][1] = 8.68471050262;
   fScal_1[2][1] = 2.0/(fMax_1[2][1]-fMin_1[2][1]);
   fOff_1[2][1] = fMin_1[2][1]*fScal_1[2][1]+1.;
   fMin_1[0][2] = 126.97845459;
   fMax_1[0][2] = 2277.4987793;
   fScal_1[0][2] = 2.0/(fMax_1[0][2]-fMin_1[0][2]);
   fOff_1[0][2] = fMin_1[0][2]*fScal_1[0][2]+1.;
   fMin_1[1][2] = 125.825294495;
   fMax_1[1][2] = 1926.56140137;
   fScal_1[1][2] = 2.0/(fMax_1[1][2]-fMin_1[1][2]);
   fOff_1[1][2] = fMin_1[1][2]*fScal_1[1][2]+1.;
   fMin_1[2][2] = 125.825294495;
   fMax_1[2][2] = 2277.4987793;
   fScal_1[2][2] = 2.0/(fMax_1[2][2]-fMin_1[2][2]);
   fOff_1[2][2] = fMin_1[2][2]*fScal_1[2][2]+1.;
   fMin_1[0][3] = 4.91857872476e-06;
   fMax_1[0][3] = 0.405025333166;
   fScal_1[0][3] = 2.0/(fMax_1[0][3]-fMin_1[0][3]);
   fOff_1[0][3] = fMin_1[0][3]*fScal_1[0][3]+1.;
   fMin_1[1][3] = 5.9500340285e-05;
   fMax_1[1][3] = 0.47649076581;
   fScal_1[1][3] = 2.0/(fMax_1[1][3]-fMin_1[1][3]);
   fOff_1[1][3] = fMin_1[1][3]*fScal_1[1][3]+1.;
   fMin_1[2][3] = 4.91857872476e-06;
   fMax_1[2][3] = 0.47649076581;
   fScal_1[2][3] = 2.0/(fMax_1[2][3]-fMin_1[2][3]);
   fOff_1[2][3] = fMin_1[2][3]*fScal_1[2][3]+1.;
   fMin_1[0][4] = -4.50663423538;
   fMax_1[0][4] = 4.51134681702;
   fScal_1[0][4] = 2.0/(fMax_1[0][4]-fMin_1[0][4]);
   fOff_1[0][4] = fMin_1[0][4]*fScal_1[0][4]+1.;
   fMin_1[1][4] = -4.5036110878;
   fMax_1[1][4] = 4.50834369659;
   fScal_1[1][4] = 2.0/(fMax_1[1][4]-fMin_1[1][4]);
   fOff_1[1][4] = fMin_1[1][4]*fScal_1[1][4]+1.;
   fMin_1[2][4] = -4.50663423538;
   fMax_1[2][4] = 4.51134681702;
   fScal_1[2][4] = 2.0/(fMax_1[2][4]-fMin_1[2][4]);
   fOff_1[2][4] = fMin_1[2][4]*fScal_1[2][4]+1.;
   fMin_1[0][5] = 50.1059684753;
   fMax_1[0][5] = 1964.14489746;
   fScal_1[0][5] = 2.0/(fMax_1[0][5]-fMin_1[0][5]);
   fOff_1[0][5] = fMin_1[0][5]*fScal_1[0][5]+1.;
   fMin_1[1][5] = 50.0584754944;
   fMax_1[1][5] = 2753.2824707;
   fScal_1[1][5] = 2.0/(fMax_1[1][5]-fMin_1[1][5]);
   fOff_1[1][5] = fMin_1[1][5]*fScal_1[1][5]+1.;
   fMin_1[2][5] = 50.0584754944;
   fMax_1[2][5] = 2753.2824707;
   fScal_1[2][5] = 2.0/(fMax_1[2][5]-fMin_1[2][5]);
   fOff_1[2][5] = fMin_1[2][5]*fScal_1[2][5]+1.;
   fMin_1[0][6] = -2.4010925293;
   fMax_1[0][6] = 2.39041256905;
   fScal_1[0][6] = 2.0/(fMax_1[0][6]-fMin_1[0][6]);
   fOff_1[0][6] = fMin_1[0][6]*fScal_1[0][6]+1.;
   fMin_1[1][6] = -2.38632035255;
   fMax_1[1][6] = 2.38307738304;
   fScal_1[1][6] = 2.0/(fMax_1[1][6]-fMin_1[1][6]);
   fOff_1[1][6] = fMin_1[1][6]*fScal_1[1][6]+1.;
   fMin_1[2][6] = -2.4010925293;
   fMax_1[2][6] = 2.39041256905;
   fScal_1[2][6] = 2.0/(fMax_1[2][6]-fMin_1[2][6]);
   fOff_1[2][6] = fMin_1[2][6]*fScal_1[2][6]+1.;
   fMin_1[0][7] = 0.0488347522914;
   fMax_1[0][7] = 0.99988257885;
   fScal_1[0][7] = 2.0/(fMax_1[0][7]-fMin_1[0][7]);
   fOff_1[0][7] = fMin_1[0][7]*fScal_1[0][7]+1.;
   fMin_1[1][7] = 0.0229892414063;
   fMax_1[1][7] = 0.999983787537;
   fScal_1[1][7] = 2.0/(fMax_1[1][7]-fMin_1[1][7]);
   fOff_1[1][7] = fMin_1[1][7]*fScal_1[1][7]+1.;
   fMin_1[2][7] = 0.0229892414063;
   fMax_1[2][7] = 0.999983787537;
   fScal_1[2][7] = 2.0/(fMax_1[2][7]-fMin_1[2][7]);
   fOff_1[2][7] = fMin_1[2][7]*fScal_1[2][7]+1.;
   fMin_1[0][8] = 2;
   fMax_1[0][8] = 8;
   fScal_1[0][8] = 2.0/(fMax_1[0][8]-fMin_1[0][8]);
   fOff_1[0][8] = fMin_1[0][8]*fScal_1[0][8]+1.;
   fMin_1[1][8] = 2;
   fMax_1[1][8] = 9;
   fScal_1[1][8] = 2.0/(fMax_1[1][8]-fMin_1[1][8]);
   fOff_1[1][8] = fMin_1[1][8]*fScal_1[1][8]+1.;
   fMin_1[2][8] = 2;
   fMax_1[2][8] = 9;
   fScal_1[2][8] = 2.0/(fMax_1[2][8]-fMin_1[2][8]);
   fOff_1[2][8] = fMin_1[2][8]*fScal_1[2][8]+1.;
   fMin_1[0][9] = 1.5914440155e-05;
   fMax_1[0][9] = 1;
   fScal_1[0][9] = 2.0/(fMax_1[0][9]-fMin_1[0][9]);
   fOff_1[0][9] = fMin_1[0][9]*fScal_1[0][9]+1.;
   fMin_1[1][9] = 1.93119049072e-05;
   fMax_1[1][9] = 1;
   fScal_1[1][9] = 2.0/(fMax_1[1][9]-fMin_1[1][9]);
   fOff_1[1][9] = fMin_1[1][9]*fScal_1[1][9]+1.;
   fMin_1[2][9] = 1.5914440155e-05;
   fMax_1[2][9] = 1;
   fScal_1[2][9] = 2.0/(fMax_1[2][9]-fMin_1[2][9]);
   fOff_1[2][9] = fMin_1[2][9]*fScal_1[2][9]+1.;
   fMin_1[0][10] = 3.26525550918e-05;
   fMax_1[0][10] = 6.50682735443;
   fScal_1[0][10] = 2.0/(fMax_1[0][10]-fMin_1[0][10]);
   fOff_1[0][10] = fMin_1[0][10]*fScal_1[0][10]+1.;
   fMin_1[1][10] = 1.18112052405e-06;
   fMax_1[1][10] = 6.68952894211;
   fScal_1[1][10] = 2.0/(fMax_1[1][10]-fMin_1[1][10]);
   fOff_1[1][10] = fMin_1[1][10]*fScal_1[1][10]+1.;
   fMin_1[2][10] = 1.18112052405e-06;
   fMax_1[2][10] = 6.68952894211;
   fScal_1[2][10] = 2.0/(fMax_1[2][10]-fMin_1[2][10]);
   fOff_1[2][10] = fMin_1[2][10]*fScal_1[2][10]+1.;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) {
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   }
   if ( indicesPut.empty() ) {
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   }

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fOff_1[cls][ivar];
      double scale  = fScal_1[cls][ivar];
      iv[indicesPut.at(ivar)] = scale*dv[ivar]-offset;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
